/* generated by tools/gen_cjk_dict.py from jieba dict.txt */
/* do not edit by hand */
#ifndef WHALEUI_CJK_DICT_LITE_H
#define WHALEUI_CJK_DICT_LITE_H

struct CjkWordGroup { const char* head;
                     const char* const* tails; int count; };

static const char* const t0[] = {
    "\xE4\xB8\xAA",
    "\xE4\xBA\x9B",
    "\xE7\xA7\x8D",
    "\xE8\x88\xAC",
    "\xE5\xAE\x9A",
    "\xE6\xA0\xB7",
    "\xE6\xAC\xA1",
    "\xE7\x9B\xB4",
    "\xE5\x88\x87",
    "\xE5\xA3\xB0",
    "\xE8\xB5\xB7",
    "\xE7\x82\xB9",
    "\xE4\xB8\x8B",
    "\xE6\x9D\xA1",
    "\xE4\xBD\x8D",
    "\xE5\x8F\xA5",
    "\xE5\xA4\xA9",
    "\xE5\xB9\xB4",
    "\xE9\x98\xB5",
    "\xE8\xBE\xB9",
    "\xE5\x9D\x97",
    "\xE7\x89\x87",
    "\xE5\x8F\xAA",
    "\xE9\x9D\xA2",
    "\xE5\xBA\xA7",
    "\xE4\xBB\xB6",
    "\xE7\xBA\xA7",
    "\xE5\x9C\xBA",
    "\xE7\x9C\xBC",
    "\xE5\xBC\xA0",
    "\xE4\xB8\xAD",
    "\xE5\xAE\xB6",
    "\xE8\x87\xB4",
    "\xE6\x97\xB6",
    "\xE6\xAD\xA5",
    "\xE6\x97\xA6",
};

static const char* const t1[] = {
    "\xE5\x85\x83",
};

static const char* const t2[] = {
    "\xE4\xB8\xAA",
    "\xE5\xB9\xB4",
};

static const char* const t3[] = {
    "\xE6\xB5\xB7",
};

static const char* const t4[] = {
    "\xE6\x9D\xA5",
    "\xE5\x8E\xBB",
};

static const char* const t5[] = {
    "\xE6\x98\xAF",
    "\xE8\x83\xBD",
    "\xE5\x90\x8C",
    "\xE4\xBC\x9A",
    "\xE8\xBF\x87",
    "\xE6\x96\xAD",
    "\xE7\x9F\xA5",
    "\xE8\xA6\x81",
    "\xE6\x95\xA2",
    "\xE4\xBB\x85",
    "\xE5\x88\xB0",
    "\xE5\x8F\xAF",
    "\xE5\xB0\x91",
    "\xE5\x86\x8D",
    "\xE5\xBE\x97",
    "\xE8\xB6\xB3",
    "\xE4\xBA\x86",
    "\xE9\x94\x99",
};

static const char* const t6[] = {
    "\xE4\xB8\x9A",
    "\xE5\xAE\xB6",
    "\xE9\x97\xA8",
};

static const char* const t7[] = {
    "\xE7\x95\x8C",
    "\xE7\xBA\xAA",
};

static const char* const t8[] = {
    "\xE5\x8A\xA1",
};

static const char* const t9[] = {
    "\xE8\xA5\xBF",
    "\xE5\x8C\x97",
    "\xE9\x83\xA8",
};

static const char* const t10[] = {
    "\xE4\xB8\xAA",
    "\xE7\xA7\x8D",
};

static const char* const t11[] = {
    "\xE9\x87\x8D",
};

static const char* const t12[] = {
    "\xE4\xBA\xBA",
};

static const char* const t13[] = {
    "\xE5\x9B\xBD",
    "\xE5\xBF\x83",
    "\xE5\xA4\xAE",
    "\xE5\xAD\xA6",
    "\xE9\x97\xB4",
};

static const char* const t14[] = {
    "\xE5\xAF\x8C",
};

static const char* const t15[] = {
    "\xE4\xBA\x86",
    "\xE4\xB8\xBB",
    "\xE4\xBB\x80\xE4\xB9\x88",
};

static const char* const t16[] = {
    "\xE8\xA6\x81",
    "\xE5\xB8\xAD",
    "\xE4\xBB\xBB",
    "\xE5\xBC\xA0",
};

static const char* const t17[] = {
    "\xE8\xA1\x8C",
};

static const char* const t18[] = {
    "\xE9\x97\xB4",
    "\xE4\xB8\x80",
    "\xE5\x90\x8E",
    "\xE4\xB8\xAD",
    "\xE5\x89\x8D",
    "\xE4\xB8\x8B",
    "\xE5\xA4\x96",
};

static const char* const t19[] = {
    "\xE8\xAE\xB8",
};

static const char* const t20[] = {
    "\xE8\xAE\xB0",
};

static const char* const t21[] = {
    "\xE8\xA7\xA3",
};

static const char* const t22[] = {
    "\xE6\x83\x85",
    "\xE4\xB8\x9A",
    "\xE4\xBB\xB6",
    "\xE5\x8A\xA1",
};

static const char* const t23[] = {
    "\xE4\xBA\xBA",
};

static const char* const t24[] = {
    "\xE6\x98\xAF",
};

static const char* const t25[] = {
    "\xE6\xB4\xB2",
};

static const char* const t26[] = {
    "\xE9\x80\x9A",
};

static const char* const t27[] = {
    "\xE5\x93\x81",
    "\xE7\x94\x9F",
    "\xE4\xB8\x9A",
    "\xE9\x87\x8F",
};

static const char* const t28[] = {
    "\xE8\x87\xAA",
};

static const char* const t29[] = {
    "\xE6\xB0\x91",
    "\xE4\xBB\xAC",
    "\xE5\x8F\xA3",
    "\xE5\x91\x98",
    "\xE6\xB0\x91\xE6\x94\xBF\xE5\xBA\x9C",
    "\xE5\xA4\xA7",
    "\xE7\x89\xA9",
    "\xE7\xB1\xBB",
    "\xE6\x95\xB0",
    "\xE6\x89\x8D",
    "\xE5\xAE\xB6",
    "\xE6\xB0\x91\xE6\xB3\x95\xE9\x99\xA2",
    "\xE5\xA3\xAB",
};

static const char* const t30[] = {
    "\xE5\x85\x83",
};

static const char* const t31[] = {
    "\xE4\xB9\x88",
};

static const char* const t32[] = {
    "\xE5\xA4\xA9",
    "\xE6\x97\xA5",
    "\xE5\xB9\xB4",
};

static const char* const t33[] = {
    "\xE7\xBB\x8D",
};

static const char* const t34[] = {
    "\xE7\x84\xB6",
};

static const char* const t35[] = {
    "\xE8\x80\x8C",
    "\xE4\xBA\x8B",
    "\xE6\xAD\xA4",
};

static const char* const t36[] = {
    "\xE4\xBB\xAC",
};

static const char* const t37[] = {
    "\xE8\xA1\xA8",
};

static const char* const t38[] = {
    "\xE5\x8F\x8A",
    "\xE4\xB8\x8A",
    "\xE5\x90\x8E",
    "\xE6\x9D\xA5",
    "\xE5\x89\x8D",
    "\xE4\xB8\x8B",
    "\xE4\xB8\xBA",
};

static const char* const t39[] = {
    "\xE5\x80\xBC",
    "\xE6\xA0\xBC",
};

static const char* const t40[] = {
    "\xE5\x8A\xA1",
    "\xE4\xBD\x95",
    "\xE6\x9C\x9F",
};

static const char* const t41[] = {
    "\xE4\xB8\x9A",
};

static const char* const t42[] = {
    "\xE4\xBA\xBA",
};

static const char* const t43[] = {
    "\xE5\x8A\xBF",
};

static const char* const t44[] = {
    "\xE8\xAE\xAE",
};

static const char* const t45[] = {
    "\xE7\xBB\x9F",
};

static const char* const t46[] = {
    "\xE4\xB9\x8E",
};

static const char* const t47[] = {
    "\xE6\x98\xAF",
};

static const char* const t48[] = {
    "\xE4\xBA\x8E",
    "\xE7\xBD\xAE",
};

static const char* const t49[] = {
    "\xE7\xB3\xBB",
    "\xE8\x82\xB2",
    "\xE5\x88\xB6",
    "\xE7\x8E\xB0",
};

static const char* const t50[] = {
    "\xE4\xB8\xBA",
    "\xE7\x94\xA8",
    "\xE6\x88\x98",
    "\xE5\x93\x81",
    "\xE5\x87\xBA",
};

static const char* const t51[] = {
    "\xE4\xBB\xAC",
};

static const char* const t52[] = {
    "\xE7\x94\xA8",
};

static const char* const t53[] = {
    "\xE5\xA6\x82",
};

static const char* const t54[] = {
    "\xE6\x98\xAF",
};

static const char* const t55[] = {
    "\xE8\xBF\x9B",
};

static const char* const t56[] = {
    "\xE7\xBD\x97\xE6\x96\xAF",
};

static const char* const t57[] = {
    "\xE6\x8A\xA4",
    "\xE6\x8C\x81",
    "\xE8\xAF\x81",
    "\xE9\x9A\x9C",
};

static const char* const t58[] = {
    "\xE6\x81\xAF",
};

static const char* const t59[] = {
    "\xE5\xBA\xB7",
};

static const char* const t60[] = {
    "\xE5\xAD\x90",
    "\xE7\xAB\xA5",
};

static const char* const t61[] = {
    "\xE5\xBC\x9F",
};

static const char* const t62[] = {
    "\xE5\x88\x86",
};

static const char* const t63[] = {
    "\xE7\x94\x9F",
    "\xE8\xBF\x9B",
    "\xE5\x90\x8E",
};

static const char* const t64[] = {
    "\xE5\x9B\xBD",
    "\xE7\x9C\x81",
    "\xE9\x83\xA8",
    "\xE9\x9D\xA2",
    "\xE5\xB8\x82",
    "\xE5\x9B\xBD\xE4\xBA\xBA\xE5\xA4\xA7",
    "\xE4\xBD\x93",
};

static const char* const t65[] = {
    "\xE5\x8F\xB8",
    "\xE9\x87\x8C",
    "\xE6\xB0\x91",
    "\xE8\xB7\xAF",
    "\xE5\x85\x83",
    "\xE5\xB8\x83",
};

static const char* const t66[] = {
    "\xE5\x90\x8C",
};

static const char* const t67[] = {
    "\xE7\xB3\xBB",
    "\xE4\xBA\x8E",
    "\xE9\x94\xAE",
};

static const char* const t68[] = {
    "\xE4\xB8\xAD",
    "\xE4\xBB\x96",
    "\xE5\xAE\x9E",
    "\xE5\xAE\x83",
};

static const char* const t69[] = {
    "\xE6\x9C\x89",
    "\xE4\xBD\x93",
};

static const char* const t70[] = {
    "\xE5\xAE\xB9",
    "\xE9\x83\xA8",
};

static const char* const t71[] = {
    "\xE4\xBA\x8B",
    "\xE9\x98\x9F",
};

static const char* const t72[] = {
    "\xE4\xB8\x9A",
    "\xE6\xB0\x91",
    "\xE6\x9D\x91",
};

static const char* const t73[] = {
    "\xE5\xAE\x9A",
    "\xE8\xAE\xAE",
};

static const char* const t74[] = {
    "\xE5\xA4\x87",
};

static const char* const t75[] = {
    "\xE5\xB0\x91",
};

static const char* const t76[] = {
    "\xE4\xB8\xAA",
    "\xE4\xB9\x8E",
};

static const char* const t77[] = {
    "\xE6\x9D\xA5",
    "\xE7\x8E\xB0",
    "\xE5\x8E\xBB",
    "\xE5\x8F\xA3",
    "\xE7\x89\x88",
};

static const char* const t78[] = {
    "\xE5\x88\xAB",
    "\xE5\xB8\x83",
    "\xE6\x9E\x90",
    "\xE4\xB8\xBA",
    "\xE9\x92\x9F",
    "\xE5\xAD\x90",
    "\xE9\x85\x8D",
};

static const char* const t79[] = {
    "\xE6\x89\x8D",
};

static const char* const t80[] = {
    "\xE9\x80\xA0",
    "\xE4\xBD\x9C",
};

static const char* const t81[] = {
    "\xE7\x94\xA8",
    "\xE7\x9B\x8A",
};

static const char* const t82[] = {
    "\xE4\xBA\xBA",
};

static const char* const t83[] = {
    "\xE5\xBA\x95",
};

static const char* const t84[] = {
    "\xE5\xBA\xA6",
    "\xE5\xAE\x9A",
    "\xE9\x80\xA0",
};

static const char* const t85[] = {
    "\xE9\x87\x8F",
};

static const char* const t86[] = {
    "\xE6\xB3\x95",
};

static const char* const t87[] = {
    "\xE8\x83\xBD",
};

static const char* const t88[] = {
    "\xE5\xBC\xBA",
    "\xE4\xB8\x8A",
};

static const char* const t89[] = {
    "\xE7\x89\xA9",
};

static const char* const t90[] = {
    "\xE5\x8A\x9B",
};

static const char* const t91[] = {
    "\xE5\x8A\xA8",
};

static const char* const t92[] = {
    "\xE6\x8B\xAC",
};

static const char* const t93[] = {
    "\xE5\xAD\xA6",
};

static const char* const t94[] = {
    "\xE4\xBA\xAC",
};

static const char* const t95[] = {
    "\xE5\x9F\x9F",
};

static const char* const t96[] = {
    "\xE9\x99\xA2",
};

static const char* const t97[] = {
    "\xE5\x88\x86",
};

static const char* const t98[] = {
    "\xE4\xBD\x8D",
};

static const char* const t99[] = {
    "\xE4\xBA\xAC",
    "\xE5\x8C\x97",
    "\xE9\x83\xA8",
};

static const char* const t100[] = {
    "\xE5\xBA\xA6",
};

static const char* const t101[] = {
    "\xE4\xBD\xBF",
};

static const char* const t102[] = {
    "\xE6\x98\xAF",
};

static const char* const t103[] = {
    "\xE5\x8F\xB2",
};

static const char* const t104[] = {
    "\xE5\x8A\x9B",
};

static const char* const t105[] = {
    "\xE6\x9D\xA5",
    "\xE5\x9B\xA0",
    "\xE5\x88\x99",
};

static const char* const t106[] = {
    "\xE5\xB9\xB4",
};

static const char* const t107[] = {
    "\xE5\x8A\xA0",
    "\xE4\xB8\x8E",
};

static const char* const t108[] = {
    "\xE7\xA7\xB0",
};

static const char* const t109[] = {
    "\xE5\x85\xB6",
};

static const char* const t110[] = {
    "\xE6\x96\xB9",
};

static const char* const t111[] = {
    "\xE5\xAF\xB9",
    "\xE5\xBA\x94",
    "\xE6\x98\xA0",
};

static const char* const t112[] = {
    "\xE5\xB1\x95",
    "\xE7\x8E\xB0",
    "\xE7\x94\x9F",
    "\xE8\xA8\x80\xE4\xBA\xBA",
    "\xE8\xA1\xA8",
    "\xE5\xB8\x83",
    "\xE6\x8C\xA5",
    "\xE5\x87\xBA",
    "\xE8\xBE\xBE",
};

static const char* const t113[] = {
    "\xE5\xBE\x97",
};

static const char* const t114[] = {
    "\xE5\x88\xB0",
};

static const char* const t115[] = {
    "\xE5\x8C\x96",
    "\xE6\x88\x90",
};

static const char* const t116[] = {
    "\xE4\xBB\xA3",
};

static const char* const t117[] = {
    "\xE5\xA4\x96",
};

static const char* const t118[] = {
    "\xE8\xA6\x81",
    "\xE8\xA7\x81",
    "\xE8\x83\xBD",
    "\xE6\x9C\x89",
    "\xE5\xA5\xBD",
};

static const char* const t119[] = {
    "\xE5\xBC\x80",
};

static const char* const t120[] = {
    "\xE4\xBB\xA5",
    "\xE8\x83\xBD",
    "\xE6\x98\xAF",
};

static const char* const t121[] = {
    "\xE6\xB9\xBE",
};

static const char* const t122[] = {
    "\xE7\xA7\x8D",
    "\xE7\xBA\xA7",
    "\xE5\x9C\xB0",
    "\xE4\xB8\xAA",
    "\xE5\x9B\xBD",
};

static const char* const t123[] = {
    "\xE4\xBD\x9C",
};

static const char* const t124[] = {
    "\xE6\x97\xB6",
    "\xE5\xBF\x97",
    "\xE6\xA0\xB7",
    "\xE6\x84\x8F",
};

static const char* const t125[] = {
    "\xE7\xA7\xB0",
    "\xE5\xAD\x97",
};

static const char* const t126[] = {
    "\xE6\x9D\xA5",
};

static const char* const t127[] = {
    "\xE8\xAF\xB4",
};

static const char* const t128[] = {
    "\xE8\xAF\x89",
};

static const char* const t129[] = {
    "\xE5\x9B\xB4",
};

static const char* const t130[] = {
    "\xE4\xBB\xA4",
};

static const char* const t131[] = {
    "\xE5\xB9\xB3",
};

static const char* const t132[] = {
    "\xE4\xBB\xAC",
};

static const char* const t133[] = {
    "\xE7\xA7\x8D",
};

static const char* const t134[] = {
    "\xE9\x87\x8C",
};

static const char* const t135[] = {
    "\xE5\x93\x81",
    "\xE4\xB8\x9A",
};

static const char* const t136[] = {
    "\xE6\xAC\xA2",
};

static const char* const t137[] = {
    "\xE6\x9D\xA5",
    "\xE7\xAD\x94",
    "\xE5\x8E\xBB",
    "\xE5\x88\xB0",
};

static const char* const t138[] = {
    "\xE4\xB8\xBA",
    "\xE6\xAD\xA4",
    "\xE7\xB4\xA0",
    "\xE8\x80\x8C",
};

static const char* const t139[] = {
    "\xE9\x9A\xBE",
};

static const char* const t140[] = {
    "\xE5\xAE\xB6",
    "\xE9\x99\x85",
    "\xE5\x8A\xA1\xE9\x99\xA2",
    "\xE5\x86\x85",
    "\xE6\xB0\x91\xE5\x85\x9A",
};

static const char* const t141[] = {
    "\xE7\x89\x87",
};

static const char* const t142[] = {
    "\xE5\x9C\xB0",
};

static const char* const t143[] = {
    "\xE6\x96\xB9",
    "\xE5\x8C\xBA",
    "\xE4\xBD\x8D",
    "\xE7\x90\x86",
    "\xE9\x9D\xA2",
};

static const char* const t144[] = {
    "\xE5\x9C\xA8",
};

static const char* const t145[] = {
    "\xE6\x8C\x81",
};

static const char* const t146[] = {
    "\xE5\xB8\x82",
    "\xE9\x82\xA6",
};

static const char* const t147[] = {
    "\xE5\x85\xBB",
};

static const char* const t148[] = {
    "\xE6\x9C\xAC",
    "\xE7\xA1\x80",
    "\xE5\x9C\xB0",
};

static const char* const t149[] = {
    "\xE5\x86\x85",
};

static const char* const t150[] = {
    "\xE9\x95\xBF",
    "\xE5\x8A\xA0",
};

static const char* const t151[] = {
    "\xE9\x9F\xB3",
};

static const char* const t152[] = {
    "\xE7\x90\x86",
    "\xE4\xBA\x8E",
};

static const char* const t153[] = {
    "\xE6\x9D\x82",
};

static const char* const t154[] = {
    "\xE4\xBA\xA4\xE9\x83\xA8",
    "\xE5\x9B\xBD",
};

static const char* const t155[] = {
    "\xE5\xB0\x91",
    "\xE5\xB9\xB4",
    "\xE7\xA7\x8D",
    "\xE6\xAC\xA1",
};

static const char* const t156[] = {
    "\xE5\xAD\xA6",
    "\xE5\xAE\xB6",
    "\xE9\x87\x8F",
    "\xE4\xBC\x9A",
    "\xE9\x81\x93",
    "\xE5\x9E\x8B",
    "\xE9\x99\x86",
    "\xE8\x87\xA3",
    "\xE5\xB0\x8F",
};

static const char* const t157[] = {
    "\xE5\xAE\x89\xE9\x97\xA8",
    "\xE4\xB8\x8B",
    "\xE7\x84\xB6",
};

static const char* const t158[] = {
    "\xE4\xBA\xBA",
};

static const char* const t159[] = {
    "\xE4\xBA\xBA",
    "\xE5\x84\xBF",
    "\xE5\xAD\x90",
};

static const char* const t160[] = {
    "\xE4\xBB\xAC",
};

static const char* const t161[] = {
    "\xE5\x83\x8F",
};

static const char* const t162[] = {
    "\xE6\x9E\x9C",
    "\xE4\xBD\x95",
    "\xE6\xAD\xA4",
    "\xE4\xBB\x8A",
};

static const char* const t163[] = {
    "\xE5\xA5\xB3",
};

static const char* const t164[] = {
    "\xE7\xBB\x88",
};

static const char* const t165[] = {
    "\xE5\xA8\x98",
};

static const char* const t166[] = {
    "\xE5\x91\x98\xE4\xBC\x9A",
    "\xE5\x91\x98",
};

static const char* const t167[] = {
    "\xE4\xBD\x93",
};

static const char* const t168[] = {
    "\xE5\x9C\xA8",
};

static const char* const t169[] = {
    "\xE7\x94\x9F",
    "\xE9\x99\xA2",
    "\xE6\xA0\xA1",
    "\xE4\xB9\xA0",
};

static const char* const t170[] = {
    "\xE5\xAD\x90",
};

static const char* const t171[] = {
    "\xE4\xBB\xAC",
};

static const char* const t172[] = {
    "\xE5\x85\xA8",
    "\xE6\x8E\x92",
};

static const char* const t173[] = {
    "\xE6\x88\x90",
    "\xE5\x85\xA8",
    "\xE5\x96\x84",
};

static const char* const t174[] = {
    "\xE6\x95\x99",
};

static const char* const t175[] = {
    "\xE5\x91\x98",
};

static const char* const t176[] = {
    "\xE6\x98\x8C",
};

static const char* const t177[] = {
    "\xE8\xA1\x8C",
    "\xE7\x8E\xB0",
    "\xE9\x99\x85",
    "\xE6\x96\xBD",
    "\xE9\x99\x85\xE4\xB8\x8A",
    "\xE5\x9C\xA8",
    "\xE9\xAA\x8C",
    "\xE8\xB7\xB5",
};

static const char* const t178[] = {
    "\xE5\xB8\x83",
};

static const char* const t179[] = {
    "\xE6\xB3\x95",
};

static const char* const t180[] = {
    "\xE5\xBA\xAD",
    "\xE9\x87\x8C",
};

static const char* const t181[] = {
    "\xE6\x98\x93",
};

static const char* const t182[] = {
    "\xE4\xBA\x8E",
    "\xE6\x96\xB9",
};

static const char* const t183[] = {
    "\xE5\xBC\xB9",
    "\xE8\x87\xB4",
};

static const char* const t184[] = {
    "\xE5\xBB\xBA",
};

static const char* const t185[] = {
    "\xE5\x86\x9B",
};

static const char* const t186[] = {
    "\xE6\x97\xB6",
    "\xE8\xAF\xB4",
};

static const char* const t187[] = {
    "\xE5\x85\xB6",
};

static const char* const t188[] = {
    "\xE6\x98\xAF",
    "\xE4\xB8\x9A",
};

static const char* const t189[] = {
    "\xE7\xAE\xA1",
};

static const char* const t190[] = {
    "\xE6\xB0\x91",
};

static const char* const t191[] = {
    "\xE5\xBC\x80",
};

static const char* const t192[] = {
    "\xE4\xBA\x8E",
};

static const char* const t193[] = {
    "\xE4\xBD\x9C",
    "\xE4\xB8\x9A",
    "\xE7\xA8\x8B",
    "\xE4\xBA\xBA",
};

static const char* const t194[] = {
    "\xE5\x8F\xB3",
};

static const char* const t195[] = {
    "\xE5\xA4\xA7",
};

static const char* const t196[] = {
    "\xE7\xBB\x8F",
};

static const char* const t197[] = {
    "\xE5\x9C\xBA",
    "\xE9\x95\xBF",
};

static const char* const t198[] = {
    "\xE7\x88\xB6",
};

static const char* const t199[] = {
    "\xE6\x9C\x9B",
};

static const char* const t200[] = {
    "\xE5\x9B\xBD\xE4\xB8\xBB\xE4\xB9\x89",
};

static const char* const t201[] = {
    "\xE6\x9D\xA5",
};

static const char* const t202[] = {
    "\xE5\x8A\xA9",
};

static const char* const t203[] = {
    "\xE5\xA7\x94\xE4\xBC\x9A",
};

static const char* const t204[] = {
    "\xE9\x83\xA8",
};

static const char* const t205[] = {
    "\xE5\x9D\x87",
    "\xE6\xB0\x91",
    "\xE5\x8E\x9F",
    "\xE6\x96\xB9\xE5\x8D\x83\xE7\xB1\xB3",
};

static const char* const t206[] = {
    "\xE4\xBB\xA3",
};

static const char* const t207[] = {
    "\xE4\xB8\x94",
};

static const char* const t208[] = {
    "\xE6\xB3\x9B",
    "\xE5\x9C\xBA",
    "\xE5\xB7\x9E",
};

static const char* const t209[] = {
    "\xE8\xAF\xA5",
    "\xE7\x94\xA8",
    "\xE5\xBD\x93",
};

static const char* const t210[] = {
    "\xE8\xAE\xBE",
    "\xE7\xAB\x8B",
    "\xE7\xAD\x91",
    "\xE8\xAE\xAE",
    "\xE6\x88\x90",
};

static const char* const t211[] = {
    "\xE5\xA7\x8B",
    "\xE5\x8F\x91",
    "\xE6\x94\xBE",
    "\xE5\xB1\x95",
};

static const char* const t212[] = {
    "\xE8\xB5\xB7",
};

static const char* const t213[] = {
    "\xE5\xAD\x90",
};

static const char* const t214[] = {
    "\xE8\xB0\x83",
};

static const char* const t215[] = {
    "\xE6\x97\xB6",
    "\xE7\x84\xB6",
    "\xE5\xB9\xB4",
    "\xE5\x9C\xB0",
};

static const char* const t216[] = {
    "\xE6\x88\x90",
    "\xE5\xBC\x8F",
    "\xE5\x8A\xBF",
};

static const char* const t217[] = {
    "\xE5\x93\x8D",
};

static const char* const t218[] = {
    "\xE5\xBE\x80",
};

static const char* const t219[] = {
    "\xE5\xA4\x9A",
    "\xE5\xA4\xA7",
};

static const char* const t220[] = {
    "\xE5\x88\xB0",
};

static const char* const t221[] = {
    "\xE5\x9B\xBD",
};

static const char* const t222[] = {
    "\xE4\xB8\xAD",
    "\xE9\x87\x8C",
    "\xE6\x83\xB3",
    "\xE7\x90\x86",
};

static const char* const t223[] = {
    "\xE9\xA1\xBB",
};

static const char* const t224[] = {
    "\xE7\x84\xB6",
};

static const char* const t225[] = {
    "\xE4\xB9\x88",
    "\xE6\xA0\xB7",
};

static const char* const t226[] = {
    "\xE6\x83\xB3",
};

static const char* const t227[] = {
    "\xE8\xB4\xA8",
};

static const char* const t228[] = {
    "\xE7\x90\x86",
    "\xE7\xBB\x9F",
    "\xE6\x98\xAF",
};

static const char* const t229[] = {
    "\xE5\xA4\x8D",
};

static const char* const t230[] = {
    "\xE5\x86\xB5",
};

static const char* const t231[] = {
    "\xE5\x88\xB0",
};

static const char* const t232[] = {
    "\xE8\xA7\x81",
    "\xE4\xB9\x89",
    "\xE6\x80\x9D",
};

static const char* const t233[] = {
    "\xE5\x88\xB0",
    "\xE8\xA7\x89",
};

static const char* const t234[] = {
    "\xE6\x84\x8F",
};

static const char* const t235[] = {
    "\xE4\xB8\xBA",
    "\xE7\xAB\x8B",
    "\xE5\x8A\x9F",
    "\xE7\xBB\xA9",
    "\xE9\x95\xBF",
};

static const char* const t236[] = {
    "\xE4\xBB\xAC",
    "\xE5\x9B\xBD",
};

static const char* const t237[] = {
    "\xE8\x80\x85",
};

static const char* const t238[] = {
    "\xE4\xBA\x89",
    "\xE7\x95\xA5",
    "\xE6\x96\x97",
};

static const char* const t239[] = {
    "\xE4\xBB\xA5",
    "\xE6\x9C\x89",
    "\xE8\xB0\x93",
};

static const char* const t240[] = {
    "\xE6\xAE\xB5",
    "\xE4\xB8\xAD",
};

static const char* const t241[] = {
    "\xE8\xA1\x8C",
};

static const char* const t242[] = {
    "\xE5\xA4\xA7",
};

static const char* const t243[] = {
    "\xE5\x87\x86",
};

static const char* const t244[] = {
    "\xE5\x88\xB0",
};

static const char* const t245[] = {
    "\xE6\x9C\xAF",
};

static const char* const t246[] = {
    "\xE8\xB5\x84",
    "\xE5\x85\xA5",
};

static const char* const t247[] = {
    "\xE5\x91\x8A",
    "\xE9\x81\x93",
};

static const char* const t248[] = {
    "\xE4\xBB\xBB",
};

static const char* const t249[] = {
    "\xE7\x94\x9F",
};

static const char* const t250[] = {
    "\xE6\x9C\x89",
};

static const char* const t251[] = {
    "\xE5\x87\xBA",
    "\xE6\x8C\xA5",
    "\xE5\xAF\xBC",
};

static const char* const t252[] = {
    "\xE7\x85\xA7",
};

static const char* const t253[] = {
    "\xE6\x8F\xA1",
};

static const char* const t254[] = {
    "\xE5\x8F\x97",
    "\xE7\x9D\x80",
};

static const char* const t255[] = {
    "\xE5\x88\xB6",
};

static const char* const t256[] = {
    "\xE6\x96\xBD",
};

static const char* const t257[] = {
    "\xE5\x87\xBA",
    "\xE9\xAB\x98",
    "\xE4\xBE\x9B",
};

static const char* const t258[] = {
    "\xE6\x8C\x81",
};

static const char* const t259[] = {
    "\xE5\x85\xA5",
};

static const char* const t260[] = {
    "\xE9\x9D\xA9",
    "\xE5\x8F\x98",
};

static const char* const t261[] = {
    "\xE5\x87\xBB",
};

static const char* const t262[] = {
    "\xE5\x9C\xA8",
};

static const char* const t263[] = {
    "\xE6\xB2\xBB",
    "\xE5\xBA\x9C",
    "\xE4\xBD\x93",
    "\xE7\xAD\x96",
    "\xE6\x9D\x83",
};

static const char* const t264[] = {
    "\xE4\xBA\x8B",
};

static const char* const t265[] = {
    "\xE4\xBA\xBA",
};

static const char* const t266[] = {
    "\xE8\x82\xB2",
    "\xE6\x8E\x88",
    "\xE5\xB8\x88",
};

static const char* const t267[] = {
    "\xE9\x87\x8F",
    "\xE5\xAD\xA6",
};

static const char* const t268[] = {
    "\xE4\xB8\xAA",
};

static const char* const t269[] = {
    "\xE5\x8C\x96",
    "\xE5\xAD\xA6",
    "\xE7\xAB\xA0",
    "\xE6\x98\x8E",
};

static const char* const t270[] = {
    "\xE4\xBA\x89",
};

static const char* const t271[] = {
    "\xE9\x97\xBB",
};

static const char* const t272[] = {
    "\xE9\x9D\xA2",
    "\xE6\xB3\x95",
    "\xE5\xBC\x8F",
    "\xE5\x90\x91",
    "\xE6\xA1\x88",
};

static const char* const t273[] = {
    "\xE6\xB8\xB8",
};

static const char* const t274[] = {
    "\xE6\xB3\x95",
};

static const char* const t275[] = {
    "\xE7\x84\xB6",
};

static const char* const t276[] = {
    "\xE6\x9C\xAC",
};

static const char* const t277[] = {
    "\xE9\x97\xB4",
    "\xE5\x80\x99",
    "\xE6\x9C\x9F",
    "\xE4\xBB\xA3",
};

static const char* const t278[] = {
    "\xE7\x99\xBD",
    "\xE6\x98\xBE",
    "\xE7\xA1\xAE",
};

static const char* const t279[] = {
    "\xE5\x90\xA6",
    "\xE4\xB8\x8D\xE6\x98\xAF",
};

static const char* const t280[] = {
    "\xE7\xA4\xBA",
};

static const char* const t281[] = {
    "\xE4\xB8\x8A",
};

static const char* const t282[] = {
    "\xE9\x80\x9A",
    "\xE9\x81\x8D",
};

static const char* const t283[] = {
    "\xE5\x8A\xA0",
};

static const char* const t284[] = {
    "\xE7\xBB\x8F",
};

static const char* const t285[] = {
    "\xE5\x90\x8E",
    "\xE5\xA4\xA7",
    "\xE9\xAB\x98",
    "\xE7\xBB\x88",
    "\xE8\xBF\x91",
};

static const char* const t286[] = {
    "\xE5\x85\xB3",
    "\xE4\xBA\x9B",
    "\xE4\xBA\xBA",
    "\xE6\x95\x88",
    "\xE6\x97\xB6",
    "\xE9\x99\x90\xE5\x85\xAC\xE5\x8F\xB8",
};

static const char* const t287[] = {
    "\xE5\x8F\x8B",
};

static const char* const t288[] = {
    "\xE5\x8A\xA1",
};

static const char* const t289[] = {
    "\xE9\x97\xB4",
};

static const char* const t290[] = {
    "\xE6\x9D\xA5",
};

static const char* const t291[] = {
    "\xE7\xBA\xA7",
    "\xE6\x9D\xA5",
    "\xE6\x8A\xA5",
    "\xE8\xBA\xAB",
};

static const char* const t292[] = {
    "\xE5\x85\xB3",
    "\xE6\x9E\x84",
    "\xE4\xBC\x9A",
    "\xE5\x9C\xBA",
    "\xE6\xA2\xB0",
};

static const char* const t293[] = {
    "\xE5\x8A\x9B",
    "\xE5\x88\xA9",
};

static const char* const t294[] = {
    "\xE8\x87\xAA\xE6\x88\x90",
};

static const char* const t295[] = {
    "\xE6\x96\x99",
};

static const char* const t296[] = {
    "\xE4\xBB\xB6",
};

static const char* const t297[] = {
    "\xE8\xAF\xB4",
    "\xE5\x88\xB0",
    "\xE8\x87\xAA",
};

static const char* const t298[] = {
    "\xE6\x88\x90",
};

static const char* const t299[] = {
    "\xE4\xBA\x9B",
};

static const char* const t300[] = {
    "\xE5\x87\x86",
};

static const char* const t301[] = {
    "\xE5\xAD\x90",
};

static const char* const t302[] = {
    "\xE6\x8D\xAE",
    "\xE6\x9C\xAC",
};

static const char* const t303[] = {
    "\xE5\xAF\x9F\xE9\x99\xA2",
    "\xE6\x9F\xA5",
};

static const char* const t304[] = {
    "\xE7\x89\xA9",
};

static const char* const t305[] = {
    "\xE6\xB4\xB2",
};

static const char* const t306[] = {
    "\xE6\x98\xAF",
    "\xE5\xBC\x8F",
    "\xE7\xA1\xAE",
    "\xE5\xB8\xB8",
};

static const char* const t307[] = {
    "\xE5\xA4\x96",
    "\xE6\x97\xB6",
};

static const char* const t308[] = {
    "\xE6\xB1\x89",
    "\xE6\xB1\x89\xE5\xB8\x82",
    "\xE5\x99\xA8",
    "\xE5\x8A\x9F",
};

static const char* const t309[] = {
    "\xE4\xBA\xB2",
};

static const char* const t310[] = {
    "\xE5\xB9\xB4",
    "\xE4\xB8\xAA",
    "\xE5\xA4\xA9",
};

static const char* const t311[] = {
    "\xE8\xBE\x83",
    "\xE8\xB5\x9B",
    "\xE4\xBE\x8B",
    "\xE5\xA6\x82",
};

static const char* const t312[] = {
    "\xE4\xB8\x9A",
};

static const char* const t313[] = {
    "\xE6\xB3\xBD\xE4\xB8\x9C",
};

static const char* const t314[] = {
    "\xE7\xB1\xB3",
};

static const char* const t315[] = {
    "\xE6\x97\x8F",
    "\xE4\xB8\xBB",
};

static const char* const t316[] = {
    "\xE5\x80\x99",
};

static const char* const t317[] = {
    "\xE5\xB9\xB3",
};

static const char* const t318[] = {
    "\xE8\xBD\xA6",
};

static const char* const t319[] = {
    "\xE6\x9C\x89",
};

static const char* const t320[] = {
    "\xE7\x96\x97",
};

static const char* const t321[] = {
    "\xE5\xBE\x8B",
    "\xE5\x9B\xBD",
    "\xE8\xA7\x84",
};

static const char* const t322[] = {
    "\xE6\x84\x8F",
};

static const char* const t323[] = {
    "\xE5\x8A\xA8",
};

static const char* const t324[] = {
    "\xE5\x86\x9B",
    "\xE6\x8B\x94",
};

static const char* const t325[] = {
    "\xE6\x81\xAF",
};

static const char* const t326[] = {
    "\xE6\xA5\x9A",
};

static const char* const t327[] = {
    "\xE5\x8C\x97",
    "\xE5\x8C\x97\xE7\x9C\x81",
};

static const char* const t328[] = {
    "\xE5\x90\x8E",
    "\xE8\x80\x8C",
};

static const char* const t329[] = {
    "\xE5\x9B\xBD",
};

static const char* const t330[] = {
    "\xE4\xBA\xB2",
    "\xE6\xAF\x8D",
};

static const char* const t331[] = {
    "\xE8\xB4\xA8",
};

static const char* const t332[] = {
    "\xE5\x88\xAB",
    "\xE7\x82\xB9",
    "\xE8\x89\xB2",
    "\xE6\xAE\x8A",
    "\xE5\xBE\x81",
};

static const char* const t333[] = {
    "\xE6\x80\x81",
    "\xE5\x86\xB5",
};

static const char* const t334[] = {
    "\xE7\xAB\x8B",
};

static const char* const t335[] = {
    "\xE5\xA2\x83",
};

static const char* const t336[] = {
    "\xE5\x9C\xA8",
    "\xE8\xB1\xA1",
    "\xE4\xBB\xA3",
    "\xE4\xBB\xA3\xE5\x8C\x96",
};

static const char* const t337[] = {
    "\xE8\xAE\xBA",
    "\xE8\xA7\xA3",
};

static const char* const t338[] = {
    "\xE8\x87\xB3",
    "\xE4\xB9\x88",
};

static const char* const t339[] = {
    "\xE4\xBA\xA7",
    "\xE6\xB4\xBB",
    "\xE7\x89\xA9",
    "\xE5\x91\xBD",
    "\xE9\x95\xBF",
};

static const char* const t340[] = {
    "\xE4\xBA\x8E",
    "\xE6\x88\xB7",
};

static const char* const t341[] = {
    "\xE4\xBA\x8E",
};

static const char* const t342[] = {
    "\xE8\xAF\x9D",
    "\xE5\xAD\x90",
};

static const char* const t343[] = {
    "\xE4\xBA\xBA",
};

static const char* const t344[] = {
    "\xE4\xB8\x8B",
};

static const char* const t345[] = {
    "\xE7\xA7\x91",
    "\xE5\xBA\xA6",
};

static const char* const t346[] = {
    "\xE5\xB8\x9D",
    "\xE4\xB8\x8A",
};

static const char* const t347[] = {
    "\xE7\x9D\xA3",
};

static const char* const t348[] = {
    "\xE5\x89\x8D",
    "\xE6\xA0\x87",
    "\xE7\x9A\x84",
};

static const char* const t349[] = {
    "\xE6\x8E\xA5",
    "\xE8\xBE\x96\xE5\xB8\x82",
};

static const char* const t350[] = {
    "\xE5\x85\xB3",
    "\xE5\x90\x8C",
    "\xE4\xBF\xA1",
    "\xE5\xBD\x93",
    "\xE5\xAF\xB9",
    "\xE4\xBA\x92",
    "\xE5\xBA\x94",
};

static const char* const t351[] = {
    "\xE7\xBA\xA7",
};

static const char* const t352[] = {
    "\xE5\x88\xB0",
    "\xE8\xA7\x81",
    "\xE7\x9D\x80",
    "\xE6\x9D\xA5",
    "\xE7\x9C\x8B",
};

static const char* const t353[] = {
    "\xE6\xAD\xA3",
    "\xE6\x98\xAF",
    "\xE7\x9A\x84",
};

static const char* const t354[] = {
    "\xE7\x9D\x9B",
};

static const char* const t355[] = {
    "\xE7\x9B\xBE",
};

static const char* const t356[] = {
    "\xE9\x81\x93",
    "\xE8\xAF\x86",
};

static const char* const t357[] = {
    "\xE9\xA6\x96",
    "\xE9\xA6\x96\xE5\xB8\x82",
};

static const char* const t358[] = {
    "\xE7\xA9\xB6",
    "\xE5\x88\xB6",
};

static const char* const t359[] = {
    "\xE5\xAE\x9A",
    "\xE5\xAE\x9E",
};

static const char* const t360[] = {
    "\xE4\xBC\x9A",
    "\xE4\xBC\x9A\xE4\xB8\xBB\xE4\xB9\x89",
    "\xE5\x8C\xBA",
};

static const char* const t361[] = {
    "\xE5\xBC\x80",
};

static const char* const t362[] = {
    "\xE6\x8A\x80",
    "\xE5\xAD\xA6",
};

static const char* const t363[] = {
    "\xE4\xB9\xA6\xE9\x95\xBF",
};

static const char* const t364[] = {
    "\xE6\x9E\x81",
};

static const char* const t365[] = {
    "\xE4\xB8\xBA",
};

static const char* const t366[] = {
    "\xE5\xBA\xA6",
    "\xE5\xBA\x8F",
};

static const char* const t367[] = {
    "\xE5\xAE\x9A",
};

static const char* const t368[] = {
    "\xE5\x86\x9B",
    "\xE9\x97\xB4",
};

static const char* const t369[] = {
    "\xE7\x84\xB6",
};

static const char* const t370[] = {
    "\xE5\x8D\xB3",
    "\xE5\x88\xBB",
};

static const char* const t371[] = {
    "\xE4\xBA\x89",
};

static const char* const t372[] = {
    "\xE7\x84\xB6",
};

static const char* const t373[] = {
    "\xE4\xB8\x80",
    "\xE4\xBA\x8C",
    "\xE4\xB8\x80\xE6\xAC\xA1",
};

static const char* const t374[] = {
    "\xE7\xAD\x89",
};

static const char* const t375[] = {
    "\xE5\x8D\x95",
};

static const char* const t376[] = {
    "\xE7\x90\x86",
};

static const char* const t377[] = {
    "\xE5\x9E\x8B",
    "\xE4\xBC\xBC",
};

static const char* const t378[] = {
    "\xE9\xA3\x9F",
};

static const char* const t379[] = {
    "\xE7\xA5\x9E",
};

static const char* const t380[] = {
    "\xE7\xBB\x9F",
};

static const char* const t381[] = {
    "\xE7\xBB\x87",
    "\xE6\x88\x90",
};

static const char* const t382[] = {
    "\xE8\x83\x9E",
};

static const char* const t383[] = {
    "\xE4\xBA\x8E",
};

static const char* const t384[] = {
    "\xE6\xB5\x8E",
    "\xE8\xBF\x87",
    "\xE9\xAA\x8C",
    "\xE8\x90\xA5",
    "\xE5\xB8\xB8",
};

static const char* const t385[] = {
    "\xE6\x9E\x84",
    "\xE6\x9E\x9C",
    "\xE6\x9D\x9F",
    "\xE5\x90\x88",
};

static const char* const t386[] = {
    "\xE4\xB8\x80",
    "\xE6\xB2\xBB",
    "\xE8\xAE\xA1",
};

static const char* const t387[] = {
    "\xE7\xBB\xAD",
};

static const char* const t388[] = {
    "\xE6\x8A\xA4",
};

static const char* const t389[] = {
    "\xE5\x90\x88",
};

static const char* const t390[] = {
    "\xE8\xBE\x91",
};

static const char* const t391[] = {
    "\xE7\xBB\x9C",
};

static const char* const t392[] = {
    "\xE5\x9B\xBD",
    "\xE5\x85\x83",
};

static const char* const t393[] = {
    "\xE4\xBC\x97",
};

static const char* const t394[] = {
    "\xE5\xB8\x88",
};

static const char* const t395[] = {
    "\xE8\x99\x91",
    "\xE8\xAF\x95",
    "\xE7\x94\x9F",
};

static const char* const t396[] = {
    "\xE4\xB8\x94",
    "\xE6\x98\xAF",
};

static const char* const t397[] = {
    "\xE4\xB8\x9A",
    "\xE6\x9D\x83",
};

static const char* const t398[] = {
    "\xE7\xB3\xBB",
    "\xE5\x90\x88",
};

static const char* const t399[] = {
    "\xE4\xB8\x9C",
    "\xE4\xBB\xBD",
};

static const char* const t400[] = {
    "\xE5\xAE\x9A",
};

static const char* const t401[] = {
    "\xE5\x88\xA9",
};

static const char* const t402[] = {
    "\xE5\x8A\x9B",
    "\xE5\xA4\x9F",
};

static const char* const t403[] = {
    "\xE4\xB8\x8A",
};

static const char* const t404[] = {
    "\xE5\xB7\xB1",
    "\xE7\x84\xB6",
    "\xE6\xB2\xBB\xE5\x8C\xBA",
    "\xE7\x94\xB1",
    "\xE6\xB2\xBB\xE5\xB7\x9E",
};

static const char* const t405[] = {
    "\xE5\xB0\x91",
};

static const char* const t406[] = {
    "\xE7\xA9\xBA",
};

static const char* const t407[] = {
    "\xE5\xA5\xBD",
};

static const char* const t408[] = {
    "\xE6\x9C\xAF",
};

static const char* const t409[] = {
    "\xE8\x81\x94",
};

static const char* const t410[] = {
    "\xE5\xB9\xB2",
};

static const char* const t411[] = {
    "\xE5\x9B\xBD",
    "\xE9\x9B\x84",
};

static const char* const t412[] = {
    "\xE5\x9B\xB4",
};

static const char* const t413[] = {
    "\xE5\xB7\x9E",
};

static const char* const t414[] = {
    "\xE5\xBE\x97",
};

static const char* const t415[] = {
    "\xE5\x90\x8D",
};

static const char* const t416[] = {
    "\xE5\x8F\xA4",
};

static const char* const t417[] = {
    "\xE7\x84\xB6",
};

static const char* const t418[] = {
    "\xE6\x94\xBF",
    "\xE5\x8A\xA8",
    "\xE4\xB8\xBA",
    "\xE4\xB8\x9A",
    "\xE4\xBD\xBF",
};

static const char* const t419[] = {
    "\xE7\xA4\xBA",
    "\xE7\x8E\xB0",
};

static const char* const t420[] = {
    "\xE5\xA4\x87",
};

static const char* const t421[] = {
    "\xE9\x98\xB3",
};

static const char* const t422[] = {
    "\xE6\x96\xB9",
    "\xE5\x8C\x97",
    "\xE9\x83\xA8",
    "\xE5\x8D\x97",
};

static const char* const t423[] = {
    "\xE6\xB1\x82",
};

static const char* const t424[] = {
    "\xE5\x88\xB0",
};

static const char* const t425[] = {
    "\xE5\xAE\x9A",
    "\xE6\xA8\xA1",
    "\xE5\x88\x92",
};

static const char* const t426[] = {
    "\xE5\xBE\x97",
};

static const char* const t427[] = {
    "\xE5\x86\xB3",
    "\xE9\x87\x8A",
};

static const char* const t428[] = {
    "\xE5\x88\x92",
    "\xE7\xAE\x97\xE6\x9C\xBA",
};

static const char* const t429[] = {
    "\xE4\xB8\xBA",
    "\xE8\xAF\x86",
};

static const char* const t430[] = {
    "\xE8\xAE\xBA",
};

static const char* const t431[] = {
    "\xE7\xBB\x83",
};

static const char* const t432[] = {
    "\xE8\x80\x85",
};

static const char* const t433[] = {
    "\xE5\xA4\x9A",
};

static const char* const t434[] = {
    "\xE8\xAE\xA1",
    "\xE7\xAB\x8B",
    "\xE5\xA4\x87",
};

static const char* const t435[] = {
    "\xE6\x98\x8E",
};

static const char* const t436[] = {
    "\xE6\x9D\xA1",
};

static const char* const t437[] = {
    "\xE8\xA8\x80",
};

static const char* const t438[] = {
    "\xE9\x81\x93",
    "\xE8\xAF\x9D",
    "\xE6\x98\x8E",
};

static const char* const t439[] = {
    "\xE6\x95\xB4",
    "\xE6\x9F\xA5",
};

static const char* const t440[] = {
    "\xE8\xB4\xA3",
};

static const char* const t441[] = {
    "\xE7\x8C\xAE",
};

static const char* const t442[] = {
    "\xE4\xBA\xA7",
    "\xE6\x94\xBF",
};

static const char* const t443[] = {
    "\xE4\xBB\xBB",
};

static const char* const t444[] = {
    "\xE5\xB8\x81",
};

static const char* const t445[] = {
    "\xE9\x87\x8F",
};

static const char* const t446[] = {
    "\xE6\x97\x8F",
};

static const char* const t447[] = {
    "\xE6\x98\x93",
};

static const char* const t448[] = {
    "\xE6\xBA\x90",
    "\xE6\x9C\xAC",
    "\xE6\x96\x99",
    "\xE9\x87\x91",
};

static const char* const t449[] = {
    "\xE6\x9D\xA5",
};

static const char* const t450[] = {
    "\xE8\xBF\x87",
};

static const char* const t451[] = {
    "\xE6\x9D\xA5\xE8\xB6\x8A",
};

static const char* const t452[] = {
    "\xE4\xB8\x8A",
    "\xE4\xBD\x93",
    "\xE5\xAD\x90",
    "\xE8\xBE\xB9",
};

static const char* const t453[] = {
    "\xE5\xA4\xA7",
};

static const char* const t454[] = {
    "\xE5\x88\xB0",
};

static const char* const t455[] = {
    "\xE9\x80\x9F",
};

static const char* const t456[] = {
    "\xE7\xA8\x8B",
    "\xE5\x8E\xBB",
    "\xE6\x9D\xA5",
};

static const char* const t457[] = {
    "\xE5\x8A\xA8",
    "\xE8\xBE\x93",
};

static const char* const t458[] = {
    "\xE6\x9C\x89",
    "\xE6\x98\xAF",
    "\xE8\xA6\x81",
};

static const char* const t459[] = {
    "\xE4\xB8\xAA",
    "\xE6\xA0\xB7",
    "\xE4\xBA\x9B",
    "\xE7\xA7\x8D",
    "\xE9\x87\x8C",
    "\xE4\xB9\x88",
    "\xE6\x97\xB6",
    "\xE6\xAC\xA1",
    "\xE4\xBD\x8D",
};

static const char* const t460[] = {
    "\xE8\xA1\x8C",
    "\xE5\x85\xA5",
    "\xE4\xB8\x80\xE6\xAD\xA5",
    "\xE6\x94\xBB",
    "\xE6\x9D\xA5",
};

static const char* const t461[] = {
    "\xE7\xBB\xAD",
};

static const char* const t462[] = {
    "\xE5\xBA\x94",
    "\xE5\xBD\x93",
};

static const char* const t463[] = {
    "\xE4\xB8\xBE",
    "\xE6\x8B\xA9",
};

static const char* const t464[] = {
    "\xE6\xB8\x90",
};

static const char* const t465[] = {
    "\xE8\xBF\x87",
    "\xE5\xB8\xB8",
};

static const char* const t466[] = {
    "\xE5\xBA\xA6",
};

static const char* const t467[] = {
    "\xE6\x88\x90",
};

static const char* const t468[] = {
    "\xE8\xB7\xAF",
};

static const char* const t469[] = {
    "\xE5\x9D\x80",
};

static const char* const t470[] = {
    "\xE4\xB9\x88",
    "\xE4\xBA\x9B",
    "\xE4\xB8\xAA",
    "\xE9\x87\x8C",
    "\xE6\xA0\xB7",
};

static const char* const t471[] = {
    "\xE5\x88\x86",
    "\xE9\x97\xA8",
    "\xE9\x98\x9F",
    "\xE9\x95\xBF",
};

static const char* const t472[] = {
    "\xE7\x94\xA8",
    "\xE5\x8F\x96",
};

static const char* const t473[] = {
    "\xE9\x9D\xA2",
};

static const char* const t474[] = {
    "\xE8\xA6\x81",
    "\xE7\x82\xB9",
    "\xE5\xA4\xA7",
    "\xE6\x96\xB0",
    "\xE8\xA7\x86",
};

static const char* const t475[] = {
    "\xE8\x9E\x8D",
};

static const char* const t476[] = {
    "\xE8\xB7\xAF",
};

static const char* const t477[] = {
    "\xE8\xA1\x8C",
};

static const char* const t478[] = {
    "\xE5\x94\xAE",
};

static const char* const t479[] = {
    "\xE8\xAF\xAF",
};

static const char* const t480[] = {
    "\xE6\xB1\x9F",
    "\xE6\x9C\x9F",
    "\xE5\xAE\x89",
};

static const char* const t481[] = {
    "\xE9\xA2\x98",
    "\xE9\x81\x93",
};

static const char* const t482[] = {
    "\xE4\xBC\x8D",
};

static const char* const t483[] = {
    "\xE6\xAE\xB5",
};

static const char* const t484[] = {
    "\xE8\xBF\x91",
};

static const char* const t485[] = {
    "\xE9\x95\xBF",
};

static const char* const t486[] = {
    "\xE4\xBA\x86",
};

static const char* const t487[] = {
    "\xE7\x9D\x80",
};

static const char* const t488[] = {
    "\xE9\x81\x93",
    "\xE4\xBB\xA5",
};

static const char* const t489[] = {
    "\xE5\x9B\xA2",
    "\xE4\xB8\xAD",
};

static const char* const t490[] = {
    "\xE8\xA6\x81",
    "\xE6\xB1\x82",
};

static const char* const t491[] = {
    "\xE5\xB9\xB4",
};

static const char* const t492[] = {
    "\xE5\xB8\xB8",
};

static const char* const t493[] = {
    "\xE7\xA7\xAF",
    "\xE5\x89\x8D",
    "\xE5\xAF\xB9",
};

static const char* const t494[] = {
    "\xE5\x91\xBD",
};

static const char* const t495[] = {
    "\xE5\xB0\x8F\xE5\xAE\x9D",
};

static const char* const t496[] = {
    "\xE4\xB9\x90",
};

static const char* const t497[] = {
    "\xE7\x9B\xAE",
};

static const char* const t498[] = {
    "\xE5\xAF\xBC",
    "\xE5\x9F\x9F",
};

static const char* const t499[] = {
    "\xE6\x9C\xBA",
};

static const char* const t500[] = {
    "\xE5\x93\x81",
};

static const char* const t501[] = {
    "\xE5\x85\x88",
};

static const char* const t502[] = {
    "\xE6\xB8\xAF",
};

static const char* const t503[] = {
    "\xE9\x80\x9F",
    "\xE5\xBA\xA6",
    "\xE7\xBA\xA7",
    "\xE5\x85\xB4",
};

static const struct CjkWordGroup kCjkDict[] = {
    {"\xE4\xB8\x80", t0, 36},
    {"\xE4\xB8\x87", t1, 1},
    {"\xE4\xB8\x89", t2, 2},
    {"\xE4\xB8\x8A", t3, 1},
    {"\xE4\xB8\x8B", t4, 2},
    {"\xE4\xB8\x8D", t5, 18},
    {"\xE4\xB8\x93", t6, 3},
    {"\xE4\xB8\x96", t7, 2},
    {"\xE4\xB8\x9A", t8, 1},
    {"\xE4\xB8\x9C", t9, 3},
    {"\xE4\xB8\xA4", t10, 2},
    {"\xE4\xB8\xA5", t11, 1},
    {"\xE4\xB8\xAA", t12, 1},
    {"\xE4\xB8\xAD", t13, 5},
    {"\xE4\xB8\xB0", t14, 1},
    {"\xE4\xB8\xBA", t15, 3},
    {"\xE4\xB8\xBB", t16, 4},
    {"\xE4\xB8\xBE", t17, 1},
    {"\xE4\xB9\x8B", t18, 7},
    {"\xE4\xB9\x9F", t19, 1},
    {"\xE4\xB9\xA6", t20, 1},
    {"\xE4\xBA\x86", t21, 1},
    {"\xE4\xBA\x8B", t22, 4},
    {"\xE4\xBA\x8C", t23, 1},
    {"\xE4\xBA\x8E", t24, 1},
    {"\xE4\xBA\x9A", t25, 1},
    {"\xE4\xBA\xA4", t26, 1},
    {"\xE4\xBA\xA7", t27, 4},
    {"\xE4\xBA\xB2", t28, 1},
    {"\xE4\xBA\xBA", t29, 13},
    {"\xE4\xBA\xBF", t30, 1},
    {"\xE4\xBB\x80", t31, 1},
    {"\xE4\xBB\x8A", t32, 3},
    {"\xE4\xBB\x8B", t33, 1},
    {"\xE4\xBB\x8D", t34, 1},
    {"\xE4\xBB\x8E", t35, 3},
    {"\xE4\xBB\x96", t36, 1},
    {"\xE4\xBB\xA3", t37, 1},
    {"\xE4\xBB\xA5", t38, 7},
    {"\xE4\xBB\xB7", t39, 2},
    {"\xE4\xBB\xBB", t40, 3},
    {"\xE4\xBC\x81", t41, 1},
    {"\xE4\xBC\x97", t42, 1},
    {"\xE4\xBC\x98", t43, 1},
    {"\xE4\xBC\x9A", t44, 1},
    {"\xE4\xBC\xA0", t45, 1},
    {"\xE4\xBC\xBC", t46, 1},
    {"\xE4\xBD\x86", t47, 1},
    {"\xE4\xBD\x8D", t48, 2},
    {"\xE4\xBD\x93", t49, 4},
    {"\xE4\xBD\x9C", t50, 5},
    {"\xE4\xBD\xA0", t51, 1},
    {"\xE4\xBD\xBF", t52, 1},
    {"\xE4\xBE\x8B", t53, 1},
    {"\xE4\xBE\xBF", t54, 1},
    {"\xE4\xBF\x83", t55, 1},
    {"\xE4\xBF\x84", t56, 1},
    {"\xE4\xBF\x9D", t57, 4},
    {"\xE4\xBF\xA1", t58, 1},
    {"\xE5\x81\xA5", t59, 1},
    {"\xE5\x84\xBF", t60, 2},
    {"\xE5\x85\x84", t61, 1},
    {"\xE5\x85\x85", t62, 1},
    {"\xE5\x85\x88", t63, 3},
    {"\xE5\x85\xA8", t64, 7},
    {"\xE5\x85\xAC", t65, 6},
    {"\xE5\x85\xB1", t66, 1},
    {"\xE5\x85\xB3", t67, 3},
    {"\xE5\x85\xB6", t68, 4},
    {"\xE5\x85\xB7", t69, 2},
    {"\xE5\x86\x85", t70, 2},
    {"\xE5\x86\x9B", t71, 2},
    {"\xE5\x86\x9C", t72, 3},
    {"\xE5\x86\xB3", t73, 2},
    {"\xE5\x87\x86", t74, 1},
    {"\xE5\x87\x8F", t75, 1},
    {"\xE5\x87\xA0", t76, 2},
    {"\xE5\x87\xBA", t77, 5},
    {"\xE5\x88\x86", t78, 7},
    {"\xE5\x88\x9A", t79, 1},
    {"\xE5\x88\x9B", t80, 2},
    {"\xE5\x88\xA9", t81, 2},
    {"\xE5\x88\xAB", t82, 1},
    {"\xE5\x88\xB0", t83, 1},
    {"\xE5\x88\xB6", t84, 3},
    {"\xE5\x8A\x9B", t85, 1},
    {"\xE5\x8A\x9E", t86, 1},
    {"\xE5\x8A\x9F", t87, 1},
    {"\xE5\x8A\xA0", t88, 2},
    {"\xE5\x8A\xA8", t89, 1},
    {"\xE5\x8A\xAA", t90, 1},
    {"\xE5\x8A\xB3", t91, 1},
    {"\xE5\x8C\x85", t92, 1},
    {"\xE5\x8C\x96", t93, 1},
    {"\xE5\x8C\x97", t94, 1},
    {"\xE5\x8C\xBA", t95, 1},
    {"\xE5\x8C\xBB", t96, 1},
    {"\xE5\x8D\x81", t97, 1},
    {"\xE5\x8D\x95", t98, 1},
    {"\xE5\x8D\x97", t99, 3},
    {"\xE5\x8D\xB0", t100, 1},
    {"\xE5\x8D\xB3", t101, 1},
    {"\xE5\x8D\xB4", t102, 1},
    {"\xE5\x8E\x86", t103, 1},
    {"\xE5\x8E\x8B", t104, 1},
    {"\xE5\x8E\x9F", t105, 3},
    {"\xE5\x8E\xBB", t106, 1},
    {"\xE5\x8F\x82", t107, 2},
    {"\xE5\x8F\x88", t108, 1},
    {"\xE5\x8F\x8A", t109, 1},
    {"\xE5\x8F\x8C", t110, 1},
    {"\xE5\x8F\x8D", t111, 3},
    {"\xE5\x8F\x91", t112, 9},
    {"\xE5\x8F\x96", t113, 1},
    {"\xE5\x8F\x97", t114, 1},
    {"\xE5\x8F\x98", t115, 2},
    {"\xE5\x8F\xA4", t116, 1},
    {"\xE5\x8F\xA6", t117, 1},
    {"\xE5\x8F\xAA", t118, 5},
    {"\xE5\x8F\xAC", t119, 1},
    {"\xE5\x8F\xAF", t120, 3},
    {"\xE5\x8F\xB0", t121, 1},
    {"\xE5\x90\x84", t122, 5},
    {"\xE5\x90\x88", t123, 1},
    {"\xE5\x90\x8C", t124, 4},
    {"\xE5\x90\x8D", t125, 2},
    {"\xE5\x90\x8E", t126, 1},
    {"\xE5\x90\xAC", t127, 1},
    {"\xE5\x91\x8A", t128, 1},
    {"\xE5\x91\xA8", t129, 1},
    {"\xE5\x91\xBD", t130, 1},
    {"\xE5\x92\x8C", t131, 1},
    {"\xE5\x92\xB1", t132, 1},
    {"\xE5\x93\x81", t133, 1},
    {"\xE5\x93\xAA", t134, 1},
    {"\xE5\x95\x86", t135, 2},
    {"\xE5\x96\x9C", t136, 1},
    {"\xE5\x9B\x9E", t137, 4},
    {"\xE5\x9B\xA0", t138, 4},
    {"\xE5\x9B\xB0", t139, 1},
    {"\xE5\x9B\xBD", t140, 5},
    {"\xE5\x9B\xBE", t141, 1},
    {"\xE5\x9C\x9F", t142, 1},
    {"\xE5\x9C\xB0", t143, 5},
    {"\xE5\x9D\x90", t144, 1},
    {"\xE5\x9D\x9A", t145, 1},
    {"\xE5\x9F\x8E", t146, 2},
    {"\xE5\x9F\xB9", t147, 1},
    {"\xE5\x9F\xBA", t148, 3},
    {"\xE5\xA2\x83", t149, 1},
    {"\xE5\xA2\x9E", t150, 2},
    {"\xE5\xA3\xB0", t151, 1},
    {"\xE5\xA4\x84", t152, 2},
    {"\xE5\xA4\x8D", t153, 1},
    {"\xE5\xA4\x96", t154, 2},
    {"\xE5\xA4\x9A", t155, 4},
    {"\xE5\xA4\xA7", t156, 9},
    {"\xE5\xA4\xA9", t157, 3},
    {"\xE5\xA4\xAB", t158, 1},
    {"\xE5\xA5\xB3", t159, 3},
    {"\xE5\xA5\xB9", t160, 1},
    {"\xE5\xA5\xBD", t161, 1},
    {"\xE5\xA6\x82", t162, 4},
    {"\xE5\xA6\x87", t163, 1},
    {"\xE5\xA7\x8B", t164, 1},
    {"\xE5\xA7\x91", t165, 1},
    {"\xE5\xA7\x94", t166, 2},
    {"\xE5\xAA\x92", t167, 1},
    {"\xE5\xAD\x98", t168, 1},
    {"\xE5\xAD\xA6", t169, 4},
    {"\xE5\xAD\xA9", t170, 1},
    {"\xE5\xAE\x83", t171, 1},
    {"\xE5\xAE\x89", t172, 2},
    {"\xE5\xAE\x8C", t173, 3},
    {"\xE5\xAE\x97", t174, 1},
    {"\xE5\xAE\x98", t175, 1},
    {"\xE5\xAE\x9C", t176, 1},
    {"\xE5\xAE\x9E", t177, 8},
    {"\xE5\xAE\xA3", t178, 1},
    {"\xE5\xAE\xAA", t179, 1},
    {"\xE5\xAE\xB6", t180, 2},
    {"\xE5\xAE\xB9", t181, 1},
    {"\xE5\xAF\xB9", t182, 2},
    {"\xE5\xAF\xBC", t183, 2},
    {"\xE5\xB0\x81", t184, 1},
    {"\xE5\xB0\x86", t185, 1},
    {"\xE5\xB0\x8F", t186, 2},
    {"\xE5\xB0\xA4", t187, 1},
    {"\xE5\xB0\xB1", t188, 2},
    {"\xE5\xB0\xBD", t189, 1},
    {"\xE5\xB1\x85", t190, 1},
    {"\xE5\xB1\x95", t191, 1},
    {"\xE5\xB1\x9E", t192, 1},
    {"\xE5\xB7\xA5", t193, 4},
    {"\xE5\xB7\xA6", t194, 1},
    {"\xE5\xB7\xA8", t195, 1},
    {"\xE5\xB7\xB2", t196, 1},
    {"\xE5\xB8\x82", t197, 2},
    {"\xE5\xB8\x88", t198, 1},
    {"\xE5\xB8\x8C", t199, 1},
    {"\xE5\xB8\x9D", t200, 1},
    {"\xE5\xB8\xA6", t201, 1},
    {"\xE5\xB8\xAE", t202, 1},
    {"\xE5\xB8\xB8", t203, 1},
    {"\xE5\xB9\xB2", t204, 1},
    {"\xE5\xB9\xB3", t205, 4},
    {"\xE5\xB9\xB4", t206, 1},
    {"\xE5\xB9\xB6", t207, 1},
    {"\xE5\xB9\xBF", t208, 3},
    {"\xE5\xBA\x94", t209, 3},
    {"\xE5\xBB\xBA", t210, 5},
    {"\xE5\xBC\x80", t211, 4},
    {"\xE5\xBC\x95", t212, 1},
    {"\xE5\xBC\x9F", t213, 1},
    {"\xE5\xBC\xBA", t214, 1},
    {"\xE5\xBD\x93", t215, 4},
    {"\xE5\xBD\xA2", t216, 3},
    {"\xE5\xBD\xB1", t217, 1},
    {"\xE5\xBE\x80", t218, 1},
    {"\xE5\xBE\x88", t219, 2},
    {"\xE5\xBE\x97", t220, 1},
    {"\xE5\xBE\xB7", t221, 1},
    {"\xE5\xBF\x83", t222, 4},
    {"\xE5\xBF\x85", t223, 1},
    {"\xE5\xBF\xBD", t224, 1},
    {"\xE6\x80\x8E", t225, 2},
    {"\xE6\x80\x9D", t226, 1},
    {"\xE6\x80\xA7", t227, 1},
    {"\xE6\x80\xBB", t228, 3},
    {"\xE6\x81\xA2", t229, 1},
    {"\xE6\x83\x85", t230, 1},
    {"\xE6\x83\xB3", t231, 1},
    {"\xE6\x84\x8F", t232, 3},
    {"\xE6\x84\x9F", t233, 2},
    {"\xE6\x84\xBF", t234, 1},
    {"\xE6\x88\x90", t235, 5},
    {"\xE6\x88\x91", t236, 2},
    {"\xE6\x88\x96", t237, 1},
    {"\xE6\x88\x98", t238, 3},
    {"\xE6\x89\x80", t239, 3},
    {"\xE6\x89\x8B", t240, 2},
    {"\xE6\x89\xA7", t241, 1},
    {"\xE6\x89\xA9", t242, 1},
    {"\xE6\x89\xB9", t243, 1},
    {"\xE6\x89\xBE", t244, 1},
    {"\xE6\x8A\x80", t245, 1},
    {"\xE6\x8A\x95", t246, 2},
    {"\xE6\x8A\xA5", t247, 2},
    {"\xE6\x8B\x85", t248, 1},
    {"\xE6\x8B\x9B", t249, 1},
    {"\xE6\x8B\xA5", t250, 1},
    {"\xE6\x8C\x87", t251, 3},
    {"\xE6\x8C\x89", t252, 1},
    {"\xE6\x8E\x8C", t253, 1},
    {"\xE6\x8E\xA5", t254, 2},
    {"\xE6\x8E\xA7", t255, 1},
    {"\xE6\x8E\xAA", t256, 1},
    {"\xE6\x8F\x90", t257, 3},
    {"\xE6\x94\xAF", t258, 1},
    {"\xE6\x94\xB6", t259, 1},
    {"\xE6\x94\xB9", t260, 2},
    {"\xE6\x94\xBB", t261, 1},
    {"\xE6\x94\xBE", t262, 1},
    {"\xE6\x94\xBF", t263, 5},
    {"\xE6\x95\x85", t264, 1},
    {"\xE6\x95\x8C", t265, 1},
    {"\xE6\x95\x99", t266, 3},
    {"\xE6\x95\xB0", t267, 2},
    {"\xE6\x95\xB4", t268, 1},
    {"\xE6\x96\x87", t269, 4},
    {"\xE6\x96\x97", t270, 1},
    {"\xE6\x96\xB0", t271, 1},
    {"\xE6\x96\xB9", t272, 5},
    {"\xE6\x97\x85", t273, 1},
    {"\xE6\x97\xA0", t274, 1},
    {"\xE6\x97\xA2", t275, 1},
    {"\xE6\x97\xA5", t276, 1},
    {"\xE6\x97\xB6", t277, 4},
    {"\xE6\x98\x8E", t278, 3},
    {"\xE6\x98\xAF", t279, 2},
    {"\xE6\x98\xBE", t280, 1},
    {"\xE6\x99\x9A", t281, 1},
    {"\xE6\x99\xAE", t282, 2},
    {"\xE6\x9B\xB4", t283, 1},
    {"\xE6\x9B\xBE", t284, 1},
    {"\xE6\x9C\x80", t285, 5},
    {"\xE6\x9C\x89", t286, 6},
    {"\xE6\x9C\x8B", t287, 1},
    {"\xE6\x9C\x8D", t288, 1},
    {"\xE6\x9C\x9F", t289, 1},
    {"\xE6\x9C\xAA", t290, 1},
    {"\xE6\x9C\xAC", t291, 4},
    {"\xE6\x9C\xBA", t292, 5},
    {"\xE6\x9D\x83", t293, 2},
    {"\xE6\x9D\x8E", t294, 1},
    {"\xE6\x9D\x90", t295, 1},
    {"\xE6\x9D\xA1", t296, 1},
    {"\xE6\x9D\xA5", t297, 3},
    {"\xE6\x9E\x84", t298, 1},
    {"\xE6\x9F\x90", t299, 1},
    {"\xE6\xA0\x87", t300, 1},
    {"\xE6\xA0\xB7", t301, 1},
    {"\xE6\xA0\xB9", t302, 2},
    {"\xE6\xA3\x80", t303, 2},
    {"\xE6\xA4\x8D", t304, 1},
    {"\xE6\xAC\xA7", t305, 1},
    {"\xE6\xAD\xA3", t306, 4},
    {"\xE6\xAD\xA4", t307, 2},
    {"\xE6\xAD\xA6", t308, 4},
    {"\xE6\xAF\x8D", t309, 1},
    {"\xE6\xAF\x8F", t310, 3},
    {"\xE6\xAF\x94", t311, 4},
    {"\xE6\xAF\x95", t312, 1},
    {"\xE6\xAF\x9B", t313, 1},
    {"\xE6\xAF\xAB", t314, 1},
    {"\xE6\xB0\x91", t315, 2},
    {"\xE6\xB0\x94", t316, 1},
    {"\xE6\xB0\xB4", t317, 1},
    {"\xE6\xB1\xBD", t318, 1},
    {"\xE6\xB2\xA1", t319, 1},
    {"\xE6\xB2\xBB", t320, 1},
    {"\xE6\xB3\x95", t321, 3},
    {"\xE6\xB3\xA8", t322, 1},
    {"\xE6\xB4\xBB", t323, 1},
    {"\xE6\xB5\xB7", t324, 2},
    {"\xE6\xB6\x88", t325, 1},
    {"\xE6\xB8\x85", t326, 1},
    {"\xE6\xB9\x96", t327, 2},
    {"\xE7\x84\xB6", t328, 2},
    {"\xE7\x88\xB1", t329, 1},
    {"\xE7\x88\xB6", t330, 2},
    {"\xE7\x89\xA9", t331, 1},
    {"\xE7\x89\xB9", t332, 5},
    {"\xE7\x8A\xB6", t333, 2},
    {"\xE7\x8B\xAC", t334, 1},
    {"\xE7\x8E\xAF", t335, 1},
    {"\xE7\x8E\xB0", t336, 4},
    {"\xE7\x90\x86", t337, 2},
    {"\xE7\x94\x9A", t338, 2},
    {"\xE7\x94\x9F", t339, 5},
    {"\xE7\x94\xA8", t340, 2},
    {"\xE7\x94\xB1", t341, 1},
    {"\xE7\x94\xB5", t342, 2},
    {"\xE7\x94\xB7", t343, 1},
    {"\xE7\x95\x99", t344, 1},
    {"\xE7\x99\xBE", t345, 2},
    {"\xE7\x9A\x87", t346, 2},
    {"\xE7\x9B\x91", t347, 1},
    {"\xE7\x9B\xAE", t348, 3},
    {"\xE7\x9B\xB4", t349, 2},
    {"\xE7\x9B\xB8", t350, 7},
    {"\xE7\x9C\x81", t351, 1},
    {"\xE7\x9C\x8B", t352, 5},
    {"\xE7\x9C\x9F", t353, 3},
    {"\xE7\x9C\xBC", t354, 1},
    {"\xE7\x9F\x9B", t355, 1},
    {"\xE7\x9F\xA5", t356, 2},
    {"\xE7\x9F\xB3", t357, 2},
    {"\xE7\xA0\x94", t358, 2},
    {"\xE7\xA1\xAE", t359, 2},
    {"\xE7\xA4\xBE", t360, 3},
    {"\xE7\xA6\xBB", t361, 1},
    {"\xE7\xA7\x91", t362, 2},
    {"\xE7\xA7\x98", t363, 1},
    {"\xE7\xA7\xAF", t364, 1},
    {"\xE7\xA7\xB0", t365, 1},
    {"\xE7\xA8\x8B", t366, 2},
    {"\xE7\xA8\xB3", t367, 1},
    {"\xE7\xA9\xBA", t368, 2},
    {"\xE7\xAA\x81", t369, 1},
    {"\xE7\xAB\x8B", t370, 2},
    {"\xE7\xAB\x9E", t371, 1},
    {"\xE7\xAB\x9F", t372, 1},
    {"\xE7\xAC\xAC", t373, 3},
    {"\xE7\xAD\x89", t374, 1},
    {"\xE7\xAE\x80", t375, 1},
    {"\xE7\xAE\xA1", t376, 1},
    {"\xE7\xB1\xBB", t377, 2},
    {"\xE7\xB2\xAE", t378, 1},
    {"\xE7\xB2\xBE", t379, 1},
    {"\xE7\xB3\xBB", t380, 1},
    {"\xE7\xBB\x84", t381, 2},
    {"\xE7\xBB\x86", t382, 1},
    {"\xE7\xBB\x88", t383, 1},
    {"\xE7\xBB\x8F", t384, 5},
    {"\xE7\xBB\x93", t385, 4},
    {"\xE7\xBB\x9F", t386, 3},
    {"\xE7\xBB\xA7", t387, 1},
    {"\xE7\xBB\xB4", t388, 1},
    {"\xE7\xBB\xBC", t389, 1},
    {"\xE7\xBC\x96", t390, 1},
    {"\xE7\xBD\x91", t391, 1},
    {"\xE7\xBE\x8E", t392, 2},
    {"\xE7\xBE\xA4", t393, 1},
    {"\xE8\x80\x81", t394, 1},
    {"\xE8\x80\x83", t395, 3},
    {"\xE8\x80\x8C", t396, 2},
    {"\xE8\x81\x8C", t397, 2},
    {"\xE8\x81\x94", t398, 2},
    {"\xE8\x82\xA1", t399, 2},
    {"\xE8\x82\xAF", t400, 1},
    {"\xE8\x83\x9C", t401, 1},
    {"\xE8\x83\xBD", t402, 2},
    {"\xE8\x84\xB8", t403, 1},
    {"\xE8\x87\xAA", t404, 5},
    {"\xE8\x87\xB3", t405, 1},
    {"\xE8\x88\xAA", t406, 1},
    {"\xE8\x89\xAF", t407, 1},
    {"\xE8\x89\xBA", t408, 1},
    {"\xE8\x8B\x8F", t409, 1},
    {"\xE8\x8B\xA5", t410, 1},
    {"\xE8\x8B\xB1", t411, 2},
    {"\xE8\x8C\x83", t412, 1},
    {"\xE8\x8D\x86", t413, 1},
    {"\xE8\x8E\xB7", t414, 1},
    {"\xE8\x91\x97", t415, 1},
    {"\xE8\x92\x99", t416, 1},
    {"\xE8\x99\xBD", t417, 1},
    {"\xE8\xA1\x8C", t418, 5},
    {"\xE8\xA1\xA8", t419, 2},
    {"\xE8\xA3\x85", t420, 1},
    {"\xE8\xA5\x84", t421, 1},
    {"\xE8\xA5\xBF", t422, 4},
    {"\xE8\xA6\x81", t423, 1},
    {"\xE8\xA7\x81", t424, 1},
    {"\xE8\xA7\x84", t425, 3},
    {"\xE8\xA7\x89", t426, 1},
    {"\xE8\xA7\xA3", t427, 2},
    {"\xE8\xAE\xA1", t428, 2},
    {"\xE8\xAE\xA4", t429, 2},
    {"\xE8\xAE\xA8", t430, 1},
    {"\xE8\xAE\xAD", t431, 1},
    {"\xE8\xAE\xB0", t432, 1},
    {"\xE8\xAE\xB8", t433, 1},
    {"\xE8\xAE\xBE", t434, 3},
    {"\xE8\xAF\x81", t435, 1},
    {"\xE8\xAF\x8D", t436, 1},
    {"\xE8\xAF\xAD", t437, 1},
    {"\xE8\xAF\xB4", t438, 3},
    {"\xE8\xB0\x83", t439, 2},
    {"\xE8\xB4\x9F", t440, 1},
    {"\xE8\xB4\xA1", t441, 1},
    {"\xE8\xB4\xA2", t442, 2},
    {"\xE8\xB4\xA3", t443, 1},
    {"\xE8\xB4\xA7", t444, 1},
    {"\xE8\xB4\xA8", t445, 1},
    {"\xE8\xB4\xB5", t446, 1},
    {"\xE8\xB4\xB8", t447, 1},
    {"\xE8\xB5\x84", t448, 4},
    {"\xE8\xB5\xB7", t449, 1},
    {"\xE8\xB6\x85", t450, 1},
    {"\xE8\xB6\x8A", t451, 1},
    {"\xE8\xBA\xAB", t452, 4},
    {"\xE8\xBE\x83", t453, 1},
    {"\xE8\xBE\xBE", t454, 1},
    {"\xE8\xBF\x85", t455, 1},
    {"\xE8\xBF\x87", t456, 3},
    {"\xE8\xBF\x90", t457, 2},
    {"\xE8\xBF\x98", t458, 3},
    {"\xE8\xBF\x99", t459, 9},
    {"\xE8\xBF\x9B", t460, 5},
    {"\xE8\xBF\x9E", t461, 1},
    {"\xE9\x80\x82", t462, 2},
    {"\xE9\x80\x89", t463, 2},
    {"\xE9\x80\x90", t464, 1},
    {"\xE9\x80\x9A", t465, 2},
    {"\xE9\x80\x9F", t466, 1},
    {"\xE9\x80\xA0", t467, 1},
    {"\xE9\x81\x93", t468, 1},
    {"\xE9\x81\x97", t469, 1},
    {"\xE9\x82\xA3", t470, 5},
    {"\xE9\x83\xA8", t471, 4},
    {"\xE9\x87\x87", t472, 2},
    {"\xE9\x87\x8C", t473, 1},
    {"\xE9\x87\x8D", t474, 5},
    {"\xE9\x87\x91", t475, 1},
    {"\xE9\x93\x81", t476, 1},
    {"\xE9\x93\xB6", t477, 1},
    {"\xE9\x94\x80", t478, 1},
    {"\xE9\x94\x99", t479, 1},
    {"\xE9\x95\xBF", t480, 3},
    {"\xE9\x97\xAE", t481, 2},
    {"\xE9\x98\x9F", t482, 1},
    {"\xE9\x98\xB6", t483, 1},
    {"\xE9\x99\x84", t484, 1},
    {"\xE9\x99\xA2", t485, 1},
    {"\xE9\x99\xA4", t486, 1},
    {"\xE9\x9A\x8F", t487, 1},
    {"\xE9\x9A\xBE", t488, 2},
    {"\xE9\x9B\x86", t489, 2},
    {"\xE9\x9C\x80", t490, 2},
    {"\xE9\x9D\x92", t491, 1},
    {"\xE9\x9D\x9E", t492, 1},
    {"\xE9\x9D\xA2", t493, 3},
    {"\xE9\x9D\xA9", t494, 1},
    {"\xE9\x9F\xA6", t495, 1},
    {"\xE9\x9F\xB3", t496, 1},
    {"\xE9\xA1\xB9", t497, 1},
    {"\xE9\xA2\x86", t498, 2},
    {"\xE9\xA3\x9E", t499, 1},
    {"\xE9\xA3\x9F", t500, 1},
    {"\xE9\xA6\x96", t501, 1},
    {"\xE9\xA6\x99", t502, 1},
    {"\xE9\xAB\x98", t503, 4},
};
static const int kCjkGroupCount = 504;

#endif /* WHALEUI_CJK_DICT_LITE_H */
