#ifndef WHALEUI_CJK_DICT_H
#define WHALEUI_CJK_DICT_H

/* Runtime CJK dictionary for word navigation, loaded from
 * res/whaleui_dict.bin (generated by tools/gen_cjk_dict.py).
 *
 * The binary format is grouped by head character (each head stored once,
 * tails repeat) so the full 330k-word lexicon fits in ~2 MB. The loader
 * validates the magic + version, searches a few well-known locations
 * (exe dir, ./res, cwd) and falls back to a tiny built-in list when the
 * file is missing or damaged, so word jumps never silently break.
 *
 * Full and lite builds use the same file (full lexicon); minimal builds do
 * no segmentation and never touch this. */

#ifdef __cplusplus
extern "C" {
#endif

/* 1 when a dictionary is available (file loaded or built-in fallback) */
int whaleui_cjk_dict_ready(void);

/* is `w` (a 2-4 hanzi word) in the dictionary? */
int whaleui_cjk_dict_has(const char* w, int len);

/* explicit load; 0 on success. Auto-loading on first use is the norm, so
 * callers only need this to override the search path. */
int whaleui_cjk_dict_load(const char* path);

#ifdef __cplusplus
}
#endif

#endif /* WHALEUI_CJK_DICT_H */
