/* render_paint.cpp - paint primitives (fill/blend/rounded/border/shadow/img) and the paint_node dispatch. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include "animate/animate.h"
#include <SDL3/SDL.h>
#ifdef WHALEUI_BUILD_FULL
#include <SDL3_image/SDL_image.h>
#else
/* stb_image decode (lite/minimal have no SDL_image) */
#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>
#endif

#include <lexbor/dom/dom.h>

#include <algorithm>
#include <cmath>
#include <cstring>
#include <string>
#include <vector>
/* (struct Clip lives in render_internal.h) */

void dirty_rect(int x0, int y0, int x1, int y1, Clip* out)
{
    if (!out) {
        return;
    }
    if (out->w <= 0 || out->h <= 0) {
        out->x = x0;
        out->y = y0;
        out->w = x1 - x0;
        out->h = y1 - y0;
        return;
    }
    int ax0 = out->x < x0 ? out->x : x0;
    int ay0 = out->y < y0 ? out->y : y0;
    int ax1 = (out->x + out->w) > x1 ? (out->x + out->w) : x1;
    int ay1 = (out->y + out->h) > y1 ? (out->y + out->h) : y1;
    out->x = ax0;
    out->y = ay0;
    out->w = ax1 - ax0;
    out->h = ay1 - ay0;
}

void clip_rect(int& x0, int& y0, int& x1, int& y1, const Clip* clip)
{
    if (!clip || clip->w <= 0 || clip->h <= 0) {
        return;
    }
    int cx0 = clip->x, cy0 = clip->y;
    int cx1 = clip->x + clip->w, cy1 = clip->y + clip->h;
    if (x0 < cx0) { x0 = cx0; }
    if (y0 < cy0) { y0 = cy0; }
    if (x1 > cx1) { x1 = cx1; }
    if (y1 > cy1) { y1 = cy1; }
}

void fill_rect(std::vector<unsigned int>& fb, int fbw, int fbh,
               int x, int y, int w, int h, unsigned int color, const Clip* clip)
{
    if (g_gpu) {
        int c[4];
        const int* cp = nullptr;
        if (clip) {
            c[0] = clip->x;
            c[1] = clip->y;
            c[2] = clip->w;
            c[3] = clip->h;
            cp = c;
        }
        whaleui_gpu_rect(g_gpu, static_cast<float>(x), static_cast<float>(y),
                         static_cast<float>(w), static_cast<float>(h),
                         0.0f, color, cp);
        return;
    }
    if (w <= 0 || h <= 0) {
        return;
    }
    int x0 = x < 0 ? 0 : x;
    int y0 = y < 0 ? 0 : y;
    int x1 = x + w > fbw ? fbw : x + w;
    int y1 = y + h > fbh ? fbh : y + h;
    clip_rect(x0, y0, x1, y1, clip);
    unsigned int a = (color >> 24) & 0xFF;
    if (a == 0 || x1 <= x0 || y1 <= y0) {
        return;
    }
    if (a == 255) {
        for (int yy = y0; yy < y1; ++yy) {
            std::fill(fb.begin() + static_cast<size_t>(yy) * fbw + x0,
                      fb.begin() + static_cast<size_t>(yy) * fbw + x1, color);
        }
        return;
    }
    unsigned int r = (color >> 16) & 0xFF, g = (color >> 8) & 0xFF, b = color & 0xFF;
    for (int yy = y0; yy < y1; ++yy) {
        for (int xx = x0; xx < x1; ++xx) {
            unsigned int& d = fb[static_cast<size_t>(yy) * fbw + xx];
            unsigned int dr = (d >> 16) & 0xFF, dg = (d >> 8) & 0xFF, db = d & 0xFF;
            unsigned int nr = (r * a + dr * (255 - a)) / 255;
            unsigned int ng = (g * a + dg * (255 - a)) / 255;
            unsigned int nb = (b * a + db * (255 - a)) / 255;
            d = 0xFF000000 | (nr << 16) | (ng << 8) | nb;
        }
    }
}

bool inside_rounded(int px, int py, int x, int y, int w, int h, int radius)
{
    if (w <= 0 || h <= 0) {
        return false;
    }
    if (radius <= 0) {
        return px >= x && px < x + w && py >= y && py < y + h;
    }
    long dx = 0, dy = 0;
    if (px < x + radius) {
        dx = static_cast<long>(x + radius - px);
    } else if (px >= x + w - radius) {
        dx = static_cast<long>(px - (x + w - radius)) + 1;
    }
    if (py < y + radius) {
        dy = static_cast<long>(y + radius - py);
    } else if (py >= y + h - radius) {
        dy = static_cast<long>(py - (y + h - radius)) + 1;
    }
    if (dx != 0 || dy != 0) {
        long r2 = static_cast<long>(radius) * radius;
        return dx * dx + dy * dy <= r2;
    }
    return true; /* in the middle band */
}

void fill_round_rect(std::vector<unsigned int>& fb, int fbw, int fbh,
                     int x, int y, int w, int h, int radius,
                     unsigned int color, const Clip* clip)
{
    if (g_gpu) {
        int c[4];
        const int* cp = nullptr;
        if (clip) {
            c[0] = clip->x;
            c[1] = clip->y;
            c[2] = clip->w;
            c[3] = clip->h;
            cp = c;
        }
        whaleui_gpu_rect(g_gpu, static_cast<float>(x), static_cast<float>(y),
                         static_cast<float>(w), static_cast<float>(h),
                         static_cast<float>(radius), color, cp);
        return;
    }
    if (radius <= 0) {
        fill_rect(fb, fbw, fbh, x, y, w, h, color, clip);
        return;
    }
    int half = w < h ? w / 2 : h / 2;
    if (radius > half) {
        radius = half;
    }
    int x0 = x < 0 ? 0 : x;
    int y0 = y < 0 ? 0 : y;
    int x1 = x + w > fbw ? fbw : x + w;
    int y1 = y + h > fbh ? fbh : y + h;
    clip_rect(x0, y0, x1, y1, clip);
    unsigned int a = (color >> 24) & 0xFF;
    if (a == 0 || x1 <= x0 || y1 <= y0) {
        return;
    }
    unsigned int r = (color >> 16) & 0xFF, g = (color >> 8) & 0xFF, b = color & 0xFF;
    for (int yy = y0; yy < y1; ++yy) {
        for (int xx = x0; xx < x1; ++xx) {
            if (!inside_rounded(xx, yy, x, y, w, h, radius)) {
                continue; /* outside the rounded corner */
            }
            unsigned int& d = fb[static_cast<size_t>(yy) * fbw + xx];
            unsigned int dr = (d >> 16) & 0xFF, dg = (d >> 8) & 0xFF, db = d & 0xFF;
            if (a == 255) {
                d = color;
            } else {
                unsigned int nr = (r * a + dr * (255 - a)) / 255;
                unsigned int ng = (g * a + dg * (255 - a)) / 255;
                unsigned int nb = (b * a + db * (255 - a)) / 255;
                d = 0xFF000000 | (nr << 16) | (ng << 8) | nb;
            }
        }
    }
}

void fill_round_border(std::vector<unsigned int>& fb, int fbw, int fbh,
                       int x, int y, int w, int h, int radius, int bw,
                       unsigned int color, unsigned int bg, const Clip* clip)
{
    if (g_gpu) {
        /* ring via two rounded rects: outer in the border color, then the
         * inner rect re-filled with the element's background color */
        fill_round_rect(fb, fbw, fbh, x, y, w, h, radius, color, clip);
        int ix = x + bw, iy = y + bw, iw = w - 2 * bw, ih = h - 2 * bw;
        int irad = radius - bw;
        if (irad < 0) {
            irad = 0;
        }
        fill_round_rect(fb, fbw, fbh, ix, iy, iw, ih, irad, bg, clip);
        return;
    }
    if (bw <= 0) {
        return;
    }
    if (radius <= 0) {
        fill_rect(fb, fbw, fbh, x, y, w, bw, color, clip);               /* top */
        fill_rect(fb, fbw, fbh, x, y + h - bw, w, bw, color, clip);      /* bottom */
        fill_rect(fb, fbw, fbh, x + w - bw, y, bw, h, color, clip);      /* right */
        fill_rect(fb, fbw, fbh, x, y, bw, h, color, clip);               /* left */
        return;
    }
    int half = w < h ? w / 2 : h / 2;
    if (radius > half) {
        radius = half;
    }
    int ix = x + bw, iy = y + bw, iw = w - 2 * bw, ih = h - 2 * bw;
    int irad = radius - bw;
    if (irad < 0) {
        irad = 0;
    }
    int x0 = x < 0 ? 0 : x;
    int y0 = y < 0 ? 0 : y;
    int x1 = x + w > fbw ? fbw : x + w;
    int y1 = y + h > fbh ? fbh : y + h;
    clip_rect(x0, y0, x1, y1, clip);
    unsigned int a = (color >> 24) & 0xFF;
    if (a == 0 || x1 <= x0 || y1 <= y0) {
        return;
    }
    unsigned int r = (color >> 16) & 0xFF, g = (color >> 8) & 0xFF, b = color & 0xFF;
    for (int yy = y0; yy < y1; ++yy) {
        for (int xx = x0; xx < x1; ++xx) {
            if (!inside_rounded(xx, yy, x, y, w, h, radius)) {
                continue; /* outside the outer rounded rect */
            }
            if (inside_rounded(xx, yy, ix, iy, iw, ih, irad)) {
                continue; /* inside the inner rect: that is the fill area */
            }
            unsigned int& d = fb[static_cast<size_t>(yy) * fbw + xx];
            unsigned int dr = (d >> 16) & 0xFF, dg = (d >> 8) & 0xFF, db = d & 0xFF;
            if (a == 255) {
                d = color;
            } else {
                unsigned int nr = (r * a + dr * (255 - a)) / 255;
                unsigned int ng = (g * a + dg * (255 - a)) / 255;
                unsigned int nb = (b * a + db * (255 - a)) / 255;
                d = 0xFF000000 | (nr << 16) | (ng << 8) | nb;
            }
        }
    }
}

void blend_surface(std::vector<unsigned int>& fb, int fbw, int fbh,
                   const SDL_Surface* surf, int dx, int dy, const Clip* clip,
                   const unsigned int* tint)
{
    if (!surf || !surf->pixels) {
        return;
    }
    const unsigned char* src = static_cast<const unsigned char*>(surf->pixels);
    int pitch = surf->pitch;
    unsigned int tr = tint ? (*tint >> 16) & 0xFF : 0;
    unsigned int tg = tint ? (*tint >> 8) & 0xFF : 0;
    unsigned int tb = tint ? *tint & 0xFF : 0;
    for (int y = 0; y < surf->h; ++y) {
        int ty = dy + y;
        if (ty < 0 || ty >= fbh) {
            continue;
        }
        if (clip && (ty < clip->y || ty >= clip->y + clip->h)) {
            continue;
        }
        for (int x = 0; x < surf->w; ++x) {
            int tx = dx + x;
            if (tx < 0 || tx >= fbw) {
                continue;
            }
            if (clip && (tx < clip->x || tx >= clip->x + clip->w)) {
                continue;
            }
            const unsigned char* s = src + static_cast<size_t>(y) * pitch + static_cast<size_t>(x) * 4;
            unsigned int a = s[3];
            if (a == 0) {
                continue;
            }
            unsigned int sr = tint ? tr : s[0];
            unsigned int sg = tint ? tg : s[1];
            unsigned int sb = tint ? tb : s[2];
            unsigned int& d = fb[static_cast<size_t>(ty) * fbw + tx];
            if (a == 255) {
                /* opaque: no blending math (hot path for anti-aliased
                 * glyph cores; text is the biggest per-frame cost) */
                d = 0xFF000000 | (sr << 16) | (sg << 8) | sb;
                continue;
            }
            unsigned int dr = (d >> 16) & 0xFF, dg = (d >> 8) & 0xFF, db = d & 0xFF;
            unsigned int nr = (sr * a + dr * (255 - a)) / 255;
            unsigned int ng = (sg * a + dg * (255 - a)) / 255;
            unsigned int nb = (sb * a + db * (255 - a)) / 255;
            d = 0xFF000000 | (nr << 16) | (ng << 8) | nb;
        }
    }
}

int parse_shadow(const std::string& v, int& ox, int& oy, int& blur,
                 unsigned int& col)
{
    ox = oy = blur = 0;
    col = 0;
    std::vector<std::string> tok;
    const char* p = v.c_str();
    while (*p) {
        while (*p == ' ' || *p == '\t') {
            ++p;
        }
        if (!*p) {
            break;
        }
        const char* s = p;
        while (*p && *p != ' ' && *p != '\t') {
            ++p;
        }
        tok.emplace_back(s, static_cast<size_t>(p - s));
    }
    int nums[3] = {0, 0, 0};
    size_t ni = 0;
    std::string colstr;
    for (size_t i = 0; i < tok.size(); ++i) {
        const std::string& t = tok[i];
        if (ni < 3 && !t.empty() &&
            (t[0] == '-' || (t[0] >= '0' && t[0] <= '9'))) {
            nums[ni++] = std::atoi(t.c_str());
        } else if (!colstr.empty()) {
            colstr += ' ';
            colstr += t;
        } else {
            colstr = t;
        }
    }
    ox = nums[0];
    oy = nums[1];
    blur = nums[2];
    if (blur <= 0 || colstr.empty()) {
        return -1;
    }
    return whaleui_render_parse_color(colstr.c_str(), &col);
}

int parse_shadow_any(const std::string& v, int& ox, int& oy, int& blur,
                     unsigned int& col)
{
    int rc = parse_shadow(v, ox, oy, blur, col);
    if (rc != 0) {
        /* retry allowing zero blur: split tokens and treat the color as
         * the last token */
        std::vector<std::string> tok;
        const char* p = v.c_str();
        while (*p) {
            while (*p == ' ' || *p == '\t') {
                ++p;
            }
            if (!*p) {
                break;
            }
            const char* s = p;
            while (*p && *p != ' ' && *p != '\t') {
                ++p;
            }
            tok.emplace_back(s, static_cast<size_t>(p - s));
        }
        ox = oy = blur = 0;
        col = 0;
        int nums[2] = {0, 0};
        size_t ni = 0;
        std::string colstr;
        for (size_t i = 0; i < tok.size(); ++i) {
            const std::string& t = tok[i];
            if (ni < 2 && !t.empty() &&
                (t[0] == '-' || (t[0] >= '0' && t[0] <= '9'))) {
                nums[ni++] = std::atoi(t.c_str());
            } else if (!colstr.empty()) {
                colstr += ' ';
                colstr += t;
            } else {
                colstr = t;
            }
        }
        ox = nums[0];
        oy = nums[1];
        if (colstr.empty()) {
            return -1;
        }
        return whaleui_render_parse_color(colstr.c_str(), &col);
    }
    return rc;
}

std::vector<std::string> split_space2(const std::string& v)
{
    std::vector<std::string> out;
    const char* p = v.c_str();
    while (*p) {
        while (*p == ' ' || *p == '\t') {
            ++p;
        }
        if (!*p) {
            break;
        }
        const char* s = p;
        while (*p && *p != ' ' && *p != '\t') {
            ++p;
        }
        out.emplace_back(s, static_cast<size_t>(p - s));
    }
    return out;
}

void paint_shadow(whaleui_render_t* r, whaleui_layout_node_t* n,
                  int off_x, int off_y, const Clip* clip)
{
    std::string v = sget(n->style, "box-shadow");
    if (v.empty() || v == "none") {
        return;
    }
    /* "inset" prefix: the shadow projects inward from the box edges */
    bool inset = false;
    if (v.compare(0, 5, "inset") == 0 &&
        (v.size() == 5 || v[5] == ' ' || v[5] == '\t')) {
        inset = true;
        v = v.substr(5);
    }
    int ox = 0, oy = 0, blur = 0;
    unsigned int col = 0;
    if (parse_shadow(v, ox, oy, blur, col) != 0) {
        return;
    }
    /* off-screen shadows cost nothing */
    int sx0 = n->border.x + off_x + ox - blur;
    int sy0 = n->border.y + off_y + oy - blur;
    if (sx0 + n->border.w + 2 * blur <= 0 || sx0 >= r->fb_w ||
        sy0 + n->border.h + 2 * blur <= 0 || sy0 >= r->fb_h) {
        return;
    }
    int radius = 0;
    std::string br = sget(n->style, "border-radius");
    if (!br.empty()) {
        radius = std::atoi(br.c_str());
    }
    unsigned int a = (col >> 24) & 0xFF;
    if (a == 0) {
        return;
    }
    /* GPU path: the mipmap blur approximation (blur_tex + multi-level
     * resampling) - one shape + one sampling quad instead of blur/2
     * concentric fills. Inset shadows blend the blurred gradient over the
     * painted geometry (after the geometry pass). */
    if (g_gpu) {
        if (inset) {
            whaleui_gpu_inset(g_gpu,
                              static_cast<float>(n->border.x + off_x),
                              static_cast<float>(n->border.y + off_y),
                              static_cast<float>(n->border.w),
                              static_cast<float>(n->border.h),
                              static_cast<float>(radius),
                              static_cast<float>(blur), col);
        } else {
            whaleui_gpu_shadow(g_gpu,
                               static_cast<float>(n->border.x + off_x + ox),
                               static_cast<float>(n->border.y + off_y + oy),
                               static_cast<float>(n->border.w),
                               static_cast<float>(n->border.h),
                               static_cast<float>(radius),
                               static_cast<float>(blur), col);
        }
        return;
    }
    /* concentric layers, alpha fading outwards (inset: inwards); skip the
     * near-invisible outermost ring and step by 2px (half the fill cost,
     * gradient still smooth) */
    for (int k = (blur > 0 ? blur - 1 : 0); k >= 1; k -= 2) {
        unsigned int ka = static_cast<unsigned>(a * (blur - k + 1) / (blur + 1));
        if (ka < 4) {
            continue;
        }
        unsigned int c = (ka << 24) | (col & 0x00FFFFFF);
        int sx, sy, sw, sh;
        if (inset) {
            /* inward: each layer is the box shrunk by k */
            sx = n->border.x + off_x + k;
            sy = n->border.y + off_y + k;
            sw = n->border.w - 2 * k;
            sh = n->border.h - 2 * k;
            if (sw <= 0 || sh <= 0) {
                continue;
            }
        } else {
            sx = n->border.x + off_x + ox - k;
            sy = n->border.y + off_y + oy - k;
            sw = n->border.w + 2 * k;
            sh = n->border.h + 2 * k;
        }
        if (radius > 0) {
            fill_round_rect(r->pixels, r->fb_w, r->fb_h, sx, sy, sw, sh,
                            radius, c, clip);
        } else {
            fill_rect(r->pixels, r->fb_w, r->fb_h, sx, sy, sw, sh, c, clip);
        }
    }
}

SDL_Surface* img_surface(whaleui_render_t* r, const std::string& src)
{
    if (src.empty()) {
        return nullptr;
    }
    auto it = r->images.find(src);
    if (it != r->images.end()) {
        return it->second;
    }
    SDL_Surface* s = nullptr;
    if (src.compare(0, 7, "http://") != 0 &&
        src.compare(0, 8, "https://") != 0 &&
        src.compare(0, 5, "data:") != 0) {
        std::string path = src;
        if (path.compare(0, 7, "file://") == 0) {
            path = path.substr(7);
            if (!path.empty() && (path[0] == '/' || path[0] == '\\')) {
                path = path.substr(1); /* file:///C:/x -> C:/x */
            }
        }
#ifdef WHALEUI_BUILD_FULL
        s = IMG_Load(path.c_str());
#else
        /* stb_image decode (lite/minimal have no SDL_image) */
        int iw = 0, ih = 0, ich = 0;
        unsigned char* px = stbi_load(path.c_str(), &iw, &ih, &ich, 4);
        if (px && iw > 0 && ih > 0) {
            s = SDL_CreateSurface(iw, ih, SDL_PIXELFORMAT_RGBA32);
            if (s) {
                std::memcpy(s->pixels, px, static_cast<size_t>(iw) * ih * 4);
            }
        }
        if (px) {
            stbi_image_free(px);
        }
#endif
    }
    r->images[src] = s;
    return s;
}

void paint_img(whaleui_render_t* r, whaleui_layout_node_t* n, int off_x,
               int off_y, const Clip* clip)
{
    size_t alen = 0;
    const lxb_char_t* src = lxb_dom_element_get_attribute(
        n->el, (const lxb_char_t*)"src", 3, &alen);
    std::string srcs = src ? std::string(reinterpret_cast<const char*>(src),
                                         alen)
                           : std::string();
    int x = n->border.x + off_x;
    int y = n->border.y + off_y;
    int w = n->border.w;
    int h = n->border.h;
    if (x + w <= 0 || y + h <= 0 || x >= r->fb_w || y >= r->fb_h) {
        return;
    }
    SDL_Surface* img = img_surface(r, srcs);
    if (img && img->w > 0 && img->h > 0) {
        /* object-fit: cover keeps the aspect and crops, contain letterboxes,
         * fill (default) stretches */
        std::string of = sget(n->style, "object-fit");
        int dw = w, dh = h, dx = x, dy = y;
        if (of == "cover" || of == "contain") {
            float ar = static_cast<float>(img->w) / img->h;
            float dar = w > 0 ? static_cast<float>(w) / h : 1.0f;
            if ((of == "cover") == (ar > dar)) {
                dh = static_cast<int>(w / ar);
                dy = y + (h - dh) / 2;
            } else {
                dw = static_cast<int>(h * ar);
                dx = x + (w - dw) / 2;
            }
        }
        if (dw > 0 && dh > 0) {
            SDL_Surface* scaled = SDL_ScaleSurface(img, dw, dh,
                                                   SDL_SCALEMODE_LINEAR);
            if (scaled) {
                if (g_gpu) {
                    blend_surface(r->text_layer, r->fb_w, r->fb_h, scaled,
                                  dx, dy, clip, nullptr);
                } else {
                    blend_surface(r->pixels, r->fb_w, r->fb_h, scaled,
                                  dx, dy, clip, nullptr);
                }
                SDL_DestroySurface(scaled);
            }
        }
        return;
    }
    /* placeholder box: dim fill + hairline border, so broken images still
     * occupy their laid-out space visibly */
    unsigned int dim = 0xFF2A2E38;
    fill_rect(r->pixels, r->fb_w, r->fb_h, x, y, w, h, dim, clip);
    unsigned int edge = 0xFF3A4150;
    fill_rect(r->pixels, r->fb_w, r->fb_h, x, y, w, 1, edge, clip);
    fill_rect(r->pixels, r->fb_w, r->fb_h, x, y + h - 1, w, 1, edge, clip);
    fill_rect(r->pixels, r->fb_w, r->fb_h, x, y, 1, h, edge, clip);
    fill_rect(r->pixels, r->fb_w, r->fb_h, x + w - 1, y, 1, h, edge, clip);
}

void compute_paint_bounds(whaleui_layout_node_t* n)
{
    whaleui_rect_t b = n->border;
    for (whaleui_layout_node_t* c = n->first_child; c; c = c->next) {
        if (!c->visible) {
            continue;
        }
        compute_paint_bounds(c);
        int x0 = b.x, y0 = b.y, x1 = b.x + b.w, y1 = b.y + b.h;
        int cx0 = c->bounds.x, cy0 = c->bounds.y;
        int cx1 = c->bounds.x + c->bounds.w, cy1 = c->bounds.y + c->bounds.h;
        if (cx0 < x0) x0 = cx0;
        if (cy0 < y0) y0 = cy0;
        if (cx1 > x1) x1 = cx1;
        if (cy1 > y1) y1 = cy1;
        b.x = x0;
        b.y = y0;
        b.w = x1 - x0;
        b.h = y1 - y0;
    }
    n->bounds = b;
}

const int kCullMargin = 64;

/* z-order: elements that paint on top of normal flow ("high roots").
 * Unified bottom-layer rule, NOT per-element special-casing: anything
 * with z-index > 0 or a fixed/sticky position gets its own paint layer
 * (UA default CSS raises popup/fixed elements). */
bool is_high_root(const whaleui_layout_node_t* n)
{
    if (!n->el || n->is_text) {
        return false;
    }
    return n->hz || n->fx || n->sk;
}

/* should a high root clear the old text under it? Only when its own
 * background is (near-)opaque: then it occludes the lower layers and the
 * text_layer's "text always on top" composite must not let the lower
 * glyphs show through. Semi-transparent high roots (a blur header, a
 * noise overlay) leave the lower text in place - it shows through their
 * background, which is the correct CSS stacking. */
static bool high_root_occludes(const whaleui_layout_node_t* n)
{
    if (!is_high_root(n)) {
        return false;
    }
    unsigned int bg = color_of(n->style, "background-color", 0);
    if (bg == 0) {
        bg = color_of(n->style, "background", 0);
    }
    return ((bg >> 24) & 0xFF) >= 250;
}

/* clear a rectangle of the text layer (the old glyphs underneath a
 * higher layer's area must not survive the composite) */
void text_layer_clear(whaleui_render_t* r, int x, int y, int w, int h)
{
    if (x < 0) {
        w += x;
        x = 0;
    }
    if (y < 0) {
        h += y;
        y = 0;
    }
    if (x + w > r->fb_w) {
        w = r->fb_w - x;
    }
    if (y + h > r->fb_h) {
        h = r->fb_h - y;
    }
    if (w <= 0 || h <= 0) {
        return;
    }
    for (int yy = y; yy < y + h; ++yy) {
        std::fill(r->text_layer.begin() + static_cast<size_t>(yy) * r->fb_w + x,
                  r->text_layer.begin() + static_cast<size_t>(yy) * r->fb_w + x + w,
                  0);
    }
}

void clear_subtree_text(whaleui_render_t* r,
                        whaleui_layout_node_t* nd, int off_x,
                        int off_y)
{
    if (!nd->visible) {
        return;
    }
    int nox = off_x, noy = off_y;
    if (nd->el && !nd->is_text && nd->fx) {
        nox = 0;
        noy = 0;
    }
    text_layer_clear(r, nd->border.x + nox, nd->border.y + noy,
                     nd->border.w, nd->border.h);
    int coy = noy + (nd->is_text ? 0 : scroll_delta(r, nd));
    for (whaleui_layout_node_t* c = nd->first_child; c; c = c->next) {
        clear_subtree_text(r, c, nox, coy);
    }
}

bool paint_cull(whaleui_render_t* r, whaleui_layout_node_t* n, int off_x,
                int off_y, const Clip* clip)
{
    (void)r;
    if (!clip || clip->w <= 0 || clip->h <= 0) {
        return false;
    }
    int x0 = n->bounds.x + off_x - kCullMargin;
    int y0 = n->bounds.y + off_y - kCullMargin;
    int x1 = n->bounds.x + n->bounds.w + off_x + kCullMargin;
    int y1 = n->bounds.y + n->bounds.h + off_y + kCullMargin;
    return x1 <= clip->x || x0 >= clip->x + clip->w ||
           y1 <= clip->y || y0 >= clip->y + clip->h;
}

void paint_node(whaleui_render_t* r, whaleui_layout_node_t* n, int off_x,
                int off_y, int& seq, int sel_lo, int sel_hi,
                const Clip* clip, bool tc)
{
    if (!n->visible) {
        return;
    }
    const int my_seq = seq++;
    /* transform value read ONCE per node (the tc check below and the paint
     * transform block both need it); position:fixed is checked only when no
     * transform is present. Transformed / fixed subtrees are painted at
     * offset positions the layout bounds don't know about: never cull them,
     * and propagate the flag down so descendants use the same rule. */
    std::string ntv; /* "transform" value of this node ("" = none) */
    bool has_xf = false;
    if (n->el && !n->is_text) {
        has_xf = n->xf != 0;
        if (!tc && has_xf) {
            ntv = sget(n->style, "transform");
            tc = true;
        } else if (!tc && n->fx) {
            tc = true;
        } else if (!tc && n->sk) {
            /* sticky pins the box at top:N while scrolling, so its painted
             * box leaves the layout bounds - culling on the laid-out
             * position would drop it (and its subtree) mid-scroll */
            tc = true;
        }
    }
    /* a selection endpoint outside the repaint region must still receive
     * its sequence number (sel_seq does the same), so the in-viewport
     * middle of the selection keeps highlighting. Text runs skip the
     * subtree cull entirely: their laid-out bounds carry the estimated
     * text width, which can fall short of the real glyph extent (inline
     * lines, letter-spacing) - culling on it drops glyphs that actually
     * reach the repaint strip. paint_text has its own framebuffer check
     * and the clip clips the horizontal overflow. */
    if (!tc && !n->is_text &&
        !(n->el && (n->el == r->sel_anchor_el ||
                    n->el == r->sel_focus_el)) &&
        paint_cull(r, n, off_x, off_y, clip)) {
        return; /* whole subtree outside the repaint region */
    }
    if (n->is_text) {
        paint_text(r, n, off_x, off_y, my_seq, sel_lo, sel_hi, clip);
        return;
    }
    /* position:fixed elements are laid out against the viewport and must
     * not move with ancestor scroll offsets */
    if (n->fx) {
        off_x = 0;
        off_y = 0;
    }
    /* position:sticky: keep the box pinned at top:N once scrolling would
     * push it past that edge (the layout pass already shifted the box by
     * the scroll amount, so border.y + off_y is the current viewport
     * position). Simplified to the page/root scroll; container-bottom
     * clamping is skipped (ponytail: add when a page needs it). */
    if (n->sk) {
        /* top is usually px; %/vh are rare on sticky (ponytail) */
        int st = std::atoi(sget(n->style, "top").c_str());
        int cur = n->border.y + off_y;
        if (cur < st) {
            off_y += st - cur;
        }
    }
    /* transform: translate (px/%) + uniform scale around the element's
     * center (default transform-origin). The shifted box is drawn here and
     * off_x/off_y carry the translation into the subtree. Child coordinates
     * are NOT scaled. ponytail: scale is visual on this box; true 2D
     * transform stacks + hit-testing are a later step. */
    float tdx = 0.0f, tdy = 0.0f, tsx = 1.0f, tsy = 1.0f;
    if (has_xf) {
        whaleui_transform_t tf;
        if (whaleui_transform_eval(ntv.c_str(),
                                   static_cast<float>(n->border.w),
                                   static_cast<float>(n->border.h), &tf) == 0) {
            tdx = tf.tx;
            tdy = tf.ty;
            tsx = tf.sx;
            tsy = tf.sy;
        }
    }
    int bw = n->border.w;
    int bh = n->border.h;
    if (tsx != 1.0f || tsy != 1.0f) {
        /* non-uniform scale (scaleX/scaleY): the box shrinks per axis,
         * anchored at the center like the uniform path */
        bw = static_cast<int>(n->border.w * tsx);
        bh = static_cast<int>(n->border.h * tsy);
    }
    int nox = off_x + static_cast<int>(tdx) + (n->border.w - bw) / 2;
    int noy = off_y + static_cast<int>(tdy) + (n->border.h - bh) / 2;
    /* z-order high root with an opaque background: this element's layer
     * occludes lower layers - clear the old text under it so lower
     * glyphs do not show through its background. Unified rule; the popup
     * and fixed headers are just z-raised elements. */
    if (high_root_occludes(n)) {
        clear_subtree_text(r, n, off_x, off_y);
    }
    /* overflow: hidden/auto/scroll clips descendants to the border box
     * (auto/scroll containers also shift children by scroll_y at layout) */
    Clip self;
    const Clip* eff = clip;
    std::string ov = sget(n->style, "overflow");
    if (ov == "hidden" || ov == "auto" || ov == "scroll") {
        self.x = n->border.x + nox;
        self.y = n->border.y + noy;
        self.w = bw;
        self.h = bh;
        eff = &self;
        /* cull clipped containers fully outside the framebuffer: on a
         * scrolled page most of the document is off-screen, so skip their
         * whole subtree (the biggest scroll-paint win) */
        if (self.y + self.h <= 0 || self.y >= r->fb_h) {
            return;
        }
    }
    /* soft shadow first, so the element body covers the inner layers */
#ifndef WHALEUI_BUILD_MINIMAL
    paint_shadow(r, n, nox, noy, eff);
#endif
    /* <img>: bitmap (object-fit) or placeholder replaces the background */
    if (n->el && tag_eq(n->el, "img")) {
        paint_img(r, n, nox, noy, eff);
    }
    /* native controls (checkbox/radio/progress) own their box appearance
     * (painted at a fixed native size by paint_checkbox/progress below),
     * so the layout box's background/border must NOT also paint - that
     * drew a second larger frame around the control ("checkbox 外面更大
     * 的框"). */
    bool native_ctrl = !n->pseudo && n->el &&
                       (is_check_radio(n->el) ||
                        n->tag_id == WUI_TAG_PROGRESS ||
                        n->tag_id == WUI_TAG_METER);
    if (!native_ctrl) {
    /* background (border-radius supported). A gradient in `background`/
     * `background-image` paints over the plain color (which shows through
     * the gradient's transparent stops). */
    unsigned int bg = color_of(n->style, "background", 0);
    unsigned int bg2 = color_of(n->style, "background-color", 0);
    if (bg == 0) {
        bg = bg2;
    }
    int radius = 0;
    std::string br = sget(n->style, "border-radius");
    if (!br.empty()) {
        radius = std::atoi(br.c_str());
    }
    unsigned int bg_c = 0; /* inner re-fill color for rounded border rings */
    if (bg != 0) {
        unsigned int a = (bg >> 24) & 0xFF;
        unsigned int a8 = static_cast<unsigned>(a * n->opacity);
        unsigned int c = (a8 << 24) | (bg & 0x00FFFFFF);
        bg_c = c;
    }
    /* backdrop-filter: blur the already-painted background under this box.
     * GPU path: pass C (in gpu_flush) overwrites the region with the
     * blurred geometry and blends the body color on top, so the plain body
     * paint below is skipped - but only on full repaints (scroll/partial
     * frames skip pass C, so the body background paints normally). CPU
     * path has no access to the GPU geometry: the body background still
     * paints (ponytail: real CPU backdrop blur when needed). */
    std::string bdf = sget(n->style, "backdrop-filter");
#ifdef WHALEUI_BUILD_MINIMAL
    bool backdrop = false; /* minimal: backdrop blur removed */
#else
    bool backdrop = !bdf.empty() && bdf != "none";
#endif
    if (backdrop && g_gpu && g_backdrop_active) {
        float bblur = 8.0f;
        size_t bp = bdf.find("blur(");
        if (bp != std::string::npos) {
            bblur = static_cast<float>(std::atof(bdf.c_str() + bp + 5));
        }
        whaleui_gpu_backdrop(g_gpu, static_cast<float>(n->border.x + nox),
                             static_cast<float>(n->border.y + noy),
                             static_cast<float>(bw), static_cast<float>(bh),
                             static_cast<float>(radius), bblur, bg_c);
    } else {
    if (bg != 0) {
        if (radius > 0) {
            fill_round_rect(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                            n->border.y + noy,
                            bw, bh, radius, bg_c, eff);
        } else {
            fill_rect(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                      n->border.y + noy,
                      bw, bh, bg_c, eff);
        }
    }
    Gradient grad;
    std::string bgv = sget(n->style, "background-image");
    if (bgv.empty()) {
        bgv = sget(n->style, "background");
    }
    if (parse_gradient(bgv, grad)) {
        if (radius > 0) {
            /* gradients ignore the corner arcs (ponytail: fill the full
             * rect; clipped inside rounded containers already) */
        }
        fill_gradient(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                      n->border.y + noy, bw, bh, grad, eff);
    }
    /* border (follows the corner arcs when border-radius is set) */
    int bw2[4] = {n->border_w[0], n->border_w[1], n->border_w[2], n->border_w[3]};
    bool any = bw2[0] || bw2[1] || bw2[2] || bw2[3];
    if (any) {
        unsigned int bc = color_of(n->style, "border-color",
                                   border_color_of(n->style, 0xFF000000));
        if (bc != 0) {
            unsigned int a = (bc >> 24) & 0xFF;
            unsigned int a8 = static_cast<unsigned>(a * n->opacity);
            unsigned int c = (a8 << 24) | (bc & 0x00FFFFFF);
            int radius = 0;
            std::string br2 = sget(n->style, "border-radius");
            if (!br2.empty()) {
                radius = std::atoi(br2.c_str());
            }
            /* uniform border width for the ring */
            int brw = bw2[1] > 0 ? bw2[1] : (bw2[3] > 0 ? bw2[3] : (bw2[0] > 0 ? bw2[0] : bw2[2]));
            if (radius > 0 && brw > 0) {
                fill_round_border(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                                  n->border.y + noy,
                                  bw, bh, radius, brw, c, bg_c, eff);
            } else {
                if (bw2[0]) { /* top */
                    fill_rect(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                              n->border.y + noy, bw, bw2[0], c, eff);
                }
                if (bw2[2]) { /* bottom */
                    fill_rect(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                              n->border.y + noy + bh - bw2[2], bw, bw2[2], c, eff);
                }
                if (bw2[1]) { /* right */
                    fill_rect(r->pixels, r->fb_w, r->fb_h,
                              n->border.x + nox + bw - bw2[1],
                              n->border.y + noy, bw2[1], bh, c, eff);
                }
                if (bw2[3]) { /* left */
                    fill_rect(r->pixels, r->fb_w, r->fb_h, n->border.x + nox,
                              n->border.y + noy, bw2[3], bh, c, eff);
                }
            }
        }
    }
    } /* end if(!native_ctrl): native controls paint their own box */
    } /* end else: plain body paint (skipped for GPU backdrop-filter) */
    int child_off_y = noy + scroll_delta(r, n);
    for (whaleui_layout_node_t* c = n->first_child; c; c = c->next) {
        paint_node(r, c, nox, child_off_y, seq, sel_lo, sel_hi, eff, tc);
    }
    /* scrollbar sits on top of the content */
    if (n->scroll_max > 0) {
        paint_scrollbar(r, n, nox, noy, eff);
    }
    /* native controls drawn by the engine (not editable): checkbox/radio
     * boxes and progress/meter tracks. tag_id pre-filters before the
     * attribute checks. Pseudo-element boxes share el with their owner but
     * must not trigger the owner's control painting (an input's ::after
     * focus underline is a plain painted box). */
    const int tid = n->tag_id;
    if (!n->pseudo && n->el && tid == WUI_TAG_INPUT && is_check_radio(n->el)) {
        paint_checkbox(r, n, nox, noy, eff);
    } else if (!n->pseudo && n->el &&
               (tid == WUI_TAG_PROGRESS || tid == WUI_TAG_METER)) {
        paint_progress(r, n, nox, noy, eff);
    } else if (!n->pseudo && n->el && is_editable_node(n)) {
        paint_editable(r, n, nox, noy, eff);
    }
    /* <select> control: value + arrow painted here; the expanded list is
     * painted LAST in render_frame so nothing occludes it. Pseudo-element
     * boxes (the focus underline) share el with the select but must not
     * trigger the value paint - its transform (scaleX) shifts nox and
     * drew a second value+arrow offset right and down ("鍙充笅瑙掗噸澶嶆寜閽?). */
    if (!n->pseudo && is_select_node(n)) {
        paint_select_value(r, n, nox, noy, eff);
    }
}
