/* render_control.cpp - form controls (checkbox/radio/progress/editable/scrollbar/select) paint. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include "style/style.h" /* whaleui_style_virtual: select popup chrome */
#include <lexbor/dom/dom.h>

#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
void paint_checkbox(whaleui_render_t* r, whaleui_layout_node_t* n,
                    int off_x, int off_y, const Clip* clip)
{
    lxb_dom_element* el = n->el;
    if (!el) {
        return;
    }
    size_t alen = 0;
    const lxb_char_t* t = lxb_dom_element_get_attribute(
        el, (const lxb_char_t*)"type", 4, &alen);
    bool is_radio = t && alen == 5 && std::memcmp(t, "radio", 5) == 0;
    bool checked = lxb_dom_element_has_attribute(
        el, (const lxb_char_t*)"checked", 7);
    int bx = n->border.x + off_x;
    int by = n->border.y + off_y;
    /* native control size 16x16, regardless of the layout box: flex/inline
     * flows can mis-size an unchecked checkbox (11px wide, 32px tall - the
     * inline-block height takes the line box), which painted a squashed
     * sliver instead of a checkbox. The position still comes from the box.
     * needs: layout fix - inline/flex children with an explicit height
     * must keep it (the 32px line-box height); [type=...] selectors. */
    const int bw = 16, bh = 16;
    if (bw <= 0 || bh <= 0) {
        return;
    }
    unsigned int bg = 0xFFFFFFFF, fg = 0xFF8a8a8a, acc = 0xFF0067C0;
    auto it = r->theme_vars.find("--field");
    if (it != r->theme_vars.end()) {
        whaleui_render_parse_color(it->second.c_str(), &bg);
    }
    auto itb = r->theme_vars.find("--border-strong");
    if (itb != r->theme_vars.end()) {
        whaleui_render_parse_color(itb->second.c_str(), &fg);
    }
    if (itb == r->theme_vars.end()) {
        /* older themes without --border-strong fall back to --border */
        auto itb2 = r->theme_vars.find("--border");
        if (itb2 != r->theme_vars.end()) {
            whaleui_render_parse_color(itb2->second.c_str(), &fg);
        }
    }
    auto ita = r->theme_vars.find("--accent");
    if (ita != r->theme_vars.end()) {
        whaleui_render_parse_color(ita->second.c_str(), &acc);
    }
    int cx = bx + bw / 2, cy = by + bh / 2;
    if (is_radio) {
        int rad = bw / 2;
        /* solid background + 1px crisp ring (fill_round_border paints the
         * outline in full-strength color instead of an SDF-faded sliver) */
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh, rad,
                        bg, clip);
        fill_round_border(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh,
                          rad, 1, fg, bg, clip);
        if (checked) {
            fill_round_rect(r->pixels, r->fb_w, r->fb_h, cx - bw / 4,
                            cy - bh / 4, bw / 2, bh / 2, bw / 4, acc, clip);
        }
    } else {
        int rad = 3;
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh, rad,
                        bg, clip);
        fill_round_border(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh,
                          rad, 1, fg, bg, clip);
        if (checked) {
            /* check mark: a left-low / right-high tick (✓). Drawn as thick
             * staircase strokes so it reads as a check at any size. NOTE:
             * the shape is a placeholder by design - different themes draw
             * their own check glyph; keep this simple V and let a theme
             * override if it needs a distinctive mark. */
            int sw = bw / 5;
            if (sw < 1) {
                sw = 1;
            }
            /* left arm: top-left -> low bend (short) */
            for (int i = 0; i <= 3; ++i) {
                fill_rect(r->pixels, r->fb_w, r->fb_h,
                          bx + 2 + i, cy - 1 + i, sw, 2, acc, clip);
            }
            /* right arm: low bend -> top-right (long, so the tick leans
             * right-up like a browser check) */
            for (int i = 0; i <= 8; ++i) {
                fill_rect(r->pixels, r->fb_w, r->fb_h,
                          bx + 4 + i, cy + 2 - i, sw, 2, acc, clip);
            }
        }
    }
}

void paint_progress(whaleui_render_t* r, whaleui_layout_node_t* n,
                    int off_x, int off_y, const Clip* clip)
{
    lxb_dom_element* el = n->el;
    if (!el) {
        return;
    }
    double value = 0, max = 1;
    size_t alen = 0;
    const lxb_char_t* v = lxb_dom_element_get_attribute(
        el, (const lxb_char_t*)"value", 5, &alen);
    if (v && alen > 0) {
        value = std::atof(reinterpret_cast<const char*>(v));
    }
    const lxb_char_t* m = lxb_dom_element_get_attribute(
        el, (const lxb_char_t*)"max", 3, &alen);
    if (m && alen > 0) {
        double mx = std::atof(reinterpret_cast<const char*>(m));
        if (mx > 0) {
            max = mx;
        }
    }
    if (value < 0) {
        value = 0;
    }
    if (value > max) {
        value = max;
    }
    int bx = n->content.x + off_x;
    int by = n->content.y + off_y;
    int bw = n->content.w, bh = n->content.h;
    if (bw <= 0 || bh <= 0) {
        return;
    }
    unsigned int track = 0xFFE0E0E0, fill = 0xFF0067C0;
    auto it = r->theme_vars.find("--field");
    if (it != r->theme_vars.end()) {
        whaleui_render_parse_color(it->second.c_str(), &track);
    }
    auto ita = r->theme_vars.find("--accent");
    if (ita != r->theme_vars.end()) {
        whaleui_render_parse_color(ita->second.c_str(), &fill);
    }
    int rad = bh / 2;
    fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh, rad,
                    track, clip);
    int fw2 = static_cast<int>(bw * (value / max));
    if (fw2 > 0) {
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, fw2, bh, rad,
                        fill, clip);
    }
}

void paint_editable(whaleui_render_t* r, whaleui_layout_node_t* n,
                    int off_x, int off_y, const Clip* clip)
{
    lxb_dom_element* el = n->el;
    if (!el || !is_editable(el)) {
        return;
    }
    int fs = 16;
    std::string fsv = sget(n->style, "font-size");
    if (!fsv.empty()) {
        fs = std::atoi(fsv.c_str());
    }
    std::string family = sget(n->style, "font-family");
    std::string fw = sget(n->style, "font-weight");
    bool bold = fw == "bold" || fw == "bolder" ||
                (!fw.empty() && std::atoi(fw.c_str()) >= 600);
    std::string fst = sget(n->style, "font-style");
    int style = (bold ? kFontBold : 0) |
                ((fst == "italic" || fst == "oblique") ? kFontItalic : 0);
    std::string val = edit_value(el);
    bool focused = (el == r->edit_el);
    /* caret/highlight geometry: input centers in its content box; textarea/
     * contenteditable follow the layout text run so they line up with the
     * painted glyphs (which sit at the run's top, not the box center) */
    whaleui_layout_node_t* geo = editable_geo(n);
    /* editable text wraps like the painted run does (textarea/content-
     * editable wrap at their content width; input stays single-line) */
    int wrap_w = tag_eq(el, "input") ? 0 : run_wrap_w(geo);
    int tx = 0, ty = 0;
    text_origin(r, geo, val, fs, family, bold, &tx, &ty, wrap_w);
    tx += off_x;
    /* the editable box's OWN scroll: the layout baked scroll_y into the
     * run position, but the live scroll (edit_ensure_visible runs AFTER
     * the relayout, and wheel scrolls never relayout) can differ - without
     * this delta the first line stays shifted out of view and the caret
     * renders below the text. */
    ty += off_y + scroll_delta(r, n);
    int th = text_line_h(r, fs, family, bold);

    /* single-line input: content scrolls horizontally with the caret and is
     * clipped to the content box (long values never stretch or spill) */
    int hx = 0;
    Clip iclip;
    bool clip_input = false;
    if (tag_eq(el, "input")) {
        auto hi = r->hscrolls.find(el);
        hx = hi == r->hscrolls.end() ? 0 : hi->second;
        tx -= hx;
        if (clip && n->content.w > 0) {
            iclip = *clip;
            int x0 = n->content.x + off_x;
            int y0 = n->content.y + off_y;
            int x1 = x0 + n->content.w;
            int y1 = y0 + n->content.h;
            if (iclip.x < x0) {
                iclip.w -= x0 - iclip.x;
                iclip.x = x0;
            }
            if (iclip.x + iclip.w > x1) {
                iclip.w = x1 - iclip.x;
            }
            if (iclip.y < y0) {
                iclip.h -= y0 - iclip.y;
                iclip.y = y0;
            }
            if (iclip.y + iclip.h > y1) {
                iclip.h = y1 - iclip.y;
            }
            clip_input = iclip.w > 0 && iclip.h > 0;
        }
    }
    const Clip* ic = clip_input ? &iclip : clip;

    if (tag_eq(el, "input")) {
        /* input has no text children: paint the value here, always.
         * The y MUST carry the scroll offset (off_y + own scroll_delta)
         * like iclip does - the layout tree keeps the pre-scroll position,
         * and painting at the raw content.y puts the glyphs outside iclip
         * (a scrolled page left the input text blank until a hover
         * relayout re-baked the position). draw_text_at re-centers
         * vertically itself, so pass the uncentered content top. */
        unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
        std::string shown = val;
        unsigned int pc = fg;
        if (shown.empty()) {
            /* placeholder: shown only while the value is empty (browser
             * behavior); the muted theme color keeps it visually secondary */
            size_t plen = 0;
            const lxb_char_t* ph = lxb_dom_element_get_attribute(
                el, (const lxb_char_t*)"placeholder", 11, &plen);
            if (ph && plen > 0) {
                shown.assign(reinterpret_cast<const char*>(ph), plen);
                auto mi = r->theme_vars.find("--muted");
                if (mi != r->theme_vars.end()) {
                    whaleui_render_parse_color(mi->second.c_str(), &pc);
                } else {
                    pc = 0x99808080;
                }
            }
        }
        if (!shown.empty()) {
            draw_text_at(r, shown, n->content.x - hx + off_x,
                         n->content.y + off_y + scroll_delta(r, n),
                         n->content.w, n->content.h,
                         fs, family, pc, style, 0, el, ic);
        }
    } else if (tag_eq(el, "textarea") && val.empty()) {
        /* empty textarea: its value glyphs normally come from the layout
         * text run (paint_text), which does not exist for an empty value -
         * paint the placeholder here instead. */
        size_t plen = 0;
        const lxb_char_t* ph = lxb_dom_element_get_attribute(
            el, (const lxb_char_t*)"placeholder", 11, &plen);
        if (ph && plen > 0) {
            unsigned int pc = 0x99808080;
            auto mi = r->theme_vars.find("--muted");
            if (mi != r->theme_vars.end()) {
                whaleui_render_parse_color(mi->second.c_str(), &pc);
            }
            std::string phs(reinterpret_cast<const char*>(ph), plen);
            draw_text_at(r, phs, n->content.x + off_x,
                         n->content.y + off_y + scroll_delta(r, n),
                         n->content.w, n->content.h, fs, family, pc, style,
                         0, el, ic);
        }
    }
    /* textarea / contenteditable: the value glyphs come from the layout
     * text run (paint_text), which already carries the live scroll delta
     * and the viewport clip - painting the value a second time here
     * double-rendered it (ghosted text). tx/ty below still anchor the
     * focused selection/caret geometry. */
    if (focused) {
        size_t a = 0, b = 0;
        if (sel_range_for(r, el, val.size(), &a, &b, -1, -1, -1)) {
            std::vector<TRect> rects = sel_rects(r, val, fs, family, bold,
                                                 a, b, wrap_w);
            expand_hl_rects(rects, text_line_h(r, fs, family, bold));
            unsigned int hl = sel_hl_color(r, n, 0x3C);
            if (tag_eq(el, "input") && geo->content.h > 0) {
                /* single-line input: the wash fills the whole content box
                 * (native control look); the text sits vertically centered,
                 * so the top edge is (content.h - text height)/2 above the
                 * text origin ty. */
                int top = -(geo->content.h -
                            text_line_h(r, fs, family, bold)) / 2;
                for (size_t i = 0; i < rects.size(); ++i) {
                    rects[i].y = top;
                    rects[i].h = geo->content.h;
                }
            }
            for (size_t i = 0; i < rects.size(); ++i) {
                fill_rect(r->pixels, r->fb_w, r->fb_h,
                          tx + rects[i].x, ty + rects[i].y,
                          rects[i].w, rects[i].h, hl, ic);
            }
        }
        size_t caret = static_cast<size_t>(r->sel_focus);
        if (caret > val.size()) {
            caret = val.size();
        }
        /* keep the IME candidate window anchored at the caret */
        update_ime_area(r, val, fs, family, bold, caret, tx, ty, wrap_w);
        paint_caret(r, tx, ty, val, fs, family, bold, caret, ic, wrap_w);
        if (!r->compose.empty()) {
            unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
            unsigned int comp = (0xC8 << 24) | (fg & 0x00FFFFFF);
            int cxx = 0, cyy = 0, chh = 16;
            caret_pos(r, val, fs, family, bold, caret, &cxx, &cyy, &chh,
                      wrap_w);
            draw_text_at(r, r->compose, tx + cxx, ty + cyy, 300, chh,
                         fs, family, comp, style, 0, el, ic);
        }
    }
}

void paint_scrollbar(whaleui_render_t* r, whaleui_layout_node_t* n,
                     int off_x, int off_y, const Clip* clip)
{
    if (n->scroll_max <= 0 || n->border.h < 24) {
        return;
    }
    const int bw = 8;
    int track_x = n->border.x + off_x + n->border.w - bw;
    int track_y = n->border.y + off_y;
    int track_h = n->border.h;
    int content_h = n->scroll_max + n->content.h;
    if (content_h <= 0) {
        return;
    }
    int thumb_h = track_h * n->content.h / content_h;
    if (thumb_h < 10) {
        thumb_h = 10;
    }
    if (thumb_h > track_h) {
        thumb_h = track_h;
    }
    /* live scroll position (layout tree may be stale between scrolls) */
    int sy = n->scroll_y;
    auto sit = r->scrolls.find(n->el);
    if (sit != r->scrolls.end()) {
        sy = sit->second;
    }
    /* thumb position in float and clamped to the track: integer division
     * truncation plus an out-of-range live scroll made the thumb jump
     * around on tall pages */
    float frac = n->scroll_max > 0
                     ? static_cast<float>(sy) /
                           static_cast<float>(n->scroll_max)
                     : 0.0f;
    if (frac < 0.0f) {
        frac = 0.0f;
    }
    if (frac > 1.0f) {
        frac = 1.0f;
    }
    int thumb_y = track_y +
                  static_cast<int>((track_h - thumb_h) * frac);
    unsigned int track = 0x10000000;
    unsigned int thumb = 0x50000000;
    auto it = r->theme_vars.find("--border");
    if (it != r->theme_vars.end()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(it->second.c_str(), &c) == 0) {
            track = (0x18 << 24) | (c & 0x00FFFFFF);
            thumb = (0x55 << 24) | (c & 0x00FFFFFF);
        }
    }
    /* the scrollbar column is repainted as its own region, IGNORING the
     * caller's clip (which on a scroll-shift is only the exposed strip):
     * the thumb can sit anywhere on the track, so a strip-only clip would
     * leave the shifted old thumb image behind ("scrollbar rendering
     * wrong" after restoring scroll-shift). The 8px column is cheap to
     * repaint every scroll frame. */
    Clip bar = { track_x, track_y, bw, track_h };
    fill_rect(r->pixels, r->fb_w, r->fb_h, track_x, track_y, bw, track_h,
              track, &bar);
    fill_rect(r->pixels, r->fb_w, r->fb_h, track_x, thumb_y, bw, thumb_h,
              thumb, &bar);
}

void select_options(lxb_dom_element* sel, std::vector<std::string>& texts,
                    std::vector<std::string>& values)
{
    lxb_dom_node* c = sel->node.first_child;
    while (c) {
        if (c->type == LXB_DOM_NODE_TYPE_ELEMENT) {
            lxb_dom_element* el = lxb_dom_interface_element(c);
            size_t len = 0;
            const lxb_char_t* name = lxb_dom_element_local_name(el, &len);
            if (name && len == 6 && std::memcmp(name, "option", 6) == 0) {
                /* text = concatenated text children */
                std::string txt;
                lxb_dom_node* t = el->node.first_child;
                while (t) {
                    if (t->type == LXB_DOM_NODE_TYPE_TEXT) {
                        const lexbor_str_t* s = &lxb_dom_interface_text(t)->char_data.data;
                        if (s->data) {
                            txt.append(reinterpret_cast<const char*>(s->data), s->length);
                        }
                    }
                    t = t->next;
                }
                texts.push_back(txt);
                size_t vlen = 0;
                const lxb_char_t* v = lxb_dom_element_get_attribute(
                    el, (const lxb_char_t*)"value", 5, &vlen);
                values.push_back(v ? std::string(reinterpret_cast<const char*>(v), vlen) : txt);
            }
        }
        c = c->next;
    }
}

bool is_select_node(whaleui_layout_node_t* n)
{
    if (!n || !n->el) {
        return false;
    }
    size_t len = 0;
    const lxb_char_t* name = lxb_dom_element_local_name(n->el, &len);
    return name && len == 6 && std::memcmp(name, "select", 6) == 0;
}

void paint_select_value(whaleui_render_t* r, whaleui_layout_node_t* n,
                        int off_x, int off_y, const Clip* clip)
{
    std::vector<std::string> texts, values;
    select_options(n->el, texts, values);
    if (texts.empty()) {
        return;
    }
    int sel = r->select_index.count(n->el) ? r->select_index[n->el] : 0;
    if (sel < 0 || sel >= static_cast<int>(texts.size())) {
        sel = 0;
    }
    int fs = 13;
    unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
    /* value text left, arrow pinned to the right edge. Both are nudged up
     * 2px: segoe's glyphs sit ~2px below the line-box center, so metric
     * centering alone leaves the text looking low inside the control. */
    int arrow_x = n->content.x + off_x + n->content.w - 16;
    int text_w = arrow_x - n->content.x - off_x - 8;
    if (text_w < 10) {
        text_w = 10;
    }
    int vy = n->content.y + off_y - 2;
    draw_text_at(r, texts[sel], n->content.x + off_x + 2, vy,
                 text_w, n->content.h, fs, "", fg, 0, 0, n->el, clip);
    /* large solid triangle ▲: the small ? is only a few px tall and looks
     * like it floats above the text baseline */
    draw_text_at(r, "\xe2\x96\xbc", arrow_x, vy,
                 16, n->content.h, fs, "", fg, 0, 0, n->el, clip);
}

void paint_select_list(whaleui_render_t* r, whaleui_layout_node_t* n,
                       int off_y, const Clip* clip)
{
    std::vector<std::string> texts, values;
    select_options(n->el, texts, values);
    if (texts.empty()) {
        return;
    }
    int sel = r->select_index.count(n->el) ? r->select_index[n->el] : 0;
    if (sel < 0 || sel >= static_cast<int>(texts.size())) {
        sel = 0;
    }
    /* popup chrome comes from the theme stylesheet, not hard-coded colors:
     * the renderer computes the virtual .select-popup / .select-option
     * classes (whaleui_style_virtual) and paints from their styles. */
    WhaleUIComputedStyle popup, opt_hover, opt_sel;
    whaleui_style_virtual(".select-popup", r->rules, r->rule_count,
                          r->theme_vars, popup);
    whaleui_style_virtual(".select-option-hover", r->rules, r->rule_count,
                          r->theme_vars, opt_hover);
    whaleui_style_virtual(".select-option-selected", r->rules, r->rule_count,
                          r->theme_vars, opt_sel);
    int fs = 13;
    unsigned int fg = color_of(popup, "color", 0xFF1a1a1a);
    int list_x = n->border.x;
    int list_y = n->border.y + off_y + n->border.h;
    int list_w = n->border.w;
    int list_h = static_cast<int>(texts.size()) * kSelectItemH;
    /* corner radius + border + background + shadow from .select-popup */
    int radius = 0;
    std::string br = sget(popup, "border-radius");
    if (!br.empty()) {
        radius = std::atoi(br.c_str());
    }
    unsigned int bg = color_of(popup, "background", 0xFF000000);
    unsigned int border_c = color_of(popup, "border", 0xFF000000);
    unsigned int hover_bg = color_of(opt_hover, "background", 0x00000000);
    unsigned int sel_bg = color_of(opt_sel, "background", 0xFF0067C0);
    unsigned int sel_fg = color_of(opt_sel, "color", 0xFFFFFFFF);
    /* box-shadow: only the first shadow is painted (engine limitation) */
    int sh_ox = 0, sh_oy = 0, sh_blur = 0;
    unsigned int sh_col = 0;
    {
        std::string sv = sget(popup, "box-shadow");
        size_t comma = sv.find(',');
        if (comma != std::string::npos) {
            sv = sv.substr(0, comma);
        }
        parse_shadow(sv, sh_ox, sh_oy, sh_blur, sh_col);
    }
    if (sh_blur > 0) {
        /* soft shadow under the popup (before the card background) */
        const int blur = sh_blur;
        for (int k = blur; k >= 1; --k) {
            unsigned int ka = static_cast<unsigned>(0x28 * (blur - k + 1) / (blur + 1));
            unsigned int c = (ka << 24); /* black, alpha faded outwards */
            if (radius > 0) {
                fill_round_rect(r->pixels, r->fb_w, r->fb_h,
                                list_x + 0 - k, list_y + 2 - k,
                                list_w + 2 * k, list_h + 2 * k, radius, c, clip);
            } else {
                fill_rect(r->pixels, r->fb_w, r->fb_h,
                          list_x + 0 - k, list_y + 2 - k,
                          list_w + 2 * k, list_h + 2 * k, c, clip);
            }
        }
    }
    if (radius > 0) {
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, list_x, list_y,
                        list_w, list_h, radius, bg, clip);
    } else {
        fill_rect(r->pixels, r->fb_w, r->fb_h, list_x, list_y, list_w,
                  list_h, bg, clip);
    }
    for (int i = 0; i < static_cast<int>(texts.size()); ++i) {
        int iy = list_y + i * kSelectItemH;
        unsigned int row_bg = 0x00000000;
        if (i == r->open_select_hover) {
            row_bg = hover_bg;
        }
        if (i == sel) {
            row_bg = sel_bg;
        }
        if (row_bg && ((row_bg >> 24) & 0xFF) != 0) {
            if (radius > 0) {
                fill_round_rect(r->pixels, r->fb_w, r->fb_h, list_x, iy,
                                list_w, kSelectItemH, radius, row_bg, clip);
            } else {
                fill_rect(r->pixels, r->fb_w, r->fb_h, list_x, iy,
                          list_w, kSelectItemH, row_bg, clip);
            }
        }
        unsigned int row_fg = i == sel ? sel_fg : fg;
        draw_text_at(r, texts[i], list_x + 8, iy, list_w - 16,
                     kSelectItemH, fs, "", row_fg, i == sel, 0, n->el, clip);
    }
    /* border around the list (follows the corner arcs when rounded) */
    fill_round_border(r->pixels, r->fb_w, r->fb_h, list_x, list_y,
                      list_w, list_h, radius, 1, border_c, bg, clip);
}
