/* render_text.cpp - text rasterization (SDL3_ttf full / stb_truetype lite+minimal), selection, caret and IME. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include "font/font.h"
#include <SDL3/SDL.h>
#ifdef WHALEUI_BUILD_FULL
#include <SDL3_ttf/SDL_ttf.h>
#else
/* stb_truetype text backend for lite/minimal builds (header-only) */
#define STB_TRUETYPE_IMPLEMENTATION
#include <stb/stb_truetype.h>
#endif

#include <lexbor/dom/dom.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <string>
#include <vector>
std::vector<std::string> split_families(const std::string& s)
{
    std::vector<std::string> out;
    const char* p = s.c_str();
    while (*p) {
        while (*p == ' ' || *p == '\t' || *p == ',') {
            ++p;
        }
        if (!*p) {
            break;
        }
        const char* start = p;
        bool quoted = *p == '"' || *p == '\'';
        if (quoted) {
            ++start;
            ++p;
            while (*p && *p != '"' && *p != '\'') {
                ++p;
            }
            out.emplace_back(start, static_cast<size_t>(p - start));
            if (*p) {
                ++p;
            }
            continue;
        }
        while (*p && *p != ',') {
            ++p;
        }
        std::string fam(start, static_cast<size_t>(p - start));
        size_t b = fam.find_first_not_of(" \t");
        size_t e = fam.find_last_not_of(" \t");
        if (b != std::string::npos) {
            out.push_back(fam.substr(b, e - b + 1));
        }
    }
    return out;
}

/* --- 缂佸顑呯花顓㈠礃閸涱喗鐎柡鍫墯鐢捇鎮?闁哥儐鍨粩瀵糕偓鍦仧楠?full 濞?stb 闁稿繗浜弫?---
 * 闁圭儤甯炴晶妤冩嫻閻旇崵鐓?UTF-8 閻熸瑱绲块悥婊堝Υ娴ｇ懓浠橀柛鎺曟硾閻⊙呯箔閿曗偓椤︹晠鎮堕崱鏇犵憿闁圭顦崕姘辨閻樺樊鍟嶉幖杈惧濞?soft-wrap;
 * 婵炴挸寮堕悡瀣沪?SDL3_ttf / stb_truetype)闁告瑯浜濊ぐ浣圭瑹濞戞ê绀嬮悗娑欘殘椤戜胶鈧妫勭€规娊宕堕悙鍓佹濞戞挸楠搁悺褑銇愰姀銏㈠笡闁告帟缈伴埀?
 * 缂傚倹鐗炵欢顐﹀极閺夋鍔?caret/selection/hit-test)濞戞挸娴风划顖炲礆鐠哄搫褰欓柣顫妼閹挻绋夐埀顒佺閸婄噥鏀介悽顖氬暙閻?
 * 闁圭鍋撳ù?full 濞?lite/minimal 闁汇劌瀚畷鑼偘鐏炶偐绉寸紓鍐惧枔閳ь兛鐒︾敮鍫曞礆鐠鸿櫣鎽熺紒妤嬬畳椤㈡垶绋夐崫鍕殮闁稿繈鍔嬬粩鎾嚊濞ｎ兘鍋?*/

struct TextLayoutLine { size_t cstart; size_t cend; int w; };
struct TextLayout {
    std::string disp;          /* 闁哄嫬澧介妵姘跺棘閸ャ劍鎷?闁硅矇鍐ㄧ厬閻庢稒顨堥浣轰沪閺囩偟纾?缂佸顭峰▍搴ㄥ触鎼达絾鐣?UTF-8 */
    std::vector<size_t> map;   /* disp 婵絽绻愰悺褏绮敃浣瑰闯闁?闁?闁告鍠愰弸鍐嫉椤掆偓閻⊙囨嚍閸屾矮鐒婄紒?*/
    std::vector<size_t> dbytes;/* disp 婵絽绻愰悺褏绮敃浣瑰闯闁?闁?disp 閻庢稒顨夋俊顓㈠磻韫囨泤?*/
    std::vector<TextLayoutLine> lines;
    int tw, th;
};
/* 闁告娲栭悺褏绮敃鈧崕姘辨閻樺樊鍟?婵炴挸寮堕悡瀣沪閸屾氨鏉介柣?閻㈩垰鍟惇顒勬倻椤擄紕鐔呯€?ASCII 閻犙勫缁憋妇鈧? */
typedef int (*TextGlyphFn)(unsigned int cp, void* st);

/* 閻熸瑱绲块悥婊堝储閻斿憡鐎柡鍫厸鐠愮喖寮伴崜褋浠涢柡鍌氭处濠€? \r 闊洨鏅弳?CRLF),\n 闁哄偆鍙€椤?\t 閻忕偞娲栫槐鎴炵▔?4 缂佸瞼鍎ら悧?
 * 闁稿繑婀圭紞?C0/DEL 闁硅矇鍐ㄧ厬閻庢稒顨堥浣烘崉鐎圭姷绠?濞戞挸绉村畷鐗堟媴?;婵絽绻嬮柌婊堝及閸撗佷粵閻庢稒顨堥浣烘媼閺夎法绉块柛妯煎枎娴滃摜绮斿Ч鍥ｅ亾?*/
static void layout_decode(const std::string& text, TextLayout& L)
{
    const unsigned char* sb =
        reinterpret_cast<const unsigned char*>(text.c_str());
    size_t i = 0;
    while (i < text.size()) {
        size_t start = i;
        unsigned char c = sb[i];
        unsigned int cp = c;
        int len = 1;
        if (c >= 0x80) {
            if ((c & 0xE0) == 0xC0 && i + 1 < text.size()) {
                cp = ((c & 0x1F) << 6) | (sb[i + 1] & 0x3F);
                len = 2;
            } else if ((c & 0xF0) == 0xE0 && i + 2 < text.size()) {
                cp = ((c & 0x0F) << 12) | ((sb[i + 1] & 0x3F) << 6) |
                     (sb[i + 2] & 0x3F);
                len = 3;
            } else if ((c & 0xF8) == 0xF0 && i + 3 < text.size()) {
                cp = ((c & 0x07) << 18) | ((sb[i + 1] & 0x3F) << 12) |
                     ((sb[i + 2] & 0x3F) << 6) | (sb[i + 3] & 0x3F);
                len = 4;
            } else {
                cp = 0; /* malformed byte: skip */
            }
        }
        i += len;
        if (cp == '\r') {
            continue;
        }
        if (cp == '\n') {
            L.disp += '\n';
            L.dbytes.push_back(L.disp.size() - 1);
            L.map.push_back(start);
            continue;
        }
        if (cp == '\t') {
            for (int k = 0; k < 4; ++k) {
                L.disp += ' ';
                L.dbytes.push_back(L.disp.size() - 1);
                L.map.push_back(start);
            }
            continue;
        }
        if (cp < 0x20 || cp == 0x7F) {
            continue;
        }
        L.disp.append(text, start, static_cast<size_t>(len));
        L.dbytes.push_back(L.disp.size() - static_cast<size_t>(len));
        L.map.push_back(start);
    }
}

/* 閻熸瑱绲块悥婊堝及閸撗佷粵闁哄倸娲﹀﹢鐗堢▔椤撶偟鎽熺紒妤嬪閸屻劌顕?ci 濠㈣泛瀚▓鎴︽儘娴ｅ搫浠?*/
static unsigned int disp_cp_at(const TextLayout& L, size_t ci){
    size_t b0 = L.dbytes[ci];
    size_t b1 = (ci + 1 < L.dbytes.size()) ? L.dbytes[ci + 1] : L.disp.size();
    const unsigned char* u =
        reinterpret_cast<const unsigned char*>(L.disp.c_str());
    unsigned char c = u[b0];
    if (c < 0x80) {
        return c;
    }
    if ((c & 0xE0) == 0xC0 && b0 + 1 < b1) {
        return ((c & 0x1F) << 6) | (u[b0 + 1] & 0x3F);
    }
    if ((c & 0xF0) == 0xE0 && b0 + 2 < b1) {
        return ((c & 0x0F) << 12) | ((u[b0 + 1] & 0x3F) << 6) |
               (u[b0 + 2] & 0x3F);
    }
    if ((c & 0xF8) == 0xF0 && b0 + 3 < b1) {
        return ((c & 0x07) << 18) | ((u[b0 + 1] & 0x3F) << 12) |
               ((u[b0 + 2] & 0x3F) << 6) | (u[b0 + 3] & 0x3F);
    }
    return 0;
}

/* 闁?wrap_w 闁哄偆鍙€椤?闂侇偅鍔曢悺褏绮敂鍓ф焾閻犱讲鈧剚鍟嶉幖?閻℃帒鎳庨鏃堝籍鐠虹儤绀€闂侇偀鍋撻柛鎺斿濞撳爼宕ユ惔婵堫伇濞戞搩浜為埞鏍冀?闁?
 * wrap_w <= 0 = 濞戞挸绉烽拏瀣箲閵忥綆鏀介柕鍡楀€界换鎴﹀炊閻愬妲ㄩ悶娑樼灱濞堟垿寮伴崜褋浠涢悗娑欘殘椤戜線鎳犻崘銊︾函 [cstart,cend) 濞戞挸楠搁崕姘辨閻樺樊鍟嶉柕?*/
static void layout_wrap(TextLayout& L, int wrap_w, int lh,
                        TextGlyphFn gw, void* st)
{
    const size_t nc = L.map.size();
    size_t ci = 0;
    while (ci < nc) {
        size_t ls = ci;
        int wacc = 0;
        size_t last_sp = static_cast<size_t>(-1);
        int wacc_at_sp = 0;
        bool nl = false;
        while (ci < nc) {
            const char dch = L.disp[L.dbytes[ci]];
            if (dch == '\n') {
                nl = true;
                break;
            }
            int w = gw(disp_cp_at(L, ci), st);
            const bool is_sp = dch == ' ';
            if (wrap_w > 0 && wacc > 0 && wacc + w > wrap_w) {
                /* 閻℃帒鎳庨?濞村吋锚閸樻盯宕堕悙琛″亾閳ь剟宕氶悧鍫熶粯闁告艾绨肩粩瀛樼▔椤忓棌鏁勯柡宥夋？缁狅綁宕?閻犲洤绉舵鍥棘椤撯槅鏀? */
                size_t br = ci;
                int bw = wacc;
                if (last_sp != static_cast<size_t>(-1)) {
                    br = last_sp + 1;
                    bw = wacc_at_sp;
                }
                if (br <= ls) { /* 缂佸瞼鍎ら悧鎼佸及椤栨繍鏀藉Λ锝嗙墱閻℃垵顕ｉ崒姘卞煑:闁哄偆鍘煎﹢顏囥亹閹惧啿顤呴悗娑欘殘椤戜線宕?*/
                    br = ci;
                    bw = wacc;
                }
                L.lines.push_back({ls, br, bw});
                if (bw > L.tw) {
                    L.tw = bw;
                }
                L.th += lh;
                ci = br;
                break;
            }
            wacc += w;
            if (is_sp && wrap_w > 0) {
                last_sp = ci;
                wacc_at_sp = wacc;
            }
            ++ci;
        }
        if (ci >= nc || nl) {
            /* 闂侇偅妲掔欢顐ゆ偘瀹€鍐ㄦ闁绘帒澧庣划銊╁级?闁哄倸娲﹀﹢浼村嫉椤愩垻鍟查柟瀛樼墬濡顕ｈ箛鏂垮簥閻? */
            L.lines.push_back({ls, ci, wacc});
            if (wacc > L.tw) {
                L.tw = wacc;
            }
            L.th += lh;
            if (nl) {
                ++ci; /* 閻犲搫鐤囩换?\n */
            }
        }
    }
    /* 闁哄倸娲﹀﹢鐗堢?\n 缂備焦鎸搁悢顒勫籍?闁哄牜鍋勯悢顒佹交濡粯绠掑☉鎾亾濞戞搩浜為埞鏍偘?缂傚倹鐗炵欢顐﹀闯閵娾晛娅￠柛蹇擃槹閻栵綁宕戝鍐╄含闁哄牃鍋撻柛姘凹缁斿鎮?闁?
     * 濞戞挸绉疯棢濞?text_size/缂備焦锚閸?闁告稒鍨濋懙鎴犱焊閸楃偟姣岀紒鐘炽仦缁斿鎮?闁告劕鎳庨鎰板极缂堢姷绉奸柛瀣箣缁楀懘濡?*/
    if (!L.lines.empty() && !L.disp.empty() && L.disp.back() == '\n') {
        L.lines.push_back({nc, nc, 0});
        L.th += lh;
    }
}

static TextLayout layout_text(const std::string& text, int wrap_w, int lh,
                              TextGlyphFn gw, void* st)
{
    TextLayout L = {};
    layout_decode(text, L);
    layout_wrap(L, wrap_w, lh, gw, st);
    return L;
}

/* --- 闁哄倸娲﹀﹢鏉棵圭€ｎ亶鍟?闁告稒鍨濋懙?闂侇偄顦扮€?闁稿繗浜弫銈団偓鍦仧楠?闁糕晞妗ㄧ花顒佺▔婵犲洦妗ㄩ柣銊ュ椤㈡垹鏁崘銊ф拱) --- */

/* 閻庢稒顨呴懜鐗堟媴瀹ュ懏绂?缂備胶鍠嶇粩鎾触鎼达綆浼傞柟鎭掑劚瑜?full 濞?stb 闁稿繗浜弫?:闁稿秴绻掔粈灞剧▔?0xAARRGGBB;
 * colored=true 闁哄啳娉涢崕姘辨閻樺搫娈伴悽顖ょ畵椤や線鎳?鐟滄壋鏅炴竟?emoji),闁告熬绠戦崹顖炲磽韫囨洜顦卞☉鎾虫惈婢х娀寮查婵嗩棌 閼?alpha闁?
 * xoff/yoff 濞戞捁妗ㄧ紞鍛村炊閸撗勭ゲ閻?pen+baseline 闁汇劌瀚划顖炲礆鐠鸿桨鐒婄紒澶嬬湽閳?*/
struct GlyphImg
{
    int w, h;
    int xoff, yoff;
    int advance;
    bool colored;
    std::vector<unsigned int> px;
};

/* full: 闁告娲栭悺褏绮敃鈧鏃€鎯旈敂鐣屻偞闂佹彃绻掑▓鎴炵▔婵犱胶鐟撻柡?閻庢稒銇炵紞瀣?render_get_font 闁? */
struct TextMeasureCtx
{
    whaleui_render_t* r;
    int fs;
    std::string family;
    bool bold;
};
#ifdef WHALEUI_BUILD_FULL
static int glyph_ttf(unsigned int cp, void* st);
#else
static int glyph_stb(unsigned int cp, void* st);
#endif

#ifdef WHALEUI_BUILD_FULL

/* open a registered font file (no fallback chain, no cache); returns the
 * TTF_Font at an arbitrary size (callers set the real size via
 * ensure_font_state). NULL when the family is not registered. */
static TTF_Font* open_registry_font(const std::string& family)
{
    whaleui_font_registry* reg = whaleui_font_registry_get();
    for (size_t i = 0; i < reg->count; ++i) {
        if (std::strcmp(reg->fonts[i].family, family.c_str()) == 0) {
            SDL_IOStream* io = nullptr;
            if (reg->fonts[i].path) {
                io = SDL_IOFromFile(reg->fonts[i].path, "rb");
            } else if (reg->fonts[i].data && reg->fonts[i].len) {
                io = SDL_IOFromMem(const_cast<unsigned char*>(
                                       reg->fonts[i].data),
                                   reg->fonts[i].len);
            }
            if (!io) {
                return nullptr;
            }
            return TTF_OpenFontIO(io, true, 16.0f);
        }
    }
    return nullptr;
}

/* apply (size, style) to a font only when it changed (SDL3_ttf rebuilds
 * its glyph cache on either call, so skipping the no-op calls matters on
 * mixed-size pages) */
static void ensure_font_state(whaleui_render_t* r, TTF_Font* font, int size,
                              int style)
{
    auto it = r->font_state.find(font);
    if (it != r->font_state.end() && it->second.first == size &&
        it->second.second == style) {
        return;
    }
    TTF_SetFontSize(font, static_cast<float>(size > 0 ? size : 16));
    TTF_SetFontStyle(font, style);
    r->font_state[font] = std::make_pair(size > 0 ? size : 16, style);
}

/* sync the primary font AND its whole fallback chain to the current
 * (size, style): SDL3_ttf renders a fallback glyph at the FALLBACK's own
 * size, so every chain member must match the run being rasterized. */
static void sync_chain(whaleui_render_t* r, TTF_Font* font, int size,
                       int style)
{
    ensure_font_state(r, font, size, style);
    auto it = r->font_chain.find(font);
    if (it != r->font_chain.end()) {
        for (TTF_Font* fb : it->second) {
            ensure_font_state(r, fb, size, style);
        }
    }
}

/* lazily open the next registered font that can provide `cp`, attach it
 * to every primary font's fallback chain and return it. Called when a
 * glyph is missing - a page that never renders CJK/emoji never opens
 * those fonts (a registered-but-unused font costs only its path string).
 * A font that does NOT provide the glyph is closed again and remembered
 * in fallback_tried, so it is not reopened for every missing glyph. */
static TTF_Font* ensure_fallback(whaleui_render_t* r, TTF_Font* font,
                                 int size, int style, unsigned int cp)
{
    whaleui_font_registry* reg = whaleui_font_registry_get();
    for (size_t i = 0; i < reg->count; ++i) {
        const std::string fam = reg->fonts[i].family;
        bool open = false;
        for (auto& f : r->fonts) {
            if (f.first == fam) {
                open = true;
                break;
            }
        }
        /* the default font already covers its own family */
        if (open || fam == r->default_family) {
            continue;
        }
        bool tried = false;
        for (auto& t : r->fallback_tried) {
            if (t == fam) {
                tried = true;
                break;
            }
        }
        if (tried) {
            continue;
        }
        TTF_Font* fb = open_registry_font(fam);
        if (!fb) {
            continue;
        }
        ensure_font_state(r, fb, size, style);
        if (!TTF_FontHasGlyph(fb, cp)) {
            /* cannot help with this glyph: close it and remember, so the
             * next missing glyph does not reopen a useless font */
            TTF_CloseFont(fb);
            r->fallback_tried.push_back(fam);
            continue;
        }
        /* NOTE: no TTF_AddFallbackFont. SDL3_ttf's font chain makes
         * TTF_FontHasGlyph report TRUE for chain-provided glyphs while
         * metrics/bitmap still come from the primary (.notdef), and one
         * shared fallback font restyles across sizes when any primary
         * syncs. The engine manages fallback itself: glyph_ttf /
         * glyph_img_ttf pick the providing font via ensure_fallback and
         * rasterize it directly (font_chain below only records which
         * primaries already attach this fallback, for size syncing). */
        for (auto& kv : r->font_chain) {
            kv.second.push_back(fb);
        }
        r->fallback_open.push_back(fb);
        r->fonts.emplace_back(fam, fb); /* marks it open */
        return fb;
    }
    return nullptr;
}

/* case-insensitive family-name match (CSS "Segoe UI" vs TTF real name) */
static bool family_eq(const char* a, const char* b)
{
    if (!a || !b) {
        return false;
    }
    for (; *a && *b; ++a, ++b) {
        char ca = *a;
        char cb = *b;
        if (ca >= 'A' && ca <= 'Z') {
            ca = static_cast<char>(ca - 'A' + 'a');
        }
        if (cb >= 'A' && cb <= 'Z') {
            cb = static_cast<char>(cb - 'A' + 'a');
        }
        if (ca != cb) {
            return false;
        }
    }
    return *a == 0 && *b == 0;
}

/* get (or open) the font for a family; one TTF_Font per family, size and
 * style applied on demand. Generic families ("" / sans-serif / serif /
 * monospace) and unknown families resolve to the default font. CSS family
 * lists like "Segoe UI", Helvetica, sans-serif match the real font names
 * reported by SDL3_ttf, so a page naming a font we registered by file
 * name ("segoeui.ttf") still resolves to it. */
TTF_Font* render_get_font(whaleui_render_t* r, const std::string& family, int size,
                          int style)
{
    if (size <= 0) {
        size = 16;
    }
    std::string key = family;
    for (auto& f : r->fonts) {
        if (f.first == key) {
            sync_chain(r, f.second, size, style);
            return f.second;
        }
    }
    /* try each family in the CSS list, in order */
    std::vector<std::string> fams = split_families(family);
    if (fams.empty()) {
        fams.push_back("");
    }
    TTF_Font* font = nullptr;
    for (const std::string& fam : fams) {
        if (fam.empty() || fam == "sans-serif" || fam == "serif" ||
            fam == "monospace") {
            font = r->font_default;
            break;
        }
        font = open_registry_font(fam);
        if (font) {
            break;
        }
        /* file-name miss: match the real family name of an opened font
         * ("Segoe UI" -> the font opened from segoeui.ttf). The default
         * font is opened at render_create and not in r->fonts, so it is
         * checked too. */
        if (r->font_default) {
            const char* real = TTF_GetFontFamilyName(r->font_default);
            if (real && family_eq(real, fam.c_str())) {
                font = r->font_default;
                break;
            }
        }
        for (auto& f : r->fonts) {
            const char* real = TTF_GetFontFamilyName(f.second);
            if (real && family_eq(real, fam.c_str())) {
                font = f.second;
                break;
            }
        }
        if (font) {
            break;
        }
    }
    if (!font) {
        font = r->font_default;
    }
    if (font) {
        /* record the fallbacks opened so far (engine-managed fallback; no
         * TTF_AddFallbackFont - see ensure_fallback's note) */
        if (r->font_chain.find(font) == r->font_chain.end()) {
            r->font_chain[font]; /* create the chain entry */
        }
        sync_chain(r, font, size, style);
        r->fonts.emplace_back(key, font);
    }
    return font;
}
#else /* !WHALEUI_BUILD_FULL: text rendering needs SDL3_ttf (full only).
         stb_font text lands with the lite/minimal font path. */
TTF_Font* render_get_font(whaleui_render_t*, const std::string&, int, int) { return nullptr; }
#endif

/* (struct TRect lives in render_internal.h) */

#ifdef WHALEUI_BUILD_FULL
/* full: 闁告娲栭悺褏绮敃鈧崕姘辨閻樺樊鍟嶉柕鍡曠簿SCII 濞戞挸閰ｅ?ASCII 缂備胶鍠嶇粩瀵告導?TTF_GetGlyphMetrics(閻?
 * fallback chain,CJK/emoji 閻庣妫勭€瑰啿顫㈤敐鍥ｂ偓?,濞?glyph_img_ttf 闁?advance 闁告艾鏈花?
 * 婵炴挸寮堕悡瀣媴瀹ュ洨鏋傚☉鎾抽缁旈浠﹂埀顒傗偓纭呮鐎硅櫕绋夐妷锔惧濞戞挴鍋撻柤閿嬬暘閳ь兛绮維CII 闁活潿鍔庣槐锔锯偓娑欘焾閵?闂?ASCII 闁?(font,cp) 缂傚倹鎸搁悺銊╁Υ?*/
static int glyph_ttf(unsigned int cp, void* st)
{
    TextMeasureCtx* c = static_cast<TextMeasureCtx*>(st);
    TTF_Font* font = render_get_font(c->r, c->family, c->fs,
                                     c->bold ? kFontBold : 0);
    if (!font) {
        return 0;
    }
    if (cp < 0x80) {
        if (c->r->ascii_font != font || c->r->ascii_fs != c->fs) {
            c->r->ascii_font = font;
            c->r->ascii_fs = c->fs;
            for (int i = 0; i < 128; ++i) {
                int m0 = 0, m1 = 0, m2 = 0, m3 = 0, adv = 0;
                TTF_GetGlyphMetrics(font, static_cast<Uint32>(i),
                                    &m0, &m1, &m2, &m3, &adv);
                c->r->ascii_w[i] = adv;
            }
        }
        return c->r->ascii_w[cp];
    }
    /* non-ASCII: cached per (font, size, codepoint); fallback chain included */
    /* The chain is NOT used for metrics: TTF_GetGlyphMetrics reports the
     * PRIMARY font's .notdef advance for missing glyphs (it does not walk
     * the fallback chain, while TTF_GetGlyphImage does) - measuring the
     * primary font gave CJK a 12px .notdef width at 18px while the paint
     * path drew 18px glyphs. Layout/widths/raster buffers were all off and
     * the last CJK char fell outside the buffer ("婵烇絽宕€瑰啿效閸屾粌鍋? lost its 缂?.
     * Measure the FALLBACK font that will actually render the glyph. */
    TTF_Font* gfont = font;
    if (cp >= 0x80 || !TTF_FontHasGlyph(font, cp)) {
        TTF_Font* fb = ensure_fallback(c->r, font, c->fs,
                                       c->bold ? kFontBold : 0, cp);
        if (fb) {
            gfont = fb;
        }
    }
    if (gfont) {
        ensure_font_state(c->r, gfont, c->fs,
                          c->bold ? kFontBold : 0);
    }
    std::tuple<TTF_Font*, int, unsigned int> key(
        gfont, static_cast<int>(c->fs), cp);
    auto it = c->r->glyph_w_cache.find(key);
    if (it != c->r->glyph_w_cache.end()) {
        return it->second;
    }
    int m0 = 0, m1 = 0, m2 = 0, m3 = 0, adv = 0;
    TTF_GetGlyphMetrics(gfont, cp, &m0, &m1, &m2, &m3, &adv);
    c->r->glyph_w_cache[key] = adv;
    return adv;
}

/* full: 閻庢稒顨呴懜鐗堟媴瀹ュ懏绂?缂備胶鍠嶇粩?GlyphImg 闁规亽鍎辫ぐ?闁靛棔绻俆F_GetGlyphImage 閻?fallback 闂?
 * TTF_IMAGE_COLOR(COLR 鐟滄壋鏅炴竟濠勨偓娑欘殔閼?闁?闁稿秴绻掔粈宀勬嚊椤忓嫮鏁ㄥΛ鐗堢矎婢?TTF_IMAGE_ALPHA(闁诲繑婢樼€?
 * 闁?濠?fg 闁肩懓鐪伴埀顒€鍊搁悾鐐媴?x = pen + minx(bitmap_left), y = baseline - maxy
 * (bitmap_top),濞?TTF_GetGlyphMetrics 閺夆晜鏌ㄥú鏍ㄧ▔閳ь剟鎳?advance 濞?glyph_ttf 闁告艾鏈花顕€濡?
 * ponytail: 婵絽绻愰悺褑銇愰姀鐘电处/闂佸簱鍋撴慨锝勬缁斿瓨绋?SDL_Surface,闁?ckey 闁汇劌瀚惌鎯ь嚗?select 濞戞挸顑嗘刊铏圭驳?
 * 婵絽绻愰幎姘舵焻閹邦剛鎽熺憸鑸灪鐟曞棝寮?闁兼眹鍎寸换鏍尵閼姐倗鍙氶柡鍌氭处濠€浼村箣閹邦喗鎳曞Λ?闁?(font,cp) 缂傚倹鎸搁悺銊р偓娑欘殔閼哥増鎷呭鍛闁?*/
static bool glyph_img_ttf(whaleui_render_t* r, const std::string& family,
                          int fs, int style, unsigned int cp, unsigned int fg,
                          GlyphImg& out)
{
    TTF_Font* font = render_get_font(r, family, fs, style);
    if (!font) {
        return false;
    }
    /* render_get_font synced the font + its chain to THIS size/style. A
     * glyph the primary font does not provide lazily opens the next
     * registered font as fallback (unused CJK/emoji fonts cost nothing
     * until a page needs them). TTF_GetGlyphMetrics alone cannot detect
     * this - it reports .notdef metrics for missing glyphs AND does not
     * walk the fallback chain, so the metrics + bitmap below must come
     * from the SAME font that provides the glyph (glyph_ttf measures the
     * same font - see its comment). */
    TTF_Font* gfont = font;
    if (cp >= 0x80 || !TTF_FontHasGlyph(font, cp)) {
        /* non-ASCII: never trust TTF_FontHasGlyph on the primary - once a
         * fallback font is attached to its chain (TTF_AddFallbackFont),
         * hasGlyph reports true for chain-provided glyphs while
         * metrics/bitmap still come from the primary (.notdef 16px box for
         * CJK at 48px). Always ask ensure_fallback for the font that truly
         * provides the glyph (it returns null when the primary has it). */
        TTF_Font* fb = ensure_fallback(r, font, fs, style, cp);
        if (fb) {
            gfont = fb;
        }
    }
    /* gfont may be a SHARED fallback font (one msyh serves every primary
     * font) that another primary font restyled to a different size:
     * re-apply (fs, style) right before measuring + rasterizing this
     * glyph, or a stray 16px sync leaves a 48px CJK run rasterizing 16px
     * glyphs (big titles looked cut/short). */
    if (gfont) {
        ensure_font_state(r, gfont, fs, style);
    }
    int minx = 0, maxx = 0, miny = 0, maxy = 0, adv = 0;
    if (!TTF_GetGlyphMetrics(gfont, cp, &minx, &maxx, &miny, &maxy, &adv)) {
        return false;
    }
    TTF_ImageType type = TTF_IMAGE_INVALID;
    SDL_Surface* img = TTF_GetGlyphImage(gfont, cp, &type);
    if (!img) {
        return false;
    }
    out.w = img->w;
    out.h = img->h;
    out.xoff = minx;
    out.yoff = -maxy;
    out.advance = adv;
    out.colored = (type == TTF_IMAGE_COLOR);
    out.px.resize(static_cast<size_t>(img->w) * img->h);
    if (out.colored) {
        /* ARGB8888 閻忓繐绻掗顒勫礃閸涱厾鎽犻幖?= B,G,R,A 闁?0xAARRGGBB,濞?framebuffer 濞戞挴鍋撻柤?*/
        std::memcpy(out.px.data(), img->pixels, out.px.size() * 4);
    } else {
        /* 闁诲繑婢樼€瑰磭鈧稒顨呴懜?SDL3_ttf 闁告劖鐟у▍褔鎳?+ alpha,闁哄洦瀵у畷鍙夌▔?fg 闁?濞?fg alpha) */
        const unsigned char* p =
            static_cast<const unsigned char*>(img->pixels);
        const unsigned int rgb = fg & 0xFFFFFF;
        const unsigned int fa = (fg >> 24) & 0xFF;
        for (size_t i = 0; i < out.px.size(); ++i) {
            unsigned int a = p[i * 4 + 3] * fa / 255;
            out.px[i] = a ? (a << 24) | rgb : 0;
        }
    }
    SDL_DestroySurface(img);
    return true;
}
#else
/* --- stb_truetype 闁告艾娴烽?婵炴潙顑呴?+ 鐟滄壋鏅炴竟濠勨偓娑欘殔閼?COLR/CPAL,闁告瑥鍊介埀?stb#512/#1135) --- */

/* 濠㈠爢鍜佷紓閻犲洩顕цぐ?sfnt 閻炴稏鍔岄悺褍鈻撻棃娑欑秵濞?big-endian) */
static unsigned int be16(const unsigned char* p)
{
    return (static_cast<unsigned int>(p[0]) << 8) | p[1];
}
static unsigned int be32(const unsigned char* p)
{
    return (static_cast<unsigned int>(p[0]) << 24) |
           (static_cast<unsigned int>(p[1]) << 16) |
           (static_cast<unsigned int>(p[2]) << 8) | p[3];
}

/* 闁革负鍔岄悺褎鎷呴幘瀛樻闁硅鍠曢懙鎴﹀蓟閵夛箑顥?sfnt 閻?tag 4 閻庢稒顨夋俊?闁汇劌瀚禍鍝ョ矓?閺夆晜鏌ㄥú鏍儎缁嬫鍤犻柡浣哄瀹撲胶鎸ф搴′化闁汇劌瀚禍鍝ョ矓?
 * TTC 闁告瑦鐗滈鍥ㄧ▔閳ь剚绋夐鍕憻濞达絾鎸堕埀顒€鍊规竟妯荤▔瀹ュ懎鐓傞弶鈺傛煥濞?-1闁?*/
static int font_table_off(const unsigned char* data, size_t len, const char* tag)
{
    if (!data || len < 12) {
        return -1;
    }
    int fontstart = stbtt_GetFontOffsetForIndex(data, 0);
    if (fontstart < 0 || fontstart + 12 > static_cast<int>(len)) {
        return -1;
    }
    unsigned int n = be16(data + fontstart + 4);
    for (unsigned int i = 0; i < n; ++i) {
        size_t r = static_cast<size_t>(fontstart) + 12 + i * 16;
        if (r + 16 > len) {
            return -1;
        }
        const unsigned char* rec = data + r;
        if (rec[0] == static_cast<unsigned char>(tag[0]) &&
            rec[1] == static_cast<unsigned char>(tag[1]) &&
            rec[2] == static_cast<unsigned char>(tag[2]) &&
            rec[3] == static_cast<unsigned char>(tag[3])) {
            unsigned int off = be32(rec + 8);
            return off < len ? static_cast<int>(off) : -1;
        }
    }
    return -1;
}

/* COLR 閻忕偛鍊介鍥亹?閻忕偛鍊搁悺褑銇?id + 閻犲鍟虫竟濠囧级閹稿孩钂嬮柣?闁告瑥鍊介埀?stb#1135 闁?stbtt_glyphlayer) */
struct ColrLayer { unsigned short glyph; unsigned short color; };

/* 闁哄被鍎叉竟?glyph 闁?COLR 閻?缂佺偓瀵ч埀顑嫬顥囬柟?base glyph records 闁?glyph id 闁告娲ょ花?
 * 闁轰椒鍗抽崳铏圭棯瑜嶉崵鎴︽儌缁舵瑩宕欓悩鎻掔．,婵絽绻愰悺褑銇愰～顓狀伇婵炲棌鈧啿璁查柟鎭掑劚瑜?闁靛棗鍊界换鎴﹀炊閻愯尙婀撮柡?0 = 閻犲洢鍎遍悺褑銇愰姀鈩冿骏閻忕偛鍊堕埀?*/
static int colr_layers(const unsigned char* data, int colr_off,
                       unsigned int gid, const ColrLayer*& out)
{
    const unsigned char* t = data + colr_off;
    unsigned int n = be16(t + 2);
    unsigned int bgo = be32(t + 4);
    unsigned int lo = be32(t + 8);
    for (unsigned int i = 0; i < n; ++i) {
        const unsigned char* r = t + bgo + i * 6;
        if (be16(r) == gid) {
            unsigned int fi = be16(r + 2);
            unsigned int nl = be16(r + 4);
            out = reinterpret_cast<const ColrLayer*>(t + lo + fi * 4);
            return static_cast<int>(nl);
        }
    }
    return 0;
}

/* CPAL v0 閻犲鍟虫竟濠囧级閸ф鏉归柤?BGRA 闁告劕鎳庨悺銊︽償?闁?0xAARRGGBB);colorid==0xFFFF 闁汇垼绮鹃惃鐔兼偨?
 * 闁哄倸婀遍弫銈夊礈瀹ュ棙鐝柤鐟扮湴閳ь剙鍊歌ぐ鍥╂嫬閸愵厼顥忛柡?0(濡絾鐗旈柌?闁?*/
static unsigned int colr_palette_color(const unsigned char* data, int cpal_off,
                                       unsigned int colorid)
{
    if (cpal_off < 0 || colorid == 0xFFFF) {
        return 0xFFFFFFFF;
    }
    const unsigned char* t = data + cpal_off;
    unsigned int npa = be16(t + 4);
    unsigned int npe = be16(t + 2);
    if (npa == 0 || colorid >= npe) {
        return 0xFFFFFFFF;
    }
    unsigned int cro = be32(t + 8);
    unsigned int pidx = be16(t + 12); /* palette 0 闁?colorRecordIndices */
    const unsigned char* c = t + cro + pidx * 4 + colorid * 4;
    return (static_cast<unsigned int>(c[3]) << 24) |
           (static_cast<unsigned int>(c[2]) << 16) |
           (static_cast<unsigned int>(c[1]) << 8) | c[0];
}

/* 婵炴挸寮堕悡?COLR 闁告帒妫楅惇鎵偓娑欘殔閼哥増绋?RGBA(0xAARRGGBB);閺夆晜鏌ㄥú?false 閻炴稏鍔庨妵姘跺籍閻樿尙婀?閻犲鍟伴弫銈夊棘绾懓娉?
 * 闁哄拋鍣ｉ埀顒佹皑娴煎棙鎯旈敃浣虹唴鐎?闁靛棗鍊归惁锛勪沪?stbtt 濞达絽绉村ù?+ 閻犲鍟虫竟濠囧级閸ф鏉归柤?src-over 闁告艾鐗婇崹姘跺Υ?*/
static bool colr_render(const stbtt_fontinfo& info, float scale,
                        const unsigned char* data, int colr_off, int cpal_off,
                        unsigned int gid, unsigned int fg,
                        std::vector<unsigned int>& px, int& w, int& h,
                        int& xoff, int& yoff)
{
    const ColrLayer* layers = nullptr;
    int nl = colr_layers(data, colr_off, gid, layers);
    if (nl <= 0) {
        return false;
    }
    struct R { unsigned char* bmp; int w, h, x, y; unsigned int color; };
    std::vector<R> rs;
    int minx = 0x7FFFFFFF, miny = 0x7FFFFFFF, maxx = -0x7FFFFFFF, maxy = -0x7FFFFFFF;
    for (int i = 0; i < nl; ++i) {
        int bw = 0, bh = 0, bx = 0, by = 0;
        unsigned char* bmp = stbtt_GetGlyphBitmap(&info, scale, scale,
                                                  layers[i].glyph,
                                                  &bw, &bh, &bx, &by);
        if (!bmp || bw <= 0 || bh <= 0) {
            stbtt_FreeBitmap(bmp, nullptr);
            continue;
        }
        R r;
        r.bmp = bmp;
        r.w = bw;
        r.h = bh;
        r.x = bx;
        r.y = by;
        r.color = colr_palette_color(data, cpal_off, layers[i].color);
        if (layers[i].color == 0xFFFF) {
            r.color = fg;
        }
        rs.push_back(r);
        if (bx < minx) minx = bx;
        if (by < miny) miny = by;
        if (bx + bw > maxx) maxx = bx + bw;
        if (by + bh > maxy) maxy = by + bh;
    }
    if (rs.empty()) {
        return false;
    }
    w = maxx - minx;
    h = maxy - miny;
    xoff = minx;
    yoff = miny;
    px.assign(static_cast<size_t>(w) * h, 0);
    for (size_t ri = 0; ri < rs.size(); ++ri) {
        const R& r = rs[ri];
        const unsigned int sr = (r.color >> 16) & 0xFF;
        const unsigned int sg = (r.color >> 8) & 0xFF;
        const unsigned int sb = r.color & 0xFF;
        for (int yy = 0; yy < r.h; ++yy) {
            int dy = r.y - miny + yy;
            if (dy < 0 || dy >= h) {
                continue;
            }
            for (int xx = 0; xx < r.w; ++xx) {
                unsigned int sa = r.bmp[yy * r.w + xx];
                if (sa == 0) {
                    continue;
                }
                int dx = r.x - minx + xx;
                if (dx < 0 || dx >= w) {
                    continue;
                }
                unsigned int& d = px[static_cast<size_t>(dy) * w + dx];
                unsigned int da = (d >> 24) & 0xFF;
                /* src-over */
                unsigned int oa = sa + da * (255 - sa) / 255;
                if (oa == 0) {
                    continue;
                }
                unsigned int dr = (d >> 16) & 0xFF;
                unsigned int dg = (d >> 8) & 0xFF;
                unsigned int db = d & 0xFF;
                unsigned int oc = (sr * sa + dr * da * (255 - sa) / 255) / oa;
                unsigned int og = (sg * sa + dg * da * (255 - sa) / 255) / oa;
                unsigned int ob = (sb * sa + db * da * (255 - sa) / 255) / oa;
                d = (oa << 24) | (oc << 16) | (og << 8) | ob;
            }
        }
        stbtt_FreeBitmap(r.bmp, nullptr);
    }
    return true;
}

/* stb font table for measuring (mirrors the draw path in draw_text_at) */
struct StbFonts
{
    struct F { stbtt_fontinfo info; float scale; int asc; int line_h; bool ok; };
    std::vector<F> fonts;
    std::vector<int> colr, cpal; /* 婵絽绻愰悺褎鎷?COLR/CPAL 閻炴稏鍔屾禍鍝ョ矓?闁哄啰濮鹃妴鍐╃▔?-1 */
    size_t pref;
    int line_h;
    explicit StbFonts(const std::string& family, int fs)
        : pref(static_cast<size_t>(-1)), line_h(fs > 0 ? fs : 16)
    {
        whaleui_font_registry* reg = whaleui_font_registry_get();
        if (!reg) {
            return;
        }
        for (size_t fi = 0; fi < reg->count; ++fi) {
            F f;
            f.ok = false;
            f.scale = 1.0f;
            f.asc = 0;
            f.line_h = line_h;
            const unsigned char* d = reg->fonts[fi].data;
            size_t l = reg->fonts[fi].len;
            int co = -1, cp = -1;
            if (d && l >= 4) {
                int off = stbtt_GetFontOffsetForIndex(d, 0);
                if (off >= 0 && stbtt_InitFont(&f.info, d, off)) {
                    f.scale = stbtt_ScaleForPixelHeight(&f.info, static_cast<float>(fs));
                    int desc = 0, linegap = 0;
                    stbtt_GetFontVMetrics(&f.info, &f.asc, &desc, &linegap);
                    f.line_h = static_cast<int>((f.asc - desc + linegap) * f.scale + 0.5f);
                    f.ok = true;
                    line_h = f.line_h;
                    co = font_table_off(d, l, "COLR");
                    cp = font_table_off(d, l, "CPAL");
                }
            }
            colr.push_back(co);
            cpal.push_back(cp);
            fonts.push_back(f);
        }
        /* preferred font: first CSS family match, else first usable font */
        std::vector<std::string> fams = split_families(family);
        for (const std::string& fam : fams) {
            if (fam.empty()) {
                continue;
            }
            bool generic = fam == "sans-serif" || fam == "serif" ||
                           fam == "monospace";
            if (generic) {
                continue;
            }
            for (size_t fi = 0; fi < fonts.size(); ++fi) {
                if (fonts[fi].ok && reg->fonts[fi].family &&
                    std::strcmp(reg->fonts[fi].family, fam.c_str()) == 0) {
                    pref = fi;
                    break;
                }
            }
            if (pref != static_cast<size_t>(-1)) {
                break;
            }
        }
        if (pref == static_cast<size_t>(-1)) {
            for (size_t fi = 0; fi < fonts.size(); ++fi) {
                if (fonts[fi].ok) {
                    pref = fi;
                    break;
                }
            }
        }
    }
    size_t pick(size_t start, unsigned int cp) const
    {
        if (start != static_cast<size_t>(-1) && fonts[start].ok &&
            stbtt_FindGlyphIndex(&fonts[start].info, cp) != 0) {
            return start;
        }
        for (size_t fi = 0; fi < fonts.size(); ++fi) {
            if (fi == start || !fonts[fi].ok) {
                continue;
            }
            if (stbtt_FindGlyphIndex(&fonts[fi].info, cp) != 0) {
                return fi;
            }
        }
        return static_cast<size_t>(-1);
    }
};
/* stb: 闁告娲栭悺褏绮敃鈧崕姘辨閻樺樊鍟?閻?fallback 閻庢稒銇炵紞瀣偘? */
static int glyph_stb(unsigned int cp, void* st)
{
    StbFonts* f = static_cast<StbFonts*>(st);
    size_t fi = f->pick(f->pref, cp);
    if (fi == static_cast<size_t>(-1)) {
        return 0;
    }
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&f->fonts[fi].info, cp, &adv, &lsb);
    return static_cast<int>(adv * f->fonts[fi].scale + 0.5f);
}

/* stb: 閻庢稒顨呴懜鐗堟媴瀹ュ懏绂?缂備胶鍠嶇粩?GlyphImg 闁规亽鍎辫ぐ?闁靛棔鏅疧LR 闁告帒妫楅惇鎵偓娑欘殔閼哥増娼忛幘鍐叉瘔闁煎浜滈悽顐ｏ紣濠婂棗顥?
 * (colored=true),闁哄拋鍣ｉ埀顒佽壘閻⊙嗐亹椤叀绀?fg 闁?閼?alpha闁靛棗鈧埣ff/yoff 濞戞捁娅ｅù澶屸偓?pen+baseline
 * 闁汇劌瀚紞鍛村炊閹傜剨缂?stb 閻犲浂鍘虹粻?濞?glyph_stb 闁告艾鏈花顔济圭€ｎ亶鍟?闁?*/
static bool glyph_img_stb(StbFonts& stb, unsigned int cp, unsigned int fg,
                          GlyphImg& out)
{
    size_t fi = stb.pick(stb.pref, cp);
    if (fi == static_cast<size_t>(-1)) {
        return false;
    }
    const StbFonts::F& f = stb.fonts[fi];
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&f.info, cp, &adv, &lsb);
    out.advance = static_cast<int>(adv * f.scale + 0.5f);
    unsigned int gid = stbtt_FindGlyphIndex(&f.info, cp);
    if (gid == 0) {
        return false;
    }
    const unsigned char* data = f.info.data;
    if (stb.colr[fi] >= 0 &&
        colr_render(f.info, f.scale, data, stb.colr[fi], stb.cpal[fi],
                    gid, fg, out.px, out.w, out.h, out.xoff, out.yoff)) {
        out.colored = true;
        return true;
    }
    unsigned char* bmp = stbtt_GetGlyphBitmap(&f.info, f.scale, f.scale,
                                              gid, &out.w, &out.h,
                                              &out.xoff, &out.yoff);
    if (!bmp || out.w <= 0 || out.h <= 0) {
        stbtt_FreeBitmap(bmp, nullptr);
        return false;
    }
    out.colored = false;
    out.px.resize(static_cast<size_t>(out.w) * out.h);
    const unsigned int sr = (fg >> 16) & 0xFF;
    const unsigned int sg = (fg >> 8) & 0xFF;
    const unsigned int sb = fg & 0xFF;
    const unsigned int fa = (fg >> 24) & 0xFF; /* 闁告挸绉靛▍?alpha 濞戞梹锚閸╁瞼鈧稒顨呴懜鐗堢▔?*/
    for (size_t i = 0; i < out.px.size(); ++i) {
        unsigned int a = bmp[i] * fa / 255;
        out.px[i] = a ? (a << 24) | (sr << 16) | (sg << 8) | sb : 0;
    }
    stbtt_FreeBitmap(bmp, nullptr);
    return true;
}
#endif

/* 閻庢稒顨呴懜鎵喆閸℃凹娼曢柣鈺傚浮閻?ascent + descent/2),闁活潿鍔嬬花顒勫棘閸パ呮憻/闁稿繐顦伴悥?闂侇偄顦亸顖炲垂閸屾粍绾悘鐐叉噸閼?
 * 閻炴稑鐭傞悵?th 闁告凹鍋夐、鎴犳崉?闁?th 閻忕偛鎳嶉懙鎴炲濮樻剚鍞ㄩ柣銏ｎ嚙濠€顏嗙磽閹惧啿鏆卞銈呯埣閸庢挳鎯冮崟顐ゆ憻鐟滆埇鍨奸～瀣喆婢跺﹣鐒婂☉鎾愁焾閳?
 * 濞?draw_text_at 闁汇劌瀚惇铏▔椤撶偟鍞ㄩ柛鎴濇缁旀挳鎳?闂侇剙鐏濋崢?caret 濞戞挸瀛╅弸鍐偓娑欘殜閺佸﹥鎷呭鍐ｅ亾?*/
int text_glyph_h(whaleui_render_t* r, int fs, const std::string& family,
                 bool bold)
{
    int gh = 0;
#ifdef WHALEUI_BUILD_FULL
    TTF_Font* gfont = render_get_font(r, family, fs, bold ? kFontBold : 0);
    if (gfont) {
        int ga = TTF_GetFontAscent(gfont);
        int gd = TTF_GetFontDescent(gfont);
        if (ga > 0) {
            gh = ga + gd / 2;
        }
    }
#endif
    return gh > 0 ? gh : text_line_h(r, fs, family, bold);
}

void text_size(whaleui_render_t* r, const std::string& text, int fs,
               const std::string& family, bool bold, int* tw, int* th,
               int wrap_w)
{
    *tw = *th = 0;
    if (text.empty() || !r) {
        return;
    }
    /* content-addressed cache: the layout pass measures every run every
     * relayout (a width animation re-lays out each frame) - the layout_text
     * walk below was the per-frame cost. Text/width/face unchanged -> O(1). */
    uint64_t key = 1469598103934665603ull;
    for (size_t i = 0; i < text.size(); ++i) {
        key ^= static_cast<unsigned char>(text[i]);
        key *= 1099511628211ull;
    }
    key ^= static_cast<uint64_t>(fs) * 0x9E3779B97F4A7C15ull;
    key ^= static_cast<uint64_t>(bold) * 0xBF58476D1CE4E5B9ull;
    key ^= static_cast<uint64_t>(wrap_w) * 0x94D049BB133111EBull;
    for (size_t i = 0; i < family.size(); ++i) {
        key ^= static_cast<unsigned char>(family[i]);
        key *= 1099511628211ull;
    }
    auto it = r->text_size_cache.find(key);
    if (it != r->text_size_cache.end()) {
        *tw = it->second.first;
        *th = it->second.second;
        return;
    }
    int lh = text_line_h(r, fs, family, bold);
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextLayout L = layout_text(text, wrap_w, lh, glyph_ttf, &mc);
#else
    StbFonts stb(family, fs);
    TextLayout L = layout_text(text, wrap_w, lh, glyph_stb, &stb);
#endif
    *tw = L.tw;
    *th = L.th;
    r->text_size_cache[key] = std::make_pair(*tw, *th);
}

int text_line_h(whaleui_render_t* r, int fs, const std::string& family, bool bold)
{
#ifdef WHALEUI_BUILD_FULL
    TTF_Font* font = render_get_font(r, family, fs,
                                     bold ? kFontBold : 0);
    if (font) {
        int h = TTF_GetFontHeight(font);
        if (h > 0) {
            return h;
        }
    }
    return fs > 0 ? fs : 16;
#else
    StbFonts stb(family, fs > 0 ? fs : 16);
    return stb.line_h;
#endif
}

std::vector<TRect> sel_rects(whaleui_render_t* r, const std::string& text,
                             int fs, const std::string& family, bool bold,
                             size_t a, size_t b, int wrap_w)
{
    std::vector<TRect> out;
    if (a > text.size()) {
        a = text.size();
    }
    if (b > text.size()) {
        b = text.size();
    }
    if (a > b) {
        std::swap(a, b);
    }
    if (a == b || text.empty()) {
        return out;
    }
    int lh = text_line_h(r, fs, family, bold);
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    const size_t nc = L.map.size();
    for (size_t li = 0; li < L.lines.size(); ++li) {
        const TextLayoutLine& ln = L.lines[li];
        int xacc = 0;
        int x0 = -1, x1 = -1;
        for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
            int w = gw(disp_cp_at(L, ci), st);
            if (x0 < 0 && L.map[ci] >= a) {
                x0 = xacc;
            }
            if (x1 < 0 && L.map[ci] >= b) {
                x1 = xacc;
                break;
            }
            xacc += w;
        }
        if (x0 < 0) {
            continue; /* line ends before a */
        }
        if (x1 < 0) {
            x1 = xacc; /* range extends past this line's end */
        }
        if (x1 > x0) {
            TRect rc = {x0, static_cast<int>(li) * lh, x1 - x0, lh};
            out.push_back(rc);
        }
        if (x1 >= xacc) {
            continue; /* keep scanning later lines (range continues) */
        }
        break;
    }
    return out;
}

void caret_pos(whaleui_render_t* r, const std::string& text, int fs,
               const std::string& family, bool bold, size_t off,
               int* cx, int* cy, int* ch, int wrap_w)
{
    int lh = text_line_h(r, fs, family, bold);
    if (lh <= 0) {
        lh = fs > 0 ? fs : 16;
    }
    if (text.empty()) {
        *cx = 0;
        *cy = 0;
        *ch = lh;
        return;
    }
    if (off > text.size()) {
        off = text.size();
    }
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    const size_t nc = L.map.size();
    /* 闁?off 闁圭鍋撻柛锔哄姀椤?off 闁解偓閽樺韬?[閻炴稑鐭傞々濠氬磻韫囨泤? 閻炴稑鑻悢顒勫磻韫囨泤顭?闁告牗妞藉Λ鍧楀Υ?
     * 閻炴稑鐭傞々濠氬籍?caret 闁汇垼顕у﹢顏嗘嫚閵夘煈鏀?x=0(濞戞挸绉靛Σ鎼佸礈瀹ュ嫮顏遍悶娑樼灱濞堟垹鎮扮仦鐣屽暡)闁?*/
    for (size_t li = 0; li < L.lines.size(); ++li) {
        const TextLayoutLine& ln = L.lines[li];
        size_t ls_off = (ln.cstart < nc) ? L.map[ln.cstart] : off;
        size_t le_off = (ln.cend < nc) ? L.map[ln.cend] : text.size();
        if (off < ls_off) {
            /* 闁解偓閽樺韬☉鎾筹梗缁斿鎮扮仦鐐睘閻忓繐褰炵粻锝夊触鎼存稈鍋撴担瑙勬嫳閻炴稑鐭侀、鎴烇純閺嶏妇顓洪柛?闁告瑯浜滃﹢顏嗙矚妤︽鏀藉☉鏂款儔濡潡鎯?
             * \n 濠㈣泛瀚ぐ鏌ユ嚄?鐟滅増鎸风紞鏃堝嫉椤掑喚鏀介悶娑樼焸椤╃粯寰勯崟顓熷€?*/
            *cx = 0;
            *cy = static_cast<int>(li) * lh;
            *ch = lh;
            return;
        }
        if (off >= ls_off && off <= le_off) {
            int xacc = 0;
            for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
                if (L.map[ci] >= off) {
                    break;
                }
                xacc += gw(disp_cp_at(L, ci), st);
            }
            *cx = xacc;
            *cy = static_cast<int>(li) * lh;
            *ch = lh;
            return;
        }
    }
    /* 闁稿繑绮岀花?闁哄倸娲﹀﹢浼村嫉椤愩垻鍟?*/
    const TextLayoutLine& last = L.lines.back();
    *cx = last.w;
    *cy = static_cast<int>(L.lines.size() - 1) * lh;
    *ch = lh;
}

/* defined below (editing helpers); needed by the paint path above */
void text_origin(whaleui_render_t* r, whaleui_layout_node_t* n,
                 const std::string& text, int fs, const std::string& family,
                 bool bold, int* tx, int* ty);
struct whaleui_layout_node;
whaleui_layout_node_t* editable_geo(whaleui_layout_node_t* n);

size_t utf8_char_len(unsigned char c)
{
    if (c < 0x80) {
        return 1;
    }
    if ((c & 0xE0) == 0xC0) {
        return 2;
    }
    if ((c & 0xF0) == 0xE0) {
        return 3;
    }
    if ((c & 0xF8) == 0xF0) {
        return 4;
    }
    return 1;
}

void apply_text_transform(std::string& s, const std::string& t)
{
    if (t == "uppercase") {
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c < 0x80 && c >= 'a' && c <= 'z') {
                s[i] = static_cast<char>(c - 32);
            }
        }
    } else if (t == "lowercase") {
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c < 0x80 && c >= 'A' && c <= 'Z') {
                s[i] = static_cast<char>(c + 32);
            }
        }
    } else if (t == "capitalize") {
        bool word_start = true;
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c >= 0x80) {
                i += utf8_char_len(c) - 1;
                word_start = false;
                continue;
            }
            if (c == ' ' || c == '\t' || c == '-') {
                word_start = true;
            } else if (word_start) {
                if (c >= 'a' && c <= 'z') {
                    s[i] = static_cast<char>(c - 32);
                }
                word_start = false;
            }
        }
    }
}

void draw_text_at(whaleui_render_t* r, const std::string& text,
                  int bx, int by, int bw, int bh,
                  int fs, const std::string& family, unsigned int color,
                  int style, int align, lxb_dom_element* ckey,
                  const Clip* clip, int lsp, bool wrap, float opacity,
                  bool outline)
{
    /* 缂傚倹鎸搁悺銊╁蓟閵夘煈鍤勯柛蹇撶墣椤?text+闁哄秴鍢茬槐鈩冪▔瀹ュ懎缍侀柡?闁圭儤甯炴晶?layout_text)濞戞挸楠搁悺褑銇愰姀鐘插辅闁哄秴鎳庣€垫煡寮?
     * 婵絽绻愰幎姘舵煂瀹ュ拋妲婚悹渚婄磿閻?闁炽儲鏌￠埀?闁告柣鍔庨弫鍓ф暜瑜嶉顔夹掕箛搴ㄥ殝 run 闂佹彃绉甸弻濠囧箳閹烘柨顣奸柡鍥╁亾濡?42ms 闁汇劌瀚妵鍥ㄥ緞濞ｎ兘鍋?
     * 闁告稒鍨濋懙鎴︽儎鐎涙ê澶嶉柣顫妿缁憋妇鈧稒顭囧▓鎴炴媴瀹ュ懏绂堝☉鎾抽閺勫倻鈧?閺夆晝鍋涢悺褎鎷呴幘鏉戔叺鐎殿喒鍋?閻炴稑鐭傞悵顔济圭€ｎ喖娅ら梺顔尖偓鐔哄劜閺夆晛娲㈤埀?*/
    std::vector<unsigned int>* src = nullptr;
    int tw = 0, th = 0;
    int tx = bx, ty = by; /* paint origin (align/center applied below) */
    std::string ckey_str; /* cache key to write on miss ("" = no caching) */
#ifdef WHALEUI_BUILD_FULL
    if (ckey && !text.empty()) {
        uint64_t h = 1469598103934665603ull;
        for (size_t i = 0; i < text.size(); ++i) {
            h ^= static_cast<unsigned char>(text[i]);
            h *= 1099511628211ull;
        }
        char key[160];
        std::snprintf(key, sizeof(key), "%p|%d|%d|%s|%d|%u|%d|%llu",
                      static_cast<void*>(ckey), fs, style, family.c_str(),
                      wrap ? bw : -1, color, lsp,
                      static_cast<unsigned long long>(h));
        auto it = r->text_cache.find(key);
        if (it != r->text_cache.end() && !it->second.px.empty()) {
            whaleui_render_t::TextCacheEntry& e = it->second;
            src = &e.px;
            tw = e.w;
            th = e.h;
            e.last_use = ++r->tc_tick;
        } else {
            ckey_str = key;
        }
    }
#endif
    if (!src) {
        /* cache miss: layout + rasterize this run */
        if (fs <= 0) {
            fs = 16;
        }
        const bool bold = (style & kFontBold) != 0;
        int lh = text_line_h(r, fs, family, bold);
        if (lh <= 0) {
            lh = fs;
        }
        /* 缂備胶鍠嶇粩瀵糕偓娑欘殔閼镐即骞掗妷銉ョ稉:闁圭儤甯炴晶?婵炴潙顑呴?濞戞挸娴风划顖炲礆鐠哄搫褰欓柣顫妼閹挻绋夐埀顒勫触鎼达綆浼傞悗娑欘殔閼镐即寮堕妷锔剧埍,advance/闁稿绻掍簺
         * 濞戞挶鍎查悧鍛婄▔閳ь剟鎳?full 濞?stb 闁告瑯浜濆﹢浣规交濞嗘挸娅″☉鎾崇Т閹?婵炴挸寮堕悡瀣嚗椤忓棗绠氶柛娆樹簼濠€浣圭▔閳ь剚绂?*/
        int baseline_off;
        TextLayout L;
#ifdef WHALEUI_BUILD_FULL
        TTF_Font* font = render_get_font(r, family, fs, style);
        if (!font) {
            return;
        }
        baseline_off = TTF_GetFontAscent(font);
        TextMeasureCtx mc = { r, fs, family, bold };
        L = layout_text(text, (wrap && bw > 0) ? bw : 0, lh, glyph_ttf, &mc);
#else
        StbFonts stb(family, fs);
        if (stb.pref == static_cast<size_t>(-1)) {
            return;
        }
        baseline_off = static_cast<int>(stb.fonts[stb.pref].asc *
                                        stb.fonts[stb.pref].scale + 0.5f);
        L = layout_text(text, (wrap && bw > 0) ? bw : 0, lh, glyph_stb, &stb);
#endif
        if (L.lines.empty()) {
            return;
        }
        tw = L.tw;
        th = L.th;
        /* letter-spacing is added to the pen per glyph (px += advance +
         * lsp) but L.tw is the plain advance sum: a spaced line's last
         * glyph lands lsp*(chars-1) past tw and the raster clip (tx2 >=
         * tw) sliced its right side off - small fonts with letter-spacing
         * visibly lost their tail. Grow the buffer by the widest line's
         * spacing so every glyph fits. */
        if (lsp > 0) {
            size_t max_ch = 0;
            for (size_t li = 0; li < L.lines.size(); ++li) {
                size_t ch = L.lines[li].cend - L.lines[li].cstart;
                if (ch > max_ch) {
                    max_ch = ch;
                }
            }
            if (max_ch > 1) {
                tw += lsp * static_cast<int>(max_ch - 1);
            }
        }
        /* some glyphs are wider than their advance (msyh's f/t/v/w/y/
         * A/V/W/Y/Z/&/_// have maxx 1px past advance; italic/kerning add
         * more): L.tw is the advance sum, so a line's LAST glyph's ink
         * falls past tw and the raster clip (tx2 >= tw) sliced it off -
         * small mixed CJK/latin text lost its tail. The 2px slack covers
         * the typical 1px overflow plus a hair of anti-aliasing. */
        tw += 2;
        if (tw <= 0 || th <= 0) {
            return;
        }
        auto glyph_img = [&](unsigned int cp, GlyphImg& g) {
#ifdef WHALEUI_BUILD_FULL
            return glyph_img_ttf(r, family, fs, style, cp, color, g);
#else
            return glyph_img_stb(stb, cp, color, g);
#endif
        };
        /* 闂侇偅鍔曢悺褑銇愰姀陇顩柡?闁哥儐鍨粩鏉戭嚗椤忓棗绠?:閻庢稒顨呴懜鐗堟媴瀹ュ懏绂?RGBA,鐎瑰憡褰冮幆鍫ュ礈瀹ュ棙鐝柤鐟板级閸ㄣ劏銇愰埡鍕棌 emoji
         * 闁煎浜ｉ棅鈺傦紣濠婂棗顥?src-over 闁告帞澧楅弸鍐嫉椤掑倻澶勯柛鎰湴閳ь兛闈爐b 闁哄啰濮撮幃搴ㄥ箣閹邦喚鐓愬ù?闁哄拋鍣ｉ埀顒佽壘閻⊙嗐亹閵忕姴绀佺紒?
         * 1px 闁告劕绉堕弫鐐▔閳ь剙鈻?fake bold);full 闁汇劌瀚惌鏍ㄦ媴閹捐埖鏆?FreeType 闁革负鍔岄悺褑銇愰姀鐘叉暥閻庣懓鏈崹姘跺Υ?*/
        std::vector<unsigned int> buf(static_cast<size_t>(tw) * th, 0);
        for (size_t li = 0; li < L.lines.size(); ++li) {
            const TextLayoutLine& ln = L.lines[li];
            const int baseline = static_cast<int>(li * lh) + baseline_off;
            int px = 0;
            for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
                GlyphImg g = {};
                if (glyph_img(disp_cp_at(L, ci), g)) {
                    const int passes =
#ifndef WHALEUI_BUILD_FULL
                        (bold && !g.colored) ? 2 :
#endif
                        1;
                for (int pass = 0; pass < passes; ++pass) {
                    const int dx0 = px + g.xoff + pass;
                    const int dy0 = baseline + g.yoff;
                    for (int yy = 0; yy < g.h; ++yy) {
                        const int ty2 = dy0 + yy;
                        if (ty2 < 0 || ty2 >= th) {
                            continue;
                        }
                        for (int xx = 0; xx < g.w; ++xx) {
                            const int tx2 = dx0 + xx;
                            if (tx2 < 0 || tx2 >= tw) {
                                continue;
                            }
                            const unsigned int sp =
                                g.px[static_cast<size_t>(yy) * g.w + xx];
                            const unsigned int sa = (sp >> 24) & 0xFF;
                            if (sa == 0) {
                                continue;
                            }
                            if (outline) {
                                /* text-stroke paints the glyph OUTLINE
                                 * only. The 8-direction whole-glyph copies
                                 * (dx/dy = +-sw) filled wide strokes solid
                                 * - a 200px glyph with 1px stroke came out
                                 * as a solid silhouette ("glyph 閻庡湱鍋涚缓?).
                                 * Keep only pixels with a transparent
                                 * neighbour; solid interiors stay empty. */
                                bool edge = false;
                                for (int oy2 = -1; oy2 <= 1 && !edge; ++oy2) {
                                    for (int ox2 = -1; ox2 <= 1 && !edge;
                                         ++ox2) {
                                        if (!ox2 && !oy2) {
                                            continue;
                                        }
                                        int ny2 = yy + oy2, nx2 = xx + ox2;
                                        unsigned int na = 0;
                                        if (ny2 >= 0 && ny2 < g.h &&
                                            nx2 >= 0 && nx2 < g.w) {
                                            na = (g.px[static_cast<size_t>(ny2) * g.w +
                                                         nx2] >>
                                                  24) & 0xFF;
                                        }
                                        if (na == 0) {
                                            edge = true;
                                        }
                                    }
                                }
                                if (!edge) {
                                    continue;
                                }
                            }
                            unsigned int& d =
                                buf[static_cast<size_t>(ty2) * tw + tx2];
                            const unsigned int da = (d >> 24) & 0xFF;
                            const unsigned int oa =
                                sa + da * (255 - sa) / 255;
                            if (oa == 0) {
                                continue;
                            }
                            const unsigned int sr = (sp >> 16) & 0xFF;
                            const unsigned int sg = (sp >> 8) & 0xFF;
                            const unsigned int sb = sp & 0xFF;
                            const unsigned int dr = (d >> 16) & 0xFF;
                            const unsigned int dg = (d >> 8) & 0xFF;
                            const unsigned int db = d & 0xFF;
                            d = (oa << 24) |
                                (((sr * sa + dr * da * (255 - sa) / 255) /
                                  oa) << 16) |
                                (((sg * sa + dg * da * (255 - sa) / 255) /
                                  oa) << 8) |
                                ((sb * sa + db * da * (255 - sa) / 255) / oa);
                        }
                    }
                }
            }
            px += g.advance + lsp;
        }
    }
    /* 閻庨潧缍婄紞?line-box 閻忕偛鎳嶉懙?閻℃帒鎳庨崵顓㈡儎閹烘垹鎽嶅ǎ鍥ㄧ箖鐎垫梹銇勯崼鏇炲姤閻庨潧缍婄紞?select 闁稿﹨澹堥崵婊呮偘鐏炴垝绨抽悹? */
    tx = bx;
    if (align == 1) {
        tx = bx + (bw - tw) / 2;
    } else if (align == 2) {
        tx = bx + bw - tw;
    }
    /* 闁告劖鐟х槐锔锯偓?full):miss 闁哄啳鍩栨俊鎼佸礆濮橆厾鍨洪柡宥囧帶鐎垫煡鎯冮崟顏嗙Т闁搞儲鍎抽悺銊╁礂閵壯呭閻庢稒眉缁剁敻宕ユ惔锝囨暰閻㈩垎鍐炬Щ闁?*/
    if (!ckey_str.empty()) {
        whaleui_render_t::TextCacheEntry& e = r->text_cache[ckey_str];
        if (e.px.empty() || e.w != tw || e.h != th) {
            /* account the old raster bytes before replacing */
            r->tc_bytes -= e.px.size() * sizeof(unsigned int);
            e.px = std::move(buf);
            e.w = tw;
            e.h = th;
            r->tc_bytes += e.px.size() * sizeof(unsigned int);
        }
        e.last_use = ++r->tc_tick;
        /* bounded cache: a large page (qwen 21k) has hundreds of runs; cap
         * the total raster bytes and evict the least-recently-used entries
         * so it cannot grow unbounded. */
        const size_t kMaxBytes = 16 * 1024 * 1024; /* 16MB */
        while (r->tc_bytes > kMaxBytes) {
            auto victim = r->text_cache.begin();
            for (auto it = r->text_cache.begin(); it != r->text_cache.end();
                 ++it) {
                if (it->second.last_use < victim->second.last_use) {
                    victim = it;
                }
            }
            if (victim == r->text_cache.end()) {
                break;
            }
            r->tc_bytes -= victim->second.px.size() * sizeof(unsigned int);
            r->text_cache.erase(victim);
        }
        src = &e.px;
    } else {
        src = &buf;
    }
    } /* end cache miss: layout + rasterize */
    /* 闁搞劌鍊诲ú璺ㄤ沪閸涱剝鍘柟?閻庢稒顨呴懜浼存儎?(ascent+descent)闁兼澘鐭傚顏嗘偘瀹€鍕蒋 th:th 闁告凹鍋夐、鎴犳崉濠靛洦顦ч柤姹囧劜鐎?
     * th 閻忕偛鎳嶉懙?閻庢稒顨呴懜?闁汇垼顕у﹢顏嗙磽閹惧啿鏆卞銈呯埣閸?濞戞挸顑嗛弻鐔兼偩濞嗗繐姣夌紒宀冩濞?闁哄倸娲ら悺褏鎲撮崱姘兼綍闁稿绻嬬粭?闁炽儲鏌￠埀?input
     * 闁?闁瑰嘲銈搁悡鑸电▔婵犲浂妫熼柣銊ュ閻楁挳宕堕悩顔瑰亾閸屾氨绠戝銈堫嚙濠€?cache miss 濞戞柨顑呴ˇ濠氬箥瑜戦、?闁告稒鍨濋懙鎴犵磽閹惧磭鎽犻柤姹囧劥閻戯附娼?
     * ty 濞ｅ洦绻冪€垫棃宕氬┑鍡忓亾?by(濡炪倕鐖奸崕瀵糕偓闈涚秺缂?,闁告艾濂旂粩鎾棘閸ャ劍鎷卞Λ锝嗙墪閹舵氨浠﹂崨顒冨幀闁靛棔绀侀幃妤冪磼椤撶偞濮庨悹鎰尦閵嗗﹪宕戣箛搴ｇ憪闁?*/
    {
        int gh = text_glyph_h(r, fs, family, (style & kFontBold) != 0);
        if (gh < 1) {
            gh = th;
        }
        ty = gh <= bh ? by + (bh - gh) / 2 : by;
    }
    /* blend:闁烩晜鎸抽埀?RGBA(濞戞挸绉撮崯鈧柣顫妼婢х娀寮查婵嗩棌闁哄本鎹佹竟?鐟滄壋鏅炴竟?emoji 濞ｅ洦绻勯弳鈧柤濂変海闂娾晜锛愬鍡楊棌)闁?
     * opacity 闁哄嫷鍨版慨鈺呭箑娴ｇ儤鐣?闁告柣鍔庨弫?濞戞挻鏌х粭澶嬫交濞戞氨澶勯悗?key,闁圭鍋撳ù鐘劚濠€顏呮交濞嗘挸娅￠柟绋款槸閸庢氨妲愰悩鐢电礆闁衡偓?
     * alpha 闁炽儲鏌￠埀?缂傚倹鎸搁悺銊╁箰婢舵劖楗柟顑跨窔椤や線鎳濋幓鎺濇Щ闁?opacity 闁告柣鍔庨弫鐐▔瀹ュ懎鏅欏ù锝堟硶缁憋妇鈧稒锕㈤埀顒佸姇閹舵碍寰勬潏銊︽珡闁?
     * GPU 閻犱警鍨扮欢鐐哄礃?text_layer,CPU 閻犱警鍨扮欢鐐哄礃?framebuffer闁?*/
    std::vector<unsigned int>& fb = g_gpu ? r->text_layer : r->pixels;
    const int fw = g_gpu ? r->fb_w : r->width;
    const int fh = g_gpu ? r->fb_h : r->height;
    const bool fade = opacity < 1.0f;
    for (int yy = 0; yy < th; ++yy) {
        const int fy = ty + yy;
        if (fy < 0 || fy >= fh) {
            continue;
        }
        if (clip && (fy < clip->y || fy >= clip->y + clip->h)) {
            continue;
        }
        for (int xx = 0; xx < tw; ++xx) {
            unsigned int sp = (*src)[static_cast<size_t>(yy) * tw + xx];
            unsigned int sa = (sp >> 24) & 0xFF;
            if (sa == 0) {
                continue;
            }
            if (fade) {
                sa = static_cast<unsigned int>(sa * opacity);
                if (sa == 0) {
                    continue;
                }
                sp = (sa << 24) | (sp & 0x00FFFFFF);
            }
            const int fx = tx + xx;
            if (fx < 0 || fx >= fw) {
                continue;
            }
            if (clip && (fx < clip->x || fx >= clip->x + clip->w)) {
                continue;
            }
            unsigned int& d = fb[static_cast<size_t>(fy) * fw + fx];
            if (sa == 255) {
                /* opaque: direct copy, no src-over math (the common case
                 * for CJK/body glyph centers) */
                d = sp;
                continue;
            }
            const unsigned int da = (d >> 24) & 0xFF;
            if (da == 0) {
                /* destination transparent (the text layer was just cleared):
                 * write through without src-over math */
                d = sp;
                continue;
            }
            const unsigned int oa = sa + da * (255 - sa) / 255;
            if (oa == 0) {
                continue;
            }
            const unsigned int sr = (sp >> 16) & 0xFF;
            const unsigned int sg = (sp >> 8) & 0xFF;
            const unsigned int sb = sp & 0xFF;
            const unsigned int dr = (d >> 16) & 0xFF;
            const unsigned int dg = (d >> 8) & 0xFF;
            const unsigned int db = d & 0xFF;
            d = (oa << 24) |
                (((sr * sa + dr * da * (255 - sa) / 255) / oa) << 16) |
                (((sg * sa + dg * da * (255 - sa) / 255) / oa) << 8) |
                ((sb * sa + db * da * (255 - sa) / 255) / oa);
        }
    }
}

bool sel_range_for(whaleui_render_t* r, lxb_dom_element* el, size_t len,
                   size_t* a, size_t* b, int seq, int sel_lo, int sel_hi)
{    lxb_dom_element* sa = r->sel_anchor_el;
    lxb_dom_element* sf = r->sel_focus_el;
    if (!sa || !sf || !el) {
        return false;
    }
    if (sa == sf) {
        /* collapsed (caret / plain click): nothing is highlighted anywhere */
        if (r->sel_anchor == r->sel_focus) {
            return false;
        }
        if (el == sa) {
            size_t lo = static_cast<size_t>(r->sel_anchor);
            size_t hi = static_cast<size_t>(r->sel_focus);
            if (lo > hi) {
                std::swap(lo, hi);
            }
            *a = lo;
            *b = hi;
            return *a < *b && *a < len;
        }
        return false; /* same-element selection touches only that element */
    }
    /* cross-element: endpoint elements partially, everything between fully */
    if (el == sa) {
        *a = static_cast<size_t>(r->sel_anchor);
        *b = len;
        return *a < len;
    }
    if (el == sf) {
        *a = 0;
        *b = static_cast<size_t>(r->sel_focus);
        return *b > 0;
    }
    if (sel_lo >= 0 && sel_hi >= 0 && seq > sel_lo && seq < sel_hi) {
        *a = 0;
        *b = len;
        return len > 0;
    }
    return false;
}

void sel_seq(whaleui_render_t* r, int* lo, int* hi, const Clip* clip)
{
    *lo = *hi = -1;
    lxb_dom_element* sa = r->sel_anchor_el;
    lxb_dom_element* sf = r->sel_focus_el;
    if (!sa || !sf || sa == sf || !r->tree) {
        return;
    }
    int idx = 0;
    std::function<void(whaleui_layout_node_t*, int, int, bool)> walk =
        [&](whaleui_layout_node_t* n, int off_x, int off_y, bool tc) {
            if (!n->visible) {
                return;
            }
            const int my = idx++;
            if (n->el == sa && *lo < 0) {
                *lo = my;
            }
            if (n->el == sf && *hi < 0) {
                *hi = my;
            }
            /* same transform/fixed rule as paint_node, so the sequence
             * numbers stay aligned with what actually gets painted */
            if (!tc && n->el && !n->is_text) {
                std::string tv = sget(n->style, "transform");
                if (!tv.empty() && tv != "none") {
                    tc = true;
                } else if (sget(n->style, "position") == "fixed") {
                    tc = true;
                }
            }
            /* a selection endpoint outside the repaint region must still
             * receive its sequence number (paint_node does the same), so
             * the in-viewport middle of the selection keeps highlighting.
             * Text runs skip the cull exactly like paint_node. */
            if (!tc && !n->is_text &&
                !(n->el && (n->el == sa || n->el == sf)) &&
                paint_cull(r, n, off_x, off_y, clip)) {
                return;
            }
            if (n->is_text) {
                return;
            }
            /* clipped containers fully off-screen are skipped by paint too */
            std::string ov = sget(n->style, "overflow");
            if (ov == "hidden" || ov == "auto" || ov == "scroll") {
                int y0 = n->border.y + off_y;
                if (y0 + n->border.h <= 0 || y0 >= r->fb_h) {
                    return;
                }
            }
            int child_off = off_y + scroll_delta(r, n);
            for (whaleui_layout_node_t* c = n->first_child; c; c = c->next) {
                walk(c, off_x, child_off, tc);
            }
        };
    walk(r->tree->root, 0, 0, false);
    if (*lo > *hi) {
        std::swap(*lo, *hi);
    }
}

unsigned int accent_hl(whaleui_render_t* r, unsigned int alpha)
{
    unsigned int hl = (alpha << 24);
    auto it = r->theme_vars.find("--accent");
    if (it != r->theme_vars.end()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(it->second.c_str(), &c) == 0) {
            hl = (alpha << 24) | (c & 0x00FFFFFF);
        }
    }
    return hl;
}

void expand_hl_rects(std::vector<TRect>& rects, int lh)
{
    for (size_t i = 0; i < rects.size(); ++i) {
        TRect& rc = rects[i];
        if (rc.h < lh) {
            int d = lh - rc.h;
            rc.y -= d / 2 + 2;
            rc.h = lh;
        } else {
            rc.y -= 2;
            rc.h += 4;
        }
    }
}

void paint_text_selection(whaleui_render_t* r, whaleui_layout_node_t* n,
                          int fs, const std::string& family, bool bold,
                          int off_x, int off_y, int seq, int sel_lo,
                          int sel_hi, const Clip* clip)
{
        size_t a = 0, b = 0;
    int tw = 0, th = 0;
    int ww = run_wrap_w(n);
    text_size(r, n->text, fs, family, bold, &tw, &th, ww);
    if (th <= 0) {
        return;
    }
    int tx = 0, ty = 0;
    text_origin(r, n, n->text, fs, family, bold, &tx, &ty, ww);
    tx += off_x;
    ty += off_y;
    std::vector<TRect> rects = sel_rects(r, n->text, fs, family, bold, a, b,
                                         ww);
    expand_hl_rects(rects, text_line_h(r, fs, family, bold));
    unsigned int hl = sel_hl_color(r, n, 0x3C);
    for (size_t i = 0; i < rects.size(); ++i) {
        fill_rect(r->pixels, r->fb_w, r->fb_h,
                  tx + rects[i].x, ty + rects[i].y,
                  rects[i].w, rects[i].h, hl, clip);
    }
}

unsigned int sel_hl_color(whaleui_render_t* r, whaleui_layout_node_t* n,
                          unsigned int alpha)
{
    std::string v = sget(n->style, "selection-bg");
    if (!v.empty()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(v.c_str(), &c) == 0) {
            return (alpha << 24) | (c & 0x00FFFFFF);
        }
    }
    return accent_hl(r, alpha);
}

void paint_caret(whaleui_render_t* r, int tx, int ty, const std::string& text,
                 int fs, const std::string& family, bool bold,
                 size_t off, const Clip* clip, int wrap_w)
{
    if ((SDL_GetTicks() / 500) & 1) {
        return; /* blink: off half the time */
    }
    int cx = 0, cy = 0, ch = 16;
    caret_pos(r, text, fs, family, bold, off, &cx, &cy, &ch, wrap_w);
    fill_rect(r->pixels, r->fb_w, r->fb_h, tx + cx, ty + cy, 1, ch,
              accent_hl(r, 0xFF), clip);
}

void update_ime_area(whaleui_render_t* r, const std::string& val, int fs,
                     const std::string& family, bool bold, size_t caret,
                     int tx, int ty, int wrap_w)
{
    if (!r->edit_el || !r->window) {
        return;
    }
    int cxx = 0, cyy = 0, chh = 16;
    caret_pos(r, val, fs, family, bold, caret, &cxx, &cyy, &chh, wrap_w);
    int wx = tx + cxx;
    int wy = ty + cyy;
    if (r->fb_w != r->width && r->width > 0) {
        wx = wx * r->width / r->fb_w;
    }
    if (r->fb_h != r->height && r->height > 0) {
        wy = wy * r->height / r->fb_h;
    }
    SDL_Rect rect = {wx, wy, 2, chh};
    if (r->window) {
        struct ImeAreaTask {
            SDL_Window* w;
            SDL_Rect r;
        };
        SDL_Window* ww = r->window;
        ImeAreaTask* t = new ImeAreaTask{ww, rect};
        whaleui_sdl_on_main(
            [](void* p) {
                ImeAreaTask* a = static_cast<ImeAreaTask*>(p);
                SDL_SetTextInputArea(a->w, &a->r, 0);
                delete a;
            },
            t);
    }
}

void paint_text(whaleui_render_t* r, whaleui_layout_node_t* n, int off_x,
                int off_y, int seq, int sel_lo, int sel_hi, const Clip* clip)
{
    /* cull runs fully outside the framebuffer: creating a TTF_Text per run
     * per frame is the dominant paint cost on scroll-heavy pages */
    int ty = n->border.y + off_y;
    if (ty + n->border.h <= 0 || ty >= r->fb_h) {
        return;
    }
    unsigned int color = color_of(n->style, "color", 0xFF000000);
    /* opacity is applied at blend time (draw_text_at's opacity param), NOT
     * baked into the color: baking it made the text_cache key change every
     * animation frame, forcing full text re-rasterization per frame. */
    (void)0;

    int fs = 16;
    std::string fsv = sget(n->style, "font-size");
    if (!fsv.empty()) {
        /* clamp()/vw font-sizes (q21k h3/glyph) resolve like the layout
         * pass - atoi treated "clamp(30px,...)" as 0 and drew 16px */
        int f = font_size_px(r, fsv);
        if (f > 0) {
            fs = f;
        }
    }
    std::string family = sget(n->style, "font-family");
    /* font-weight: bold/bolder/600-900 render bold; font-style italic/
     * oblique render italic (TTF style bits, per-tag UA defaults make
     * <strong>/<em> work without any page CSS) */
    std::string fw = sget(n->style, "font-weight");
    bool bold = fw == "bold" || fw == "bolder" ||
                (!fw.empty() && std::atoi(fw.c_str()) >= 600);
    std::string fst = sget(n->style, "font-style");
    int style = (bold ? kFontBold : 0) |
                ((fst == "italic" || fst == "oblique") ? kFontItalic : 0);
    /* text-align aligns within the parent element's content box; inline
     * line members (mixed with siblings) stay left-aligned at their laid
     * out x so the line flows as one run sequence */
    std::string ta = sget(n->style, "text-align");
    int align = 0;
    if (ta == "center") {
        align = 1;
    } else if (ta == "right") {
        align = 2;
    }
    if (n->in_inline) {
        align = 0;
    }
    /* text-transform + letter-spacing apply to the painted text (ASCII
     * transforms keep the byte length, so selection offsets stay valid) */
    std::string shown = n->text;
    std::string tt = sget(n->style, "text-transform");
    if (!tt.empty() && tt != "none") {
        apply_text_transform(shown, tt);
    }
    int lsp = 0;
    std::string lsv = sget(n->style, "letter-spacing");
    if (!lsv.empty() && lsv != "normal") {
        float v = static_cast<float>(std::atof(lsv.c_str()));
        lsp = static_cast<int>(lsv.find("em") != std::string::npos
                                   ? v * fs
                                   : v);
    }
    whaleui_layout_node_t* box = n;
    if (n->parent && !n->parent->is_text) {
        box = n->parent;
    }
    paint_text_selection(r, n, fs, family, bold, off_x, off_y, seq, sel_lo,
                         sel_hi, clip);
    bool wrap = sget(n->style, "white-space") != "nowrap";
    /* paint at the run's laid-out position: block runs sit at the parent
     * content origin, inline-line runs at their accumulated x. The wrap
     * width is run_wrap_w: the block line-box remainder (inline ancestors
     * skipped, mirroring the layout pass) - the parent-box estimate here
     * wrapped an inline <code> run at its own content width (~= the text
     * width) and painted the second line over the text below. */
    int tx0 = n->border.x + off_x;
    int ty0 = n->border.y + off_y;
    int avail_w = run_wrap_w(n);
    if (avail_w < 1) {
        avail_w = 1;
    }

    /* text-shadow: offset copy (plus 2 spread layers approximating the
     * blur) painted under the glyphs. The glyph raster is cached per
     * element, so the copies only re-tint at blend time. */
    std::string tsh = sget(n->style, "text-shadow");
    if (!tsh.empty() && tsh != "none") {
        int sox = 0, soy = 0, sblur = 0;
        unsigned int scol = 0;
        if (parse_shadow_any(tsh, sox, soy, sblur, scol) == 0) {
            unsigned int sa = (scol >> 24) & 0xFF;
            if (sblur > 0) {
                for (int k = 1; k <= 2 && k <= sblur; ++k) {
                    unsigned int ka =
                        static_cast<unsigned>(sa * (sblur - k + 1) /
                                              (sblur + 1));
                    unsigned int sc = (ka << 24) | (scol & 0x00FFFFFF);
                    draw_text_at(r, shown, tx0 + sox - k, ty0 + soy - k,
                                 avail_w, n->border.h, fs, family, sc,
                                 style, align, n->el, clip, lsp, wrap,
                                 n->opacity);
                }
            }
            draw_text_at(r, shown, tx0 + sox, ty0 + soy, avail_w,
                         n->border.h, fs, family, scol, style, align, n->el,
                         clip, lsp, wrap, n->opacity);
        }
    }
    /* -webkit-text-stroke: 8-direction outline copies (stroke width is
     * usually 1px; outline color replaces the transparent fill) */
    std::string tsk = sget(n->style, "-webkit-text-stroke");
    if (tsk.empty()) {
        tsk = sget(n->style, "text-stroke");
    }
    if (!tsk.empty() && tsk != "none") {
        std::vector<std::string> toks = split_space2(tsk);
        int sw = 1;
        unsigned int scc = 0xFF000000;
        if (!toks.empty()) {
            char* end = nullptr;
            float w = std::strtof(toks[0].c_str(), &end);
            if (end != toks[0].c_str()) {
                sw = w > 0 ? static_cast<int>(w) : 1;
            }
            std::string cstr;
            for (size_t i = 1; i < toks.size(); ++i) {
                if (!cstr.empty()) {
                    cstr += ' ';
                }
                cstr += toks[i];
            }
            if (!cstr.empty()) {
                whaleui_render_parse_color(cstr.c_str(), &scc);
            }
        }
        for (int dy = -1; dy <= 1; ++dy) {
            for (int dx = -1; dx <= 1; ++dx) {
                if (!dx && !dy) {
                    continue;
                }
                draw_text_at(r, shown, tx0 + dx * sw, ty0 + dy * sw,
                             avail_w, n->border.h, fs, family, scc,
                             style, align, n->el, clip, lsp, wrap,
                             n->opacity, true);
            }
        }
    }

    /* the run's own box carries the scroll shift; draw_text_at centers the
     * glyphs in it, matching text_origin's hit/highlight geometry */
    draw_text_at(r, shown, tx0, ty0, avail_w, n->border.h,
                 fs, family, color, style, align, n->el, clip, lsp, wrap,
                 n->opacity);

    /* text-decoration: underline / line-through lines over the box (width
     * = the run's own text extent, clamped to the line remainder) */
    std::string td = sget(n->style, "text-decoration");
    if (!td.empty() && td != "none") {
        int lw = 0;
        for (size_t i = 0; i < shown.size();) {
            unsigned char c2 = static_cast<unsigned char>(shown[i]);
            if (c2 < 0x80) {
                lw += fs / 2;
                ++i;
            } else {
                size_t n2 = (c2 & 0xE0) == 0xC0 ? 2 : (c2 & 0xF0) == 0xE0 ? 3 : 4;
                lw += fs;
                i += n2;
            }
        }
        if (lw > avail_w) {
            lw = avail_w;
        }
        if (lw < 1) {
            lw = 1;
        }
        if (td.find("underline") != std::string::npos) {
            fill_rect(r->pixels, r->fb_w, r->fb_h, tx0,
                      ty0 + n->border.h - 2, lw, 1, color, clip);
        }
        if (td.find("line-through") != std::string::npos) {
            fill_rect(r->pixels, r->fb_w, r->fb_h, tx0,
                      ty0 + n->border.h / 2, lw, 1, color, clip);
        }
    }
}

void text_origin(whaleui_render_t* r, whaleui_layout_node_t* n,
                 const std::string& text, int fs, const std::string& family,
                 bool bold, int* tx, int* ty, int wrap_w)
{
    int tw = 0, th = 0;
    text_size(r, text, fs, family, bold, &tw, &th, wrap_w);
    /* vertical centering, clamped to non-negative: the layout box height
     * (estimated wrap lines) can come out shorter than the painted text
     * (per-glyph wrap), and a negative (border.h - th)/2 pushes the first
     * line above the box - invisible text, caret drifting below it */
    if (n->is_text) {
        *tx = n->border.x;
        int dy = (n->border.h - th) / 2;
        *ty = n->border.y + (dy > 0 ? dy : 0);
    } else {
        *tx = n->content.x;
        /* empty value (th == 0): top-aligned, not centered - centering
         * put the caret of an empty textarea at the bottom of the box */
        int dy = th > 0 ? (n->content.h - th) / 2 : 0;
        *ty = n->content.y + (dy > 0 ? dy : 0);
    }
}

/* wrap width a text run paints at (draw_text_at's avail_w): the parent
 * content right edge minus the run's laid-out x; 0 when the run never
 * wraps (white-space: nowrap) */
int run_wrap_w(whaleui_layout_node_t* n)
{
    if (!n) {
        return 0;
    }
    if (sget(n->style, "white-space") == "nowrap") {
        return 0;
    }
    whaleui_layout_node_t* box =
        (n->parent && !n->parent->is_text) ? n->parent : n;
    /* an inline element's text follows the OUTER line box: its wrap width
     * is the block ancestor's remaining line space, not the inline box's
     * own content width (~= the text width - wrapping exactly at it split
     * a single <code> line into two, the second drawing over the line
     * below). Only plain inline boxes are skipped; inline-block (button/
     * input/textarea) wraps at its own content width. Must mirror the
     * layout pass (layout.cpp, text-run avail walk). */
    while (box && !box->is_text &&
           sget(box->style, "display") == "inline" && box->parent &&
           !box->parent->is_text) {
        box = box->parent;
    }
    std::string disp = sget(box->style, "display");
    if (disp == "flex" || disp == "inline-flex") {
        /* a flex item's text does not soft-wrap (browser behavior): it
         * paints at its laid-out width. Wrapping against the container's
         * content edge split a 2-char checkbox label into 3 lines (the
         * parent box is narrower than the checkbox+label pair). */
        return n->border.w > 0 ? n->border.w : 0;
    }
    int w = box->content.x + box->content.w - n->border.x;
    return w > 0 ? w : 0;
}

/* byte offset of the text under (px,py), relative to the text top-left.
 * Uses the shared program-side layout, so wrapped lines, control
 * characters and both renderers (full/stb) behave identically. */
size_t byte_at_text(whaleui_render_t* r, const std::string& text, int fs,
                    const std::string& family, bool bold, int px, int py,
                    int wrap_w)
{
    if (text.empty()) {
        return 0;
    }
    int lh = text_line_h(r, fs, family, bold);
    if (lh <= 0) {
        lh = fs > 0 ? fs : 16;
    }
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    if (L.lines.empty()) {
        return 0;
    }
    if (px < 0) {
        px = 0;
    }
    if (py < 0) {
        py = 0;
    }
    size_t li = static_cast<size_t>(py / lh);
    if (li >= L.lines.size()) {
        li = L.lines.size() - 1;
    }
    const TextLayoutLine& ln = L.lines[li];
    const size_t nc = L.map.size();
    int xacc = 0;
    for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
        int w = gw(disp_cp_at(L, ci), st);
        if (px < xacc + w / 2) {
            return L.map[ci];
        }
        xacc += w;
    }
    /* past the line's right edge: the LINE end (not the whole text end) */
    return (ln.cend < nc) ? L.map[ln.cend] : text.size();
}
