/* render_control.cpp - form controls (checkbox/radio/progress/editable/scrollbar/select) paint. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include <lexbor/dom/dom.h>

#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>
void paint_checkbox(whaleui_render_t* r, whaleui_layout_node_t* n,
                    int off_x, int off_y, const Clip* clip)
{
    lxb_dom_element* el = n->el;
    if (!el) {
        return;
    }
    size_t alen = 0;
    const lxb_char_t* t = lxb_dom_element_get_attribute(
        el, (const lxb_char_t*)"type", 4, &alen);
    bool is_radio = t && alen == 5 && std::memcmp(t, "radio", 5) == 0;
    bool checked = lxb_dom_element_has_attribute(
        el, (const lxb_char_t*)"checked", 7);
    int bx = n->border.x + off_x;
    int by = n->border.y + off_y;
    int bw = n->border.w, bh = n->border.h;
    if (bw <= 0 || bh <= 0) {
        return;
    }
    unsigned int bg = 0xFFFFFFFF, fg = 0xFF8a8a8a, acc = 0xFF0067C0;
    auto it = r->theme_vars.find("--field");
    if (it != r->theme_vars.end()) {
        whaleui_render_parse_color(it->second.c_str(), &bg);
    }
    auto itb = r->theme_vars.find("--border");
    if (itb != r->theme_vars.end()) {
        whaleui_render_parse_color(itb->second.c_str(), &fg);
    }
    auto ita = r->theme_vars.find("--accent");
    if (ita != r->theme_vars.end()) {
        whaleui_render_parse_color(ita->second.c_str(), &acc);
    }
    int cx = bx + bw / 2, cy = by + bh / 2;
    if (is_radio) {
        int rad = bw / 2;
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh, rad,
                        bg, clip);
        /* ring: 1px dark outline via a smaller inner fill */
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx + 1, by + 1,
                        bw - 2, bh - 2, rad - 1, bg, clip);
        /* outline */
        for (int k = 0; k < 1; ++k) {
            fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx + 1, by + 1,
                            bw - 2, bh - 2, rad - 1, fg, clip);
        }
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx + 1, by + 1,
                        bw - 2, bh - 2, rad - 1, bg, clip);
        if (checked) {
            fill_round_rect(r->pixels, r->fb_w, r->fb_h, cx - bw / 4,
                            cy - bh / 4, bw / 2, bh / 2, bw / 4, acc, clip);
        }
    } else {
        int rad = 3;
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh, rad,
                        bg, clip);
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx + 1, by + 1,
                        bw - 2, bh - 2, rad, fg, clip);
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx + 1, by + 1,
                        bw - 2, bh - 2, rad, bg, clip);
        if (checked) {
            /* check mark: two strokes drawn as thick lines */
            int sw = bw / 5;
            if (sw < 1) {
                sw = 1;
            }
            fill_rect(r->pixels, r->fb_w, r->fb_h,
                      bx + bw / 5, cy, bw / 4, sw, acc, clip);
            fill_rect(r->pixels, r->fb_w, r->fb_h,
                      bx + bw / 2 - sw / 2, cy, sw, bh / 3, acc, clip);
            fill_rect(r->pixels, r->fb_w, r->fb_h,
                      bx + bw / 2, cy - bh / 4, bw / 3, sw, acc, clip);
        }
    }
}

void paint_progress(whaleui_render_t* r, whaleui_layout_node_t* n,
                    int off_x, int off_y, const Clip* clip)
{
    lxb_dom_element* el = n->el;
    if (!el) {
        return;
    }
    double value = 0, max = 1;
    size_t alen = 0;
    const lxb_char_t* v = lxb_dom_element_get_attribute(
        el, (const lxb_char_t*)"value", 5, &alen);
    if (v && alen > 0) {
        value = std::atof(reinterpret_cast<const char*>(v));
    }
    const lxb_char_t* m = lxb_dom_element_get_attribute(
        el, (const lxb_char_t*)"max", 3, &alen);
    if (m && alen > 0) {
        double mx = std::atof(reinterpret_cast<const char*>(m));
        if (mx > 0) {
            max = mx;
        }
    }
    if (value < 0) {
        value = 0;
    }
    if (value > max) {
        value = max;
    }
    int bx = n->content.x + off_x;
    int by = n->content.y + off_y;
    int bw = n->content.w, bh = n->content.h;
    if (bw <= 0 || bh <= 0) {
        return;
    }
    unsigned int track = 0xFFE0E0E0, fill = 0xFF0067C0;
    auto it = r->theme_vars.find("--field");
    if (it != r->theme_vars.end()) {
        whaleui_render_parse_color(it->second.c_str(), &track);
    }
    auto ita = r->theme_vars.find("--accent");
    if (ita != r->theme_vars.end()) {
        whaleui_render_parse_color(ita->second.c_str(), &fill);
    }
    int rad = bh / 2;
    fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, bw, bh, rad,
                    track, clip);
    int fw2 = static_cast<int>(bw * (value / max));
    if (fw2 > 0) {
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, bx, by, fw2, bh, rad,
                        fill, clip);
    }
}

void paint_editable(whaleui_render_t* r, whaleui_layout_node_t* n,
                    int off_x, int off_y, const Clip* clip)
{
    lxb_dom_element* el = n->el;
    if (!el || !is_editable(el)) {
        return;
    }
    int fs = 16;
    std::string fsv = sget(n->style, "font-size");
    if (!fsv.empty()) {
        fs = std::atoi(fsv.c_str());
    }
    std::string family = sget(n->style, "font-family");
    std::string fw = sget(n->style, "font-weight");
    bool bold = fw == "bold" || fw == "bolder" ||
                (!fw.empty() && std::atoi(fw.c_str()) >= 600);
    std::string fst = sget(n->style, "font-style");
    int style = (bold ? kFontBold : 0) |
                ((fst == "italic" || fst == "oblique") ? kFontItalic : 0);
    std::string val = edit_value(el);
    bool focused = (el == r->edit_el);
    /* caret/highlight geometry: input centers in its content box; textarea/
     * contenteditable follow the layout text run so they line up with the
     * painted glyphs (which sit at the run's top, not the box center) */
    whaleui_layout_node_t* geo = editable_geo(n);
    int tx = 0, ty = 0;
    text_origin(r, geo, val, fs, family, bold, &tx, &ty);
    tx += off_x;
    ty += off_y;
    int th = text_line_h(r, fs, family, bold);

    /* single-line input: content scrolls horizontally with the caret and is
     * clipped to the content box (long values never stretch or spill) */
    int hx = 0;
    Clip iclip;
    bool clip_input = false;
    if (tag_eq(el, "input")) {
        auto hi = r->hscrolls.find(el);
        hx = hi == r->hscrolls.end() ? 0 : hi->second;
        tx -= hx;
        if (clip && n->content.w > 0) {
            iclip = *clip;
            int x0 = n->content.x + off_x;
            int y0 = n->content.y + off_y;
            int x1 = x0 + n->content.w;
            int y1 = y0 + n->content.h;
            if (iclip.x < x0) {
                iclip.w -= x0 - iclip.x;
                iclip.x = x0;
            }
            if (iclip.x + iclip.w > x1) {
                iclip.w = x1 - iclip.x;
            }
            if (iclip.y < y0) {
                iclip.h -= y0 - iclip.y;
                iclip.y = y0;
            }
            if (iclip.y + iclip.h > y1) {
                iclip.h = y1 - iclip.y;
            }
            clip_input = iclip.w > 0 && iclip.h > 0;
        }
    }
    const Clip* ic = clip_input ? &iclip : clip;

    if (tag_eq(el, "input")) {
        /* input has no text children: paint the value here, always */
        unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
        draw_text_at(r, val, n->content.x - hx + off_x, n->content.y,
                     n->content.w, n->content.h,
                     fs, family, fg, style, 0, el, ic);
    }
    if (focused) {
        size_t a = 0, b = 0;
        if (sel_range_for(r, el, val.size(), &a, &b, -1, -1, -1)) {
            std::vector<TRect> rects = sel_rects(r, val, fs, family, bold, a, b);
            expand_hl_rects(rects, text_line_h(r, fs, family, bold));
            unsigned int hl = sel_hl_color(r, n, 0x3C);
            if (tag_eq(el, "input") && geo->content.h > 0) {
                /* single-line input: the wash fills the whole content box
                 * (native control look); the text sits vertically centered,
                 * so the top edge is (content.h - text height)/2 above the
                 * text origin ty. */
                int top = -(geo->content.h -
                            text_line_h(r, fs, family, bold)) / 2;
                for (size_t i = 0; i < rects.size(); ++i) {
                    rects[i].y = top;
                    rects[i].h = geo->content.h;
                }
            }
            for (size_t i = 0; i < rects.size(); ++i) {
                fill_rect(r->pixels, r->fb_w, r->fb_h,
                          tx + rects[i].x, ty + rects[i].y,
                          rects[i].w, rects[i].h, hl, ic);
            }
        }
        size_t caret = static_cast<size_t>(r->sel_focus);
        if (caret > val.size()) {
            caret = val.size();
        }
        /* keep the IME candidate window anchored at the caret */
        update_ime_area(r, val, fs, family, bold, caret, tx, ty);
        paint_caret(r, tx, ty, val, fs, family, bold, caret, ic);
        if (!r->compose.empty()) {
            unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
            unsigned int comp = (0xC8 << 24) | (fg & 0x00FFFFFF);
            int cxx = 0, cyy = 0, chh = 16;
            caret_pos(r, val, fs, family, bold, caret, &cxx, &cyy, &chh);
            draw_text_at(r, r->compose, tx + cxx, ty + cyy, 300, chh,
                         fs, family, comp, style, 0, el, ic);
        }
    }
}

void paint_scrollbar(whaleui_render_t* r, whaleui_layout_node_t* n,
                     int off_x, int off_y, const Clip* clip)
{
    if (n->scroll_max <= 0 || n->border.h < 24) {
        return;
    }
    const int bw = 8;
    int track_x = n->border.x + off_x + n->border.w - bw;
    int track_y = n->border.y + off_y;
    int track_h = n->border.h;
    int content_h = n->scroll_max + n->content.h;
    if (content_h <= 0) {
        return;
    }
    int thumb_h = track_h * n->content.h / content_h;
    if (thumb_h < 10) {
        thumb_h = 10;
    }
    if (thumb_h > track_h) {
        thumb_h = track_h;
    }
    /* live scroll position (layout tree may be stale between scrolls) */
    int sy = n->scroll_y;
    auto sit = r->scrolls.find(n->el);
    if (sit != r->scrolls.end()) {
        sy = sit->second;
    }
    int thumb_y = track_y +
                  (track_h - thumb_h) * sy /
                      (n->scroll_max > 0 ? n->scroll_max : 1);
    unsigned int track = 0x10000000;
    unsigned int thumb = 0x50000000;
    auto it = r->theme_vars.find("--border");
    if (it != r->theme_vars.end()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(it->second.c_str(), &c) == 0) {
            track = (0x18 << 24) | (c & 0x00FFFFFF);
            thumb = (0x55 << 24) | (c & 0x00FFFFFF);
        }
    }
    fill_rect(r->pixels, r->fb_w, r->fb_h, track_x, track_y, bw, track_h,
              track, clip);
    fill_rect(r->pixels, r->fb_w, r->fb_h, track_x, thumb_y, bw, thumb_h,
              thumb, clip);
}

void select_options(lxb_dom_element* sel, std::vector<std::string>& texts,
                    std::vector<std::string>& values)
{
    lxb_dom_node* c = sel->node.first_child;
    while (c) {
        if (c->type == LXB_DOM_NODE_TYPE_ELEMENT) {
            lxb_dom_element* el = lxb_dom_interface_element(c);
            size_t len = 0;
            const lxb_char_t* name = lxb_dom_element_local_name(el, &len);
            if (name && len == 6 && std::memcmp(name, "option", 6) == 0) {
                /* text = concatenated text children */
                std::string txt;
                lxb_dom_node* t = el->node.first_child;
                while (t) {
                    if (t->type == LXB_DOM_NODE_TYPE_TEXT) {
                        const lexbor_str_t* s = &lxb_dom_interface_text(t)->char_data.data;
                        if (s->data) {
                            txt.append(reinterpret_cast<const char*>(s->data), s->length);
                        }
                    }
                    t = t->next;
                }
                texts.push_back(txt);
                size_t vlen = 0;
                const lxb_char_t* v = lxb_dom_element_get_attribute(
                    el, (const lxb_char_t*)"value", 5, &vlen);
                values.push_back(v ? std::string(reinterpret_cast<const char*>(v), vlen) : txt);
            }
        }
        c = c->next;
    }
}

bool is_select_node(whaleui_layout_node_t* n)
{
    if (!n || !n->el) {
        return false;
    }
    size_t len = 0;
    const lxb_char_t* name = lxb_dom_element_local_name(n->el, &len);
    return name && len == 6 && std::memcmp(name, "select", 6) == 0;
}

void paint_select_value(whaleui_render_t* r, whaleui_layout_node_t* n,
                        int off_x, int off_y, const Clip* clip)
{
    std::vector<std::string> texts, values;
    select_options(n->el, texts, values);
    if (texts.empty()) {
        return;
    }
    int sel = r->select_index.count(n->el) ? r->select_index[n->el] : 0;
    if (sel < 0 || sel >= static_cast<int>(texts.size())) {
        sel = 0;
    }
    int fs = 13;
    unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
    /* value text left, arrow pinned to the right edge. Both are nudged up
     * 2px: segoe's glyphs sit ~2px below the line-box center, so metric
     * centering alone leaves the text looking low inside the control. */
    int arrow_x = n->content.x + off_x + n->content.w - 16;
    int text_w = arrow_x - n->content.x - off_x - 8;
    if (text_w < 10) {
        text_w = 10;
    }
    int vy = n->content.y + off_y - 2;
    draw_text_at(r, texts[sel], n->content.x + off_x + 2, vy,
                 text_w, n->content.h, fs, "", fg, 0, 0, n->el, clip);
    /* large solid triangle ▲: the small ? is only a few px tall and looks
     * like it floats above the text baseline */
    draw_text_at(r, "\xe2\x96\xbc", arrow_x, vy,
                 16, n->content.h, fs, "", fg, 0, 0, n->el, clip);
}

void paint_select_list(whaleui_render_t* r, whaleui_layout_node_t* n,
                       int off_y, const Clip* clip)
{
    std::vector<std::string> texts, values;
    select_options(n->el, texts, values);
    if (texts.empty()) {
        return;
    }
    int sel = r->select_index.count(n->el) ? r->select_index[n->el] : 0;
    if (sel < 0 || sel >= static_cast<int>(texts.size())) {
        sel = 0;
    }
    int fs = 13;
    unsigned int fg = color_of(n->style, "color", 0xFF1a1a1a);
    int list_x = n->border.x;
    int list_y = n->border.y + off_y + n->border.h;
    int list_w = n->border.w;
    int list_h = static_cast<int>(texts.size()) * kSelectItemH;
    /* the popup follows the select's corner radius (default theme radius),
     * instead of square corners that clash with the rounded control */
    int radius = 0;
    std::string br = sget(n->style, "border-radius");
    if (!br.empty()) {
        radius = std::atoi(br.c_str());
    }
    unsigned int bg = 0xFF000000;
    auto it = r->theme_vars.find("--card");
    if (it != r->theme_vars.end()) {
        whaleui_render_parse_color(it->second.c_str(), &bg);
    }
    /* soft shadow under the popup (before the card background) */
    {
        const int blur = 6;
        for (int k = blur; k >= 1; --k) {
            unsigned int ka = static_cast<unsigned>(0x28 * (blur - k + 1) / (blur + 1));
            unsigned int c = (ka << 24); /* black, alpha faded outwards */
            if (radius > 0) {
                fill_round_rect(r->pixels, r->fb_w, r->fb_h,
                                list_x + 0 - k, list_y + 2 - k,
                                list_w + 2 * k, list_h + 2 * k, radius, c, clip);
            } else {
                fill_rect(r->pixels, r->fb_w, r->fb_h,
                          list_x + 0 - k, list_y + 2 - k,
                          list_w + 2 * k, list_h + 2 * k, c, clip);
            }
        }
    }
    if (radius > 0) {
        fill_round_rect(r->pixels, r->fb_w, r->fb_h, list_x, list_y,
                        list_w, list_h, radius, bg, clip);
    } else {
        fill_rect(r->pixels, r->fb_w, r->fb_h, list_x, list_y, list_w,
                  list_h, bg, clip);
    }
    unsigned int border_c = 0xFF000000;
    auto itb = r->theme_vars.find("--border");
    if (itb != r->theme_vars.end()) {
        whaleui_render_parse_color(itb->second.c_str(), &border_c);
    }
    /* selected + hovered rows get a translucent accent wash */
    unsigned int acc = 0xFF0067C0;
    auto ita = r->theme_vars.find("--accent");
    if (ita != r->theme_vars.end()) {
        whaleui_render_parse_color(ita->second.c_str(), &acc);
    }
    unsigned int sel_wash = (0x26 << 24) | (acc & 0x00FFFFFF); /* ~15% accent */
    unsigned int hover_wash = (0x14 << 24) | (acc & 0x00FFFFFF);
    for (int i = 0; i < static_cast<int>(texts.size()); ++i) {
        int iy = list_y + i * kSelectItemH;
        if (i == r->open_select_hover) {
            if (radius > 0) {
                fill_round_rect(r->pixels, r->fb_w, r->fb_h, list_x, iy,
                                list_w, kSelectItemH, radius, hover_wash, clip);
            } else {
                fill_rect(r->pixels, r->fb_w, r->fb_h, list_x, iy,
                          list_w, kSelectItemH, hover_wash, clip);
            }
        }
        if (i == sel) {
            if (radius > 0) {
                fill_round_rect(r->pixels, r->fb_w, r->fb_h, list_x, iy,
                                list_w, kSelectItemH, radius, sel_wash, clip);
            } else {
                fill_rect(r->pixels, r->fb_w, r->fb_h, list_x, iy,
                          list_w, kSelectItemH, sel_wash, clip);
            }
            draw_text_at(r, texts[i], list_x + 8, iy, list_w - 16,
                         kSelectItemH, fs, "", acc, true, 0, n->el, clip);
        } else {
            draw_text_at(r, texts[i], list_x + 8, iy, list_w - 16,
                         kSelectItemH, fs, "", fg, 0, 0, n->el, clip);
        }
    }
    /* border around the list (follows the corner arcs when rounded) */
    fill_round_border(r->pixels, r->fb_w, r->fb_h, list_x, list_y,
                      list_w, list_h, radius, 1, border_c, bg, clip);
}
