/* render_color.cpp - CSS color parsing (named/hex/rgb(a)) and gradients. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include "render/gpu.h"

#include <cmath>
#include <cstdio>
#include <cstring>
#include <string>
#include <vector>
struct NamedColor { const char* name; unsigned int value; };

const NamedColor k_named[] = {
    {"black", 0xFF000000}, {"silver", 0xFFC0C0C0}, {"gray", 0xFF808080},
    {"white", 0xFFFFFFFF}, {"maroon", 0xFF800000}, {"red", 0xFFFF0000},
    {"purple", 0xFF800080}, {"fuchsia", 0xFFFF00FF}, {"green", 0xFF008000},
    {"lime", 0xFF00FF00}, {"olive", 0xFF808000}, {"yellow", 0xFFFFFF00},
    {"navy", 0xFF000080}, {"blue", 0xFF0000FF}, {"teal", 0xFF008080},
    {"aqua", 0xFF00FFFF}, {"orange", 0xFFFFA500}, {"pink", 0xFFFFC0CB},
    {"brown", 0xFFA52A2A}, {"transparent", 0x00000000},
};

unsigned int hex_byte(const char* s, int* ok)
{
    unsigned int v = 0;
    for (int i = 0; i < 2; ++i) {
        char c = s[i];
        v <<= 4;
        if (c >= '0' && c <= '9') {
            v |= static_cast<unsigned>(c - '0');
        } else if (c >= 'a' && c <= 'f') {
            v |= static_cast<unsigned>(c - 'a' + 10);
        } else if (c >= 'A' && c <= 'F') {
            v |= static_cast<unsigned>(c - 'A' + 10);
        } else {
            *ok = 0;
            return 0;
        }
    }
    return v;
}

unsigned int hex_nib(char c, int* ok)
{
    if (c >= '0' && c <= '9') {
        return static_cast<unsigned>(c - '0');
    }
    if (c >= 'a' && c <= 'f') {
        return static_cast<unsigned>(c - 'a' + 10);
    }
    if (c >= 'A' && c <= 'F') {
        return static_cast<unsigned>(c - 'A' + 10);
    }
    *ok = 0;
    return 0;
}

void split_grad_parts(const std::string& s, std::vector<std::string>& out)
{
    size_t depth = 0, start = 0;
    for (size_t i = 0; i <= s.size(); ++i) {
        char c = i < s.size() ? s[i] : ',';
        if (c == '(') {
            ++depth;
        } else if (c == ')') {
            if (depth > 0) {
                --depth;
            }
        } else if (c == ',' && depth == 0) {
            std::string part = s.substr(start, i - start);
            size_t b = part.find_first_not_of(" \t");
            size_t e = part.find_last_not_of(" \t");
            if (b != std::string::npos) {
                out.push_back(part.substr(b, e - b + 1));
            }
            start = i + 1;
        }
    }
}

int parse_gradient(const std::string& v, Gradient& out)
{
    size_t li = v.find("linear-gradient(");
    size_t ri = v.find("radial-gradient(");
    if (li == std::string::npos && ri == std::string::npos) {
        return 0;
    }
    bool lin = li != std::string::npos &&
               (ri == std::string::npos || li < ri);
    size_t start = lin ? li : ri;
    /* "linear-gradient(" / "radial-gradient(" are both 16 chars */
    size_t open = start + 16;
    size_t depth = 1;
    size_t end = std::string::npos;
    for (size_t i = open; i < v.size(); ++i) {
        if (v[i] == '(') {
            ++depth;
        } else if (v[i] == ')') {
            if (--depth == 0) {
                end = i;
                break;
            }
        }
    }
    if (end == std::string::npos) {
        return 0;
    }
    out = Gradient();
    out.type = lin ? 0 : 1;
    out.angle_deg = 180.0f; /* default: to bottom */
    out.rx = 0;
    out.ry = 0;
    out.cx = 0.5f;
    out.cy = 0.5f;
    std::vector<std::string> parts;
    split_grad_parts(v.substr(open, end - open), parts);
    if (parts.empty()) {
        return 0;
    }
    size_t first = 0;
    if (!lin) {
        /* radial first part: "1100px 560px at 72% -12%" / "circle 200px" */
        const std::string& head = parts[0];
        size_t at = head.find(" at ");
        std::string size_s = at == std::string::npos ? head : head.substr(0, at);
        std::string pos_s = at == std::string::npos ? std::string() : head.substr(at + 4);
        if (!pos_s.empty()) {
            float px = 0, py = 0;
            if (std::sscanf(pos_s.c_str(), "%f%% %f%%", &px, &py) == 2) {
                out.cx = px / 100.0f;
                out.cy = py / 100.0f;
            } else if (std::sscanf(pos_s.c_str(), "%fpx %fpx", &px, &py) == 2) {
                out.cx = px;
                out.cy = py;
                out.cx += 100.0f; /* marker: absolute px center */
            }
        }
        float rx = 0, ry = 0;
        if (std::sscanf(size_s.c_str(), "%fpx %fpx", &rx, &ry) == 2) {
            out.rx = rx;
            out.ry = ry;
        } else if (size_s.find("circle") != std::string::npos) {
            const char* c = std::strchr(size_s.c_str(), ' ');
            if (c) {
                out.rx = out.ry = static_cast<float>(std::atof(c));
            }
        }
        first = 1;
    } else {
        /* linear first part: "90deg" / "to right" */
        const std::string& head = parts[0];
        if (head.find("deg") != std::string::npos) {
            out.angle_deg = static_cast<float>(std::atof(head.c_str()));
        } else if (head == "to right") {
            out.angle_deg = 90.0f;
        } else if (head == "to left") {
            out.angle_deg = 270.0f;
        } else if (head == "to top") {
            out.angle_deg = 0.0f;
        } /* "to bottom" = default 180 */
        first = 1;
    }
    /* stops: "color pos" / "color" */
    std::vector<size_t> auto_pos;
    for (size_t i = first; i < parts.size(); ++i) {
        const std::string& p = parts[i];
        size_t sp = std::string::npos;
        for (size_t j = 1; j < p.size(); ++j) {
            if (p[j] == ' ' && p[j - 1] != ' ') {
                sp = j;
                break;
            }
        }
        std::string col_s = sp == std::string::npos ? p : p.substr(0, sp);
        unsigned int c = 0;
        if (whaleui_render_parse_color(col_s.c_str(), &c) != 0) {
            continue;
        }
        GradStop st;
        st.c = c;
        st.pos = -1.0f;
        if (sp != std::string::npos) {
            std::string pos_s = p.substr(sp);
            const char* pc = pos_s.c_str();
            while (*pc == ' ' || *pc == '\t') {
                ++pc;
            }
            if (std::strchr(pc, '%')) {
                st.pos = static_cast<float>(std::atof(pc)) / 100.0f;
            } else {
                st.pos = static_cast<float>(std::atof(pc));
            }
        }
        out.stops.push_back(st);
        if (st.pos < 0) {
            auto_pos.push_back(out.stops.size() - 1);
        }
    }
    /* fill unspecified positions evenly */
    size_t n = out.stops.size();
    if (n == 0) {
        return 0;
    }
    if (auto_pos.empty()) {
        for (size_t i = 0; i < n; ++i) {
            out.stops[i].pos = n > 1 ? static_cast<float>(i) / static_cast<float>(n - 1) : 0.0f;
        }
    } else {
        for (size_t i = 0; i < auto_pos.size(); ++i) {
            size_t idx = auto_pos[i];
            float lo = idx == 0 ? 0.0f : out.stops[idx - 1].pos;
            float hi = (idx == 0 && n > 1) ? 1.0f
                                           : (idx + 1 < n ? out.stops[idx + 1].pos : 1.0f);
            if (idx > 0 && idx + 1 < n && out.stops[idx + 1].pos >= 0 &&
                out.stops[idx - 1].pos >= 0) {
                lo = out.stops[idx - 1].pos;
                hi = out.stops[idx + 1].pos;
            } else if (idx == 0) {
                lo = 0.0f;
            } else {
                hi = 1.0f;
            }
            out.stops[idx].pos = hi >= lo ? (lo + hi) / 2.0f : lo;
        }
    }
    return 1;
}

unsigned int grad_color(const Gradient& g, float t)
{
    size_t n = g.stops.size();
    if (n == 0) {
        return 0;
    }
    if (t <= 0.0f || t <= g.stops[0].pos) {
        return g.stops[0].c;
    }
    if (t >= g.stops[n - 1].pos) {
        return g.stops[n - 1].c;
    }
    for (size_t i = 0; i + 1 < n; ++i) {
        if (t <= g.stops[i + 1].pos) {
            float span = g.stops[i + 1].pos - g.stops[i].pos;
            float p = span > 0 ? (t - g.stops[i].pos) / span : 0.0f;
            unsigned int f = g.stops[i].c, g2 = g.stops[i + 1].c;
            auto ch = [p](unsigned int a, unsigned int b) -> unsigned int {
                return static_cast<unsigned int>(a + (static_cast<float>(b) - a) * p + 0.5f);
            };
            return (ch((f >> 24) & 0xFF, (g2 >> 24) & 0xFF) << 24) |
                   (ch((f >> 16) & 0xFF, (g2 >> 16) & 0xFF) << 16) |
                   (ch((f >> 8) & 0xFF, (g2 >> 8) & 0xFF) << 8) |
                   ch(f & 0xFF, g2 & 0xFF);
        }
    }
    return g.stops[n - 1].c;
}

void fill_gradient(std::vector<unsigned int>& fb, int fbw, int fbh,
                   int x, int y, int w, int h, const Gradient& g,
                   const Clip* clip)
{
    if (g_gpu) {
        /* linear gradients: corner colors (projected onto the gradient
         * axis) interpolated by the solid pipeline - free from the
         * rasterizer. Stops beyond the first two approximate with the
         * first/last color (ponytail: per-stop segments when a page needs
         * them). Radial needs per-pixel work the graphics pipeline cannot
         * do (SDL 3.4 D3D12 graphics SRV is broken), so it is skipped -
         * the flat element background underneath stays correct. */
        if (g.type == 0 && g.stops.size() >= 2) {
            float rad = g.angle_deg * 3.14159265f / 180.0f;
            float ddx = std::sin(rad), ddy = -std::cos(rad);
            float ccx = x + w * 0.5f, ccy = y + h * 0.5f;
            float t0 = 1e30f, t1 = -1e30f;
            const float corners[4][2] = {
                {static_cast<float>(x), static_cast<float>(y)},
                {static_cast<float>(x + w), static_cast<float>(y)},
                {static_cast<float>(x), static_cast<float>(y + h)},
                {static_cast<float>(x + w), static_cast<float>(y + h)}};
            for (int i = 0; i < 4; ++i) {
                float t = (corners[i][0] - ccx) * ddx +
                          (corners[i][1] - ccy) * ddy;
                if (t < t0) {
                    t0 = t;
                }
                if (t > t1) {
                    t1 = t;
                }
            }
            float span = t1 - t0;
            if (span <= 0.0f) {
                span = 1.0f;
            }
            auto tcol = [&](float px, float py) {
                float t = ((px - ccx) * ddx + (py - ccy) * ddy - t0) / span;
                return grad_color(g, t);
            };
            unsigned int c_tl = tcol(static_cast<float>(x), static_cast<float>(y));
            unsigned int c_tr = tcol(static_cast<float>(x + w), static_cast<float>(y));
            unsigned int c_bl = tcol(static_cast<float>(x), static_cast<float>(y + h));
            unsigned int c_br = tcol(static_cast<float>(x + w), static_cast<float>(y + h));
            int c2[4];
            const int* cp = nullptr;
            if (clip) {
                c2[0] = clip->x;
                c2[1] = clip->y;
                c2[2] = clip->w;
                c2[3] = clip->h;
                cp = c2;
            }
            whaleui_gpu_gradient_rect(g_gpu, static_cast<float>(x),
                                      static_cast<float>(y),
                                      static_cast<float>(w),
                                      static_cast<float>(h), c_tl, c_tr, c_bl,
                                      c_br, cp);
        } else if (g.type == 1 && g.stops.size() >= 2) {
            /* radial: concentric rounded-rect ellipses, alpha fading
             * outwards - a coarse approximation of the per-pixel ellipse
             * distance (10 layers, GPU-trivial) */
            float rx = g.rx > 0 ? g.rx : w * 0.5f;
            float ry = g.ry > 0 ? g.ry : h * 0.5f;
            float rcx = g.cx > 1.0f ? g.cx - 100.0f : x + g.cx * w;
            float rcy = g.cy * h + y;
            int c2[4];
            const int* cp = nullptr;
            if (clip) {
                c2[0] = clip->x;
                c2[1] = clip->y;
                c2[2] = clip->w;
                c2[3] = clip->h;
                cp = c2;
            }
            const int kLayers = 10;
            for (int i = kLayers; i >= 1; --i) {
                float t = static_cast<float>(i) / kLayers;
                unsigned int c = grad_color(g, t);
                if (((c >> 24) & 0xFF) == 0) {
                    continue;
                }
                float sx = rcx - rx * t;
                float sy = rcy - ry * t;
                whaleui_gpu_rect(g_gpu, sx, sy, rx * 2.0f * t,
                                 ry * 2.0f * t, rx * t, c, cp);
            }
        }
        return;
    }
    if (w <= 0 || h <= 0 || g.stops.empty()) {
        return;
    }
    int x0 = x < 0 ? 0 : x;
    int y0 = y < 0 ? 0 : y;
    int x1 = x + w > fbw ? fbw : x + w;
    int y1 = y + h > fbh ? fbh : y + h;
    clip_rect(x0, y0, x1, y1, clip);
    if (x1 <= x0 || y1 <= y0) {
        return;
    }
    auto blend = [&](int px, int py, unsigned int c) {
        unsigned int a = (c >> 24) & 0xFF;
        if (a == 0) {
            return;
        }
        unsigned int& d = fb[static_cast<size_t>(py) * fbw + px];
        if (a == 255) {
            d = 0xFF000000 | (c & 0x00FFFFFF);
            return;
        }
        unsigned int cr = (c >> 16) & 0xFF, cg = (c >> 8) & 0xFF, cb = c & 0xFF;
        unsigned int dr = (d >> 16) & 0xFF, dg = (d >> 8) & 0xFF, db = d & 0xFF;
        d = 0xFF000000 |
            (((cr * a + dr * (255 - a)) / 255) << 16) |
            (((cg * a + dg * (255 - a)) / 255) << 8) |
            ((cb * a + db * (255 - a)) / 255);
    };
    if (g.type == 0) {
        /* linear: project pixels onto the direction axis */
        float rad = g.angle_deg * 3.14159265f / 180.0f;
        float dx = std::sin(rad), dy = -std::cos(rad);
        float cx = x + w * 0.5f, cy = y + h * 0.5f;
        float t0 = 1e30f, t1 = -1e30f;
        const float corners[4][2] = {
            {static_cast<float>(x), static_cast<float>(y)},
            {static_cast<float>(x + w), static_cast<float>(y)},
            {static_cast<float>(x), static_cast<float>(y + h)},
            {static_cast<float>(x + w), static_cast<float>(y + h)}};
        for (int i = 0; i < 4; ++i) {
            float t = (corners[i][0] - cx) * dx + (corners[i][1] - cy) * dy;
            if (t < t0) {
                t0 = t;
            }
            if (t > t1) {
                t1 = t;
            }
        }
        float span = t1 - t0;
        if (span <= 0.0f) {
            span = 1.0f;
        }
        for (int py = y0; py < y1; ++py) {
            float t = ((static_cast<float>(x0) - cx) * dx +
                       (static_cast<float>(py) - cy) * dy - t0) /
                      span;
            float step = dx / span;
            for (int px = x0; px < x1; ++px) {
                blend(px, py, grad_color(g, t));
                t += step;
            }
        }
    } else {
        /* radial: ellipse distance from the center */
        float rx = g.rx > 0 ? g.rx : w * 0.5f;
        float ry = g.ry > 0 ? g.ry : h * 0.5f;
        float rcx = g.cx > 1.0f ? g.cx - 100.0f : x + g.cx * w;
        float rcy = g.cy * h + y;
        if (rx <= 0 || ry <= 0) {
            return;
        }
        for (int py = y0; py < y1; ++py) {
            float ny = (static_cast<float>(py) - rcy) / ry;
            for (int px = x0; px < x1; ++px) {
                float nx = (static_cast<float>(px) - rcx) / rx;
                float t = std::sqrt(nx * nx + ny * ny);
                blend(px, py, grad_color(g, t));
            }
        }
    }
}

extern "C" int whaleui_render_parse_color(const char* s, unsigned int* out)
{
    if (!s || !out) {
        return -1;
    }
    while (*s == ' ' || *s == '\t') {
        ++s;
    }
    if (*s == '#') {
        ++s;
        int ok = 1;
        size_t n = std::strlen(s);
        if (n == 3) { /* #rgb */
            int ok = 1;
            unsigned int r = hex_nib(s[0], &ok);
            unsigned int g = hex_nib(s[1], &ok);
            unsigned int b = hex_nib(s[2], &ok);
            *out = 0xFF000000 | ((r * 0x11) << 16) | ((g * 0x11) << 8) | (b * 0x11);
            return ok ? 0 : -2;
        }
        if (n == 6 || n == 8) {
            unsigned int r = hex_byte(s, &ok);
            unsigned int g = hex_byte(s + 2, &ok);
            unsigned int b = hex_byte(s + 4, &ok);
            unsigned int a = n == 8 ? hex_byte(s + 6, &ok) : 0xFF;
            *out = (a << 24) | (r << 16) | (g << 8) | b;
            return ok ? 0 : -2;
        }
        return -3;
    }
    if (std::strncmp(s, "rgba(", 5) == 0 || std::strncmp(s, "rgb(", 4) == 0) {
        int rr = 0, gg = 0, bb = 0;
        float faf = -1.0f;
        if (std::sscanf(s, "rgba(%d,%d,%d,%f)", &rr, &gg, &bb, &faf) >= 4) {
            unsigned int r = rr < 0 ? 0 : static_cast<unsigned>(rr);
            unsigned int g = gg < 0 ? 0 : static_cast<unsigned>(gg);
            unsigned int b = bb < 0 ? 0 : static_cast<unsigned>(bb);
            /* alpha: 0..1 float, or legacy 0..255 integer */
            unsigned int a = faf <= 1.0f
                                 ? static_cast<unsigned>(faf * 255.0f + 0.5f)
                                 : static_cast<unsigned>(faf);
            if (r > 255) { r = 255; }
            if (g > 255) { g = 255; }
            if (b > 255) { b = 255; }
            if (a > 255) { a = 255; }
            *out = (a << 24) | (r << 16) | (g << 8) | b;
            return 0;
        }
        if (std::sscanf(s, "rgb(%d,%d,%d)", &rr, &gg, &bb) >= 3) {
            unsigned int r = rr < 0 ? 0 : static_cast<unsigned>(rr);
            unsigned int g = gg < 0 ? 0 : static_cast<unsigned>(gg);
            unsigned int b = bb < 0 ? 0 : static_cast<unsigned>(bb);
            if (r > 255) { r = 255; }
            if (g > 255) { g = 255; }
            if (b > 255) { b = 255; }
            *out = (255 << 24) | (r << 16) | (g << 8) | b;
            return 0;
        }
        return -4;
    }
    for (const NamedColor& nc : k_named) {
        if (std::strcmp(s, nc.name) == 0) {
            *out = nc.value;
            return 0;
        }
    }
    return -5;
}

unsigned int color_of(const WhaleUIComputedStyle& s, const char* prop, unsigned int def)
{
    std::string v = sget(s, prop);
    if (v.empty()) {
        return def;
    }
    unsigned int c = 0;
    if (whaleui_render_parse_color(v.c_str(), &c) == 0) {
        return c;
    }
    return def;
}

unsigned int border_color_of(const WhaleUIComputedStyle& s, unsigned int def)
{
    std::string v = sget(s, "border");
    if (v.empty()) {
        return def;
    }
    unsigned int c = 0;
    if (whaleui_render_parse_color(v.c_str(), &c) == 0) {
        return c;
    }
    const char* p = v.c_str();
    while (*p) {
        while (*p == ' ' || *p == '\t') {
            ++p;
        }
        const char* s = p;
        while (*s && *s != ' ' && *s != '\t' && *s != ';') {
            ++s;
        }
        std::string tok(p, static_cast<size_t>(s - p));
        if (whaleui_render_parse_color(tok.c_str(), &c) == 0) {
            return c;
        }
        p = s;
    }
    return def;
}
