/* render_text.cpp - text rasterization (SDL3_ttf full / stb_truetype lite+minimal), selection, caret and IME. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include "font/font.h"
#include <SDL3/SDL.h>
#ifdef WHALEUI_BUILD_FULL
#include <SDL3_ttf/SDL_ttf.h>
#else
/* stb_truetype text backend for lite/minimal builds (header-only) */
#define STB_TRUETYPE_IMPLEMENTATION
#include <stb/stb_truetype.h>
#endif

#include <lexbor/dom/dom.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <string>
#include <vector>
std::vector<std::string> split_families(const std::string& s)
{
    std::vector<std::string> out;
    const char* p = s.c_str();
    while (*p) {
        while (*p == ' ' || *p == '\t' || *p == ',') {
            ++p;
        }
        if (!*p) {
            break;
        }
        const char* start = p;
        bool quoted = *p == '"' || *p == '\'';
        if (quoted) {
            ++start;
            ++p;
            while (*p && *p != '"' && *p != '\'') {
                ++p;
            }
            out.emplace_back(start, static_cast<size_t>(p - start));
            if (*p) {
                ++p;
            }
            continue;
        }
        while (*p && *p != ',') {
            ++p;
        }
        std::string fam(start, static_cast<size_t>(p - start));
        size_t b = fam.find_first_not_of(" \t");
        size_t e = fam.find_last_not_of(" \t");
        if (b != std::string::npos) {
            out.push_back(fam.substr(b, e - b + 1));
        }
    }
    return out;
}

/* --- 缂傚倸鍊风粈渚€顢栭崨鎼晞闁告侗鍨垫慨铏亜閹惧崬鐏╃紒鈧崘顔界厱婵炴垵宕弸鐔兼煟鎼搭喖娅嶉柡宀嬬節瀹曞ジ顢曢姀鐙€娼介梺姹囧焺閸ㄩ亶骞戦崶顒€绠?闂傚倷绀侀幗婊堝磿閹版澘鍨傛い鏍ㄧ矌閸楁岸鎮楅悽鐢点€婇柛瀣崌瀹曠兘顢橀悙鐗堝煕婵?full 婵?stb 闂傚倷鑳堕…鍫㈡崲濡や胶顩叉い鎺戝閺?---
 * 闂傚倷绀佸﹢閬嶅磿閵堝洦鏆滈柣鎰摠濞呯姵淇婇妶鍛殲閻庢艾顭烽弻锝夊籍閸パ冩優闂?UTF-8 闂備浇宕甸崰鎰版偡鏉堚晛绶ら柛褎顨嗛崑澶嬬節婵犲倻澧曟潻婵囩箾鏉堝墽鎮奸柟铏尰缁傛帒顫滈埀顒勫蓟濞戙垹绠抽柡鍥╁枔閵嗘劙姊洪悜鈺侇潚闁告侗鍨抽悾鍫曟⒑閹稿孩纾甸柛瀣尰閵囧嫰鏁傜憴鍕彋闂佽鍠栭悥鐓庣暦闁秴鍗抽柣妯虹仛閸犳盯姊绘担鍛婅础妞ゎ厼鐗撹棟妞ゆ牜鍋涚壕鎸庢叏濡潡鍝烘い顐ｆ礋閺岋絽螣閻戞ǚ鏋欓梺鍝ュ枎缁夊綊鐛弽銊︾秶闁诡垎灞惧枠婵?soft-wrap;
 * 濠电姷鏁搁崑鐐哄箰缁嬫鍤曢柛顐ｆ礃閸嬪倿鎮楅敐搴″幐婵?SDL3_ttf / stb_truetype)闂傚倷绀侀幉锟犳偡椤栨稓顩叉繝闈涱焾娴滅懓霉閿濆懏璐￠柣鐔活潐缁绘盯骞嬮悘娲讳簽缁牏鈧綆鍠楅崐鍨箾閹寸偟鎳愭繛鍫熒戦妵鍕箣濠婂棗鍘￠梺閫炲苯澧版い銏狅工铻為柛鏇ㄥ幐閸嬫挾鎲撮崟顐熸灆閻庤娲栭悥濂稿箖濞嗘挸绀堝ù锝堫嚃閸熲偓婵犵數鍋為崹鍫曞箰閸涘娈介柟闂寸劍閸嬨倗鎲搁幋锕€桅闁圭増婢橀～鍛存煏韫囧鐏╃紒妤嬬節濮婃椽宕ㄦ繝鍌滎儎缂傚倸鐗呴崡鎶藉春閳?
 * 缂傚倸鍊搁崐鎼佸磹瑜版帗鍋嬮柣鎰仛椤愯姤銇勯幇鍓佺暠闁哄绶氶弻鈩冨緞鐎ｉ潧鍔岄梺?caret/selection/hit-test)婵犵數鍋為崹鍫曞箰缁嬫５瑙勵槹鎼粹€崇亰濡炪倖鐗滈崑娑氱矆閸℃稒鍋ｉ柛婵嗗閹牏鎲搁悧鍫㈡噰闁哄矉缍侀敐鐐侯敆閳ь剚淇婃總鍛婄厵妞ゆ棁濮ょ亸鎵磼鐎ｎ亶妯€闁糕斁鍋撳銈嗗笂閼冲爼銆呴悜鑺ョ厱濠电姴瀚▍蹇涙煛閳ь剚绂掔€ｎ偄浠哄銈嗙墬閼归箖寮冲▎鎾寸厽?
 * 闂傚倷绀佸﹢閬嶃€傛禒瀣；闁规崘绉?full 婵?lite/minimal 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸樺ジ鎮鹃悜鑺ュ殤妞ゆ帊绀佹禒鎺楁煟韫囨洖浠╅柛瀣姉缁梻鈧潧鎽滅壕浠嬫煕閹邦厼鍔ら柡瀣閺屽秷顧侀柛蹇旂洴閹偤鏁傞悙顒佹闂佸壊鍋呭ú鏍矆閸℃稒鍋ｅΔ锔藉椤忕娀鏌熼悾灞芥灁缂佽鲸甯掕灃閻庯綆鍓涢弳銏狀渻閵堝啫鐏柛銊ュ缁瑦寰勯幇顑跨炊闂佸憡娲﹂崢钘夆枔椤曗偓濮婅櫣绮欑捄銊х杽闂佸憡鏌ㄩ鍥╁垝閳哄懎绠绘い鏃囨濞堟粌鈹戦悜鍥╃У闁稿繑锕㈠畷?*/

struct TextLayoutLine { size_t cstart; size_t cend; int w; };
struct TextLayout {
    std::string disp;          /* 闂傚倷绀侀幖顐も偓姘煎墯閺呰埖绂掔€ｎ€附鎱ㄥΟ鎸庣【婵☆偅锕㈤弻娑㈠Ψ閿濆懎顬夐梺?闂傚倷鑳堕、濠囨儗閸ヮ剙绀冮柕濞у啫绠戦梻浣筋嚙鐎涒晝绮欓幒妞尖偓鍐醇閵夘喗鏅炴繛杈剧秬濡椼劌鈻介鍫熺厸闁搞儮鏅涙禒褏鐥?缂傚倸鍊风粈渚€藝椤栫偐鈧箑鐣￠幍铏€洪柟鍏肩暘閸斿瞼鎲撮敃鍌氱閺夊牆澧界粙濠氭煟?UTF-8 */
    std::vector<size_t> map;   /* disp 濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鎵閸嬨倗鎲歌箛鏇炲灊妞ゆ挶鍨洪弲婵喢归敐鍥ㄥ殌闂傚偆鍨跺?闂?闂傚倷绀侀幉锟犫€﹂崶顒€绐楅柟鐗堟緲閸戠娀鏌涢幇闈涙灈閻庢艾顦伴妵鍕箳閸℃ぞ澹曢梻浣哄劦婵秹宕堕妸銉︾枀闂備胶顭堥張顒勬儗椤曗偓閹偞绻濋崟顓狅紲?*/
    std::vector<size_t> dbytes;/* disp 濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鎵閸嬨倗鎲歌箛鏇炲灊妞ゆ挶鍨洪弲婵喢归敐鍥ㄥ殌闂傚偆鍨跺?闂?disp 闂備浇顕х€涒晝绮欓幒妞尖偓鍐╁緞鐎ｂ晝绠氬銈嗘尪閸ㄥ湱澹曟繝姘卞彄闁搞儯鍔嶉梹?*/
    std::vector<TextLayoutLine> lines;
    int tw, th;
};
/* 闂傚倷绀侀幉锟犮€冮崱妞曟椽寮介鐔蜂槐閻熸粌绻掗崚鎺楊敇閵忊剝娅囬梺閫炲苯澧寸€规洘娲栭～婵囨綇椤垶缍楅梻浣虹帛閿氭俊顖氾躬瀹?濠电姷鏁搁崑鐐哄箰缁嬫鍤曢柛顐ｆ礃閸嬪倿鎮楅敐搴″幐婵炲矈浜弻娑氫沪閻愵剛娈ら梺鍝勵槷缁瑩寮?闂備焦鐪归崺鍕垂娴兼潙鐤い鎰堕檮閸庢垶銇勯幒鎴濐仾闁稿﹦绮妵鍕箼閸曨厾锛熼梺缁樻煥閹虫劙鍩€?ASCII 闂備浇宕垫慨宥夊礋椤愵偅顥嬬紓鍌欑劍閸炵粯淇婇崶顒€鐒? */
typedef int (*TextGlyphFn)(unsigned int cp, void* st);

/* 闂備浇宕甸崰鎰版偡鏉堚晛绶ら柛褎顨嗛崑澶嬬節婵犲倻澧曢柛灞诲姂閺岋綁寮幐搴℃殘闂佽瀵掗崳锝夊蓟閿熺姴閱囨い鎰╁灩楠炴劙鏌ｉ悩鍐插闁哥姵鐗曢锝嗗閺夋垹顦悷婊冾儐缁傛帒鈽夐姀锛勫幐闂佺鏈喊宥嗗緞閸曨剛绡€闁? \r 闂傚倸顭崑鍕洪妸鈺佺柧妞ゆ劧绠戝Ч?CRLF),\n 闂傚倷绀侀幖顐﹀磻閸℃稑鐭楅柍褜鍓氶妵?\t 闂備浇顕х换鎺楀磻閻愯娲冀椤愶綆娼熼梺鐟邦嚟閸嬬喖鍩?4 缂傚倸鍊风粈渚€鎯夋總绋跨？闁靛牆顦伴崑?
 * 闂傚倷鑳堕…鍫㈡崲閹存繐鑰块柛锔诲幘缁€?C0/DEL 闂傚倷鑳堕、濠囨儗閸ヮ剙绀冮柕濞у啫绠戦梻浣筋嚙鐎涒晝绮欓幒妞尖偓鍐醇閵夘喗鏅炴繛杈剧悼閸庛倕鐣锋径鎰€甸柛锔诲幖鍟哥紓?婵犵數鍋為崹鍫曞箰閸濄儳鐭撻柡澶嬪灩閺嗭箓鏌ｅΔ鈧悧濠冨垔?;濠电姵顔栭崳顖滃緤閻ｅ本宕查悗锝庡枟閻撳倹绻濇繝鍌滃闁告瑥锕弻娑㈠箻濡炵偓顦风紒顔炬暬閺岋絾鎯旈姀鈶╁濡炪們鍔岄悧鎾汇€侀弽銊﹀闁绘垶锚椤庢盯姊洪崫鍕垫Ъ婵炲娲滅划鏃堝锤濡や胶鍘卞┑鈽嗗灣閸樠囧几鎼粹埗鐟邦煥閸愨晜鍠愮紓渚囧枟閺屻劍鏅ラ梺鎼炲劵缁茶姤绂?*/
static void layout_decode(const std::string& text, TextLayout& L)
{
    const unsigned char* sb =
        reinterpret_cast<const unsigned char*>(text.c_str());
    size_t i = 0;
    while (i < text.size()) {
        size_t start = i;
        unsigned char c = sb[i];
        unsigned int cp = c;
        int len = 1;
        if (c >= 0x80) {
            if ((c & 0xE0) == 0xC0 && i + 1 < text.size()) {
                cp = ((c & 0x1F) << 6) | (sb[i + 1] & 0x3F);
                len = 2;
            } else if ((c & 0xF0) == 0xE0 && i + 2 < text.size()) {
                cp = ((c & 0x0F) << 12) | ((sb[i + 1] & 0x3F) << 6) |
                     (sb[i + 2] & 0x3F);
                len = 3;
            } else if ((c & 0xF8) == 0xF0 && i + 3 < text.size()) {
                cp = ((c & 0x07) << 18) | ((sb[i + 1] & 0x3F) << 12) |
                     ((sb[i + 2] & 0x3F) << 6) | (sb[i + 3] & 0x3F);
                len = 4;
            } else {
                cp = 0; /* malformed byte: skip */
            }
        }
        i += len;
        if (cp == '\r') {
            continue;
        }
        if (cp == '\n') {
            L.disp += '\n';
            L.dbytes.push_back(L.disp.size() - 1);
            L.map.push_back(start);
            continue;
        }
        if (cp == '\t') {
            for (int k = 0; k < 4; ++k) {
                L.disp += ' ';
                L.dbytes.push_back(L.disp.size() - 1);
                L.map.push_back(start);
            }
            continue;
        }
        if (cp < 0x20 || cp == 0x7F) {
            continue;
        }
        L.disp.append(text, start, static_cast<size_t>(len));
        L.dbytes.push_back(L.disp.size() - static_cast<size_t>(len));
        L.map.push_back(start);
    }
}

/* 闂備浇宕甸崰鎰版偡鏉堚晛绶ら柛褎顨嗛崑澶嬬節婵犲倻澧曢柛娆忥躬閺屾盯骞樺鐐樂缂侇喚鏁诲娲传閸曨偀鍋撶粙妫垫椽鏁冮埀顒勬晝閵忋倖鍋嬮柛顐熸噰閺嬫牕顪冮妶鍡樺暗闁稿鍠栭獮妤呮偄閾忓湱锛滃┑掳鍊曢鍛淬€呴鍕厱閻忕偠顕ф俊鍏笺亜?ci 婵犵數濮伴崹鐓庘枖濞戞埃鍋撳鐓庢灈闁崇粯鎹囬獮瀣晜閽樺澹撳┑鐐舵彧缁蹭粙骞栭锝囶浄?*/
static unsigned int disp_cp_at(const TextLayout& L, size_t ci){
    size_t b0 = L.dbytes[ci];
    size_t b1 = (ci + 1 < L.dbytes.size()) ? L.dbytes[ci + 1] : L.disp.size();
    const unsigned char* u =
        reinterpret_cast<const unsigned char*>(L.disp.c_str());
    unsigned char c = u[b0];
    if (c < 0x80) {
        return c;
    }
    if ((c & 0xE0) == 0xC0 && b0 + 1 < b1) {
        return ((c & 0x1F) << 6) | (u[b0 + 1] & 0x3F);
    }
    if ((c & 0xF0) == 0xE0 && b0 + 2 < b1) {
        return ((c & 0x0F) << 12) | ((u[b0 + 1] & 0x3F) << 6) |
               (u[b0 + 2] & 0x3F);
    }
    if ((c & 0xF8) == 0xF0 && b0 + 3 < b1) {
        return ((c & 0x07) << 18) | ((u[b0 + 1] & 0x3F) << 12) |
               ((u[b0 + 2] & 0x3F) << 6) | (u[b0 + 3] & 0x3F);
    }
    return 0;
}

/* 闂?wrap_w 闂傚倷绀侀幖顐﹀磻閸℃稑鐭楅柍褜鍓氶妵?闂傚倸鍊风欢锟犲磻閸涙潙绀夐柡鍥ュ灪閸嬨倗鎲歌箛鏇炲灊妞ゆ挶鍨洪弲婊堟煕閹炬瀚崝鎼佹⒑閼姐倕小閻犱焦鐓￠崺鈧い鎺嶇婢ь垶鏌涢悢椋幮ф?闂備胶鍎甸崜婵堟暜閹烘绠犻幖鎼厛閺佸﹪鏌￠崘銊у缂侇偄绉归幃褰掓惞閻熸澘濡虹紓浣插亾闁逞屽墴濮婄粯绗熼崶褌绨梺绋款儐閹瑰洭寮诲☉銏犵闁哄倹顑欓弳顓炩攽閻愬瓨灏柣鏍帶閻ｇ兘濡烽敂钘夊妳濠电娀娼ч悧婊勫閸ャ劎绠鹃柟瀵稿仦閹嫬霉濠婂懎浠遍柛鈺冨仱瀵粙顢橀悙鎻掓暏?闂?
 * wrap_w <= 0 = 婵犵數鍋為崹鍫曞箰閸濄儳鐭撻柣鎴ｅГ鐎氬啴鎮楅敐搴℃灈缂佺姵鐓￠弻鏇＄疀閵壯呅ｉ梺琛″亾濞寸姴顑嗛悡蹇涙煕閳╁喚娈旈柍褜鍓涢弲顐﹀箲閵忋倕绠ｉ柨鏇楀亾闁绘劕锕弻锝夊箛椤掑娈跺┑鈥崇湴閸旀垿骞冪捄琛℃婵☆垵鍋愭导鍥р攽閻愯尙澧涢柛銊ョ仢椤曪絾瀵奸弶鎴狀槶閻熸粌顑嗙粋鎺戔槈閵忊€斥偓鍨箾閹寸偟鎳愭繛鍫熒戦妵鍕箣濠婂懐鐛㈤梺鐟扮－婵炩偓鐎规洘锕㈡俊鎼佹晜閹冩瘣 [cstart,cend) 婵犵數鍋為崹鍫曞箰閸涘娈介柟闂寸绾炬寧鎱ㄥΟ鍧楀摵妞ゎ偅娲熼弻锝呂熼悜妯锋灆闂佸摜鍠庣粔褰掑蓟?*/
static void layout_wrap(TextLayout& L, int wrap_w, int lh,
                        TextGlyphFn gw, void* st)
{
    const size_t nc = L.map.size();
    size_t ci = 0;
    while (ci < nc) {
        size_t ls = ci;
        int wacc = 0;
        size_t last_sp = static_cast<size_t>(-1);
        int wacc_at_sp = 0;
        bool nl = false;
        while (ci < nc) {
            const char dch = L.disp[L.dbytes[ci]];
            if (dch == '\n') {
                nl = true;
                break;
            }
            int w = gw(disp_cp_at(L, ci), st);
            const bool is_sp = dch == ' ';
            if (wrap_w > 0 && wacc > 0 && wacc + w > wrap_w) {
                /* 闂備胶鍎甸崜婵堟暜閹烘绠犻幖鎼厛閺?婵犵數鍋炲娆撳触鐎ｎ喗鏅梻浣告啞钃遍柣鈺婂灠閻ｇ兘宕奸弴鐔封偓鐑芥偠濞戞巻鍋撻崗鍛棜闂備線鈧偛鑻晶瀵糕偓瑙勬礃瀹€鎼佸箖瑜斿畷濂告偄閸撲礁绗￠梻鍌欑閹诧繝鎳濋崜褑濮抽柤娴嬫櫇閸楁岸鎮楀☉娆樼劷闁崇粯姊归妵鍕疀閹炬惌妫忛梺杞扮鐎氫即寮婚垾鎰佸悑濠㈣泛顑戠槐鐢电磽娴ｅ搫顎撶紓宥勭閻?闂備浇宕垫慨鏉懨洪妶鍥╃煋闁煎憡顔栧▓浠嬫煕閵夘喖澧俊顐Ｉ戦妵鍕箻椤栨侗娼戦梺琛″亾? */
                size_t br = ci;
                int bw = wacc;
                if (last_sp != static_cast<size_t>(-1)) {
                    br = last_sp + 1;
                    bw = wacc_at_sp;
                }
                if (br <= ls) { /* 缂傚倸鍊风粈渚€鎯夋總绋跨？闁靛牆顦伴崑瀣煙闂傚顦﹂柛娆忥攻閵囧嫰寮介妸褏顓奸梺琛″亾闁芥ê锛夊☉銏℃櫜闁糕剝鐟ラ埛鍫ユ⒑閻戔晛澧查柛銊ф暬椤㈡岸鏁愭径濠勶紲濠殿喗锚瀹曨剟鎮?闂傚倷绀侀幖顐﹀磻閸℃稑鍌ㄩ柣鎾冲嚱閼版寧銇勮箛鎾村偍濞存粌缍婇弻鐔煎箚瑜嶉弳杈ㄣ亜閵堝懏鍤囬柟顔筋殔閳藉鈻庡Ο鑽ゆ毉婵＄偑鍊栭崹宕囨濮橆剛鏆?*/
                    br = ci;
                    bw = wacc;
                }
                L.lines.push_back({ls, br, bw});
                if (bw > L.tw) {
                    L.tw = bw;
                }
                L.th += lh;
                ci = br;
                break;
            }
            wacc += w;
            if (is_sp && wrap_w > 0) {
                last_sp = ci;
                wacc_at_sp = wacc;
            }
            ++ci;
        }
        if (ci >= nc || nl) {
            /* 闂傚倸鍊风欢锟犲磻閸涱厙锝夊箳閺冣偓椤愯姤銇勯幇鈺佲偓鏍磻濡皷鍋撻崗澶婁壕闂佸憡鍔戦崝宥夘敊閸ヮ剚鈷戠紓浣姑粭鎺戭熆瑜嶅ù鐑藉礆閹烘惟闁宠桨鑳舵?闂傚倷绀侀幖顐﹀磹缁嬫５娲晝閳ь剟鏁冮姀鈥愁嚤闁哄鍨甸悵妯侯渻閵堝棗濮傞柛銊ヮ煼瀹曨垶寮婚妷锔惧幍闁诲孩绋掗…鍥ㄦ櫠椤掍椒绻嗘い鏍ㄥ嚬濡插憡銇勯弴顏嗙К缂佺姵鐩顒勫垂椤旀儳鎼搁梻? */
            L.lines.push_back({ls, ci, wacc});
            if (wacc > L.tw) {
                L.tw = wacc;
            }
            L.th += lh;
            if (nl) {
                ++ci; /* 闂備浇宕垫慨鎾箹椤愶附鍋柛銉㈡櫆瀹?\n */
            }
        }
    }
    /* 闂傚倷绀侀幖顐﹀磹缁嬫５娲晝閳ь剟鏁冮姀銈嗗亱闁割偁鍩勫ù?\n 缂傚倸鍊搁崐鐑芥倿閿曞倸绠伴柟闂寸劍閸嬪嫭銇勯幒鎴濐仼缂?闂傚倷绀侀幖顐︽偋濠婂牆纾婚柛鏇ㄥ灡閸嬪嫭銇勯幒宥囧妽濞存嚎鍊栨穱濠囶敍濠婂懎绗＄紓浣哄У鐢帡鍩ユ径鎰妞ゆ牗鐭竟鏇炩攽閻愭潙鐏﹂柟灏栨櫆缁傚秹鎮欓崫鍕幋闂佸搫绋侀崑鍛村磻?缂傚倸鍊搁崐鎼佸磹瑜版帗鍋嬮柣鎰仛椤愯姤銇勯幇鍓佺暠闂傚偆鍨堕弻鏇熺箾閻愵剚鐝斿┑鐐叉嫅缁绘繈寮诲☉婊呯杸闁瑰灝鍟晥闂備胶绮悧顓犵礊娴ｅ摜鏆﹂柟瀛樼箥閻撱儵鏌涢幇銊︽珗闁告凹鍋婂娲传閸曨厼顣甸梺绋款儐閹瑰洭寮诲☉姗嗘僵妞ゆ帒鍊搁崵顒傜磽娴ｈ鐓ユい鏇ㄥ弮楠?闂?
     * 婵犵數鍋為崹鍫曞箰閸濄儳鐭撻柣銈庡灡閿涘倸鈹?text_size/缂傚倸鍊搁崐鐑芥倿閿曞倹鏅梻?闂傚倷绀侀幉锛勭矙閹烘鍨傛繝闈涱儐閸ゅ牓鏌熺€电小闁绘帒锕弻娑樜旈崘銊ゆ埛濠殿噯绲介惉鑲╂閹烘鍋愰柣鎰灊濞岊亞绱撴担瑙勭叆妞ゆ洦鍙冮獮?闂傚倷绀侀幉锟犲礉閺囥垹绠犻幖鎼厛閺佸﹪鏌熼悧鍫熺凡闁哄鑳剁槐鎾诲醇閵忕姌銉х磼婢跺鍋㈤柡灞剧〒閳ь剨缍嗘禍鐐电不閿濆洨纾兼俊銈傚亾闁硅櫕蓱娣?*/
    if (!L.lines.empty() && !L.disp.empty() && L.disp.back() == '\n') {
        L.lines.push_back({nc, nc, 0});
        L.th += lh;
    }
}

static TextLayout layout_text(const std::string& text, int wrap_w, int lh,
                              TextGlyphFn gw, void* st)
{
    TextLayout L = {};
    layout_decode(text, L);
    layout_wrap(L, wrap_w, lh, gw, st);
    return L;
}

/* --- 闂傚倷绀侀幖顐﹀磹缁嬫５娲晝閳ь剟鏁冮姀銈呯骇婵☆偊娼у﹢閬嶅焵椤掑﹦绉靛ù婊冪埣瀹?闂傚倷绀侀幉锛勭矙閹烘鍨傛繝闈涱儐閸?闂傚倸鍊风欢锟犲磻閸曨垁鍥箥椤旂懓浜?闂傚倷鑳堕…鍫㈡崲濡や胶顩叉い鎺戝閺嬩線鏌曢崼婵囩闁稿鎹囧畷鐑筋敇閻愮増鍩涙俊?闂傚倷鑳剁涵鍫曞疾閻愬樊娴栭柕濞у棗小濡炪倖甯婇懗鍫曞煝閺傚簱鏀介柣妯哄级婢跺嫭淇婂鐓庡闁哄矉缍佹俊鎼佸Ψ閵夘喕绱撴俊鐐€戦崹娲垂瑜版帒鏋佹い鏇楀亾鐎规洘锕㈡俊姝岊槼闁? --- */

/* 闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈濋梺缁橆殔閻楀﹥鍒婄€电硶鍋撻獮鍨姎闁瑰啿绻掔划?缂傚倸鍊搁崐鐑芥嚄閸洖绐楃€广儱娲ㄩ崡姘舵煙缂併垹鏋涢悷娆欑畵楠炴牗娼忛崜褏校婵炲鍘ч崐鍧楀蓟閻旂厧绠掗柟鐑樺灥婵酣鎮?full 婵?stb 闂傚倷鑳堕…鍫㈡崲濡や胶顩叉い鎺戝閺?:闂傚倷鑳堕…鍫㈢矓鐎靛憡宕查柟鐑樻⒒閻棝鎮橀悙鎻掆挃闁?0xAARRGGBB;
 * colored=true 闂傚倷绀侀幖顐﹀疮閸愭祴鏋栨繛鎴欏灩绾炬寧鎱ㄥΟ鍧楀摵妞ゎ偅娲熼弻锝呂熼悜妯诲創濠电偛鐗呴崡鎶藉箖娴犲鏁嶉柕鍫濇川閺嗐倕顪冮妶鍐ㄢ偓鎾舵濮樿泛绠?闂佽崵鍠愮划宥嗙珶鐎ｎ喖鐤鹃柣鎰嚟閻?emoji),闂傚倷绀侀幉锟犳偄椤掑倻涓嶉柟杈剧畱閸ㄥ倹銇勯弽顐粶缁惧彞绮欓悡顐﹀炊閵婏妇顦銈忕畱瀹曨剟鍩ユ径鎰闁惧浚鍋呴崕鎾寸節閳封偓閸涱厸鏋呴悗娈垮枟閻擄繝銆佸☉妯锋斀闁糕檧鏅滈ˉ?闂?alpha闂?
 * xoff/yoff 婵犵數鍋為崹鍫曞箲娴ｅ壊娴栭柕濞у懐顦梺鍛婄⊕濞兼瑩鎮欐繝鍥ㄧ厱闁圭偓顨呯€氼噣濡堕弻銉︾厽?pen+baseline 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸犳岸宕氶幒妤婃晬闁绘劘灏欓ˇ顐︽煟閻樿崵绱版俊妞煎姂閹偞绻濋崟顓狅紲婵犮垼娉涢鍥э耿娴犲鐓?*/
struct GlyphImg
{
    int w, h;
    int xoff, yoff;
    int advance;
    bool colored;
    std::vector<unsigned int> px;
};

/* full: 闂傚倷绀侀幉锟犮€冮崱妞曟椽寮介鐔蜂槐閻熸粌绻掗崚鎺楊敇閵忊剝娅囬梺閫炲苯澧存い銏＄懇瀵噣鍩€椤掑嫬绠氶柡鍐ㄧ墛閺呮粓鏌ｉ敐鍛邦潶闁稿鍋ゅ缁樻媴閻熸壆绁风紓浣虹帛鐢帡鍩㈤幘璇茬闁绘劗顣介弸鏍ㄧ節閻㈤潧小闁煎啿鐖奸幃鐑藉箻缂佹鍘?闂備浇顕х€涒晝绮欓幒妤€桅闁绘劗鏁哥粈濠囨倵閿濆骸浜炴い?render_get_font 闂? */
struct TextMeasureCtx
{
    whaleui_render_t* r;
    int fs;
    std::string family;
    bool bold;
};
#ifdef WHALEUI_BUILD_FULL
static int glyph_ttf(unsigned int cp, void* st);
#else
static int glyph_stb(unsigned int cp, void* st);
#endif

#ifdef WHALEUI_BUILD_FULL

/* open a registered font file (no fallback chain, no cache); returns the
 * TTF_Font at an arbitrary size (callers set the real size via
 * ensure_font_state). NULL when the family is not registered. */
static TTF_Font* open_registry_font(const std::string& family)
{
    whaleui_font_registry* reg = whaleui_font_registry_get();
    for (size_t i = 0; i < reg->count; ++i) {
        if (std::strcmp(reg->fonts[i].family, family.c_str()) == 0) {
            SDL_IOStream* io = nullptr;
            if (reg->fonts[i].path) {
                io = SDL_IOFromFile(reg->fonts[i].path, "rb");
            } else if (reg->fonts[i].data && reg->fonts[i].len) {
                io = SDL_IOFromMem(const_cast<unsigned char*>(
                                       reg->fonts[i].data),
                                   reg->fonts[i].len);
            }
            if (!io) {
                return nullptr;
            }
            return TTF_OpenFontIO(io, true, 16.0f);
        }
    }
    return nullptr;
}

/* apply (size, style) to a font only when it changed (SDL3_ttf rebuilds
 * its glyph cache on either call, so skipping the no-op calls matters on
 * mixed-size pages) */
static void ensure_font_state(whaleui_render_t* r, TTF_Font* font, int size,
                              int style)
{
    auto it = r->font_state.find(font);
    if (it != r->font_state.end() && it->second.first == size &&
        it->second.second == style) {
        /* cached as (size, style): trust it ONLY if the font really is at
         * that size. A stale entry (recorded 48 while the font was later
         * reopened/restyled at 16 by another path) would skip SetFontSize
         * and rasterize CJK at the wrong size. Expected pixel height of a
         * `size`-point SDL3_ttf font is ~size*4/3 (48pt -> 64px). */
        int exp = size * 4 / 3;
        int h = TTF_GetFontHeight(font);
        if (h <= 0 || (h >= exp - exp / 4 && h <= exp + exp / 4)) {
            return;
        }
        r->font_state.erase(font); /* stale: fall through and re-apply */
    }
    bool ok = TTF_SetFontSize(font, static_cast<float>(size > 0 ? size : 16));
    TTF_SetFontStyle(font, style);
    if (ok) {
        r->font_state[font] = std::make_pair(size > 0 ? size : 16, style);
    } else {
        r->font_state.erase(font); /* failed: retry next time */
    }
}

/* sync the primary font AND its whole fallback chain to the current
 * (size, style): SDL3_ttf renders a fallback glyph at the FALLBACK's own
 * size, so every chain member must match the run being rasterized. */
static void sync_chain(whaleui_render_t* r, TTF_Font* font, int size,
                       int style)
{
    ensure_font_state(r, font, size, style);
    auto it = r->font_chain.find(font);
    if (it != r->font_chain.end()) {
        for (TTF_Font* fb : it->second) {
            ensure_font_state(r, fb, size, style);
        }
    }
}

/* lazily open the next registered font that can provide `cp`, attach it
 * to every primary font's fallback chain and return it. Called when a
 * glyph is missing - a page that never renders CJK/emoji never opens
 * those fonts (a registered-but-unused font costs only its path string).
 * A font that does NOT provide the glyph is closed again and remembered
 * in fallback_tried, so it is not reopened for every missing glyph. */
static TTF_Font* ensure_fallback(whaleui_render_t* r, TTF_Font* font,
                                 int size, int style, unsigned int cp)
{
    /* 1) fonts already opened are reused (one TTF_Font per family; size is
     * applied on demand). Checking hasGlyph on an open font is cheap, so
     * no miss memory is needed here - only step 2 records (fam, cp). */
    for (TTF_Font* fb : r->fallback_open) {
        ensure_font_state(r, fb, size, style);
        if (TTF_FontHasGlyph(fb, cp)) {
            return fb;
        }
    }
    whaleui_font_registry* reg = whaleui_font_registry_get();
    for (size_t i = 0; i < reg->count; ++i) {
        const std::string fam = reg->fonts[i].family;
        if (fam == r->default_family || fam.empty()) {
            continue; /* the primary font covers its own family */
        }
        bool opened = false;
        for (auto& f : r->fonts) {
            if (f.first == fam) {
                opened = true;
                break;
            }
        }
        if (opened) {
            continue; /* handled by the fallback_open pass above */
        }
        bool tried = false;
        for (auto& t : r->fallback_tried) {
            if (t.first == fam && t.second == cp) {
                tried = true;
                break;
            }
        }
        if (tried) {
            continue;
        }
        TTF_Font* fb = open_registry_font(fam);
        if (!fb) {
            continue;
        }
        ensure_font_state(r, fb, size, style);
        if (!TTF_FontHasGlyph(fb, cp)) {
            /* cannot help with THIS glyph: close it and remember (fam, cp),
             * so this codepoint does not reopen it, while other codepoints
             * the font DOES provide (CJK vs emoji in msyh) still reach it */
            TTF_CloseFont(fb);
            r->fallback_tried.emplace_back(fam, cp);
            continue;
        }
        r->fallback_open.push_back(fb);
        return fb;
    }
    return nullptr;
}

/* case-insensitive family-name match (CSS "Segoe UI" vs TTF real name) */
static bool family_eq(const char* a, const char* b)
{
    if (!a || !b) {
        return false;
    }
    for (; *a && *b; ++a, ++b) {
        char ca = *a;
        char cb = *b;
        if (ca >= 'A' && ca <= 'Z') {
            ca = static_cast<char>(ca - 'A' + 'a');
        }
        if (cb >= 'A' && cb <= 'Z') {
            cb = static_cast<char>(cb - 'A' + 'a');
        }
        if (ca != cb) {
            return false;
        }
    }
    return *a == 0 && *b == 0;
}

/* get (or open) the font for a family; one TTF_Font per family, size and
 * style applied on demand. Generic families ("" / sans-serif / serif /
 * monospace) and unknown families resolve to the default font. CSS family
 * lists like "Segoe UI", Helvetica, sans-serif match the real font names
 * reported by SDL3_ttf, so a page naming a font we registered by file
 * name ("segoeui.ttf") still resolves to it. */
TTF_Font* render_get_font(whaleui_render_t* r, const std::string& family, int size,
                          int style)
{
    if (size <= 0) {
        size = 16;
    }
    std::string key = family;
    for (auto& f : r->fonts) {
        if (f.first == key) {
            sync_chain(r, f.second, size, style);
            return f.second;
        }
    }
    /* try each family in the CSS list, in order */
    std::vector<std::string> fams = split_families(family);
    if (fams.empty()) {
        fams.push_back("");
    }
    TTF_Font* font = nullptr;
    for (const std::string& fam : fams) {
        if (fam.empty() || fam == "sans-serif" || fam == "serif" ||
            fam == "monospace") {
            font = r->font_default;
            break;
        }
        font = open_registry_font(fam);
        if (font) {
            break;
        }
        /* file-name miss: match the real family name of an opened font
         * ("Segoe UI" -> the font opened from segoeui.ttf). The default
         * font is opened at render_create and not in r->fonts, so it is
         * checked too. */
        if (r->font_default) {
            const char* real = TTF_GetFontFamilyName(r->font_default);
            if (real && family_eq(real, fam.c_str())) {
                font = r->font_default;
                break;
            }
        }
        for (auto& f : r->fonts) {
            const char* real = TTF_GetFontFamilyName(f.second);
            if (real && family_eq(real, fam.c_str())) {
                font = f.second;
                break;
            }
        }
        if (font) {
            break;
        }
    }
    if (!font) {
        font = r->font_default;
    }
    if (font) {
        /* record the fallbacks opened so far (engine-managed fallback; no
         * TTF_AddFallbackFont - see ensure_fallback's note) */
        if (r->font_chain.find(font) == r->font_chain.end()) {
            r->font_chain[font]; /* create the chain entry */
        }
        sync_chain(r, font, size, style);
        r->fonts.emplace_back(key, font);
    }
    return font;
}
#else /* !WHALEUI_BUILD_FULL: text rendering needs SDL3_ttf (full only).
         stb_font text lands with the lite/minimal font path. */
TTF_Font* render_get_font(whaleui_render_t*, const std::string&, int, int) { return nullptr; }
#endif

/* (struct TRect lives in render_internal.h) */

#ifdef WHALEUI_BUILD_FULL
/* full: 闂傚倷绀侀幉锟犮€冮崱妞曟椽寮介鐔蜂槐閻熸粌绻掗崚鎺楊敇閵忊剝娅囬梺閫炲苯澧寸€规洘娲栭～婵囨綇椤垶缍楅梻浣虹帛閿氭俊顖氾躬瀹曨垰顓兼径瀣帾闂佺硶鍓濆ú婊呰姳缁哄钉II 婵犵數鍋為崹鍫曞箰閹间焦鐓€闁挎繂鎷嬮悞?ASCII 缂傚倸鍊搁崐鐑芥嚄閸洖绐楃€广儱娲ㄩ崡姘舵倵闂堟稒鍟為悘?TTF_GetGlyphMetrics(闂?
 * fallback chain,CJK/emoji 闂備浇顕уù鐑姐€佹繝鍋芥盯宕熼娑樹壕闁荤喐婢橀弳杈ㄣ亜椤愮姴鐏查柡浣瑰姍瀹曞爼鏁愰崒姘?,婵?glyph_img_ttf 闂?advance 闂傚倷绀侀幉锟犳嚌妤ｅ啫瀚夋い鎺戝€芥慨?
 * 濠电姷鏁搁崑鐐哄箰缁嬫鍤曢柛顐ｆ礃閸嬪倿鎮楅敐搴′簼濠殿垰顕埀顒€绠嶉崕鍗灻洪妸鈺佸嚑闁稿本鍩冨Σ鍫ユ煙閻愵剙鈻曟い搴㈩殘缁辨帡寮崼顐ｎ棖婵炲濯寸粻鎾诲春閳ь剚銇勯幒鎴濃偓鐢稿磻閹捐埖鍏滈柛娑卞櫘濡嫰鏌ｆ惔锝庢敯婵炲懏娲滅划娆愬緞閹邦儵銊╂煥閺冣偓閸庢娊藟閺囩喓绠鹃柟瀵稿仦鐏忋劑鏌涚€ｎ偅宕岄柡灞诲€濋弻銊р偓锝庡墯濞堫剟姊洪柅鐐茶嫰閸樺摜绱掗鎹愭噣CII 闂傚倷鐒﹀鍨焽閸ф绀夐幖杈剧稻椤洟鏌ㄩ弮鍫熸殰闁稿鎸搁埥澶娾枎濡厧濮奸梻?闂?ASCII 闂?(font,cp) 缂傚倸鍊搁崐鎼佸磹瑜版帒绠伴柟闂寸劍閸嬨倝鏌曟繛鐐珔鏉?*/
static int glyph_ttf(unsigned int cp, void* st)
{
    TextMeasureCtx* c = static_cast<TextMeasureCtx*>(st);
    TTF_Font* font = render_get_font(c->r, c->family, c->fs,
                                     c->bold ? kFontBold : 0);
    if (!font) {
        return 0;
    }
    if (cp < 0x80) {
        if (c->r->ascii_font != font || c->r->ascii_fs != c->fs) {
            c->r->ascii_font = font;
            c->r->ascii_fs = c->fs;
            for (int i = 0; i < 128; ++i) {
                int m0 = 0, m1 = 0, m2 = 0, m3 = 0, adv = 0;
                TTF_GetGlyphMetrics(font, static_cast<Uint32>(i),
                                    &m0, &m1, &m2, &m3, &adv);
                c->r->ascii_w[i] = adv;
            }
        }
        return c->r->ascii_w[cp];
    }
    /* non-ASCII: cached per (font, size, codepoint); fallback chain included */
    /* The chain is NOT used for metrics: TTF_GetGlyphMetrics reports the
     * PRIMARY font's .notdef advance for missing glyphs (it does not walk
     * the fallback chain, while TTF_GetGlyphImage does) - measuring the
     * primary font gave CJK a 12px .notdef width at 18px while the paint
     * path drew 18px glyphs. Layout/widths/raster buffers were all off and
     * the last CJK char fell outside the buffer ("濠电姷鏁搁崕鎴犲緤閽樺鏆︽い鎺戝€甸崑鎾绘偡閺夋寧姣愰柡浣哥墦閺屾稓浠﹂崜褏鐓€闂? lost its 缂?.
     * Measure the FALLBACK font that will actually render the glyph. */
    TTF_Font* gfont = font;
    if (cp >= 0x80 || !TTF_FontHasGlyph(font, cp)) {
        TTF_Font* fb = ensure_fallback(c->r, font, c->fs,
                                       c->bold ? kFontBold : 0, cp);
        if (fb) {
            gfont = fb;
        }
    }
    if (gfont) {
        ensure_font_state(c->r, gfont, c->fs,
                          c->bold ? kFontBold : 0);
    }
    std::tuple<TTF_Font*, int, unsigned int> key(
        gfont, static_cast<int>(c->fs), cp);
    auto it = c->r->glyph_w_cache.find(key);
    if (it != c->r->glyph_w_cache.end()) {
        return it->second;
    }
    int m0 = 0, m1 = 0, m2 = 0, m3 = 0, adv = 0;
    TTF_GetGlyphMetrics(gfont, cp, &m0, &m1, &m2, &m3, &adv);
    c->r->glyph_w_cache[key] = adv;
    return adv;
}

/* full: 闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈濋梺缁橆殔閻楀﹥鍒婄€电硶鍋撻獮鍨姎闁瑰啿绻掔划?缂傚倸鍊搁崐鐑芥嚄閸洖绐楃€广儱娲ㄩ崡?GlyphImg 闂傚倷娴囬～澶嬬娴犲纾块弶鍫亖娴?闂傚倷绶氬褍螞閺冨倹宕插ǎ鍥ф尵_GetGlyphImage 闂?fallback 闂?
 * TTF_IMAGE_COLOR(COLR 闂佽崵鍠愮划宥嗙珶鐎ｎ喖鐤鹃柣鎰嚟閻濊泛鈹戦悩鎻掝仱闁稿鎸搁埥澶娾枎濡崵鏆ラ梻?闂?闂傚倷鑳堕…鍫㈢矓鐎靛憡宕查柟鐑樻⒒閻棛鈧厜鍋撻柛鏇ㄥ墮濞堟粌顪冮妶鍛閻庢凹鍣ｅ顐﹀Ω閵夊孩鐩幃褔宕奸姀銏㈠帞濠?TTF_IMAGE_ALPHA(闂傚倷娴囬褏鎹㈤幋婵愮唵婵☆垰鐨烽崑?
 * 闂?婵?fg 闂傚倷娴囬崑鎰板箠閹剧粯鍎戝ù鍏兼綑閻掑灚銇勯幒鍡椾壕闂佺锕ラ幃鍌炲箖妤ｅ啯鍊锋い鎺嶇椤?x = pen + minx(bitmap_left), y = baseline - maxy
 * (bitmap_top),婵?TTF_GetGlyphMetrics 闂備礁鎼ˇ顐﹀疾濠婂牆钃熼柕濞垮剭濞差亜鍐€闁靛ě鈧弸鏍⒑闁偛鑻晶鎾煙?advance 婵?glyph_ttf 闂傚倷绀侀幉锟犳嚌妤ｅ啫瀚夋い鎺戝€芥慨铏亜閺囨浜炬繝?
 * ponytail: 濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鎵閸嬨倗鎲搁幋锕€桅闁圭増婢橀～鍛存煟濡吋鏆╁?闂傚倸鍊风粈浣鸿姳闁秴纾婚柟鎯х摠閸欏繘鏌ㄥ┑鍡楊仾妞わ箓顥撶槐鎺楀棘鐠恒劍鎲肩紓?SDL_Surface,闂?ckey 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸ㄥ爼骞嗗畝鍕畾鐟滄粓宕?select 婵犵數鍋為崹鍫曞箰閹间緡鏁勯柛鈩兠崹鏃堟煣韫囨挻璐″?
 * 濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鐗堟緲缁狀喗鎱ㄥΟ鍨厫闁绘帒顭烽弻鐔兼焽閿曗偓婢т即鏌熼悾灞芥灁闁瑰弶鎮傞幊婊堫敆閳ь剟鎮橀鍫熷仭闁哄洨鍋為ˉ銏⑩偓?闂傚倷绀侀崥瀣儑瑜版帒纾块悗闈涙啞瀹曟煡鏌″搴′簽閻忓繒鏁婚弻銈嗘叏閹邦兘鍋撳Δ鍛煑婵鍩栭悡娑㈡煕鐏炲墽顣插璺哄缁绘繈鍩€椤掍礁顕遍柡澶嬪灩椤撴椽姊鸿ぐ鎺戜喊闁哥姵顨婇獮濠囧即閻?闂?(font,cp) 缂傚倸鍊搁崐鎼佸磹瑜版帒绠伴柟闂寸劍閸嬨倝鏌曟繛褉鍋撻柛瀣尭閳藉鈻庡Ο鑽ゆ殽闂備胶鍘ч幗婊勬櫠濡ゅ懎绠柛娑卞弾閸氬鏌涘☉鍗炴灓妞も晩鍙冨?*/
static bool glyph_img_ttf(whaleui_render_t* r, const std::string& family,
                          int fs, int style, unsigned int cp, unsigned int fg,
                          GlyphImg& out)
{
    TTF_Font* font = render_get_font(r, family, fs, style);
    if (!font) {
        return false;
    }
    /* render_get_font synced the font + its chain to THIS size/style. A
     * glyph the primary font does not provide lazily opens the next
     * registered font as fallback (unused CJK/emoji fonts cost nothing
     * until a page needs them). TTF_GetGlyphMetrics alone cannot detect
     * this - it reports .notdef metrics for missing glyphs AND does not
     * walk the fallback chain, so the metrics + bitmap below must come
     * from the SAME font that provides the glyph (glyph_ttf measures the
     * same font - see its comment). */
    TTF_Font* gfont = font;
    if (cp >= 0x80 || !TTF_FontHasGlyph(font, cp)) {
        /* non-ASCII: never trust TTF_FontHasGlyph on the primary - once a
         * fallback font is attached to its chain (TTF_AddFallbackFont),
         * hasGlyph reports true for chain-provided glyphs while
         * metrics/bitmap still come from the primary (.notdef 16px box for
         * CJK at 48px). Always ask ensure_fallback for the font that truly
         * provides the glyph (it returns null when the primary has it). */
        TTF_Font* fb = ensure_fallback(r, font, fs, style, cp);
        if (fb) {
            gfont = fb;
        }
    }
    /* gfont may be a SHARED fallback font (one msyh serves every primary
     * font) that another primary font restyled to a different size:
     * re-apply (fs, style) right before measuring + rasterizing this
     * glyph, or a stray 16px sync leaves a 48px CJK run rasterizing 16px
     * glyphs (big titles looked cut/short). */
    if (gfont) {
        ensure_font_state(r, gfont, fs, style);
    }
    int minx = 0, maxx = 0, miny = 0, maxy = 0, adv = 0;
    if (!TTF_GetGlyphMetrics(gfont, cp, &minx, &maxx, &miny, &maxy, &adv)) {
        return false;
    }
    TTF_ImageType type = TTF_IMAGE_INVALID;
    SDL_Surface* img = TTF_GetGlyphImage(gfont, cp, &type);
    if (!img) {
        return false;
    }
    out.w = img->w;
    out.h = img->h;
    out.xoff = minx;
    out.yoff = -maxy;
    out.advance = adv;
    out.colored = (type == TTF_IMAGE_COLOR);
    out.px.resize(static_cast<size_t>(img->w) * img->h);
    if (out.colored) {
        /* ARGB8888 闂備浇顕х换鎰崲閹邦喗宕查柟鐑橆殢閺佸倹銇勯幒鎴濐仼缂佲偓閸愵喗鐓曟繛鎴濆船楠炴﹢鏌熼悾灞解枅妤?= B,G,R,A 闂?0xAARRGGBB,婵?framebuffer 婵犵數鍋為崹鍫曞箰閹绢喖纾婚柟鍓х帛閻?*/
        std::memcpy(out.px.data(), img->pixels, out.px.size() * 4);
    } else {
        /* 闂傚倷娴囬褏鎹㈤幋婵愮唵婵☆垰鐨烽崑鎾绘偡閹殿噯绱為梺閫炲苯澧紒瀣浮閵嗗啴宕ㄧ€涙ê娈?SDL3_ttf 闂傚倷绀侀幉锟犲礉閺嶎厽鍋＄憸宥夊煝瀹ュ牜妯勯梺?+ alpha,闂傚倷绀侀幖顐⒚洪敂閿亾缁楁稑鍟伴弳锕傛煕濞嗗浚妲洪柍?fg 闂?婵?fg alpha) */
        const unsigned char* p =
            static_cast<const unsigned char*>(img->pixels);
        const unsigned int rgb = fg & 0xFFFFFF;
        const unsigned int fa = (fg >> 24) & 0xFF;
        for (size_t i = 0; i < out.px.size(); ++i) {
            unsigned int a = p[i * 4 + 3] * fa / 255;
            out.px[i] = a ? (a << 24) | rgb : 0;
        }
    }
    SDL_DestroySurface(img);
    return true;
}
#else
/* --- stb_truetype 闂傚倷绀侀幉锟犳嚌閹灐褰掓倻缁涘鏅?濠电姷鏁搁崑鐐差焽濞嗘搩鏁勯柛娑欐儗閺?+ 闂佽崵鍠愮划宥嗙珶鐎ｎ喖鐤鹃柣鎰嚟閻濊泛鈹戦悩鎻掝仱闁稿鎸搁埥澶娾枎濡崵鏆ラ梻?COLR/CPAL,闂傚倷绀侀幉锟犳偡閵夆晛纾瑰ù鐘差儏閻?stb#512/#1135) --- */

/* 婵犵數濮伴崹褰掓偉閵忋倕妞藉ù锝夘棑绾句粙姊洪懡銈呅㈡繛娴嬫櫊椤㈡俺顦堕柕?sfnt 闂備浇宕甸崑鐐电矙韫囨稑绀夌€光偓閸曨剙浠遍悷婊冪Ч閸┿垽骞樼紒姗嗘濠电偞鍨堕悷褏绮旈崹顐ょ?big-endian) */
static unsigned int be16(const unsigned char* p)
{
    return (static_cast<unsigned int>(p[0]) << 8) | p[1];
}
static unsigned int be32(const unsigned char* p)
{
    return (static_cast<unsigned int>(p[0]) << 24) |
           (static_cast<unsigned int>(p[1]) << 16) |
           (static_cast<unsigned int>(p[2]) << 8) | p[3];
}

/* 闂傚倷绶氬鑽ゆ嫻閻旂厧绀夌€光偓閸曨剙浠遍悷婊冮叄楠炲繘宕ㄩ弶鎴狀啋闁诲孩绋掕摫妞ゆ柨绉瑰铏规兜閸滀礁娈愰梺鍝ュУ濞茬喖骞婂▎鎾崇闁挎洍鍋撻柦鍐枛閺屾洘寰勫☉姘辨殸濡?sfnt 闂?tag 4 闂備浇顕х€涒晝绮欓幒妞尖偓鍐╁緞鐎ｂ晝绠?闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸撴氨绮嬪澶婁紶闁靛／鍛帬?闂備礁鎼ˇ顐﹀疾濠婂牆钃熼柕濞垮剭濞差亜鍐€妞ゆ挾鍠庨崜顔剧磽娴ｅ壊鍎愭い鎴炵懇瀹曠敻鎮╃紒妯煎幐婵炶揪绲介幖顐︺€傞懖鈹惧亾鐟欏嫭灏柤鍐茬埣楠炴劘顦虫い锔惧閹棃鍨鹃幓鎺戭嚙闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸撴氨绮嬪澶婁紶闁靛／鍛帬?
 * TTC 闂傚倷绀侀幉锟犳偡閿曞倹鍋嬫繝濠傜墱閺佸嫰鏌涢妷锝呭闁崇粯妫冮弻宥堫檨闁告挻姘ㄧ划娆愬緞閹板灚鏅滈梺鍛婃处閸樹粙骞夌紒妯肩閺夊牆澧界粙濠氭煙缁嬭法鍩ｉ柛鈹惧亾濡炪倖宸婚崑鎾绘煕婵犲拋娼愮紒鏃傚枎铻ｉ柤濮愬€愰弸鏍倵楠炲灝鍔氶柟鍐查叄閹繝宕掗悙鑼獓闂佸啿鎼崐褰掓偂閵夛妇绠?-1闂?*/
static int font_table_off(const unsigned char* data, size_t len, const char* tag)
{
    if (!data || len < 12) {
        return -1;
    }
    int fontstart = stbtt_GetFontOffsetForIndex(data, 0);
    if (fontstart < 0 || fontstart + 12 > static_cast<int>(len)) {
        return -1;
    }
    unsigned int n = be16(data + fontstart + 4);
    for (unsigned int i = 0; i < n; ++i) {
        size_t r = static_cast<size_t>(fontstart) + 12 + i * 16;
        if (r + 16 > len) {
            return -1;
        }
        const unsigned char* rec = data + r;
        if (rec[0] == static_cast<unsigned char>(tag[0]) &&
            rec[1] == static_cast<unsigned char>(tag[1]) &&
            rec[2] == static_cast<unsigned char>(tag[2]) &&
            rec[3] == static_cast<unsigned char>(tag[3])) {
            unsigned int off = be32(rec + 8);
            return off < len ? static_cast<int>(off) : -1;
        }
    }
    return -1;
}

/* COLR 闂備浇顕х换鎺楀磻濞戙垹纾瑰ù鐘差儛閺佸﹪鏌涢妷顔荤暗濞?闂備浇顕х换鎺楀磻濞戙垹纾归柟闂寸劍閸嬨倗鎲搁幋锕€桅?id + 闂備浇宕垫慨鎾敄閸涙潙鐤柧蹇ｅ亞閻濊泛鈹戦悩鍙夋悙缂佺嫏鍥ㄧ厵缂佸鐏濋銏ゆ煢閸屾凹鍎旈柡?闂傚倷绀侀幉锟犳偡閵夆晛纾瑰ù鐘差儏閻?stb#1135 闂?stbtt_glyphlayer) */
struct ColrLayer { unsigned short glyph; unsigned short color; };

/* 闂傚倷绀侀幖顐ゆ偖椤愶箑纾块柛娆忣槺閻?glyph 闂?COLR 闂?缂傚倸鍊烽懗鍫曞磻閹惧灈鍋撶粭娑樻搐閻掑灚銇勯幋顓炲閻庢凹鍓熻棢闁搞儺鍓氶悡?base glyph records 闂?glyph id 闂傚倷绀侀幉锟犮€冮崨顒兼椽濡堕崶顏勑?
 * 闂傚倷娴囧銊ヮ渻閹烘纭€闁规儼妫勯梻顖炴煣韫囨挻璐℃俊顐灣閹茬顓兼径濠傛優闂佺鎻梽鍕磿瀹€鈧槐鎺楁嚋閻㈠灚鍣伴悗瑙勬礃閻熲晠骞冮埡鍛闁圭儤妫戠槐?濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鎵閸嬨倗鎲搁幋锕€桅闁规澘搴滅紞鏍ㄣ亜閹捐泛顎屽ù鐓庢搐閳规垿鎮欓崣澶樻闂侀€炲苯澧柛鐔绘硶閹峰寮婚妷锔惧幍闂佽鍘界敮鎺楀礉濮樿鲸鍠?闂傚倷绶氬褍螞濡ゅ懎纾归柣锝呮湰瀹曟煡鏌熸潏鍓х暠闁绘劕锕弻锝夊箛椤栨氨姣㈠┑鐘亾闁圭虎鍠楅悡?0 = 闂備浇宕垫慨鏉懨洪姀銈呯？闂侇剙绉甸崑銈囨喐閹达箑桅闁圭増婢橀～鍛存煃閳轰礁鏋﹀Δ鐘茬箻閺岋綀绠涢弴鐐扮捕闂佺锕ら悥濂稿春閳?*/
static int colr_layers(const unsigned char* data, int colr_off,
                       unsigned int gid, const ColrLayer*& out)
{
    const unsigned char* t = data + colr_off;
    unsigned int n = be16(t + 2);
    unsigned int bgo = be32(t + 4);
    unsigned int lo = be32(t + 8);
    for (unsigned int i = 0; i < n; ++i) {
        const unsigned char* r = t + bgo + i * 6;
        if (be16(r) == gid) {
            unsigned int fi = be16(r + 2);
            unsigned int nl = be16(r + 4);
            out = reinterpret_cast<const ColrLayer*>(t + lo + fi * 4);
            return static_cast<int>(nl);
        }
    }
    return 0;
}

/* CPAL v0 闂備浇宕垫慨鎾敄閸涙潙鐤柧蹇ｅ亞閻濊泛鈹戦悩鍙夋悙缂佺嫏鍥ㄧ厱鐟滃酣銆冭箛娑樼骇鐟滅増甯楅悡?BGRA 闂傚倷绀侀幉锟犲礉閺囥垹绠犻幖娣妽閸嬨倝鏌曟繝蹇涙闁?闂?0xAARRGGBB);colorid==0xFFFF 闂傚倷鐒﹂惇褰掑垂閼测晛鍨濆Δ锝呭暞閸庡秹鏌ｉ弬鍨倯闁?
 * 闂傚倷绀侀幖顐﹀磹缁嬪尅鑰块梺顒€绉撮弸渚€鏌曢崼婵愭Ц缂佲偓閸懇鍋撻獮鍨姎婵☆偅鐟╅幃鐢割敍閻愬鍘鹃梺鑽ゅ枑婢瑰棗锕㈤幘顔界厓鐟滄粓宕滃▎鎾崇９婵繂琚禍褰掓煕閵夈垺娅嗛悗姘煎墴閺屾盯骞囬棃娑樼濡炪們鍎辩换姗€寮?0(婵犵妲呴崑鎾跺緤妤ｅ啯鍋嬮柡鍐ㄧ墛閻?闂?*/
static unsigned int colr_palette_color(const unsigned char* data, int cpal_off,
                                       unsigned int colorid)
{
    if (cpal_off < 0 || colorid == 0xFFFF) {
        return 0xFFFFFFFF;
    }
    const unsigned char* t = data + cpal_off;
    unsigned int npa = be16(t + 4);
    unsigned int npe = be16(t + 2);
    if (npa == 0 || colorid >= npe) {
        return 0xFFFFFFFF;
    }
    unsigned int cro = be32(t + 8);
    unsigned int pidx = be16(t + 12); /* palette 0 闂?colorRecordIndices */
    const unsigned char* c = t + cro + pidx * 4 + colorid * 4;
    return (static_cast<unsigned int>(c[3]) << 24) |
           (static_cast<unsigned int>(c[2]) << 16) |
           (static_cast<unsigned int>(c[1]) << 8) | c[0];
}

/* 濠电姷鏁搁崑鐐哄箰缁嬫鍤曢柛顐ｆ礃閸?COLR 闂傚倷绀侀幉锛勬暜閹烘嚦娑樜旈崨顔煎壋闂佽顔栭崰鎺楀磻閹炬枼妲堟繛鍡樕戦悾鍫曟⒑閻撳孩鎲稿褎顨堢划?RGBA(0xAARRGGBB);闂備礁鎼ˇ顐﹀疾濠婂牆钃熼柕濞垮剭?false 闂備浇宕甸崑鐐电矙韫囨稑绀夐幖娣妼妗呭┑顔筋焾濞夋稓鐚惧澶嬬厽婵☆垰鐏濋惃鐑樼節閳?闂備浇宕垫慨鎾敄閸涙潙鐤ù鍏兼綑閺嬩線鏌曢崼婵愭Ц婵☆偅顭囬惀顏堫敇閻愭潙娈屽┑?
 * 闂傚倷绀侀幖顐﹀箯鐎ｎ喖闂柨婵嗩槸閻掑灚銇勯幒宥囧妽闁汇劍鍨甸湁闁绘挸瀛╅ˉ鐐烘煙椤栨稒顥堥柡浣稿暞閹峰懘鎼归悷鐗堟殽闂?闂傚倷绶氬褍螞濡ゅ懎纾圭憸鐗堝笚閸庡﹪鏌ㄥ☉妯侯仹婵?stbtt 婵犵數鍋犻幓顏嗗緤閻ｅ瞼鐭撻柡澶嬪殮?+ 闂備浇宕垫慨鎾敄閸涙潙鐤柧蹇ｅ亞閻濊泛鈹戦悩鍙夋悙缂佺嫏鍥ㄧ厱鐟滃酣銆冭箛娑樼骇鐟滅増甯楅悡?src-over 闂傚倷绀侀幉锟犳嚌妤ｅ啯鍋嬪┑鐘叉搐閸ㄥ倹鎱ㄥΟ鎸庣【鏉?*/
static bool colr_render(const stbtt_fontinfo& info, float scale,
                        const unsigned char* data, int colr_off, int cpal_off,
                        unsigned int gid, unsigned int fg,
                        std::vector<unsigned int>& px, int& w, int& h,
                        int& xoff, int& yoff)
{
    const ColrLayer* layers = nullptr;
    int nl = colr_layers(data, colr_off, gid, layers);
    if (nl <= 0) {
        return false;
    }
    struct R { unsigned char* bmp; int w, h, x, y; unsigned int color; };
    std::vector<R> rs;
    int minx = 0x7FFFFFFF, miny = 0x7FFFFFFF, maxx = -0x7FFFFFFF, maxy = -0x7FFFFFFF;
    for (int i = 0; i < nl; ++i) {
        int bw = 0, bh = 0, bx = 0, by = 0;
        unsigned char* bmp = stbtt_GetGlyphBitmap(&info, scale, scale,
                                                  layers[i].glyph,
                                                  &bw, &bh, &bx, &by);
        if (!bmp || bw <= 0 || bh <= 0) {
            stbtt_FreeBitmap(bmp, nullptr);
            continue;
        }
        R r;
        r.bmp = bmp;
        r.w = bw;
        r.h = bh;
        r.x = bx;
        r.y = by;
        r.color = colr_palette_color(data, cpal_off, layers[i].color);
        if (layers[i].color == 0xFFFF) {
            r.color = fg;
        }
        rs.push_back(r);
        if (bx < minx) minx = bx;
        if (by < miny) miny = by;
        if (bx + bw > maxx) maxx = bx + bw;
        if (by + bh > maxy) maxy = by + bh;
    }
    if (rs.empty()) {
        return false;
    }
    w = maxx - minx;
    h = maxy - miny;
    xoff = minx;
    yoff = miny;
    px.assign(static_cast<size_t>(w) * h, 0);
    for (size_t ri = 0; ri < rs.size(); ++ri) {
        const R& r = rs[ri];
        const unsigned int sr = (r.color >> 16) & 0xFF;
        const unsigned int sg = (r.color >> 8) & 0xFF;
        const unsigned int sb = r.color & 0xFF;
        for (int yy = 0; yy < r.h; ++yy) {
            int dy = r.y - miny + yy;
            if (dy < 0 || dy >= h) {
                continue;
            }
            for (int xx = 0; xx < r.w; ++xx) {
                unsigned int sa = r.bmp[yy * r.w + xx];
                if (sa == 0) {
                    continue;
                }
                int dx = r.x - minx + xx;
                if (dx < 0 || dx >= w) {
                    continue;
                }
                unsigned int& d = px[static_cast<size_t>(dy) * w + dx];
                unsigned int da = (d >> 24) & 0xFF;
                /* src-over */
                unsigned int oa = sa + da * (255 - sa) / 255;
                if (oa == 0) {
                    continue;
                }
                unsigned int dr = (d >> 16) & 0xFF;
                unsigned int dg = (d >> 8) & 0xFF;
                unsigned int db = d & 0xFF;
                unsigned int oc = (sr * sa + dr * da * (255 - sa) / 255) / oa;
                unsigned int og = (sg * sa + dg * da * (255 - sa) / 255) / oa;
                unsigned int ob = (sb * sa + db * da * (255 - sa) / 255) / oa;
                d = (oa << 24) | (oc << 16) | (og << 8) | ob;
            }
        }
        stbtt_FreeBitmap(r.bmp, nullptr);
    }
    return true;
}

/* stb font table for measuring (mirrors the draw path in draw_text_at) */
struct StbFonts
{
    struct F { stbtt_fontinfo info; float scale; int asc; int line_h; bool ok; };
    std::vector<F> fonts;
    std::vector<int> colr, cpal; /* 濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鎵閸嬨倗鎲告惔銊ョ?COLR/CPAL 闂備浇宕甸崑鐐电矙韫囨稑绀夐悘鐐插⒔椤╂煡鏌涘┑鍕姢闁?闂傚倷绀侀幖顐﹀疮閻楀牊鍙忓Δ锝呭暙杩濋梺鍛婂姀閺呮繈鍩?-1 */
    size_t pref;
    int line_h;
    explicit StbFonts(const std::string& family, int fs)
        : pref(static_cast<size_t>(-1)), line_h(fs > 0 ? fs : 16)
    {
        whaleui_font_registry* reg = whaleui_font_registry_get();
        if (!reg) {
            return;
        }
        for (size_t fi = 0; fi < reg->count; ++fi) {
            F f;
            f.ok = false;
            f.scale = 1.0f;
            f.asc = 0;
            f.line_h = line_h;
            const unsigned char* d = reg->fonts[fi].data;
            size_t l = reg->fonts[fi].len;
            int co = -1, cp = -1;
            if (d && l >= 4) {
                int off = stbtt_GetFontOffsetForIndex(d, 0);
                if (off >= 0 && stbtt_InitFont(&f.info, d, off)) {
                    f.scale = stbtt_ScaleForPixelHeight(&f.info, static_cast<float>(fs));
                    int desc = 0, linegap = 0;
                    stbtt_GetFontVMetrics(&f.info, &f.asc, &desc, &linegap);
                    f.line_h = static_cast<int>((f.asc - desc + linegap) * f.scale + 0.5f);
                    f.ok = true;
                    line_h = f.line_h;
                    co = font_table_off(d, l, "COLR");
                    cp = font_table_off(d, l, "CPAL");
                }
            }
            colr.push_back(co);
            cpal.push_back(cp);
            fonts.push_back(f);
        }
        /* preferred font: first CSS family match, else first usable font */
        std::vector<std::string> fams = split_families(family);
        for (const std::string& fam : fams) {
            if (fam.empty()) {
                continue;
            }
            bool generic = fam == "sans-serif" || fam == "serif" ||
                           fam == "monospace";
            if (generic) {
                continue;
            }
            for (size_t fi = 0; fi < fonts.size(); ++fi) {
                if (fonts[fi].ok && reg->fonts[fi].family &&
                    std::strcmp(reg->fonts[fi].family, fam.c_str()) == 0) {
                    pref = fi;
                    break;
                }
            }
            if (pref != static_cast<size_t>(-1)) {
                break;
            }
        }
        if (pref == static_cast<size_t>(-1)) {
            for (size_t fi = 0; fi < fonts.size(); ++fi) {
                if (fonts[fi].ok) {
                    pref = fi;
                    break;
                }
            }
        }
    }
    size_t pick(size_t start, unsigned int cp) const
    {
        if (start != static_cast<size_t>(-1) && fonts[start].ok &&
            stbtt_FindGlyphIndex(&fonts[start].info, cp) != 0) {
            return start;
        }
        for (size_t fi = 0; fi < fonts.size(); ++fi) {
            if (fi == start || !fonts[fi].ok) {
                continue;
            }
            if (stbtt_FindGlyphIndex(&fonts[fi].info, cp) != 0) {
                return fi;
            }
        }
        return static_cast<size_t>(-1);
    }
};
/* stb: 闂傚倷绀侀幉锟犮€冮崱妞曟椽寮介鐔蜂槐閻熸粌绻掗崚鎺楊敇閵忊剝娅囬梺閫炲苯澧寸€规洘娲栭～婵囨綇椤垶缍楅梻浣虹帛閿氭俊顖氾躬瀹?闂?fallback 闂備浇顕х€涒晝绮欓幒妤€桅闁绘劗鏁哥粈濠囨倵閿濆骸澧柛? */
static int glyph_stb(unsigned int cp, void* st)
{
    StbFonts* f = static_cast<StbFonts*>(st);
    size_t fi = f->pick(f->pref, cp);
    if (fi == static_cast<size_t>(-1)) {
        return 0;
    }
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&f->fonts[fi].info, cp, &adv, &lsb);
    return static_cast<int>(adv * f->fonts[fi].scale + 0.5f);
}

/* stb: 闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈濋梺缁橆殔閻楀﹥鍒婄€电硶鍋撻獮鍨姎闁瑰啿绻掔划?缂傚倸鍊搁崐鐑芥嚄閸洖绐楃€广儱娲ㄩ崡?GlyphImg 闂傚倷娴囬～澶嬬娴犲纾块弶鍫亖娴?闂傚倷绶氬褍螞閺冨牆鐤鹃柣銈庢箤R 闂傚倷绀侀幉锛勬暜閹烘嚦娑樜旈崨顔煎壋闂佽顔栭崰鎺楀磻閹炬枼妲堟繛鍡樕戦悾鍫曟⒑閻撳孩鎲稿褎顨呴…鍥疀濞戞顔掗梺鍛婂姇瀵爼鎯侀弮鍫熲拺闁绘挸瀵掑▓鐘裁瑰鍕煉闁诡喕绮欓、鏇㈡晲韫囨洜鐓戞繝鐢靛Т閿曘倕螞濡ゅ惤?
 * (colored=true),闂傚倷绀侀幖顐﹀箯鐎ｎ喖闂柨婵嗩槸閻掑灚銇勯幒宥嗙グ濠㈣锕㈤弻锝夊煀濞嗗繑顥撳ù婊嗩潐閵囧嫰顢曢銏犵哗缂備讲鍋?fg 闂?闂?alpha闂傚倷绶氬褍螞濡ゅ懎鐒垫い鎺嗗亾闁糕晩鏌唂/yoff 婵犵數鍋為崹鍫曞箲娴ｇ硶鏋嶉柨婵嗘偪鐟欏嫬绶為悘鐐殿焾娴?pen+baseline
 * 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬娴滅偟妲愰悙鍝勫窛闁哄鍨归崐鐐烘⒑鐠団€崇€婚柛灞剧矊婢у墽绱?stb 闂備浇宕垫慨鏉懨归崒鐐插偍闁惧繐婀辨稉?婵?glyph_stb 闂傚倷绀侀幉锟犳嚌妤ｅ啫瀚夋い鎺戝€芥慨铏亜閺冣偓缁佸綊宕烽娑樹壕闁挎繂绨奸幉楣冩煕?闂?*/
static bool glyph_img_stb(StbFonts& stb, unsigned int cp, unsigned int fg,
                          GlyphImg& out)
{
    size_t fi = stb.pick(stb.pref, cp);
    if (fi == static_cast<size_t>(-1)) {
        return false;
    }
    const StbFonts::F& f = stb.fonts[fi];
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&f.info, cp, &adv, &lsb);
    out.advance = static_cast<int>(adv * f.scale + 0.5f);
    unsigned int gid = stbtt_FindGlyphIndex(&f.info, cp);
    if (gid == 0) {
        return false;
    }
    const unsigned char* data = f.info.data;
    if (stb.colr[fi] >= 0 &&
        colr_render(f.info, f.scale, data, stb.colr[fi], stb.cpal[fi],
                    gid, fg, out.px, out.w, out.h, out.xoff, out.yoff)) {
        out.colored = true;
        return true;
    }
    unsigned char* bmp = stbtt_GetGlyphBitmap(&f.info, f.scale, f.scale,
                                              gid, &out.w, &out.h,
                                              &out.xoff, &out.yoff);
    if (!bmp || out.w <= 0 || out.h <= 0) {
        stbtt_FreeBitmap(bmp, nullptr);
        return false;
    }
    out.colored = false;
    out.px.resize(static_cast<size_t>(out.w) * out.h);
    const unsigned int sr = (fg >> 16) & 0xFF;
    const unsigned int sg = (fg >> 8) & 0xFF;
    const unsigned int sb = fg & 0xFF;
    const unsigned int fa = (fg >> 24) & 0xFF; /* 闂傚倷绀侀幉锟犲箰閸濄儳鐭撻梻鍫熺▓閺?alpha 婵犵數鍋為崹璺侯潖瑜版帗鏅梻浣虹《閺呮盯鎯夋總绋跨劦妞ゆ帊鑳堕埊鏇熴亜閵娿儲鍤囬柟铏矒閹囧醇閳垛晜鐏?*/
    for (size_t i = 0; i < out.px.size(); ++i) {
        unsigned int a = bmp[i] * fa / 255;
        out.px[i] = a ? (a << 24) | (sr << 16) | (sg << 8) | sb : 0;
    }
    stbtt_FreeBitmap(bmp, nullptr);
    return true;
}
#endif

/* 闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈濋梺瑙勵問閸犳宕伴崱娑欑厱闁斥晛鍟崵顒佺箾閸忓吋绀嬮柡宀嬬秮閸╋繝宕掑顓＄檨闂?ascent + descent/2),闂傚倷鐒﹀鍨焽閸ф绀夐悗锝庡墲婵櫕銇勯幒鎴濐仼婵☆偅锕㈤弻娑㈠Ψ閹存繃鍣洪柟?闂傚倷鑳堕…鍫㈡崲閹板叓鍥ㄥ鐎涙ê浜?闂傚倸鍊风欢锟犲磻閸曨垁鍥敍濠娾偓閻掑﹥銇勯弽顐粶闁搞劌鍊块弻娑氫沪閸撗呯厑缂備胶铏庨崹鍫曞箖濮椻偓閹瑩宕ｆ径濠冾仧闂?
 * 闂備浇宕甸崑鐐电矙閹达附鍎楅柛宀€鍋為崑?th 闂傚倷绀侀幉锟犲礄瑜版帒纾诲鑸靛姂閳ь兛绶氶獮瀣偐閸愯尙锛?闂?th 闂備浇顕х换鎺楀磻濞戙垹绠犵€广儱顦伴崵鍫ユ煙鐎电浠滄い鏇￠哺閹便劌螣鐠囨彃顫梺鍝ュ亼閸旀垿寮婚敐澶婎潊闁挎繂楠稿▓顓炩攽閻橆偄浜惧銈呯箰濡稓澹曟禒瀣厵闁诡垎鍐╂瘣闂佸搫妫楀畷顒勨€旈崘顔嘉ч柛娑卞灠閻撶喖姊虹粙鍨劉闁瑰憡濞婇獮鍡涘礃椤旇偐顦板銈嗗姂閸婃牠骞夋繝姘仭婵犲﹤妫楅悞浠嬫煕閵娿儯鍋㈤柨婵堝仧閳ь剨缍嗛崜姘跺窗閸℃鐔嗛悹铏瑰皑濮婃鏌ｉ幒鎴伐闁宠棄顦甸獮姗€骞囨担鍝勫Ъ闂?
 * 婵?draw_text_at 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸撶喖骞嗛崶顒佹優妞ゆ劑鍊愰弸鏍ь渻閵堝棙灏甸柛瀣枛瀹曨剟濡搁埡鍌滃幈闂佺懓鐡ㄧ换鍐夊▎鎴犵＜闁哄啠鍋撻柟鍛婂▕楠?闂傚倸鍊风欢锟犲礈濞嗘挻鍊舵繝闈涱儏閸?caret 婵犵數鍋為崹鍫曞箰閸濄儮鍋撳☉鎺撴珚鐎殿喗鎮傚畷姗€顢旀担闀愬濠电偞鍨堕悷顖氣枔濠婂牊鐓涘ù锝夋交閺€濠氭煙瀹勭増鍣规い鎾炽偢瀹曟﹢鏁愰崨顒€顥?*/
int text_glyph_h(whaleui_render_t* r, int fs, const std::string& family,
                 bool bold)
{
    int gh = 0;
#ifdef WHALEUI_BUILD_FULL
    TTF_Font* gfont = render_get_font(r, family, fs, bold ? kFontBold : 0);
    if (gfont) {
        int ga = TTF_GetFontAscent(gfont);
        int gd = TTF_GetFontDescent(gfont);
        if (ga > 0) {
            gh = ga + gd / 2;
        }
    }
#endif
    return gh > 0 ? gh : text_line_h(r, fs, family, bold);
}

void text_size(whaleui_render_t* r, const std::string& text, int fs,
               const std::string& family, bool bold, int* tw, int* th,
               int wrap_w)
{
    *tw = *th = 0;
    if (text.empty() || !r) {
        return;
    }
    /* content-addressed cache: the layout pass measures every run every
     * relayout (a width animation re-lays out each frame) - the layout_text
     * walk below was the per-frame cost. Text/width/face unchanged -> O(1). */
    uint64_t key = 1469598103934665603ull;
    for (size_t i = 0; i < text.size(); ++i) {
        key ^= static_cast<unsigned char>(text[i]);
        key *= 1099511628211ull;
    }
    key ^= static_cast<uint64_t>(fs) * 0x9E3779B97F4A7C15ull;
    key ^= static_cast<uint64_t>(bold) * 0xBF58476D1CE4E5B9ull;
    key ^= static_cast<uint64_t>(wrap_w) * 0x94D049BB133111EBull;
    for (size_t i = 0; i < family.size(); ++i) {
        key ^= static_cast<unsigned char>(family[i]);
        key *= 1099511628211ull;
    }
    auto it = r->text_size_cache.find(key);
    if (it != r->text_size_cache.end()) {
        *tw = it->second.first;
        *th = it->second.second;
        return;
    }
    int lh = text_line_h(r, fs, family, bold);
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextLayout L = layout_text(text, wrap_w, lh, glyph_ttf, &mc);
#else
    StbFonts stb(family, fs);
    TextLayout L = layout_text(text, wrap_w, lh, glyph_stb, &stb);
#endif
    *tw = L.tw;
    *th = L.th;
    r->text_size_cache[key] = std::make_pair(*tw, *th);
}

int text_line_h(whaleui_render_t* r, int fs, const std::string& family, bool bold)
{
#ifdef WHALEUI_BUILD_FULL
    TTF_Font* font = render_get_font(r, family, fs,
                                     bold ? kFontBold : 0);
    if (font) {
        int h = TTF_GetFontHeight(font);
        if (h > 0) {
            return h;
        }
    }
    return fs > 0 ? fs : 16;
#else
    StbFonts stb(family, fs > 0 ? fs : 16);
    return stb.line_h;
#endif
}

std::vector<TRect> sel_rects(whaleui_render_t* r, const std::string& text,
                             int fs, const std::string& family, bool bold,
                             size_t a, size_t b, int wrap_w)
{
    std::vector<TRect> out;
    if (a > text.size()) {
        a = text.size();
    }
    if (b > text.size()) {
        b = text.size();
    }
    if (a > b) {
        std::swap(a, b);
    }
    if (a == b || text.empty()) {
        return out;
    }
    int lh = text_line_h(r, fs, family, bold);
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    const size_t nc = L.map.size();
    for (size_t li = 0; li < L.lines.size(); ++li) {
        const TextLayoutLine& ln = L.lines[li];
        int xacc = 0;
        int x0 = -1, x1 = -1;
        for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
            int w = gw(disp_cp_at(L, ci), st);
            if (x0 < 0 && L.map[ci] >= a) {
                x0 = xacc;
            }
            if (x1 < 0 && L.map[ci] >= b) {
                x1 = xacc;
                break;
            }
            xacc += w;
        }
        if (x0 < 0) {
            continue; /* line ends before a */
        }
        if (x1 < 0) {
            x1 = xacc; /* range extends past this line's end */
        }
        if (x1 > x0) {
            TRect rc = {x0, static_cast<int>(li) * lh, x1 - x0, lh};
            out.push_back(rc);
        }
        if (x1 >= xacc) {
            continue; /* keep scanning later lines (range continues) */
        }
        break;
    }
    return out;
}

void caret_pos(whaleui_render_t* r, const std::string& text, int fs,
               const std::string& family, bool bold, size_t off,
               int* cx, int* cy, int* ch, int wrap_w)
{
    int lh = text_line_h(r, fs, family, bold);
    if (lh <= 0) {
        lh = fs > 0 ? fs : 16;
    }
    if (text.empty()) {
        *cx = 0;
        *cy = 0;
        *ch = lh;
        return;
    }
    if (off > text.size()) {
        off = text.size();
    }
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    const size_t nc = L.map.size();
    /* 闂?off 闂傚倷绀佸﹢閬嶃€傛禒瀣；闁瑰墽绮悡鏇㈡煥閺傛寧鎯堝┑顔瑰亾婵?off 闂傚倷娴囪闁稿鎹囬弻锕€螣娓氼垱效闂?[闂備浇宕甸崑鐐电矙閹达附鍎楅柛宀€鍋戦埀顒€鎳忕换婵嗩潩椤掑偊绱遍梻濠庡亜濞诧箑鈻? 闂備浇宕甸崑鐐电矙閹达附鍤愭い鏍仦閸嬪嫭銇勯幒鎴濐仼缁炬儳顭烽悡顐﹀炊閵婏箓鏆卞?闂傚倷绀侀幉锟犳偋濡も偓椤啴鎸婃竟鈺傜洴瀹曠螖閳ь剝绻?
     * 闂備浇宕甸崑鐐电矙閹达附鍎楅柛宀€鍋戦埀顒€鎳忕换婵嗩潩椤掑倻娼?caret 闂傚倷鐒﹂惇褰掑垂婵傚壊鏁嬬憸宥夋晝閵忋値鏁傞柛鈩兠悵浼存⒑闂堟侗妯堥柣鎾崇墦瀵?x=0(婵犵數鍋為崹鍫曞箰閸濄儳鐭撻梻鍫熷厷閿濆绠瑰ù锝呮憸椤︻參鎮楅獮鍨姎閻庢凹鍣ｉ、鏃堟焼瀹ュ棗浠╁┑鐐村灦椤洭鎮樻潏銊х闁割偆鍠庨悘鈺呮煙椤旇棄顥嬪ù鐙呯畵閹墽浠﹂懞銉︻啇)闂?*/
    for (size_t li = 0; li < L.lines.size(); ++li) {
        const TextLayoutLine& ln = L.lines[li];
        size_t ls_off = (ln.cstart < nc) ? L.map[ln.cstart] : off;
        size_t le_off = (ln.cend < nc) ? L.map[ln.cend] : text.size();
        if (off < ls_off) {
            /* 闂傚倷娴囪闁稿鎹囬弻锕€螣娓氼垱效闂傚鍓﹂崜娆撳煡婢舵劕绠荤紒娑滎潐椤ｈ偐绱撴担瑙勭叆妞ゆ洦鍙冮獮鍐箥椤旂粯鍕冮梺缁樺姦閸撴岸鎯堝鈧弻锝堢疀閹惧墎顔囬悷婊勫閸嬬喓鍒掓繝姘櫜濠㈣泛锕ㄨ闂佸湱鍘ч悺銊х矙閸儱纾婚柟鎯х摠婵挳鎮峰▎蹇擃仾閻庢碍濞婇弻锝夋倷鐎电硶妲堥梺娲诲幒缁舵岸濡存笟鈧獮瀣倻閸モ晝锛為梻浣告惈缁嬪嫭淇婇崶顒夋晣婵炲樊浜濋悡?闂傚倷绀侀幉锟犳偡椤栨稓顩叉繝濠傚枦閼版寧銇勮箛鎾搭棤闁活厽鑹捐灃闁挎梻鐡旈崕銉╂煛閳ь剟鎸婃径鍡橆潔闂佸搫鍊归娆撳磿閺冣偓娣囧﹪顢曢姀鈥充淮闂?
             * \n 婵犵數濮伴崹鐓庘枖濞戞埃鍋撳鐓庡⒉闁靛洦鍔欏濠氬Ψ閿曗偓濞?闂佽崵鍠愮划搴㈡櫠濡ゅ懎绠板瀣捣缁€濠囨煛閸愩劎澧曢悗姘槹閵囧嫰骞掗幋婵囩亾闂佽　鍋撳ù鐘差儐閸嬬姵绻涢幋鐑嗙劷闁绘帒鎲￠妵鍕煛閸愵亜绗￠悗鍨緲鐎氭澘鐣烽悢纰辨晣闁绘柨鐨濋崑?*/
            *cx = 0;
            *cy = static_cast<int>(li) * lh;
            *ch = lh;
            return;
        }
        if (off >= ls_off && off <= le_off) {
            int xacc = 0;
            for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
                if (L.map[ci] >= off) {
                    break;
                }
                xacc += gw(disp_cp_at(L, ci), st);
            }
            *cx = xacc;
            *cy = static_cast<int>(li) * lh;
            *ch = lh;
            return;
        }
    }
    /* 闂傚倷鑳堕…鍫㈡崲閹寸姴鍨濈€光偓閳ь剟鎳?闂傚倷绀侀幖顐﹀磹缁嬫５娲晝閳ь剟鏁冮姀鈥愁嚤闁哄鍨甸悵妯侯渻閵堝棗濮傞柛銊ヮ煼瀹?*/
    const TextLayoutLine& last = L.lines.back();
    *cx = last.w;
    *cy = static_cast<int>(L.lines.size() - 1) * lh;
    *ch = lh;
}

/* defined below (editing helpers); needed by the paint path above */
void text_origin(whaleui_render_t* r, whaleui_layout_node_t* n,
                 const std::string& text, int fs, const std::string& family,
                 bool bold, int* tx, int* ty);
struct whaleui_layout_node;
whaleui_layout_node_t* editable_geo(whaleui_layout_node_t* n);

size_t utf8_char_len(unsigned char c)
{
    if (c < 0x80) {
        return 1;
    }
    if ((c & 0xE0) == 0xC0) {
        return 2;
    }
    if ((c & 0xF0) == 0xE0) {
        return 3;
    }
    if ((c & 0xF8) == 0xF0) {
        return 4;
    }
    return 1;
}

void apply_text_transform(std::string& s, const std::string& t)
{
    if (t == "uppercase") {
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c < 0x80 && c >= 'a' && c <= 'z') {
                s[i] = static_cast<char>(c - 32);
            }
        }
    } else if (t == "lowercase") {
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c < 0x80 && c >= 'A' && c <= 'Z') {
                s[i] = static_cast<char>(c + 32);
            }
        }
    } else if (t == "capitalize") {
        bool word_start = true;
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c >= 0x80) {
                i += utf8_char_len(c) - 1;
                word_start = false;
                continue;
            }
            if (c == ' ' || c == '\t' || c == '-') {
                word_start = true;
            } else if (word_start) {
                if (c >= 'a' && c <= 'z') {
                    s[i] = static_cast<char>(c - 32);
                }
                word_start = false;
            }
        }
    }
}

void draw_text_at(whaleui_render_t* r, const std::string& text,
                  int bx, int by, int bw, int bh,
                  int fs, const std::string& family, unsigned int color,
                  int style, int align, lxb_dom_element* ckey,
                  const Clip* clip, int lsp, bool wrap, float opacity,
                  bool outline)
{
    /* 缂傚倸鍊搁崐鎼佸磹瑜版帒绠伴柟闂寸劍閸嬨倝鏌曟繛鐐珔闁藉啰鍠栭弻鏇熷緞濡厧甯ラ梺鎼炲€曠€氫即寮诲☉婊呯杸闁规崘娉涢埅鎻掝渻?text+闂傚倷绀侀幖顐ょ矓閹绢喖搴婇柤纰卞墯椤洟鏌嶉埡浣告殶闁崇粯姊婚埀顒€绠嶉崕閬嶅箠鎼达絿绀婂〒姘ｅ亾闁?闂傚倷绀佸﹢閬嶅磿閵堝洦鏆滈柣鎰摠濞?layout_text)婵犵數鍋為崹鍫曞箰閸涘娈介柟闂寸劍閸嬨倗鎲搁幋锕€桅闁圭増婢橀～鍛存煟濡绲婚弶鍫濇嚇濮婃椽宕崟顓夈垽鏌熼崘鍙夋崳闁逞屽墮閻忔岸鎮￠垾鎰佸殨?
     * 濠电姵顔栭崳顖滃緤閻ｅ本宕查柟鐗堟緲缁狀喗鎱ㄥΟ鍨厫闁绘挸鍊婚埀顒€绠嶉崕閬嶅箯鐎ｎ€絾绻濆顓炰化婵炴挻鑹鹃敃锔惧閸ф鐓?闂傚倷鑳堕崑銊╁磿閺屻儱钃熼柨鐔哄Т閻?闂傚倷绀侀幉锟犲蓟閿濆绀夐幖娣妼閺嬩線鏌涢幘妤€瀚▓浼存偡濠婂啰效妞ゃ垺宀搁、娆愬緞鐟欏嫬绗╃紒鐘崇⊕閹棃濡搁妷锔炬澓 run 闂傚倸鍊烽悞锕併亹閸愵亞鐭撻柣銏㈩焾閽冪喎鈹戦悩鍙夋悙缂佺姵濞婇弻鐔兼倻濡崵鍙嗗銈忕到閵堟悂寮婚敓鐘茬倞闁宠桨妞掓竟鏇炩攽?42ms 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸撶喐淇婇悽绋跨倞闁靛鍎崇粣鐐测攽閻戝洨绉甸柛蹇旓耿瀹?
     * 闂傚倷绀侀幉锛勭矙閹烘鍨傛繝闈涱儐閸ゅ牓鏌熸潏楣冩闁稿骸閰ｉ幃妤€鈽夊▍顓т簼瀵板嫬顓兼径瀣幗濡炪値鍋掗崜娆愪繆鐠恒劎纾奸柟鎻掝儏椤╊剟鏌嶈閸撴氨绮欓幒妞烩偓锕傚炊瑜夐弸鏃堟煙鐎电浠﹀┑顖氼嚟閳ь剙绠嶉崕閬嶅箠韫囨洜鐭夐柛顐ｇ妇濡插牓鏌熼悙顒€鈻曟い搴㈩殜閺岋繝宕熼鈶╁亾婵犳艾鐒?闂備礁鎼ˇ顐﹀疾濠靛纾绘繛鎴欏灪閸嬨倗鎲告惔銊ョ闁告稒娼欑粻濠氭煛婢跺鐏嶉柛娆愭そ閹鈻撻崹顔界亐闂?闂備浇宕甸崑鐐电矙閹达附鍎楅柛宀€鍋為崑鐔搞亜閺冣偓缁佸綊宕烽娑樹壕闁挎繂楠搁弸娑欑箾閸涱偄鈧繂顫忓ú顏嶆晩閻忓繑鐗曟禍楣冩煟閺傛寧鎯堥柛鏃€绮撻弻鈩冨緞閸℃ɑ鐝斿┑鐐茬湴閸ㄤ粙宕洪埀?*/
    std::vector<unsigned int>* src = nullptr;
    int tw = 0, th = 0;
    int tx = bx, ty = by; /* paint origin (align/center applied below) */
    std::string ckey_str; /* cache key to write on miss ("" = no caching) */
#ifdef WHALEUI_BUILD_FULL
    if (ckey && !text.empty()) {
        uint64_t h = 1469598103934665603ull;
        for (size_t i = 0; i < text.size(); ++i) {
            h ^= static_cast<unsigned char>(text[i]);
            h *= 1099511628211ull;
        }
        char key[160];
        std::snprintf(key, sizeof(key), "%p|%d|%d|%s|%d|%u|%d|%llu",
                      static_cast<void*>(ckey), fs, style, family.c_str(),
                      wrap ? bw : -1, color, lsp,
                      static_cast<unsigned long long>(h));
        auto it = r->text_cache.find(key);
        if (it != r->text_cache.end() && !it->second.px.empty()) {
            whaleui_render_t::TextCacheEntry& e = it->second;
            src = &e.px;
            tw = e.w;
            th = e.h;
            e.last_use = ++r->tc_tick;
        } else {
            ckey_str = key;
        }
    }
#endif
    if (!src) {
        /* cache miss: layout + rasterize this run */
        if (fs <= 0) {
            fs = 16;
        }
        const bool bold = (style & kFontBold) != 0;
        int lh = text_line_h(r, fs, family, bold);
        if (lh <= 0) {
            lh = fs;
        }
        /* 缂傚倸鍊搁崐鐑芥嚄閸洖绐楃€广儱娲ㄩ崡姘舵倵閻㈢數銆婇柛瀣尭閳藉鈻庡Ο鑽ゆ殽闂備礁銈搁弲鏌ュ础閹剁晫宓侀柟鐑橆殔鍞梺闈涱槶閸庡磭绮?闂傚倷绀佸﹢閬嶅磿閵堝洦鏆滈柣鎰摠濞?濠电姷鏁搁崑鐐差焽濞嗘搩鏁勯柛娑欐儗閺?婵犵數鍋為崹鍫曞箰缁嬫５瑙勵槹鎼粹€崇亰濡炪倖鐗滈崑娑氱矆閸℃稒鍋ｉ柛婵嗗閹牏鎲搁悧鍫㈡噰闁哄矉缍侀敐鐐侯敆閳ь剚淇婃總鍛婄厵妞ゆ棁濮ょ亸鎵磼鐎ｎ亶妯€闁糕斁鍋撳銈嗗笒鐎氼剛鎲撮敃鍌氱閺夊牆澧界粔闈浢归悡搴♀偓鍧楀箖濡も偓閳藉鈻庡Ο鑽ゆ殽闂備礁銈搁弲鏌ュ础閸愬樊鍤曢柛顐ｆ礀鍞梺鎸庢煥婢т粙宕?advance/闂傚倷鑳堕…鍫ヮ敄閸涱垱宕查柟鍝勭Ф閺?
         * 婵犵數鍋為崹鍫曞箰閸洖纾块柡灞诲劜閸嬪鏌涘☉姗堝姛闁崇粯妫冮弻宥堫檨闁告挾鍠栭獮?full 婵?stb 闂傚倷绀侀幉锟犳偡椤栨稓顩叉繝闈涙４閼板灝霉閿濆牜娼愬ù婧垮€栫换娑㈠幢濡纰嶅┑鐐叉噳閳ь剚鏋煎Σ鍫ユ煙閹咃紞鐎涙繈姊?濠电姷鏁搁崑鐐哄箰缁嬫鍤曢柛顐ｆ礃閸嬪倿鎮楅敐搴濇喚闁搞倖顨嗛妵鍕疀閹炬惌妫炵紓浣哄У瀹€鎼佸蓟濞戞ǚ鏋庢俊顖氭贡閸戠懓鈹戦悩顐壕婵炶揪绲藉﹢閬嶅煝閺冨牊鐓冪憸婊堝礈濮樿京鐭?*/
        int baseline_off;
        TextLayout L;
#ifdef WHALEUI_BUILD_FULL
        TTF_Font* font = render_get_font(r, family, fs, style);
        if (!font) {
            return;
        }
        baseline_off = TTF_GetFontAscent(font);
        TextMeasureCtx mc = { r, fs, family, bold };
        L = layout_text(text, (wrap && bw > 0) ? bw : 0, lh, glyph_ttf, &mc);
#else
        StbFonts stb(family, fs);
        if (stb.pref == static_cast<size_t>(-1)) {
            return;
        }
        baseline_off = static_cast<int>(stb.fonts[stb.pref].asc *
                                        stb.fonts[stb.pref].scale + 0.5f);
        L = layout_text(text, (wrap && bw > 0) ? bw : 0, lh, glyph_stb, &stb);
#endif
        if (L.lines.empty()) {
            return;
        }
        tw = L.tw;
        th = L.th;
        /* letter-spacing is added to the pen per glyph (px += advance +
         * lsp) but L.tw is the plain advance sum: a spaced line's last
         * glyph lands lsp*(chars-1) past tw and the raster clip (tx2 >=
         * tw) sliced its right side off - small fonts with letter-spacing
         * visibly lost their tail. Grow the buffer by the widest line's
         * spacing so every glyph fits. */
        if (lsp > 0) {
            size_t max_ch = 0;
            for (size_t li = 0; li < L.lines.size(); ++li) {
                size_t ch = L.lines[li].cend - L.lines[li].cstart;
                if (ch > max_ch) {
                    max_ch = ch;
                }
            }
            if (max_ch > 1) {
                tw += lsp * static_cast<int>(max_ch - 1);
            }
        }
        /* some glyphs are wider than their advance (msyh's f/t/v/w/y/
         * A/V/W/Y/Z/&/_// have maxx 1px past advance; italic/kerning add
         * more): L.tw is the advance sum, so a line's LAST glyph's ink
         * falls past tw and the raster clip (tx2 >= tw) sliced it off -
         * small mixed CJK/latin text lost its tail. The 2px slack covers
         * the typical 1px overflow plus a hair of anti-aliasing. */
        tw += 2;
        if (tw <= 0 || th <= 0) {
            return;
        }
        auto glyph_img = [&](unsigned int cp, GlyphImg& g) {
#ifdef WHALEUI_BUILD_FULL
            return glyph_img_ttf(r, family, fs, style, cp, color, g);
#else
            return glyph_img_stb(stb, cp, color, g);
#endif
        };
        /* 闂傚倸鍊风欢锟犲磻閸涙潙绀夐柡鍥ュ灪閸嬨倗鎲搁幋锕€桅闁圭増婢橀～鍛存⒔閸ヮ兙鈧懘顢曢敂鐣屽幐?闂傚倷绀侀幗婊堝磿閹版澘鍨傛い鏍ㄧ矌閸楁岸鏌℃径瀣劸闁搞倖顨嗛妵鍕疀閹炬惌妫炵紓?:闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈濋梺缁橆殔閻楀﹥鍒婄€电硶鍋撻獮鍨姎闁瑰啿绻掔划?RGBA,闂佽娴烽幊鎾诲箟闄囬妵鎰板礃椤旇偐鐣鹃梺鍓插亖閸庤京绮堥崼鈶╁亾楠炲灝鍔氭俊顐ｇ懇閹敻顢涢悙瀵稿幘闂佽崵鍠愬妯肩棯瑜旈弻娑㈠Ω閿濆懎顫呴梺闈涙处閸旀瑩宕洪敓鐘茬妞ゆ劦鍋呴ˉ?emoji
         * 闂傚倷鑳堕崢褔銆冩惔銏㈩洸闁挎繂顦伴ˉ濠囨煃閸濆嫬浜扮紒鎲嬬稻缁绘繃绻濋崒娑辨濡?src-over 闂傚倷绀侀幉锛勬暜閻愬瓨娅犳俊銈呮噹閸戠娀鏌涢幇闈涙灈閻庢艾顦伴妵鍕箳閹存績鍋撶紒妯虹窞闁告洦鍨遍悡鏇㈡煙闁箑澧版繝鈧幘顔界厓鐟滄粓宕楀☉銏☆棃闁绘牗浜?闂傚倷绀侀幖顐﹀疮閻楀牊鍙忛柟缁㈠枛缁犳牠骞栧ǎ顒€濡肩紒鐙呯秮閺岀喖鏌囬敃鈧弸銈夋煟閹炬潙濮囬棁?闂傚倷绀侀幖顐﹀箯鐎ｎ喖闂柨婵嗩槸閻掑灚銇勯幒宥嗙グ濠㈣锕㈤弻锝夊煀濞嗗繑顥撳ù婊冪秺閺屾洝绠涢弴鐐愩垻绱掗埀顒佹媴閾忓湱锛?
         * 1px 闂傚倷绀侀幉锟犲礉閺囩姷鐭撻柛顐ｆ礀閺嬩線鏌ｉ幇闈涘闁崇粯妫冮弻宥堫檨闁告挻鐟╅崺?fake bold);full 闂傚倷鐒﹂惇褰掑礉瀹€鈧埀顒佸嚬閸ｏ綁骞嗗畝鍕唨闁靛绠戦鎾绘⒑鐟欏嫬绀冮柛鈺傜墵瀵?FreeType 闂傚倷绶氬鑽ゆ嫻閻旂厧绀夌€光偓閸曨剙浠遍悷婊勫灴婵＄敻骞囬弶娆炬綂闂佺粯锚瀵爼寮抽妷鈺傜厽閹艰揪绲鹃崵鈧梺鍝勭墱閸撶喎鐣烽悷閭︽僵閻犺桨缍?*/
        std::vector<unsigned int> buf(static_cast<size_t>(tw) * th, 0);
        for (size_t li = 0; li < L.lines.size(); ++li) {
            const TextLayoutLine& ln = L.lines[li];
            const int baseline = static_cast<int>(li * lh) + baseline_off;
            int px = 0;
            for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
                GlyphImg g = {};
                if (glyph_img(disp_cp_at(L, ci), g)) {
                    const int passes =
#ifndef WHALEUI_BUILD_FULL
                        (bold && !g.colored) ? 2 :
#endif
                        1;
                for (int pass = 0; pass < passes; ++pass) {
                    const int dx0 = px + g.xoff + pass;
                    const int dy0 = baseline + g.yoff;
                    for (int yy = 0; yy < g.h; ++yy) {
                        const int ty2 = dy0 + yy;
                        if (ty2 < 0 || ty2 >= th) {
                            continue;
                        }
                        for (int xx = 0; xx < g.w; ++xx) {
                            const int tx2 = dx0 + xx;
                            if (tx2 < 0 || tx2 >= tw) {
                                continue;
                            }
                            const unsigned int sp =
                                g.px[static_cast<size_t>(yy) * g.w + xx];
                            const unsigned int sa = (sp >> 24) & 0xFF;
                            if (sa == 0) {
                                continue;
                            }
                            if (outline) {
                                /* text-stroke paints the glyph OUTLINE
                                 * only. The 8-direction whole-glyph copies
                                 * (dx/dy = +-sw) filled wide strokes solid
                                 * - a 200px glyph with 1px stroke came out
                                 * as a solid silhouette ("glyph 闂備浇顕ф绋匡耿闁秴纾绘繛鎴炴皑缁?).
                                 * Keep only pixels with a transparent
                                 * neighbour; solid interiors stay empty. */
                                bool edge = false;
                                for (int oy2 = -1; oy2 <= 1 && !edge; ++oy2) {
                                    for (int ox2 = -1; ox2 <= 1 && !edge;
                                         ++ox2) {
                                        if (!ox2 && !oy2) {
                                            continue;
                                        }
                                        int ny2 = yy + oy2, nx2 = xx + ox2;
                                        unsigned int na = 0;
                                        if (ny2 >= 0 && ny2 < g.h &&
                                            nx2 >= 0 && nx2 < g.w) {
                                            na = (g.px[static_cast<size_t>(ny2) * g.w +
                                                         nx2] >>
                                                  24) & 0xFF;
                                        }
                                        if (na == 0) {
                                            edge = true;
                                        }
                                    }
                                }
                                if (!edge) {
                                    continue;
                                }
                            }
                            unsigned int& d =
                                buf[static_cast<size_t>(ty2) * tw + tx2];
                            const unsigned int da = (d >> 24) & 0xFF;
                            const unsigned int oa =
                                sa + da * (255 - sa) / 255;
                            if (oa == 0) {
                                continue;
                            }
                            const unsigned int sr = (sp >> 16) & 0xFF;
                            const unsigned int sg = (sp >> 8) & 0xFF;
                            const unsigned int sb = sp & 0xFF;
                            const unsigned int dr = (d >> 16) & 0xFF;
                            const unsigned int dg = (d >> 8) & 0xFF;
                            const unsigned int db = d & 0xFF;
                            d = (oa << 24) |
                                (((sr * sa + dr * da * (255 - sa) / 255) /
                                  oa) << 16) |
                                (((sg * sa + dg * da * (255 - sa) / 255) /
                                  oa) << 8) |
                                ((sb * sa + db * da * (255 - sa) / 255) / oa);
                        }
                    }
                }
            }
            px += g.advance + lsp;
        }
    }
    /* 闂備浇顕ч柊锝咁焽瑜忕槐鐐寸節閸曨厾顦?line-box 闂備浇顕х换鎺楀磻濞戙垹绠犵€广儱顦伴崵?闂備胶鍎甸崜婵堟暜閹烘绠犻幖娣妼閸氳銇勯幘鍗炵仾闁稿骸閰ｉ弻鐔兼倻濡櫣浠奸梺纭呮缁夌褰侀梺鎼炲劘閸斿海绮婚弽顓熷€甸柛顭戝亝閳锋劙鏌曢崶褍顏€规洖銈稿鎾倷閹绘崼鎾绘⒑鐠囨煡鍙勬繛浣冲懐绀婂┑鐘插缁€?select 闂傚倷鑳堕…鍫ユ晝閵婏妇鐝堕柛顐犲劚閸氳绻濇繝鍌涘櫤闁稿锕㈤幃姗€鎮欓弶鎴犱喊缂備降鍔嶆繛濠囧箖? */
    tx = bx;
    if (align == 1) {
        tx = bx + (bw - tw) / 2;
    } else if (align == 2) {
        tx = bx + bw - tw;
    }
    /* 闂傚倷绀侀幉锟犲礉閺嶎厽鍋＄憸蹇撐ｉ幇鐗堟櫆闂佹鍨版禍?full):miss 闂傚倷绀侀幖顐﹀疮閹惰棄鏄ラ柡宥冨妺缁诲棝鏌熼梻瀵割槮缂佲偓閸℃ɑ鍙忔慨妤€妫楅獮姗€鏌涢妸锔姐仢闁哄备鈧剚鍚嬮柛銉戝啩绮梺璇查閻忔岸鎮￠敓鐘茬畾闁告劦鍠栫粈瀣亜韫囨挻顥犵€涙繈姊绘担瑙勫仩闁稿孩鐓″畷鏇㈠箮閼恒儱浠遍梺闈浥堥弲娑氱矆閸岀偞鐓忓璇″灠閹冲酣藝閳哄懏鐓熼幖娣灮閳洟鎯囨径宀€纾奸柛鎾茬劍閺嗩剛鈧娲忛崕鏌ュ箚閺冨牊鏅查柛銉ｅ妽濮ｅ酣姊哄Ч鍥х労闁搞劌閰ｅ畷姗€鎮欓顐熸櫊濮?*/
    if (!ckey_str.empty()) {
        whaleui_render_t::TextCacheEntry& e = r->text_cache[ckey_str];
        if (e.px.empty() || e.w != tw || e.h != th) {
            /* account the old raster bytes before replacing */
            r->tc_bytes -= e.px.size() * sizeof(unsigned int);
            e.px = std::move(buf);
            e.w = tw;
            e.h = th;
            r->tc_bytes += e.px.size() * sizeof(unsigned int);
        }
        e.last_use = ++r->tc_tick;
        /* bounded cache: a large page (qwen 21k) has hundreds of runs; cap
         * the total raster bytes and evict the least-recently-used entries
         * so it cannot grow unbounded. */
        const size_t kMaxBytes = 16 * 1024 * 1024; /* 16MB */
        while (r->tc_bytes > kMaxBytes) {
            auto victim = r->text_cache.begin();
            for (auto it = r->text_cache.begin(); it != r->text_cache.end();
                 ++it) {
                if (it->second.last_use < victim->second.last_use) {
                    victim = it;
                }
            }
            if (victim == r->text_cache.end()) {
                break;
            }
            r->tc_bytes -= victim->second.px.size() * sizeof(unsigned int);
            r->text_cache.erase(victim);
        }
        src = &e.px;
    } else {
        src = &buf;
    }
    } /* end cache miss: layout + rasterize */
    /* 闂傚倷鐒﹂幃鍫曞礉瀹€鍕９閻犲洩顥嗛搹瑙勫磯闁靛鍊栭崟鍐⒑閸涘﹣绶遍柛鎾寸箞瀹曘垽顢楅崟顒傚幍?闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈濇繛瀵稿帶閻°劑宕?(ascent+descent)闂傚倷绀侀崥瀣熆濮椻偓閹矂宕掑鑲╁姺濡炪倕绻愬Λ娆撳磻濡皷鍋撻崗澶婁壕闂佸憡娲﹂崢濂告嫃?th:th 闂傚倷绀侀幉锟犲礄瑜版帒纾诲鑸靛姂閳ь兛绶氶獮瀣偐閸愯尙锛忔繝鐢靛█濞佳兠洪敃鍋瑰洩顦归柡灞诲€曟晥闁搞儜鍐潥闂?
     * th 闂備浇顕х换鎺楀磻濞戙垹绠犵€广儱顦伴崵?闂備浇顕х€涒晝绮欓幒妞尖偓鍐川鐎涙ê娈?闂傚倷鐒﹂惇褰掑垂婵傚壊鏁嬬憸宥夋晝閵忋値鏁傞柛鈩冪懅閿涙繈姊虹憴鍕姢闁哥喎娼″鎶藉础閻戝棙瀵岄梺闈涚墕閹虫劙宕洪敐澶嬬厱?婵犵數鍋為崹鍫曞箰閹间緡鏁勯柛鈩冪☉閽冪喖鏌ｉ弬鍨倯闁稿鏅滅换娑㈠幢濡ゅ啰顔囧┑顕嗙到椤﹁京妲愰幒鎴犳殕闁告劏鏅╂禒鈺佲攽?闂傚倷绀侀幖顐﹀磹缁嬫５娲Χ婢跺浠遍悷婊冪箻楠炲骞橀鐓庤€垮┑顔矫崥瀣礊瀹ュ鈷戠紒瀣儥閸庡繒绱掔拠宸剳缂?闂傚倷鑳堕崑銊╁磿閺屻儱钃熼柨鐔哄Т閻?input
     * 闂?闂傚倷鑳堕幊鎾诲床閺屻儱围闁归棿鐒﹂崑鍌炴煠閸濄儲鏆╅柍缁樻煥閳规垿鎮╅崣澶屻偐濠碘槅鍋嗛崰鏍蓟閿濆惟闁靛鍎烘禒楣冩⒑缂佹﹩娈曢柟绋垮暱閻ｇ兘宕奸弴鐔蜂汗濡炪倖姊婚幊鎾寸妤ｅ啯鐓曢悘鐐靛亾閻ㄦ垹绱掗悩鍐茬仴妞ゎ亜鍟存俊鍫曞醇椤愩垺顔勬繝鐢靛Л閸?cache miss 婵犵數鍋為崹鍫曞蓟閵娾晩鏁勯柛娑欘劃閸ャ劎绡€婵﹩鍓涢濂告偡濠婂嫬鐏撮柕?闂傚倷绀侀幉锛勭矙閹烘鍨傛繝闈涱儐閸ゅ牓鏌熺€电啸缁惧彞绮欓弻鐔煎箚瑜忛敍宥夋煙閻ｅ苯鈻堥柡灞诲€曟晥闁搞儜鍐ㄐ撻梻浣虹帛閸╁﹪姊介崟顐劷?
     * ty 婵犵數鍎戠徊钘壝洪敂鐐床闁告劦浜栭崑鎾诲垂椤愶綆妫冮悗瑙勬礃閼归箖鍩為幋锕€骞㈤煫鍥ㄦ尫婢?by(婵犵绱曢崑鎴﹀磹閺囥垺鍋夊┑鍌滎焾绾惧潡鎮楅悽鐢点€婇柛瀣崌濡啫鈽夊姣欍劎绱?,闂傚倷绀侀幉锟犳嚌閻愵剛闄勯柡鍐ㄥ€婚崡姘舵煙缂併垹鏋涙俊顐ｏ耿閺屾盯濡烽敐鍛瀴闂佺懓鍢插畷顒冪亱闂佹寧绻傚Λ娑欐櫠椤忓牊鐓欓柤绋跨仛閻ㄦ垵霉閻欏懐鐣电€规洏鍔戦、妤呭礃閵娿儳鐣遍梻鍌欑窔濞佳兾涢弮鍌滅焼濞撴埃鍋撴鐐插暙铻栭柛鎰典簽閿涙粌顪冮妶鍡樺暗闁稿鍋為幈銊︽償閵婏箑浠梺褰掑亰閸樼晫浜搁敃鍌涚厪闁糕剝顨愰煬顒傗偓瑙勬礃閸ㄨ偐绮诲☉娆愬劅闁挎繂娲﹂崯浼存⒒?*/
    {
        int gh = text_glyph_h(r, fs, family, (style & kFontBold) != 0);
        if (gh < 1) {
            gh = th;
        }
        ty = gh <= bh ? by + (bh - gh) / 2 : by;
    }
    /* blend:闂傚倷鑳堕崕鐢稿疾濠婂牆绠伴柟鎯版閻?RGBA(婵犵數鍋為崹鍫曞箰閸濄儳鐭撻柟缁㈠枛閻ゎ噣鏌嶈閸撶喖寮婚敐澶涚稏妞ゆ巻鍋撳┑锛勫帶椤儻顦村┑鐐╁亾閻庢鍠楅悡锟犮€佸☉妯锋斀闁糕檧鏅滈ˉ鎴︽⒒娴ｅ憡鎯堥柡鍫墴楠炴垶鎷呴崷顓犲骄?闂佽崵鍠愮划宥嗙珶鐎ｎ喖鐤鹃柣鎰嚟閻?emoji 婵犵數鍎戠徊钘壝洪敂鐐床闁告洦鍨板Ч鏌ユ煃瑜滈崜鐔煎蓟閵堝棛闄勫璺侯槹閹癸綁姊婚崒姣板牓寮插鍫熸櫖闁归偊鍓﹂悡銉╂煕閳╁喚娈㈡俊?闂?
     * opacity 闂傚倷绀侀幖顐も偓姘卞厴瀹曞綊鎮ч崼鐔峰伎闂佸啿鎼幊搴ｇ不閹存緷褰掓晲閸パ冨闂?闂傚倷绀侀幉锟犲蓟閿濆绀夐幖娣妼閺?婵犵數鍋為崹鍫曞箰婵犳艾钃熺憸蹇曞垝椤撶喎绶為悗锝庡亗濮橈箑鈹戦悙鏉戠仸婵ǜ鍔嶅鍕礋椤栨稑鈧?key,闂傚倷绀佸﹢閬嶃€傛禒瀣；闁规崘绉ぐ鎺撳亹妞ゆ梻鍘ф慨搴♀攽閻橆偄浜惧銈呯箰閹冲繑绂嶉妶鍡欑闁糕剝蓱鐏忣厽绻涢崪鍐瘈闁哄瞼鍠撶划娆忊枎閻愵儷锕傛⒑缁嬪灝顒㈡慨妯稿妼鍗遍柟鎵閸嬫劙鏌ｉ姀銏℃毄缂佲偓閸℃稒鈷戦悶娑掆偓鍏呭?
     * alpha 闂傚倷鑳堕崑銊╁磿閺屻儱钃熼柨鐔哄Т閻?缂傚倸鍊搁崐鎼佸磹瑜版帒绠伴柟闂寸劍閸嬨倝鏌曟繛鐐珔缂佺姵婢橀…鍧楁嚋闂堟稑顫嶆俊銈嗩殢閸ㄥ爼寮婚悢纰辨晞閻犳亽鍔庨悰銏狀渻閵堝啫鈧挾娆㈠璺虹疇婵犻潧顑呯粻鐢告煙閻戞绠栨禍娑㈡⒒?opacity 闂傚倷绀侀幉锟犲蓟閿濆绀夐幖娣妼閺嬩線鏌ｉ幇闈涘闁崇粯姊婚埀顒€绠嶉崕閬嶅箠鎼淬劌鐤炬繛鍡楃贩瑜版帗鏅查柛顐ゅ枔閵嗗﹦绱撴担鐟版暰濠碘€虫喘閸┾偓妞ゆ帊鑳堕埊鏇㈡煥閺囨ê鐏查柛鈹惧亾濡炪倖甯婄粈浣规叏閸ヮ剚鐓欓柤鍝ユ暩椤ｈ尙鈧灚婢樼€氼厼顭囪箛娑樜╅柨鏃傛櫕瑜版瑩姊?
     * GPU 闂備浇宕垫慨宕囨媰閿曞倸鍨傞柟娈垮枟椤愪粙鏌ｉ幇顒佹儓缂佲偓?text_layer,CPU 闂備浇宕垫慨宕囨媰閿曞倸鍨傞柟娈垮枟椤愪粙鏌ｉ幇顒佹儓缂佲偓?framebuffer闂?*/
    std::vector<unsigned int>& fb = g_gpu ? r->text_layer : r->pixels;
    const int fw = g_gpu ? r->fb_w : r->width;
    const int fh = g_gpu ? r->fb_h : r->height;
    const bool fade = opacity < 1.0f;
    for (int yy = 0; yy < th; ++yy) {
        const int fy = ty + yy;
        if (fy < 0 || fy >= fh) {
            continue;
        }
        if (clip && (fy < clip->y || fy >= clip->y + clip->h)) {
            continue;
        }
        for (int xx = 0; xx < tw; ++xx) {
            unsigned int sp = (*src)[static_cast<size_t>(yy) * tw + xx];
            unsigned int sa = (sp >> 24) & 0xFF;
            if (sa == 0) {
                continue;
            }
            if (fade) {
                sa = static_cast<unsigned int>(sa * opacity);
                if (sa == 0) {
                    continue;
                }
                sp = (sa << 24) | (sp & 0x00FFFFFF);
            }
            const int fx = tx + xx;
            if (fx < 0 || fx >= fw) {
                continue;
            }
            if (clip && (fx < clip->x || fx >= clip->x + clip->w)) {
                continue;
            }
            unsigned int& d = fb[static_cast<size_t>(fy) * fw + fx];
            if (sa == 255) {
                /* opaque: direct copy, no src-over math (the common case
                 * for CJK/body glyph centers) */
                d = sp;
                continue;
            }
            const unsigned int da = (d >> 24) & 0xFF;
            if (da == 0) {
                /* destination transparent (the text layer was just cleared):
                 * write through without src-over math */
                d = sp;
                continue;
            }
            const unsigned int oa = sa + da * (255 - sa) / 255;
            if (oa == 0) {
                continue;
            }
            const unsigned int sr = (sp >> 16) & 0xFF;
            const unsigned int sg = (sp >> 8) & 0xFF;
            const unsigned int sb = sp & 0xFF;
            const unsigned int dr = (d >> 16) & 0xFF;
            const unsigned int dg = (d >> 8) & 0xFF;
            const unsigned int db = d & 0xFF;
            d = (oa << 24) |
                (((sr * sa + dr * da * (255 - sa) / 255) / oa) << 16) |
                (((sg * sa + dg * da * (255 - sa) / 255) / oa) << 8) |
                ((sb * sa + db * da * (255 - sa) / 255) / oa);
        }
    }
}

bool sel_range_for(whaleui_render_t* r, lxb_dom_element* el, size_t len,
                   size_t* a, size_t* b, int seq, int sel_lo, int sel_hi)
{    lxb_dom_element* sa = r->sel_anchor_el;
    lxb_dom_element* sf = r->sel_focus_el;
    if (!sa || !sf || !el) {
        return false;
    }
    if (sa == sf) {
        /* collapsed (caret / plain click): nothing is highlighted anywhere */
        if (r->sel_anchor == r->sel_focus) {
            return false;
        }
        if (el == sa) {
            size_t lo = static_cast<size_t>(r->sel_anchor);
            size_t hi = static_cast<size_t>(r->sel_focus);
            if (lo > hi) {
                std::swap(lo, hi);
            }
            *a = lo;
            *b = hi;
            return *a < *b && *a < len;
        }
        return false; /* same-element selection touches only that element */
    }
    /* cross-element: endpoint elements partially, everything between fully */
    if (el == sa) {
        *a = static_cast<size_t>(r->sel_anchor);
        *b = len;
        return *a < len;
    }
    if (el == sf) {
        *a = 0;
        *b = static_cast<size_t>(r->sel_focus);
        return *b > 0;
    }
    if (sel_lo >= 0 && sel_hi >= 0 && seq > sel_lo && seq < sel_hi) {
        *a = 0;
        *b = len;
        return len > 0;
    }
    return false;
}

void sel_seq(whaleui_render_t* r, int* lo, int* hi, const Clip* clip)
{
    *lo = *hi = -1;
    lxb_dom_element* sa = r->sel_anchor_el;
    lxb_dom_element* sf = r->sel_focus_el;
    if (!sa || !sf || sa == sf || !r->tree) {
        return;
    }
    int idx = 0;
    std::function<void(whaleui_layout_node_t*, int, int, bool)> walk =
        [&](whaleui_layout_node_t* n, int off_x, int off_y, bool tc) {
            if (!n->visible) {
                return;
            }
            const int my = idx++;
            if (n->el == sa && *lo < 0) {
                *lo = my;
            }
            if (n->el == sf && *hi < 0) {
                *hi = my;
            }
            /* same transform/fixed rule as paint_node, so the sequence
             * numbers stay aligned with what actually gets painted */
            if (!tc && n->el && !n->is_text) {
                std::string tv = sget(n->style, "transform");
                if (!tv.empty() && tv != "none") {
                    tc = true;
                } else if (sget(n->style, "position") == "fixed") {
                    tc = true;
                }
            }
            /* a selection endpoint outside the repaint region must still
             * receive its sequence number (paint_node does the same), so
             * the in-viewport middle of the selection keeps highlighting.
             * Text runs skip the cull exactly like paint_node. */
            if (!tc && !n->is_text &&
                !(n->el && (n->el == sa || n->el == sf)) &&
                paint_cull(r, n, off_x, off_y, clip)) {
                return;
            }
            if (n->is_text) {
                return;
            }
            /* clipped containers fully off-screen are skipped by paint too */
            std::string ov = sget(n->style, "overflow");
            if (ov == "hidden" || ov == "auto" || ov == "scroll") {
                int y0 = n->border.y + off_y;
                if (y0 + n->border.h <= 0 || y0 >= r->fb_h) {
                    return;
                }
            }
            int child_off = off_y + scroll_delta(r, n);
            for (whaleui_layout_node_t* c = n->first_child; c; c = c->next) {
                walk(c, off_x, child_off, tc);
            }
        };
    walk(r->tree->root, 0, 0, false);
    if (*lo > *hi) {
        std::swap(*lo, *hi);
    }
}

unsigned int accent_hl(whaleui_render_t* r, unsigned int alpha)
{
    unsigned int hl = (alpha << 24);
    auto it = r->theme_vars.find("--accent");
    if (it != r->theme_vars.end()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(it->second.c_str(), &c) == 0) {
            hl = (alpha << 24) | (c & 0x00FFFFFF);
        }
    }
    return hl;
}

void expand_hl_rects(std::vector<TRect>& rects, int lh)
{
    for (size_t i = 0; i < rects.size(); ++i) {
        TRect& rc = rects[i];
        if (rc.h < lh) {
            int d = lh - rc.h;
            rc.y -= d / 2 + 2;
            rc.h = lh;
        } else {
            rc.y -= 2;
            rc.h += 4;
        }
    }
}

void paint_text_selection(whaleui_render_t* r, whaleui_layout_node_t* n,
                          int fs, const std::string& family, bool bold,
                          int off_x, int off_y, int seq, int sel_lo,
                          int sel_hi, const Clip* clip)
{
        size_t a = 0, b = 0;
    int tw = 0, th = 0;
    int ww = run_wrap_w(n);
    text_size(r, n->text, fs, family, bold, &tw, &th, ww);
    if (th <= 0) {
        return;
    }
    int tx = 0, ty = 0;
    text_origin(r, n, n->text, fs, family, bold, &tx, &ty, ww);
    tx += off_x;
    ty += off_y;
    std::vector<TRect> rects = sel_rects(r, n->text, fs, family, bold, a, b,
                                         ww);
    expand_hl_rects(rects, text_line_h(r, fs, family, bold));
    unsigned int hl = sel_hl_color(r, n, 0x3C);
    for (size_t i = 0; i < rects.size(); ++i) {
        fill_rect(r->pixels, r->fb_w, r->fb_h,
                  tx + rects[i].x, ty + rects[i].y,
                  rects[i].w, rects[i].h, hl, clip);
    }
}

unsigned int sel_hl_color(whaleui_render_t* r, whaleui_layout_node_t* n,
                          unsigned int alpha)
{
    std::string v = sget(n->style, "selection-bg");
    if (!v.empty()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(v.c_str(), &c) == 0) {
            return (alpha << 24) | (c & 0x00FFFFFF);
        }
    }
    return accent_hl(r, alpha);
}

void paint_caret(whaleui_render_t* r, int tx, int ty, const std::string& text,
                 int fs, const std::string& family, bool bold,
                 size_t off, const Clip* clip, int wrap_w)
{
    if ((SDL_GetTicks() / 500) & 1) {
        return; /* blink: off half the time */
    }
    int cx = 0, cy = 0, ch = 16;
    caret_pos(r, text, fs, family, bold, off, &cx, &cy, &ch, wrap_w);
    fill_rect(r->pixels, r->fb_w, r->fb_h, tx + cx, ty + cy, 1, ch,
              accent_hl(r, 0xFF), clip);
}

void update_ime_area(whaleui_render_t* r, const std::string& val, int fs,
                     const std::string& family, bool bold, size_t caret,
                     int tx, int ty, int wrap_w)
{
    if (!r->edit_el || !r->window) {
        return;
    }
    int cxx = 0, cyy = 0, chh = 16;
    caret_pos(r, val, fs, family, bold, caret, &cxx, &cyy, &chh, wrap_w);
    int wx = tx + cxx;
    int wy = ty + cyy;
    if (r->fb_w != r->width && r->width > 0) {
        wx = wx * r->width / r->fb_w;
    }
    if (r->fb_h != r->height && r->height > 0) {
        wy = wy * r->height / r->fb_h;
    }
    SDL_Rect rect = {wx, wy, 2, chh};
    if (r->window) {
        struct ImeAreaTask {
            SDL_Window* w;
            SDL_Rect r;
        };
        SDL_Window* ww = r->window;
        ImeAreaTask* t = new ImeAreaTask{ww, rect};
        whaleui_sdl_on_main(
            [](void* p) {
                ImeAreaTask* a = static_cast<ImeAreaTask*>(p);
                SDL_SetTextInputArea(a->w, &a->r, 0);
                delete a;
            },
            t);
    }
}

void paint_text(whaleui_render_t* r, whaleui_layout_node_t* n, int off_x,
                int off_y, int seq, int sel_lo, int sel_hi, const Clip* clip)
{
    /* cull runs fully outside the framebuffer: creating a TTF_Text per run
     * per frame is the dominant paint cost on scroll-heavy pages */
    int ty = n->border.y + off_y;
    if (ty + n->border.h <= 0 || ty >= r->fb_h) {
        return;
    }
    unsigned int color = color_of(n->style, "color", 0xFF000000);
    /* opacity is applied at blend time (draw_text_at's opacity param), NOT
     * baked into the color: baking it made the text_cache key change every
     * animation frame, forcing full text re-rasterization per frame. */
    (void)0;

    int fs = 16;
    std::string fsv = sget(n->style, "font-size");
    if (!fsv.empty()) {
        /* clamp()/vw font-sizes (q21k h3/glyph) resolve like the layout
         * pass - atoi treated "clamp(30px,...)" as 0 and drew 16px */
        int f = font_size_px(r, fsv);
        if (f > 0) {
            fs = f;
        }
    }
    std::string family = sget(n->style, "font-family");
    /* font-weight: bold/bolder/600-900 render bold; font-style italic/
     * oblique render italic (TTF style bits, per-tag UA defaults make
     * <strong>/<em> work without any page CSS) */
    std::string fw = sget(n->style, "font-weight");
    bool bold = fw == "bold" || fw == "bolder" ||
                (!fw.empty() && std::atoi(fw.c_str()) >= 600);
    std::string fst = sget(n->style, "font-style");
    int style = (bold ? kFontBold : 0) |
                ((fst == "italic" || fst == "oblique") ? kFontItalic : 0);
    /* text-align aligns within the parent element's content box; inline
     * line members (mixed with siblings) stay left-aligned at their laid
     * out x so the line flows as one run sequence */
    std::string ta = sget(n->style, "text-align");
    int align = 0;
    if (ta == "center") {
        align = 1;
    } else if (ta == "right") {
        align = 2;
    }
    if (n->in_inline) {
        align = 0;
    }
    /* text-transform + letter-spacing apply to the painted text (ASCII
     * transforms keep the byte length, so selection offsets stay valid) */
    std::string shown = n->text;
    std::string tt = sget(n->style, "text-transform");
    if (!tt.empty() && tt != "none") {
        apply_text_transform(shown, tt);
    }
    int lsp = 0;
    std::string lsv = sget(n->style, "letter-spacing");
    if (!lsv.empty() && lsv != "normal") {
        float v = static_cast<float>(std::atof(lsv.c_str()));
        lsp = static_cast<int>(lsv.find("em") != std::string::npos
                                   ? v * fs
                                   : v);
    }
    whaleui_layout_node_t* box = n;
    if (n->parent && !n->parent->is_text) {
        box = n->parent;
    }
    paint_text_selection(r, n, fs, family, bold, off_x, off_y, seq, sel_lo,
                         sel_hi, clip);
    bool wrap = sget(n->style, "white-space") != "nowrap";
    /* paint at the run's laid-out position: block runs sit at the parent
     * content origin, inline-line runs at their accumulated x. The wrap
     * width is run_wrap_w: the block line-box remainder (inline ancestors
     * skipped, mirroring the layout pass) - the parent-box estimate here
     * wrapped an inline <code> run at its own content width (~= the text
     * width) and painted the second line over the text below. */
    int avail_w = run_wrap_w(n);
    if (avail_w < 1) {
        avail_w = 1;
    }
    /* text origin must match paint_text_selection (both center the glyphs
     * in the run box via text_origin); painting at border.y while the
     * selection wash centers left textarea glyphs shifted half a line
     * below their highlight. */
    int tx0 = n->border.x + off_x;
    int ty0 = n->border.y + off_y;
    {
        int ox = 0, oy = 0;
        text_origin(r, n, shown, fs, family, bold, &ox, &oy, avail_w);
        tx0 = ox + off_x;
        ty0 = oy + off_y;
    }
    int gh_box = text_glyph_h(r, fs, family, bold);

    /* text-shadow: offset copy (plus 2 spread layers approximating the
     * blur) painted under the glyphs. The glyph raster is cached per
     * element, so the copies only re-tint at blend time. */
    std::string tsh = sget(n->style, "text-shadow");
    if (!tsh.empty() && tsh != "none") {
        int sox = 0, soy = 0, sblur = 0;
        unsigned int scol = 0;
        if (parse_shadow_any(tsh, sox, soy, sblur, scol) == 0) {
            unsigned int sa = (scol >> 24) & 0xFF;
            if (sblur > 0) {
                for (int k = 1; k <= 2 && k <= sblur; ++k) {
                    unsigned int ka =
                        static_cast<unsigned>(sa * (sblur - k + 1) /
                                              (sblur + 1));
                    unsigned int sc = (ka << 24) | (scol & 0x00FFFFFF);
                    draw_text_at(r, shown, tx0 + sox - k, ty0 + soy - k,
                                 avail_w, gh_box, fs, family, sc,
                                 style, align, n->el, clip, lsp, wrap,
                                 n->opacity);
                }
            }
            draw_text_at(r, shown, tx0 + sox, ty0 + soy, avail_w,
                         gh_box, fs, family, scol, style, align, n->el,
                         clip, lsp, wrap, n->opacity);
        }
    }
    /* -webkit-text-stroke: 8-direction outline copies (stroke width is
     * usually 1px; outline color replaces the transparent fill) */
    std::string tsk = sget(n->style, "-webkit-text-stroke");
    if (tsk.empty()) {
        tsk = sget(n->style, "text-stroke");
    }
    if (!tsk.empty() && tsk != "none") {
        std::vector<std::string> toks = split_space2(tsk);
        int sw = 1;
        unsigned int scc = 0xFF000000;
        if (!toks.empty()) {
            char* end = nullptr;
            float w = std::strtof(toks[0].c_str(), &end);
            if (end != toks[0].c_str()) {
                sw = w > 0 ? static_cast<int>(w) : 1;
            }
            std::string cstr;
            for (size_t i = 1; i < toks.size(); ++i) {
                if (!cstr.empty()) {
                    cstr += ' ';
                }
                cstr += toks[i];
            }
            if (!cstr.empty()) {
                whaleui_render_parse_color(cstr.c_str(), &scc);
            }
        }
        for (int dy = -1; dy <= 1; ++dy) {
            for (int dx = -1; dx <= 1; ++dx) {
                if (!dx && !dy) {
                    continue;
                }
                draw_text_at(r, shown, tx0 + dx * sw, ty0 + dy * sw,
                             avail_w, gh_box, fs, family, scc,
                             style, align, n->el, clip, lsp, wrap,
                             n->opacity, true);
            }
        }
    }

    /* the run's own box carries the scroll shift. ty0 already centers the
     * glyphs in the run box (text_origin, same geometry as the selection
     * wash); pass bh = the glyph box so draw_text_at does NOT center a
     * second time - double-centering (line height vs glyph box) pushed
     * textarea glyphs half a line below their highlight. */
    draw_text_at(r, shown, tx0, ty0, avail_w, gh_box,
                 fs, family, color, style, align, n->el, clip, lsp, wrap,
                 n->opacity);

    /* text-decoration: underline / line-through lines over the box (width
     * = the run's own text extent, clamped to the line remainder) */
    std::string td = sget(n->style, "text-decoration");
    if (!td.empty() && td != "none") {
        int lw = 0;
        for (size_t i = 0; i < shown.size();) {
            unsigned char c2 = static_cast<unsigned char>(shown[i]);
            if (c2 < 0x80) {
                lw += fs / 2;
                ++i;
            } else {
                size_t n2 = (c2 & 0xE0) == 0xC0 ? 2 : (c2 & 0xF0) == 0xE0 ? 3 : 4;
                lw += fs;
                i += n2;
            }
        }
        if (lw > avail_w) {
            lw = avail_w;
        }
        if (lw < 1) {
            lw = 1;
        }
        if (td.find("underline") != std::string::npos) {
            fill_rect(r->pixels, r->fb_w, r->fb_h, tx0,
                      ty0 + n->border.h - 2, lw, 1, color, clip);
        }
        if (td.find("line-through") != std::string::npos) {
            fill_rect(r->pixels, r->fb_w, r->fb_h, tx0,
                      ty0 + n->border.h / 2, lw, 1, color, clip);
        }
    }
}

void text_origin(whaleui_render_t* r, whaleui_layout_node_t* n,
                 const std::string& text, int fs, const std::string& family,
                 bool bold, int* tx, int* ty, int wrap_w)
{
    int tw = 0, th = 0;
    text_size(r, text, fs, family, bold, &tw, &th, wrap_w);
    /* vertical centering, clamped to non-negative: the layout box height
     * (estimated wrap lines) can come out shorter than the painted text
     * (per-glyph wrap), and a negative (border.h - th)/2 pushes the first
     * line above the box - invisible text, caret drifting below it */
    if (n->is_text) {
        *tx = n->border.x;
        int dy = (n->border.h - th) / 2;
        *ty = n->border.y + (dy > 0 ? dy : 0);
    } else {
        *tx = n->content.x;
        /* empty value (th == 0): top-aligned, not centered - centering
         * put the caret of an empty textarea at the bottom of the box */
        int dy = th > 0 ? (n->content.h - th) / 2 : 0;
        *ty = n->content.y + (dy > 0 ? dy : 0);
    }
}

/* wrap width a text run paints at (draw_text_at's avail_w): the parent
 * content right edge minus the run's laid-out x; 0 when the run never
 * wraps (white-space: nowrap) */
int run_wrap_w(whaleui_layout_node_t* n)
{
    if (!n) {
        return 0;
    }
    if (sget(n->style, "white-space") == "nowrap") {
        return 0;
    }
    whaleui_layout_node_t* box =
        (n->parent && !n->parent->is_text) ? n->parent : n;
    /* an inline element's text follows the OUTER line box: its wrap width
     * is the block ancestor's remaining line space, not the inline box's
     * own content width (~= the text width - wrapping exactly at it split
     * a single <code> line into two, the second drawing over the line
     * below). Only plain inline boxes are skipped; inline-block (button/
     * input/textarea) wraps at its own content width. Must mirror the
     * layout pass (layout.cpp, text-run avail walk). */
    while (box && !box->is_text &&
           sget(box->style, "display") == "inline" && box->parent &&
           !box->parent->is_text) {
        box = box->parent;
    }
    std::string disp = sget(box->style, "display");
    if (disp == "flex" || disp == "inline-flex") {
        /* a flex item's text does not soft-wrap (browser behavior): it
         * paints at its laid-out width. Wrapping against the container's
         * content edge split a 2-char checkbox label into 3 lines (the
         * parent box is narrower than the checkbox+label pair). */
        return n->border.w > 0 ? n->border.w : 0;
    }
    int w = box->content.x + box->content.w - n->border.x;
    return w > 0 ? w : 0;
}

/* byte offset of the text under (px,py), relative to the text top-left.
 * Uses the shared program-side layout, so wrapped lines, control
 * characters and both renderers (full/stb) behave identically. */
size_t byte_at_text(whaleui_render_t* r, const std::string& text, int fs,
                    const std::string& family, bool bold, int px, int py,
                    int wrap_w)
{
    if (text.empty()) {
        return 0;
    }
    int lh = text_line_h(r, fs, family, bold);
    if (lh <= 0) {
        lh = fs > 0 ? fs : 16;
    }
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    if (L.lines.empty()) {
        return 0;
    }
    if (px < 0) {
        px = 0;
    }
    if (py < 0) {
        py = 0;
    }
    size_t li = static_cast<size_t>(py / lh);
    if (li >= L.lines.size()) {
        li = L.lines.size() - 1;
    }
    const TextLayoutLine& ln = L.lines[li];
    const size_t nc = L.map.size();
    int xacc = 0;
    for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
        int w = gw(disp_cp_at(L, ci), st);
        if (px < xacc + w / 2) {
            return L.map[ci];
        }
        xacc += w;
    }
    /* past the line's right edge: the LINE end (not the whole text end) */
    return (ln.cend < nc) ? L.map[ln.cend] : text.size();
}
