/* render_text.cpp - text rasterization (SDL3_ttf full / stb_truetype lite+minimal), selection, caret and IME. */
// Generated by tools: split from render.cpp (step 5 maintenance).
// Shared helpers: render_internal.h.

#include "render/render_internal.h"
#include "font/font.h"
#include <SDL3/SDL.h>
#ifdef WHALEUI_BUILD_FULL
#include <SDL3_ttf/SDL_ttf.h>
#else
/* stb_truetype text backend for lite/minimal builds (header-only) */
#define STB_TRUETYPE_IMPLEMENTATION
#include <stb/stb_truetype.h>
#endif

#include <lexbor/dom/dom.h>

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <functional>
#include <string>
#include <vector>
std::vector<std::string> split_families(const std::string& s)
{
    std::vector<std::string> out;
    const char* p = s.c_str();
    while (*p) {
        while (*p == ' ' || *p == '\t' || *p == ',') {
            ++p;
        }
        if (!*p) {
            break;
        }
        const char* start = p;
        bool quoted = *p == '"' || *p == '\'';
        if (quoted) {
            ++start;
            ++p;
            while (*p && *p != '"' && *p != '\'') {
                ++p;
            }
            out.emplace_back(start, static_cast<size_t>(p - start));
            if (*p) {
                ++p;
            }
            continue;
        }
        while (*p && *p != ',') {
            ++p;
        }
        std::string fam(start, static_cast<size_t>(p - start));
        size_t b = fam.find_first_not_of(" \t");
        size_t e = fam.find_last_not_of(" \t");
        if (b != std::string::npos) {
            out.push_back(fam.substr(b, e - b + 1));
        }
    }
    return out;
}

/* --- 缂傚倷绀侀鍛搭敄閸涱垵濮虫い鎾卞灩缁€鍐煕濞戝崬鏋熼柣搴櫍閺岋繝宕奸銏狀潽闁汇埄鍨遍幑鍥箖?闂備礁鎽滈崕鎰板垂椤栨粎鍗氶悗鐢电《閸嬫捇宕烽鐐版埛濡?full 濠?stb 闂備胶顭堢换妤佺椤掑嫬鏋?---
 * 闂備礁婀遍崕銈囨暜閻愬瓨娅犳俊銈呭暞鐎氬鏌ｉ弮鍥у惞闁?UTF-8 闂佽崵鍠愰悷杈╁緤閸ф鍋夋繝濠傜墕杩濇繛杈剧悼閹虫挻绂掑鈧弻娑㈠箳閺囩喓銆愰梺鐑╁閸涱垳鐣堕梺鎸庢磵閸嬫挻銇勯敂瑙勬珚闁诡喖鐖煎畷閬嶅即閻樺灚鍠涢梻浣告贡椤牓藝椤栫偛纾挎慨妯块哺椤洟鏌ｅΟ鐑樷枙闁哥喎绉归獮鏍ㄦ綇閹屾喘濠?soft-wrap;
 * 婵犵數鍋為幐绋款嚕閸洘鍋傞悗锝庡厸濞?SDL3_ttf / stb_truetype)闂備礁鎲￠悷顖涚濠靛浜瑰ù锝呮贡閻熻绻涢幋鐏活亞绮堢€ｎ喗鍊垫繛鎴炵懐濞堟ɑ銇勯幋婊嗗厡闁逞屽墰椤㈠﹤螞閸曨厸鍋撶憴鍕枙鐎规洖鐖奸幃娆撳礈娴ｈ鍟€濠电偞鍨堕幐鍛婎殽閹间焦鍋ょ憸鎴﹀Φ閹版澘顫呴柕蹇嬪灩缁楋繝姊洪崨濠傜缂傚牅鍗抽崺鈧?
 * 缂傚倸鍊搁崐褰掓偋閻愬灚顐芥い鎰剁畱閺嬩線鏌℃径瀣靛劌闁?caret/selection/hit-test)濠电偞鍨堕幐绋棵规搴″灊妞ゆ牜鍋涚粈鍡涙偣閸濆嫭鎯堢憸鐗堢懇閺岋綁锝為鈧俊濂告煙椤旇姤灏扮紒瀣樀閸┾偓妞ゆ帊鑳堕々鐑芥煕婵犲嫬娅忛柡鈧禒瀣仺妞ゆ牗鑹鹃弳娆撴煟?
 * 闂備礁婀遍。浠嬪磻閹捐秮?full 濠?lite/minimal 闂備焦鐪归崝宀€鈧凹鍘奸悾鐑芥嚑椤掍礁浠掗柣蹇曞仩閸嬫劗绮旂€靛摜纾介柛鎰劤閺嬫棃鏌嶈閸忔盯鎮為敂鐐殰闁割偅娲栫粈鍡涙偣妤︽寧顏犻柟鐣屽枔缁辨帒螖鐎ｎ剛鏆㈠銈冨灪閸ㄥ墎绮欐径鎰紶闁告洦鍘藉▓顕€姊虹粙璺ㄧ疄闁告柨顑囩划鈺呭箻椤旇棄娈滃┑鐑囩秵閸忔﹢宕?*/

struct TextLayoutLine { size_t cstart; size_t cend; int w; };
struct TextLayout {
    std::string disp;          /* 闂備礁鎼€氼剚鏅舵禒瀣︽慨妯挎硾濡﹢鏌涢妷锝呭闁?闂備胶顢婇惌鍥礃閵娧冨箑闂佽瀛╃粙鎺椼€冮崼銉晞濞达綀妗ㄥ▽顏堟煛閸モ晛浠х痪?缂傚倷绀侀ˇ顖炩€﹀畡鎵虫瀺閹兼番鍔岀憴锕傚箹鏉堝墽绋婚柣?UTF-8 */
    std::vector<size_t> map;   /* disp 婵犳鍣徊鐣屾崲閹扮増鍋ょ憸蹇曞垝椤撱垺鏅濆ù锝囨嚀闂傤垶姊?闂?闂備礁鎲￠…鍥窗閹版澘鍑犻柛鎰靛枛鐎氬銇勯幒鍡椾壕闂佺儵濮嶉崶銊ユ疅闂佺鏈惌顕€鎮炴繝鍕＜?*/
    std::vector<size_t> dbytes;/* disp 婵犳鍣徊鐣屾崲閹扮増鍋ょ憸蹇曞垝椤撱垺鏅濆ù锝囨嚀闂傤垶姊?闂?disp 闂佽瀛╃粙鎺椼€冩径瀣╃箚妞ゆ挶鍨圭壕濠氱叓閸ャ劍闀?*/
    std::vector<TextLayoutLine> lines;
    int tw, th;
};
/* 闂備礁鎲￠〃鍡椕洪弽顓熷仱鐟滃繒鍒掗銏℃櫇闁逞屽墴瀹曟洖顫濇潏顭戞綗闂佺粯锚濡﹪宕?婵犵數鍋為幐绋款嚕閸洘鍋傞悗锝庡厸濞岊亪鏌涚仦鐐殤闁哄绮欓弻?闂佹眹鍩勯崹浼村疮椤愶附鍎戞い鎺戝閸婄粯銇勯幙鍕？闁绘柨鎳愰埀?ASCII 闂佽崵濮嶉崟顐缂備焦鍞绘俊鍥焵? */
typedef int (*TextGlyphFn)(unsigned int cp, void* st);

/* 闂佽崵鍠愰悷杈╁緤閸ф鍋夋繝濠傜墕閸屻劑鏌ｉ弬鎸庡暈闁诲寒鍣ｉ弻锟犲醇椤愩垹骞愰柣鐘冲姉閸犳牕顕ｆ导鏉戠鐟滃绂掑☉銏＄厸闁稿本纰嶆径鍕節閳? \r 闂傚鍋勫ú銊╁疾椤愶箑姹?CRLF),\n 闂備礁鎼崑鍡涘矗閳ь剚銇?\t 闂佽绻掗崑鐐裁洪弽顐ｎ潟闁瑰鍋熼埢?4 缂傚倷绀侀惉濂稿磿閵堝鍋?
 * 闂備胶顭堢换鎴濓耿閸︻厾绀?C0/DEL 闂備胶顢婇惌鍥礃閵娧冨箑闂佽瀛╃粙鎺椼€冮崼銉晞濞达絿鍎ゅ畷澶愭倵閸︻厼啸缂?濠电偞鍨堕幐鍝ョ矓閺夋垹鏆﹂柣妤€鐗婃刊?;婵犳鍣徊鐣屾崲鐎ｎ喗鐓傛繝濠傜墕閸欏﹪鏌涢幘妞炬缁敻鏌ｆ惔銏⑩姇妞ゃ劌鐗撻、鏍ㄦ媴閻戞ê顎涢梺鍝勵槼濞夋洜绮旈崸妤佺厱婵☆垳鍘ч弸搴∶瑰鍐╂喐缂侇喗鏌ㄦ晥闁搞儻绲芥禍?*/
static void layout_decode(const std::string& text, TextLayout& L)
{
    const unsigned char* sb =
        reinterpret_cast<const unsigned char*>(text.c_str());
    size_t i = 0;
    while (i < text.size()) {
        size_t start = i;
        unsigned char c = sb[i];
        unsigned int cp = c;
        int len = 1;
        if (c >= 0x80) {
            if ((c & 0xE0) == 0xC0 && i + 1 < text.size()) {
                cp = ((c & 0x1F) << 6) | (sb[i + 1] & 0x3F);
                len = 2;
            } else if ((c & 0xF0) == 0xE0 && i + 2 < text.size()) {
                cp = ((c & 0x0F) << 12) | ((sb[i + 1] & 0x3F) << 6) |
                     (sb[i + 2] & 0x3F);
                len = 3;
            } else if ((c & 0xF8) == 0xF0 && i + 3 < text.size()) {
                cp = ((c & 0x07) << 18) | ((sb[i + 1] & 0x3F) << 12) |
                     ((sb[i + 2] & 0x3F) << 6) | (sb[i + 3] & 0x3F);
                len = 4;
            } else {
                cp = 0; /* malformed byte: skip */
            }
        }
        i += len;
        if (cp == '\r') {
            continue;
        }
        if (cp == '\n') {
            L.disp += '\n';
            L.dbytes.push_back(L.disp.size() - 1);
            L.map.push_back(start);
            continue;
        }
        if (cp == '\t') {
            for (int k = 0; k < 4; ++k) {
                L.disp += ' ';
                L.dbytes.push_back(L.disp.size() - 1);
                L.map.push_back(start);
            }
            continue;
        }
        if (cp < 0x20 || cp == 0x7F) {
            continue;
        }
        L.disp.append(text, start, static_cast<size_t>(len));
        L.dbytes.push_back(L.disp.size() - static_cast<size_t>(len));
        L.map.push_back(start);
    }
}

/* 闂佽崵鍠愰悷杈╁緤閸ф鍋夋繝濠傜墕閸欏﹪鏌涢幘妞炬缁敻姊洪崫鍕偓绋棵洪敃鈧敃銏ゆ偋閸懇鏋栧銈嗘尵閸嬬喖骞楅悢铏圭＜婵°倕顑呴々顒勬煕鐏炶濡兼い?ci 濠电姰鍨煎▔娑氣偓姘煎枛閳绘捇骞嬮敂钘夊壓婵炶揪绲介幖顐ｇ?*/
static unsigned int disp_cp_at(const TextLayout& L, size_t ci){
    size_t b0 = L.dbytes[ci];
    size_t b1 = (ci + 1 < L.dbytes.size()) ? L.dbytes[ci + 1] : L.disp.size();
    const unsigned char* u =
        reinterpret_cast<const unsigned char*>(L.disp.c_str());
    unsigned char c = u[b0];
    if (c < 0x80) {
        return c;
    }
    if ((c & 0xE0) == 0xC0 && b0 + 1 < b1) {
        return ((c & 0x1F) << 6) | (u[b0 + 1] & 0x3F);
    }
    if ((c & 0xF0) == 0xE0 && b0 + 2 < b1) {
        return ((c & 0x0F) << 12) | ((u[b0 + 1] & 0x3F) << 6) |
               (u[b0 + 2] & 0x3F);
    }
    if ((c & 0xF8) == 0xF0 && b0 + 3 < b1) {
        return ((c & 0x07) << 18) | ((u[b0 + 1] & 0x3F) << 12) |
               ((u[b0 + 2] & 0x3F) << 6) | (u[b0 + 3] & 0x3F);
    }
    return 0;
}

/* 闂?wrap_w 闂備礁鎼崑鍡涘矗閳ь剚銇?闂傚倷绶￠崑鍛村礉閺囥垺鍋ょ憸蹇曞垝椤撱垺鏅滈柛鎾楀嫮鍔搁梺鑽ゅС鐠佹煡鍩€椤掍礁澧柛鐔风Ч楠?闂佺儵鍓濈敮鎺楀箠鎼搭煈鏁婇柡鍐ㄧ墕缁秹鎮归搹鐟板妺缂佲偓閳ь剟姊绘笟鍥т簮闁稿鎹囬弻娑㈠箳閺傛鏆┑鐐存尭閻栫厧鐣烽妷锔藉劅婵犻潧鐗滄导鍥ㄧ箾閹寸偞鎯勫ù婊呭仱閸╃偤寮介鐐插敤?闂?
 * wrap_w <= 0 = 濠电偞鍨堕幐鍝ョ矓閻戣姤瀚冮悗锝庡枛缁犳煡鏌曡箛銉хУ闁衡偓娴犲鐓忛柛鈩冾殔閳ь剛鏅幑銏ゅ箣閿曗偓閻愬﹪鏌ｉ幇顒夊殶婵″眰鍔戦幃璺衡槈濡偐浼囧┑鐐茬墛閸ㄥ灝顕ｆ导鏉戠鐟滃绂掑☉銏″€垫繛鎴炵懐濞堟ɑ銇勯幋婊呯獢闁瑰磭濞€瀹曟﹢濡搁敂鎯у毐 [cstart,cend) 濠电偞鍨堕幐鍛婎殽閹间礁纾挎慨妯块哺椤洟鏌ｅΟ鐑樷枙闁哥喎绉归弻?*/
static void layout_wrap(TextLayout& L, int wrap_w, int lh,
                        TextGlyphFn gw, void* st)
{
    const size_t nc = L.map.size();
    size_t ci = 0;
    while (ci < nc) {
        size_t ls = ci;
        int wacc = 0;
        size_t last_sp = static_cast<size_t>(-1);
        int wacc_at_sp = 0;
        bool nl = false;
        while (ci < nc) {
            const char dch = L.disp[L.dbytes[ci]];
            if (dch == '\n') {
                nl = true;
                break;
            }
            int w = gw(disp_cp_at(L, ci), st);
            const bool is_sp = dch == ' ';
            if (wrap_w > 0 && wacc > 0 && wacc + w > wrap_w) {
                /* 闂佺儵鍓濈敮鎺楀箠鎼搭煈鏁?濠电偞娼欓崥瀣晪闂佸憡蓱閻╊垰鐣烽崼鏇熷€烽悶娑掆偓鍏呭闂侀€炲苯澧寸€规洘宀搁幃褔宕奸悢鍓佸笡闂備礁鎲￠懝鍓ц姳閼测晝鍗氶悗娑欘焽閳绘梹銇勮箛鎾搭棏闁轰礁瀚伴弻鈥愁吋婢跺绱电紓浣哄缂嶄礁鐣?闂佽崵濮村ú銈囩矓閼告娈介柛銉墮濡ɑ銇勯幘顖涱潑闁衡偓? */
                size_t br = ci;
                int bw = wacc;
                if (last_sp != static_cast<size_t>(-1)) {
                    br = last_sp + 1;
                    bw = wacc_at_sp;
                }
                if (br <= ls) { /* 缂傚倷绀侀惉濂稿磿閵堝鍋嬮柟闂寸閸欏﹥銇勯弽銊х闁衡偓閽樺）娑㈡晲閸℃瑥鈷堥梺鐑╁墲閸ㄧ敻顢氶敐澶婄＜婵ê宕悡?闂備礁鎼崑鍡涘储閻撳函鑰挎い蹇撴储娴滃綊鏌熼幆褍鏆辨い銈呮嚇閹鈽夊▎妯荤暭濡炪倖鍨崇欢姘暦?*/
                    br = ci;
                    bw = wacc;
                }
                L.lines.push_back({ls, br, bw});
                if (bw > L.tw) {
                    L.tw = bw;
                }
                L.th += lh;
                ci = br;
                break;
            }
            wacc += w;
            if (is_sp && wrap_w > 0) {
                last_sp = ci;
                wacc_at_sp = wacc;
            }
            ++ci;
        }
        if (ci >= nc || nl) {
            /* 闂傚倷绶￠崑鍛ｉ幒鏃€顐芥い鎰╁€栭崑妯尖偓鍏夊亾闁告劑鍔嶉鍥⒑缂佹ê绗掑褍娴烽崚鎺楀Ω閳轰胶楠?闂備礁鎼崐绋棵洪敃鈧敃銏″閺夋垵鐝樺銈嗗姂閸ㄥ宕弻銉︾厵閻庢稒顭囨晶顒佷繆椤栨凹妲告い鏇秬缁犳盯寮崹顔惧搸闂? */
            L.lines.push_back({ls, ci, wacc});
            if (wacc > L.tw) {
                L.tw = wacc;
            }
            L.th += lh;
            if (nl) {
                ++ci; /* 闂佽崵濮撮幖顐︽偪閸モ晜宕?\n */
            }
        }
    }
    /* 闂備礁鎼崐绋棵洪敃鈧敃銏ゆ偋閸埄娴?\n 缂傚倸鍊烽悞锕傚箰閹间焦鍋勬い鎺戝缁?闂備礁鎼悧婊堝磻閸曨垱鍋勬い鎺嶇劍娴溿倖淇婇婊呭笡缂佺姵甯掗埥澶愬箻椤栨矮澹曞┑鐐村灦閹尖晜绂嶉悙鍝勭厴闁哄稁鍋呴崑?缂傚倸鍊搁崐褰掓偋閻愬灚顐芥い鎰剁畱闂傤垶鏌曟繛鐐珔婵炲拑绻濋弻娑滅疀閹垮啯效闂佺粯鐗紞浣哥暦閹存繍鐓ラ柛鎰ㄦ櫈閸氼偊姊洪崫鍕闁稿鎹囬弻娑橆潩椤掑倸鍤紓浣规煥椤曨參骞?闂?
     * 濠电偞鍨堕幐鍝ョ矓閻ゎ垱锛傚┑?text_size/缂傚倸鍊烽悞锕傛晪闂?闂備礁鎲＄粙鎺楀垂濠靛鍤堥柟瀵稿С閻掑﹪鏌涘Δ鍐ㄤ户婵絽鐬肩槐鎺楁偐閻愭垝娌紓浣规煥椤曨參骞?闂備礁鎲￠崝鏇㈠箠鎼搭煈鏁婇柟鐗堟緲閺嬩胶绱撻崼銏犘ョ紒澶娿偢閺屾稓鈧綆浜炵粻锝囩磼濡も偓閹虫ɑ淇?*/
    if (!L.lines.empty() && !L.disp.empty() && L.disp.back() == '\n') {
        L.lines.push_back({nc, nc, 0});
        L.th += lh;
    }
}

static TextLayout layout_text(const std::string& text, int wrap_w, int lh,
                              TextGlyphFn gw, void* st)
{
    TextLayout L = {};
    layout_decode(text, L);
    layout_wrap(L, wrap_w, lh, gw, st);
    return L;
}

/* --- 闂備礁鎼崐绋棵洪敃鈧敃銏ゅ级濡潧婀遍埀顒婄秵娴滃爼宕?闂備礁鎲＄粙鎺楀垂濠靛鍤?闂傚倷绶￠崑鍕囬幍顔瑰亾?闂備胶顭堢换妤佺椤掑嫬鏋侀柕鍫濇礌閸嬫捇宕烽鐐版埛濡?闂備胶纭堕弲鐐差浖閵娧嗗С妞ゆ帊鑳堕埢鏂库攽閻樺弶澶勬俊妞煎姂閺岋綁濡搁妷銉紓濡炪們鍨洪崹褰掑极椤曗偓瀹曟﹢濡歌閹? --- */

/* 闂佽瀛╃粙鎺椼€冮崨瀛樺殝闁绘鐗婃刊瀵糕偓骞垮劚閹冲繒绮?缂傚倸鍊烽懗鍫曞窗瀹ュ洨鍗氶柟缁㈠枛鐟欙箓骞栨潏鍓хУ濞寸厧鍊块弻鐔煎箒閹烘垵濮庨悷?full 濠?stb 闂備胶顭堢换妤佺椤掑嫬鏋?:闂備胶顭堢粔瀵告崲閹烘梻鐭嗛悘鐐插⒔閳?0xAARRGGBB;
 * colored=true 闂備礁鎼崯鍐测枖濞戙垹纾挎慨妯块哺椤洟鏌ｅΟ鐑樻儓婵炲牅鍗抽幃浠嬵敍閵堝洨鏆ゅ銈冨€撶欢姘跺箠?闁荤喐绮嶆竟瀣疾閻愬鐝?emoji),闂備礁鎲￠悢顒傜不閹达箑鍨傛い鏍仜绾句粙鐓崶銊︾妞わ箑宕埥澶愬箻閾忣偅鍎撴繝鈷€鍛枅鐎殿喗鐓￠、娑樷攽閸♀晜顥?闂?alpha闂?
 * xoff/yoff 濠电偞鍨堕幑浣割浖閵娧呯闁告稒娼欓悙濠囨煕閹炬瀚妶鏌ユ煟?pen+baseline 闂備焦鐪归崝宀€鈧凹鍠氶崚鎺楊敍閻愯尙顦柣鐘荤細濡椼劑鎮炴繝鍕＜濠㈣泛顑囧﹢浠嬫煃?*/
struct GlyphImg
{
    int w, h;
    int xoff, yoff;
    int advance;
    bool colored;
    std::vector<unsigned int> px;
};

/* full: 闂備礁鎲￠〃鍡椕洪弽顓熷仱鐟滃繒鍒掗銏℃櫇闁逞屽墴椤㈡瑩寮埀顒勫箚閺冨牊鏅滈柣锝呰閸嬬偤姊绘担鐟扮祷缂佺粯甯掗埢鎾诲箣閻愮鏋栨繝鐢靛С閼冲爼鎮烽幘缁樼厸?闂佽瀛╃粙鎺楀Φ閻愮數绀婇悗锝庡亞椤?render_get_font 闂? */
struct TextMeasureCtx
{
    whaleui_render_t* r;
    int fs;
    std::string family;
    bool bold;
};
#ifdef WHALEUI_BUILD_FULL
static int glyph_ttf(unsigned int cp, void* st);
#else
static int glyph_stb(unsigned int cp, void* st);
#endif

#ifdef WHALEUI_BUILD_FULL

/* open a registered font file (no fallback chain, no cache); returns the
 * TTF_Font at an arbitrary size (callers set the real size via
 * ensure_font_state). NULL when the family is not registered. */
static TTF_Font* open_registry_font(const std::string& family)
{
    whaleui_font_registry* reg = whaleui_font_registry_get();
    for (size_t i = 0; i < reg->count; ++i) {
        if (std::strcmp(reg->fonts[i].family, family.c_str()) == 0) {
            SDL_IOStream* io = nullptr;
            if (reg->fonts[i].path) {
                io = SDL_IOFromFile(reg->fonts[i].path, "rb");
            } else if (reg->fonts[i].data && reg->fonts[i].len) {
                io = SDL_IOFromMem(const_cast<unsigned char*>(
                                       reg->fonts[i].data),
                                   reg->fonts[i].len);
            }
            if (!io) {
                return nullptr;
            }
            return TTF_OpenFontIO(io, true, 16.0f);
        }
    }
    return nullptr;
}

/* apply (size, style) to a font only when it changed (SDL3_ttf rebuilds
 * its glyph cache on either call, so skipping the no-op calls matters on
 * mixed-size pages) */
static void ensure_font_state(whaleui_render_t* r, TTF_Font* font, int size,
                              int style)
{
    auto it = r->font_state.find(font);
    if (it != r->font_state.end() && it->second.first == size &&
        it->second.second == style) {
        /* cached as (size, style): trust it ONLY if the font really is at
         * that size. A stale entry (recorded 48 while the font was later
         * reopened/restyled at 16 by another path) would skip SetFontSize
         * and rasterize CJK at the wrong size. Expected pixel height of a
         * `size`-point SDL3_ttf font is ~size*4/3 (48pt -> 64px). */
        int exp = size * 4 / 3;
        int h = TTF_GetFontHeight(font);
        if (h <= 0 || (h >= exp - exp / 4 && h <= exp + exp / 4)) {
            return;
        }
        r->font_state.erase(font); /* stale: fall through and re-apply */
    }
    bool ok = TTF_SetFontSize(font, static_cast<float>(size > 0 ? size : 16));
    TTF_SetFontStyle(font, style);
    if (ok) {
        r->font_state[font] = std::make_pair(size > 0 ? size : 16, style);
    } else {
        r->font_state.erase(font); /* failed: retry next time */
    }
}

/* sync the primary font AND its whole fallback chain to the current
 * (size, style): SDL3_ttf renders a fallback glyph at the FALLBACK's own
 * size, so every chain member must match the run being rasterized. */
static void sync_chain(whaleui_render_t* r, TTF_Font* font, int size,
                       int style)
{
    ensure_font_state(r, font, size, style);
    auto it = r->font_chain.find(font);
    if (it != r->font_chain.end()) {
        for (TTF_Font* fb : it->second) {
            ensure_font_state(r, fb, size, style);
        }
    }
}

/* lazily open the next registered font that can provide `cp`, attach it
 * to every primary font's fallback chain and return it. Called when a
 * glyph is missing - a page that never renders CJK/emoji never opens
 * those fonts (a registered-but-unused font costs only its path string).
 * A font that does NOT provide the glyph is closed again and remembered
 * in fallback_tried, so it is not reopened for every missing glyph. */
static TTF_Font* ensure_fallback(whaleui_render_t* r, TTF_Font* font,
                                 int size, int style, unsigned int cp)
{
    /* 1) fonts already opened are reused (one TTF_Font per family; size is
     * applied on demand). Checking hasGlyph on an open font is cheap, so
     * no miss memory is needed here - only step 2 records (fam, cp). */
    for (TTF_Font* fb : r->fallback_open) {
        ensure_font_state(r, fb, size, style);
        if (TTF_FontHasGlyph(fb, cp)) {
            return fb;
        }
    }
    whaleui_font_registry* reg = whaleui_font_registry_get();
    for (size_t i = 0; i < reg->count; ++i) {
        const std::string fam = reg->fonts[i].family;
        if (fam == r->default_family || fam.empty()) {
            continue; /* the primary font covers its own family */
        }
        bool opened = false;
        for (auto& f : r->fonts) {
            if (f.first == fam) {
                opened = true;
                break;
            }
        }
        if (opened) {
            continue; /* handled by the fallback_open pass above */
        }
        bool tried = false;
        for (auto& t : r->fallback_tried) {
            if (t.first == fam && t.second == cp) {
                tried = true;
                break;
            }
        }
        if (tried) {
            continue;
        }
        TTF_Font* fb = open_registry_font(fam);
        if (!fb) {
            continue;
        }
        ensure_font_state(r, fb, size, style);
        if (!TTF_FontHasGlyph(fb, cp)) {
            /* cannot help with THIS glyph: close it and remember (fam, cp),
             * so this codepoint does not reopen it, while other codepoints
             * the font DOES provide (CJK vs emoji in msyh) still reach it */
            TTF_CloseFont(fb);
            r->fallback_tried.emplace_back(fam, cp);
            continue;
        }
        r->fallback_open.push_back(fb);
        return fb;
    }
    return nullptr;
}

/* case-insensitive family-name match (CSS "Segoe UI" vs TTF real name) */
static bool family_eq(const char* a, const char* b)
{
    if (!a || !b) {
        return false;
    }
    for (; *a && *b; ++a, ++b) {
        char ca = *a;
        char cb = *b;
        if (ca >= 'A' && ca <= 'Z') {
            ca = static_cast<char>(ca - 'A' + 'a');
        }
        if (cb >= 'A' && cb <= 'Z') {
            cb = static_cast<char>(cb - 'A' + 'a');
        }
        if (ca != cb) {
            return false;
        }
    }
    return *a == 0 && *b == 0;
}

/* get (or open) the font for a family; one TTF_Font per family, size and
 * style applied on demand. Generic families ("" / sans-serif / serif /
 * monospace) and unknown families resolve to the default font. CSS family
 * lists like "Segoe UI", Helvetica, sans-serif match the real font names
 * reported by SDL3_ttf, so a page naming a font we registered by file
 * name ("segoeui.ttf") still resolves to it. */
TTF_Font* render_get_font(whaleui_render_t* r, const std::string& family, int size,
                          int style)
{
    if (size <= 0) {
        size = 16;
    }
    std::string key = family;
    for (auto& f : r->fonts) {
        if (f.first == key) {
            sync_chain(r, f.second, size, style);
            return f.second;
        }
    }
    /* try each family in the CSS list, in order */
    std::vector<std::string> fams = split_families(family);
    if (fams.empty()) {
        fams.push_back("");
    }
    TTF_Font* font = nullptr;
    for (const std::string& fam : fams) {
        if (fam.empty() || fam == "sans-serif" || fam == "serif" ||
            fam == "monospace") {
            font = r->font_default;
            break;
        }
        font = open_registry_font(fam);
        if (font) {
            break;
        }
        /* file-name miss: match the real family name of an opened font
         * ("Segoe UI" -> the font opened from segoeui.ttf). The default
         * font is opened at render_create and not in r->fonts, so it is
         * checked too. */
        if (r->font_default) {
            const char* real = TTF_GetFontFamilyName(r->font_default);
            if (real && family_eq(real, fam.c_str())) {
                font = r->font_default;
                break;
            }
        }
        for (auto& f : r->fonts) {
            const char* real = TTF_GetFontFamilyName(f.second);
            if (real && family_eq(real, fam.c_str())) {
                font = f.second;
                break;
            }
        }
        if (font) {
            break;
        }
    }
    if (!font) {
        font = r->font_default;
    }
    if (font) {
        /* record the fallbacks opened so far (engine-managed fallback; no
         * TTF_AddFallbackFont - see ensure_fallback's note) */
        if (r->font_chain.find(font) == r->font_chain.end()) {
            r->font_chain[font]; /* create the chain entry */
        }
        sync_chain(r, font, size, style);
        r->fonts.emplace_back(key, font);
    }
    return font;
}
#else /* !WHALEUI_BUILD_FULL: text rendering needs SDL3_ttf (full only).
         stb_font text lands with the lite/minimal font path. */
TTF_Font* render_get_font(whaleui_render_t*, const std::string&, int, int) { return nullptr; }
#endif

/* (struct TRect lives in render_internal.h) */

#ifdef WHALEUI_BUILD_FULL
/* full: 闂備礁鎲￠〃鍡椕洪弽顓熷仱鐟滃繒鍒掗銏℃櫇闁逞屽墴瀹曟洖顫濇潏顭戞綗闂佺粯锚濡﹪宕澶嬬厪闁糕剝娲滅花绺嶤II 濠电偞鍨堕幐鎼佹煀閿濆拋鐒?ASCII 缂傚倸鍊烽懗鍫曞窗瀹ュ洨鍗氶悗闈涙啞鐏?TTF_GetGlyphMetrics(闂?
 * fallback chain,CJK/emoji 闂佽娴烽、濠偽涢崟顓涘亾閻熸澘鏆辨い顐犲灲閺佹劙宕堕敐鍌氫壕?,濠?glyph_img_ttf 闂?advance 闂備礁鎲￠懝楣冨嫉椤掑倽濮?
 * 婵犵數鍋為幐绋款嚕閸洘鍋傞悗锝庡亝婵鈧箍鍎卞ú銊╁几閸屾埃妲堥柟鐐▕椤庢绱掗弮鍫濞寸媴绠撻崺鈧い鎺戝€甸崑鎾舵兜閸涱噮妫勯柣搴ｎ攰濞呮洜绮欐径鎰ㄩ柨鏃€鍎抽ˉ鏇熺箾閹寸偞灏ㄩ柛瀣崌閺屻倝鏌ㄧ€ｎ剚娈梺閫炲苯鍘哥紒顔捐懀CII 闂備焦妞垮鍧楀礉鎼达絾顫曢柨鏃堟暜閸嬫挸鈽夊▎妯煎姼闂?闂?ASCII 闂?(font,cp) 缂傚倸鍊搁崐褰掑箰閹间焦鍋ら柕濞炬櫅杩?*/
static int glyph_ttf(unsigned int cp, void* st)
{
    TextMeasureCtx* c = static_cast<TextMeasureCtx*>(st);
    TTF_Font* font = render_get_font(c->r, c->family, c->fs,
                                     c->bold ? kFontBold : 0);
    if (!font) {
        return 0;
    }
    if (cp < 0x80) {
        if (c->r->ascii_font != font || c->r->ascii_fs != c->fs) {
            c->r->ascii_font = font;
            c->r->ascii_fs = c->fs;
            for (int i = 0; i < 128; ++i) {
                int m0 = 0, m1 = 0, m2 = 0, m3 = 0, adv = 0;
                TTF_GetGlyphMetrics(font, static_cast<Uint32>(i),
                                    &m0, &m1, &m2, &m3, &adv);
                c->r->ascii_w[i] = adv;
            }
        }
        return c->r->ascii_w[cp];
    }
    /* non-ASCII: cached per (font, size, codepoint); fallback chain included */
    /* The chain is NOT used for metrics: TTF_GetGlyphMetrics reports the
     * PRIMARY font's .notdef advance for missing glyphs (it does not walk
     * the fallback chain, while TTF_GetGlyphImage does) - measuring the
     * primary font gave CJK a 12px .notdef width at 18px while the paint
     * path drew 18px glyphs. Layout/widths/raster buffers were all off and
     * the last CJK char fell outside the buffer ("婵犵數鍎戠徊钘夌暦椤掑倵鍋撻悷鏉挎毐閺佸牓鏌涚仦鍓х煀闁? lost its 缂?.
     * Measure the FALLBACK font that will actually render the glyph. */
    TTF_Font* gfont = font;
    if (cp >= 0x80 || !TTF_FontHasGlyph(font, cp)) {
        TTF_Font* fb = ensure_fallback(c->r, font, c->fs,
                                       c->bold ? kFontBold : 0, cp);
        if (fb) {
            gfont = fb;
        }
    }
    if (gfont) {
        ensure_font_state(c->r, gfont, c->fs,
                          c->bold ? kFontBold : 0);
    }
    std::tuple<TTF_Font*, int, unsigned int> key(
        gfont, static_cast<int>(c->fs), cp);
    auto it = c->r->glyph_w_cache.find(key);
    if (it != c->r->glyph_w_cache.end()) {
        return it->second;
    }
    int m0 = 0, m1 = 0, m2 = 0, m3 = 0, adv = 0;
    TTF_GetGlyphMetrics(gfont, cp, &m0, &m1, &m2, &m3, &adv);
    c->r->glyph_w_cache[key] = adv;
    return adv;
}

/* full: 闂佽瀛╃粙鎺椼€冮崨瀛樺殝闁绘鐗婃刊瀵糕偓骞垮劚閹冲繒绮?缂傚倸鍊烽懗鍫曞窗瀹ュ洨鍗?GlyphImg 闂備浇顫夋禍浠嬪磿鏉堫偁浜?闂備線娼уΛ鏃傛崲娣囧挾_GetGlyphImage 闂?fallback 闂?
 * TTF_IMAGE_COLOR(COLR 闁荤喐绮嶆竟瀣疾閻愬鐝跺┑鐘插閸嬫挸鈽夊▎妯荤暥闂?闂?闂備胶顭堢粔瀵告崲閹烘梻鐭嗙€光偓閸曨剙娈滃銈呯箰鐎氼噣寮妸銉庢盯鎮ч崼銏㈢厔婵?TTF_IMAGE_ALPHA(闂備浇顕х换鎴濐熆濡皷鍋?
 * 闂?濠?fg 闂備浇鍋愰幊鎾绘儑娴兼潙鐒垫い鎺嗗亾闁稿﹥鎮傞幃楣冩倷椤掍礁顎?x = pen + minx(bitmap_left), y = baseline - maxy
 * (bitmap_top),濠?TTF_GetGlyphMetrics 闂佸搫顦弲婊堝蓟閵娿儍娲冀閵娧€鏋栭梺閫炲苯澧撮柟?advance 濠?glyph_ttf 闂備礁鎲￠懝楣冨嫉椤掑倽濮虫い鏇楀亾濠?
 * ponytail: 婵犳鍣徊鐣屾崲閹扮増鍋ょ憸鎴﹀Φ閹版澘顫呴柣妯兼暩婢?闂傚倷绀佺花閬嶅磻閹惧瓨鍙忛柨婵嗗椤﹂绱掗弬璺ㄦ憼缂?SDL_Surface,闂?ckey 闂備焦鐪归崝宀€鈧凹鍨堕幆宀勫箚瑜滈崵?select 濠电偞鍨堕幐鎼侇敄閸℃ê鍨旈柧蹇撴贡妞?
 * 婵犳鍣徊鐣屾崲閹版澘绠慨妯垮煐閻掑鏌熼柇锕€澧伴柟鐣屽枔閹叉悂鎳滈鈧悘顏堟偡閺囩偞顥㈢€?闂備礁鍚嬮惇褰掑磿鐎靛憡宕查柡宥庡亞鐏忕敻鏌ゆ慨鎰偓妤呭矗濮樿埖鐓涢柛灞剧婢跺嫭绻濋埀顒佸閺夋垹顓洪梺褰掑亰閸犳骞婇弴鐐?闂?(font,cp) 缂傚倸鍊搁崐褰掑箰閹间焦鍋ら柕濞р偓閸嬫挸鈽夊▎妯荤暥闂佺厧鎽滄晶妤呭箯閸涱収鍚嬮柛娑卞枤椤╊參姊?*/
static bool glyph_img_ttf(whaleui_render_t* r, const std::string& family,
                          int fs, int style, unsigned int cp, unsigned int fg,
                          GlyphImg& out)
{
    TTF_Font* font = render_get_font(r, family, fs, style);
    if (!font) {
        return false;
    }
    /* render_get_font synced the font + its chain to THIS size/style. A
     * glyph the primary font does not provide lazily opens the next
     * registered font as fallback (unused CJK/emoji fonts cost nothing
     * until a page needs them). TTF_GetGlyphMetrics alone cannot detect
     * this - it reports .notdef metrics for missing glyphs AND does not
     * walk the fallback chain, so the metrics + bitmap below must come
     * from the SAME font that provides the glyph (glyph_ttf measures the
     * same font - see its comment). */
    TTF_Font* gfont = font;
    if (cp >= 0x80 || !TTF_FontHasGlyph(font, cp)) {
        /* non-ASCII: never trust TTF_FontHasGlyph on the primary - once a
         * fallback font is attached to its chain (TTF_AddFallbackFont),
         * hasGlyph reports true for chain-provided glyphs while
         * metrics/bitmap still come from the primary (.notdef 16px box for
         * CJK at 48px). Always ask ensure_fallback for the font that truly
         * provides the glyph (it returns null when the primary has it). */
        TTF_Font* fb = ensure_fallback(r, font, fs, style, cp);
        if (fb) {
            gfont = fb;
        }
    }
    /* gfont may be a SHARED fallback font (one msyh serves every primary
     * font) that another primary font restyled to a different size:
     * re-apply (fs, style) right before measuring + rasterizing this
     * glyph, or a stray 16px sync leaves a 48px CJK run rasterizing 16px
     * glyphs (big titles looked cut/short). */
    if (gfont) {
        ensure_font_state(r, gfont, fs, style);
    }
    int minx = 0, maxx = 0, miny = 0, maxy = 0, adv = 0;
    if (!TTF_GetGlyphMetrics(gfont, cp, &minx, &maxx, &miny, &maxy, &adv)) {
        return false;
    }
    TTF_ImageType type = TTF_IMAGE_INVALID;
    SDL_Surface* img = TTF_GetGlyphImage(gfont, cp, &type);
    if (!img) {
        return false;
    }
    out.w = img->w;
    out.h = img->h;
    out.xoff = minx;
    out.yoff = -maxy;
    out.advance = adv;
    out.colored = (type == TTF_IMAGE_COLOR);
    out.px.resize(static_cast<size_t>(img->w) * img->h);
    if (out.colored) {
        /* ARGB8888 闂佽绻愮换鎰崲閹烘鏁傛い鎺戝缁€鍐煕濞戝崬骞橀柟鐣屽█楠?= B,G,R,A 闂?0xAARRGGBB,濠?framebuffer 濠电偞鍨堕幐鎾磻閹剧粯鐓?*/
        std::memcpy(out.px.data(), img->pixels, out.px.size() * 4);
    } else {
        /* 闂備浇顕х换鎴濐熆濡皷鍋撻悷鎵紞闁逞屽墯缁嬫帡銆冮崨瀛樺殝?SDL3_ttf 闂備礁鎲￠崝鏍偡瑜嶉埢宥堫樄闁?+ alpha,闂備礁鎼ú锔锯偓绗涘啰鏆﹂柛娆忣槺閳?fg 闂?濠?fg alpha) */
        const unsigned char* p =
            static_cast<const unsigned char*>(img->pixels);
        const unsigned int rgb = fg & 0xFFFFFF;
        const unsigned int fa = (fg >> 24) & 0xFF;
        for (size_t i = 0; i < out.px.size(); ++i) {
            unsigned int a = p[i * 4 + 3] * fa / 255;
            out.px[i] = a ? (a << 24) | rgb : 0;
        }
    }
    SDL_DestroySurface(img);
    return true;
}
#else
/* --- stb_truetype 闂備礁鎲￠懝鎯归悜绛嬫晜?婵犵數鍋炲娆擃敄閸涙惌鏁?+ 闁荤喐绮嶆竟瀣疾閻愬鐝跺┑鐘插閸嬫挸鈽夊▎妯荤暥闂?COLR/CPAL,闂備礁鎲￠悷銉╁磹娴犲鐒?stb#512/#1135) --- */

/* 濠电姰鍨归悥銏ゅ椽娴ｉ纾介梺鑽ゅТ濞测晠顢氳閵?sfnt 闂佽崵鍋炵粙蹇涘礉瀹€鍕仱鐟滃秹鍩㈤幘缁橆棃婵炴垶鐟х粔鍨箾?big-endian) */
static unsigned int be16(const unsigned char* p)
{
    return (static_cast<unsigned int>(p[0]) << 8) | p[1];
}
static unsigned int be32(const unsigned char* p)
{
    return (static_cast<unsigned int>(p[0]) << 24) |
           (static_cast<unsigned int>(p[1]) << 16) |
           (static_cast<unsigned int>(p[2]) << 8) | p[3];
}

/* 闂備線娼荤拹鐔煎礉瀹€鍕仱鐟滃酣骞忛崨鏉戠閻庢稒蓱椤斿秹姊虹涵鍜佸殐闁哥姵娲熼幊娆撳箣閿曗偓閽冪喖鏌曟径娑氱暠妞?sfnt 闂?tag 4 闂佽瀛╃粙鎺椼€冩径瀣╃箚?闂備焦鐪归崝宀€鈧凹鍓氱粋宥夊传閵壯呯厠?闂佸搫顦弲婊堝蓟閵娿儍娲冀椤撶喎鍓紓浣割儐椤戞瑩宕甸悩缁樼厸濞达絽鎼。鑲┾偓瑙勬尫閼冲爼骞愯椤︾増鎯旈垾鎻掑闂備焦鐪归崝宀€鈧凹鍓氱粋宥夊传閵壯呯厠?
 * TTC 闂備礁鎲￠悷锕傛偋濠婂牜鏁勯柛銉ｅ妿閳绘棃鏌嶈閸撴氨绮欐径鎰垫晜闁告洦鍘介幉缁樼箾鏉堝墽绋婚柟绋跨埣閸┾偓妞ゆ巻鍋撻柛濠咁潐缁旂喎螣閼姐倐鏋栭悗骞垮劚閹冲酣鎮￠崒鐐茬骇闁冲搫鍊归悡銉︾箾?-1闂?*/
static int font_table_off(const unsigned char* data, size_t len, const char* tag)
{
    if (!data || len < 12) {
        return -1;
    }
    int fontstart = stbtt_GetFontOffsetForIndex(data, 0);
    if (fontstart < 0 || fontstart + 12 > static_cast<int>(len)) {
        return -1;
    }
    unsigned int n = be16(data + fontstart + 4);
    for (unsigned int i = 0; i < n; ++i) {
        size_t r = static_cast<size_t>(fontstart) + 12 + i * 16;
        if (r + 16 > len) {
            return -1;
        }
        const unsigned char* rec = data + r;
        if (rec[0] == static_cast<unsigned char>(tag[0]) &&
            rec[1] == static_cast<unsigned char>(tag[1]) &&
            rec[2] == static_cast<unsigned char>(tag[2]) &&
            rec[3] == static_cast<unsigned char>(tag[3])) {
            unsigned int off = be32(rec + 8);
            return off < len ? static_cast<int>(off) : -1;
        }
    }
    return -1;
}

/* COLR 闂佽绻掗崑娑㈠磹娴犲鏁婇柛銉簵娴?闂佽绻掗崑娑㈠磹閹间焦鍋ょ憸鎴﹀Φ?id + 闂佽崵濮撮鍛村疮閾忣偆鐝跺┑鐘叉搐缁狙囨煙缁嬪灝顒㈤柦鍌氼儔閺?闂備礁鎲￠悷銉╁磹娴犲鐒?stb#1135 闂?stbtt_glyphlayer) */
struct ColrLayer { unsigned short glyph; unsigned short color; };

/* 闂備礁鎼悮顐﹀磿閸欏鐝?glyph 闂?COLR 闂?缂傚倷鑳堕崑鎾垛偓绗涘洤鐒垫い鎴墮鐎氼剟藟閸ヮ剚鐓?base glyph records 闂?glyph id 闂備礁鎲￠〃鍛洪妶鍥С?
 * 闂備浇妗ㄥ鎺楀础閹惰棄闂柧蹇撴贡濡垳鎲稿澶婂惞闁硅揪闄勯崕宀€绱掗懜鐢垫噰鐎规洘鐟╅幃鈺呭箵閹烘棑绱?婵犳鍣徊鐣屾崲閹扮増鍋ょ憸鎴﹀Φ閹板府缍栨い鎾跺娴煎洤鈹戦悙鍙夘棏闁逞屽墮閸熻法鎷嬮弻銉︾厵闁诡厽甯掗崝姘辨喐?闂備線娼уΛ妤呭磹閻ｅ本宕查柟杈剧畱閻愬﹪鏌ｉ幇顖氱毢婵犫偓閹绢喗鐓?0 = 闂佽崵濮村ú銏ゅ磿闁秵鍋ょ憸鎴﹀Φ閹版澘顫呴柍鈺佸枦妤犲繘鏌ｈ箛鏇炰粶闁稿﹤鐖奸崺鈧?*/
static int colr_layers(const unsigned char* data, int colr_off,
                       unsigned int gid, const ColrLayer*& out)
{
    const unsigned char* t = data + colr_off;
    unsigned int n = be16(t + 2);
    unsigned int bgo = be32(t + 4);
    unsigned int lo = be32(t + 8);
    for (unsigned int i = 0; i < n; ++i) {
        const unsigned char* r = t + bgo + i * 6;
        if (be16(r) == gid) {
            unsigned int fi = be16(r + 2);
            unsigned int nl = be16(r + 4);
            out = reinterpret_cast<const ColrLayer*>(t + lo + fi * 4);
            return static_cast<int>(nl);
        }
    }
    return 0;
}

/* CPAL v0 闂佽崵濮撮鍛村疮閾忣偆鐝跺┑鐘叉搐缁狙囨煕瑜庨〃蹇涘级瑜版帗鐓?BGRA 闂備礁鎲￠崝鏇㈠箠鎼淬劍鍋ら柕濠忛檮閸?闂?0xAARRGGBB);colorid==0xFFFF 闂備焦鐪归崹鑲╁垝妤ｅ啯鍎嶉柣鏂垮悑閸?
 * 闂備礁鎼崐绋匡耿闁秴鏋侀柕鍫濐槸缁€鍫⑩偓骞垮劚濡瑩鎮甸鐐寸厾闁荤喐澹嗗﹢鎾煃瑜滈崜娆撳磹濮濆被浜归柛銉㈡櫆鐎氼剟鏌涢幇闈涘箹妞ゃ儱绻橀弻?0(濠碘槅鍋撶徊楣冩偋閺冨牊鐓?闂?*/
static unsigned int colr_palette_color(const unsigned char* data, int cpal_off,
                                       unsigned int colorid)
{
    if (cpal_off < 0 || colorid == 0xFFFF) {
        return 0xFFFFFFFF;
    }
    const unsigned char* t = data + cpal_off;
    unsigned int npa = be16(t + 4);
    unsigned int npe = be16(t + 2);
    if (npa == 0 || colorid >= npe) {
        return 0xFFFFFFFF;
    }
    unsigned int cro = be32(t + 8);
    unsigned int pidx = be16(t + 12); /* palette 0 闂?colorRecordIndices */
    const unsigned char* c = t + cro + pidx * 4 + colorid * 4;
    return (static_cast<unsigned int>(c[3]) << 24) |
           (static_cast<unsigned int>(c[2]) << 16) |
           (static_cast<unsigned int>(c[1]) << 8) | c[0];
}

/* 婵犵數鍋為幐绋款嚕閸洘鍋?COLR 闂備礁鎲＄敮鎺懳涘Δ鍛剳闁规鍠掗崑鎾斥槈濞嗘ɑ鐣堕梺鐓庢憸婢ф绮?RGBA(0xAARRGGBB);闂佸搫顦弲婊堝蓟閵娿儍?false 闂佽崵鍋炵粙蹇涘礉鎼淬劌桅婵娉涚猾宥夋煟濡灝鐨烘繝鈧?闂佽崵濮撮鍛村疮娴兼潙鏋侀柕鍫濐槸濡鐥鐐村殌婵?
 * 闂備礁鎼幏瀣闯閿濆鐒垫い鎺嶇劍閻ㄦ垵霉閻撳孩顥為柟顖涙閺佸啯鎷呴搹鐟版暥闁?闂備線娼уΛ妤呭磹瑜版帗鍎婇柨娑樺濞?stbtt 濠电偠鎻徊鐣岀矓閺夋嚚?+ 闂佽崵濮撮鍛村疮閾忣偆鐝跺┑鐘叉搐缁狙囨煕瑜庨〃蹇涘级瑜版帗鐓?src-over 闂備礁鎲￠懝楣冩偋婵犲洤鍨傛慨妯挎硾杩?*/
static bool colr_render(const stbtt_fontinfo& info, float scale,
                        const unsigned char* data, int colr_off, int cpal_off,
                        unsigned int gid, unsigned int fg,
                        std::vector<unsigned int>& px, int& w, int& h,
                        int& xoff, int& yoff)
{
    const ColrLayer* layers = nullptr;
    int nl = colr_layers(data, colr_off, gid, layers);
    if (nl <= 0) {
        return false;
    }
    struct R { unsigned char* bmp; int w, h, x, y; unsigned int color; };
    std::vector<R> rs;
    int minx = 0x7FFFFFFF, miny = 0x7FFFFFFF, maxx = -0x7FFFFFFF, maxy = -0x7FFFFFFF;
    for (int i = 0; i < nl; ++i) {
        int bw = 0, bh = 0, bx = 0, by = 0;
        unsigned char* bmp = stbtt_GetGlyphBitmap(&info, scale, scale,
                                                  layers[i].glyph,
                                                  &bw, &bh, &bx, &by);
        if (!bmp || bw <= 0 || bh <= 0) {
            stbtt_FreeBitmap(bmp, nullptr);
            continue;
        }
        R r;
        r.bmp = bmp;
        r.w = bw;
        r.h = bh;
        r.x = bx;
        r.y = by;
        r.color = colr_palette_color(data, cpal_off, layers[i].color);
        if (layers[i].color == 0xFFFF) {
            r.color = fg;
        }
        rs.push_back(r);
        if (bx < minx) minx = bx;
        if (by < miny) miny = by;
        if (bx + bw > maxx) maxx = bx + bw;
        if (by + bh > maxy) maxy = by + bh;
    }
    if (rs.empty()) {
        return false;
    }
    w = maxx - minx;
    h = maxy - miny;
    xoff = minx;
    yoff = miny;
    px.assign(static_cast<size_t>(w) * h, 0);
    for (size_t ri = 0; ri < rs.size(); ++ri) {
        const R& r = rs[ri];
        const unsigned int sr = (r.color >> 16) & 0xFF;
        const unsigned int sg = (r.color >> 8) & 0xFF;
        const unsigned int sb = r.color & 0xFF;
        for (int yy = 0; yy < r.h; ++yy) {
            int dy = r.y - miny + yy;
            if (dy < 0 || dy >= h) {
                continue;
            }
            for (int xx = 0; xx < r.w; ++xx) {
                unsigned int sa = r.bmp[yy * r.w + xx];
                if (sa == 0) {
                    continue;
                }
                int dx = r.x - minx + xx;
                if (dx < 0 || dx >= w) {
                    continue;
                }
                unsigned int& d = px[static_cast<size_t>(dy) * w + dx];
                unsigned int da = (d >> 24) & 0xFF;
                /* src-over */
                unsigned int oa = sa + da * (255 - sa) / 255;
                if (oa == 0) {
                    continue;
                }
                unsigned int dr = (d >> 16) & 0xFF;
                unsigned int dg = (d >> 8) & 0xFF;
                unsigned int db = d & 0xFF;
                unsigned int oc = (sr * sa + dr * da * (255 - sa) / 255) / oa;
                unsigned int og = (sg * sa + dg * da * (255 - sa) / 255) / oa;
                unsigned int ob = (sb * sa + db * da * (255 - sa) / 255) / oa;
                d = (oa << 24) | (oc << 16) | (og << 8) | ob;
            }
        }
        stbtt_FreeBitmap(r.bmp, nullptr);
    }
    return true;
}

/* stb font table for measuring (mirrors the draw path in draw_text_at) */
struct StbFonts
{
    struct F { stbtt_fontinfo info; float scale; int asc; int line_h; bool ok; };
    std::vector<F> fonts;
    std::vector<int> colr, cpal; /* 婵犳鍣徊鐣屾崲閹扮増鍋ょ憸搴ㄥ箯?COLR/CPAL 闂佽崵鍋炵粙蹇涘礉鐏炲墽顩查柛婵勫劤閻?闂備礁鎼崯鐗堟叏妤ｅ啫违闁告劏鏅濋埢?-1 */
    size_t pref;
    int line_h;
    explicit StbFonts(const std::string& family, int fs)
        : pref(static_cast<size_t>(-1)), line_h(fs > 0 ? fs : 16)
    {
        whaleui_font_registry* reg = whaleui_font_registry_get();
        if (!reg) {
            return;
        }
        for (size_t fi = 0; fi < reg->count; ++fi) {
            F f;
            f.ok = false;
            f.scale = 1.0f;
            f.asc = 0;
            f.line_h = line_h;
            const unsigned char* d = reg->fonts[fi].data;
            size_t l = reg->fonts[fi].len;
            int co = -1, cp = -1;
            if (d && l >= 4) {
                int off = stbtt_GetFontOffsetForIndex(d, 0);
                if (off >= 0 && stbtt_InitFont(&f.info, d, off)) {
                    f.scale = stbtt_ScaleForPixelHeight(&f.info, static_cast<float>(fs));
                    int desc = 0, linegap = 0;
                    stbtt_GetFontVMetrics(&f.info, &f.asc, &desc, &linegap);
                    f.line_h = static_cast<int>((f.asc - desc + linegap) * f.scale + 0.5f);
                    f.ok = true;
                    line_h = f.line_h;
                    co = font_table_off(d, l, "COLR");
                    cp = font_table_off(d, l, "CPAL");
                }
            }
            colr.push_back(co);
            cpal.push_back(cp);
            fonts.push_back(f);
        }
        /* preferred font: first CSS family match, else first usable font */
        std::vector<std::string> fams = split_families(family);
        for (const std::string& fam : fams) {
            if (fam.empty()) {
                continue;
            }
            bool generic = fam == "sans-serif" || fam == "serif" ||
                           fam == "monospace";
            if (generic) {
                continue;
            }
            for (size_t fi = 0; fi < fonts.size(); ++fi) {
                if (fonts[fi].ok && reg->fonts[fi].family &&
                    std::strcmp(reg->fonts[fi].family, fam.c_str()) == 0) {
                    pref = fi;
                    break;
                }
            }
            if (pref != static_cast<size_t>(-1)) {
                break;
            }
        }
        if (pref == static_cast<size_t>(-1)) {
            for (size_t fi = 0; fi < fonts.size(); ++fi) {
                if (fonts[fi].ok) {
                    pref = fi;
                    break;
                }
            }
        }
    }
    size_t pick(size_t start, unsigned int cp) const
    {
        if (start != static_cast<size_t>(-1) && fonts[start].ok &&
            stbtt_FindGlyphIndex(&fonts[start].info, cp) != 0) {
            return start;
        }
        for (size_t fi = 0; fi < fonts.size(); ++fi) {
            if (fi == start || !fonts[fi].ok) {
                continue;
            }
            if (stbtt_FindGlyphIndex(&fonts[fi].info, cp) != 0) {
                return fi;
            }
        }
        return static_cast<size_t>(-1);
    }
};
/* stb: 闂備礁鎲￠〃鍡椕洪弽顓熷仱鐟滃繒鍒掗銏℃櫇闁逞屽墴瀹曟洖顫濇潏顭戞綗闂佺粯锚濡﹪宕?闂?fallback 闂佽瀛╃粙鎺楀Φ閻愮數绀婇悗锝庡墯閸? */
static int glyph_stb(unsigned int cp, void* st)
{
    StbFonts* f = static_cast<StbFonts*>(st);
    size_t fi = f->pick(f->pref, cp);
    if (fi == static_cast<size_t>(-1)) {
        return 0;
    }
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&f->fonts[fi].info, cp, &adv, &lsb);
    return static_cast<int>(adv * f->fonts[fi].scale + 0.5f);
}

/* stb: 闂佽瀛╃粙鎺椼€冮崨瀛樺殝闁绘鐗婃刊瀵糕偓骞垮劚閹冲繒绮?缂傚倸鍊烽懗鍫曞窗瀹ュ洨鍗?GlyphImg 闂備浇顫夋禍浠嬪磿鏉堫偁浜?闂備線娼уΛ鏃堝疾閻ゎ湌R 闂備礁鎲＄敮鎺懳涘Δ鍛剳闁规鍠掗崑鎾斥槈濞嗘ɑ鐣堕梺鐓庢憸婢ф顭囪箛娑樼闁告劕寮堕惁鏃堟⒑閻撳寒娈犲ù婊勭矒閹粙顢曢敐蹇曠煑濠电姴锕ゅΛ妤吽?
 * (colored=true),闂備礁鎼幏瀣闯閿濆鐒垫い鎺嶆祰婢规﹢鏌ｉ埊娆忔娴滆銇勯顐㈠绩缂佲偓?fg 闂?闂?alpha闂備線娼уΛ妤呭焵椤掆偓閸╊柆f/yoff 濠电偞鍨堕幑浣糕枍閿濆悿瑙勫緞鐏炵浜?pen+baseline
 * 闂備焦鐪归崝宀€鈧凹浜炵槐鐐哄川閺夋垹鍊為梺璇″瀻閸屾粌澧剧紓?stb 闂佽崵濮村ù鍌炲储閾忓湱涓?濠?glyph_stb 闂備礁鎲￠懝楣冨嫉椤掑倽濮虫い鏃€绁归崷顓涘亾閿濆簼鎲鹃柛?闂?*/
static bool glyph_img_stb(StbFonts& stb, unsigned int cp, unsigned int fg,
                          GlyphImg& out)
{
    size_t fi = stb.pick(stb.pref, cp);
    if (fi == static_cast<size_t>(-1)) {
        return false;
    }
    const StbFonts::F& f = stb.fonts[fi];
    int adv = 0, lsb = 0;
    stbtt_GetCodepointHMetrics(&f.info, cp, &adv, &lsb);
    out.advance = static_cast<int>(adv * f.scale + 0.5f);
    unsigned int gid = stbtt_FindGlyphIndex(&f.info, cp);
    if (gid == 0) {
        return false;
    }
    const unsigned char* data = f.info.data;
    if (stb.colr[fi] >= 0 &&
        colr_render(f.info, f.scale, data, stb.colr[fi], stb.cpal[fi],
                    gid, fg, out.px, out.w, out.h, out.xoff, out.yoff)) {
        out.colored = true;
        return true;
    }
    unsigned char* bmp = stbtt_GetGlyphBitmap(&f.info, f.scale, f.scale,
                                              gid, &out.w, &out.h,
                                              &out.xoff, &out.yoff);
    if (!bmp || out.w <= 0 || out.h <= 0) {
        stbtt_FreeBitmap(bmp, nullptr);
        return false;
    }
    out.colored = false;
    out.px.resize(static_cast<size_t>(out.w) * out.h);
    const unsigned int sr = (fg >> 16) & 0xFF;
    const unsigned int sg = (fg >> 8) & 0xFF;
    const unsigned int sb = fg & 0xFF;
    const unsigned int fa = (fg >> 24) & 0xFF; /* 闂備礁鎲￠幐鍝ョ矓闂堟稈鏋?alpha 濠电偞鍨跺褰掓晪闂佺硶鏅涢惉濂稿焵椤掍胶鈯曟い銊ユ嚇閹虫粓鎮ч崼鈶╂灃?*/
    for (size_t i = 0; i < out.px.size(); ++i) {
        unsigned int a = bmp[i] * fa / 255;
        out.px[i] = a ? (a << 24) | (sr << 16) | (sg << 8) | sb : 0;
    }
    stbtt_FreeBitmap(bmp, nullptr);
    return true;
}
#endif

/* 闂佽瀛╃粙鎺椼€冮崨瀛樺殝闁规鍠楅崰鍡涙煕閳╁啫鍤繛鍏兼礋閺岋綁鍩￠崒姘癁闂?ascent + descent/2),闂備焦妞垮鍧楀礉鐎ｎ剝濮虫い鎺戝濡﹢鏌涢妷鎴濇噺閹?闂備胶顭堢换鎰八囨导瀛樺亯?闂傚倷绶￠崑鍕囬婊€鐒婃い鏍仜閸ㄥ倿鏌涚仦鍓х煁缂佺虎鍨堕幃姗€鎮欓崣澶婃闂?
 * 闂佽崵鍋炵粙鎴︽儗閸岀偞鍋?th 闂備礁鎲￠崙褰掑磻婢舵劑鈧線骞嬮悩鍐茬／?闂?th 闂佽绻掗崑娑㈠箠瀹ュ鍤堥柟瀵稿仜椤曡鲸鎱ㄥΟ璇插闁哥偑鍔戦弻锝夊閿濆骸娈┑鐘亾妞ゅ繐妫涚壕浠嬫煙閹冩毐闁哄棗宕—鍐Χ閸涱垰鐓熼梺绋垮閹告娊骞嗛崘顔肩妞ゆ劑鍊栭幉濠氭偡濠婂棗鐒介柛銊ャ偢閿濈偟鈧綆鍓氶崰鍡楊熆鐠虹尨姊楅柣鎺戯工閳藉骞橀幇浣哄姼闂?
 * 濠?draw_text_at 闂備焦鐪归崝宀€鈧凹鍓熼幆鍥惞椤愩倐鏋栧銈嗘尵閸嬬喖宕妸鈺傜厱闁瑰瓨绻冮ˉ娆戠磼閺冣偓閹告娊骞?闂傚倷绶￠崜娆撴倶濠靛鍌?caret 濠电偞鍨堕幐鍝モ偓娑掓櫊瀵悂宕橀浣镐壕婵炴垶鐟▓婊堟煛娴ｉ潻鏀婚柟宄版噹椤撳ジ宕橀敐鍛?*/
int text_glyph_h(whaleui_render_t* r, int fs, const std::string& family,
                 bool bold)
{
    int gh = 0;
#ifdef WHALEUI_BUILD_FULL
    TTF_Font* gfont = render_get_font(r, family, fs, bold ? kFontBold : 0);
    if (gfont) {
        int ga = TTF_GetFontAscent(gfont);
        int gd = TTF_GetFontDescent(gfont);
        if (ga > 0) {
            gh = ga + gd / 2;
        }
    }
#endif
    return gh > 0 ? gh : text_line_h(r, fs, family, bold);
}

void text_size(whaleui_render_t* r, const std::string& text, int fs,
               const std::string& family, bool bold, int* tw, int* th,
               int wrap_w)
{
    *tw = *th = 0;
    if (text.empty() || !r) {
        return;
    }
    /* content-addressed cache: the layout pass measures every run every
     * relayout (a width animation re-lays out each frame) - the layout_text
     * walk below was the per-frame cost. Text/width/face unchanged -> O(1). */
    uint64_t key = 1469598103934665603ull;
    for (size_t i = 0; i < text.size(); ++i) {
        key ^= static_cast<unsigned char>(text[i]);
        key *= 1099511628211ull;
    }
    key ^= static_cast<uint64_t>(fs) * 0x9E3779B97F4A7C15ull;
    key ^= static_cast<uint64_t>(bold) * 0xBF58476D1CE4E5B9ull;
    key ^= static_cast<uint64_t>(wrap_w) * 0x94D049BB133111EBull;
    for (size_t i = 0; i < family.size(); ++i) {
        key ^= static_cast<unsigned char>(family[i]);
        key *= 1099511628211ull;
    }
    auto it = r->text_size_cache.find(key);
    if (it != r->text_size_cache.end()) {
        *tw = it->second.first;
        *th = it->second.second;
        return;
    }
    int lh = text_line_h(r, fs, family, bold);
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextLayout L = layout_text(text, wrap_w, lh, glyph_ttf, &mc);
#else
    StbFonts stb(family, fs);
    TextLayout L = layout_text(text, wrap_w, lh, glyph_stb, &stb);
#endif
    *tw = L.tw;
    *th = L.th;
    r->text_size_cache[key] = std::make_pair(*tw, *th);
}

int text_line_h(whaleui_render_t* r, int fs, const std::string& family, bool bold)
{
#ifdef WHALEUI_BUILD_FULL
    TTF_Font* font = render_get_font(r, family, fs,
                                     bold ? kFontBold : 0);
    if (font) {
        int h = TTF_GetFontHeight(font);
        if (h > 0) {
            return h;
        }
    }
    return fs > 0 ? fs : 16;
#else
    StbFonts stb(family, fs > 0 ? fs : 16);
    return stb.line_h;
#endif
}

std::vector<TRect> sel_rects(whaleui_render_t* r, const std::string& text,
                             int fs, const std::string& family, bool bold,
                             size_t a, size_t b, int wrap_w)
{
    std::vector<TRect> out;
    if (a > text.size()) {
        a = text.size();
    }
    if (b > text.size()) {
        b = text.size();
    }
    if (a > b) {
        std::swap(a, b);
    }
    if (a == b || text.empty()) {
        return out;
    }
    int lh = text_line_h(r, fs, family, bold);
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    const size_t nc = L.map.size();
    for (size_t li = 0; li < L.lines.size(); ++li) {
        const TextLayoutLine& ln = L.lines[li];
        int xacc = 0;
        int x0 = -1, x1 = -1;
        for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
            int w = gw(disp_cp_at(L, ci), st);
            if (x0 < 0 && L.map[ci] >= a) {
                x0 = xacc;
            }
            if (x1 < 0 && L.map[ci] >= b) {
                x1 = xacc;
                break;
            }
            xacc += w;
        }
        if (x0 < 0) {
            continue; /* line ends before a */
        }
        if (x1 < 0) {
            x1 = xacc; /* range extends past this line's end */
        }
        if (x1 > x0) {
            TRect rc = {x0, static_cast<int>(li) * lh, x1 - x0, lh};
            out.push_back(rc);
        }
        if (x1 >= xacc) {
            continue; /* keep scanning later lines (range continues) */
        }
        break;
    }
    return out;
}

void caret_pos(whaleui_render_t* r, const std::string& text, int fs,
               const std::string& family, bool bold, size_t off,
               int* cx, int* cy, int* ch, int wrap_w)
{
    int lh = text_line_h(r, fs, family, bold);
    if (lh <= 0) {
        lh = fs > 0 ? fs : 16;
    }
    if (text.empty()) {
        *cx = 0;
        *cy = 0;
        *ch = lh;
        return;
    }
    if (off > text.size()) {
        off = text.size();
    }
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    const size_t nc = L.map.size();
    /* 闂?off 闂備礁婀遍。浠嬪磻閹剧粯鐓曢柨鏂挎惈婵偓濡?off 闂備浇袙閸嬫捇鏌﹀Ο渚Ч闂?[闂佽崵鍋炵粙鎴︽儗閸岀偑鈧懏绻濆顒傦紱闂婎偄娲﹀▔? 闂佽崵鍋炵粙鎴︽嚐椤栫偞鍋勬い鎺戝绾惧鐓崶銊﹂暱妞?闂備礁鎲￠悧妤€顪冮挊澹╂盯宕稿Δ鈧繚?
     * 闂佽崵鍋炵粙鎴︽儗閸岀偑鈧懏绻濆顒傜潉?caret 闂備焦鐪归崹濂割敋瑜嶉敃銏ゎ敂閸℃ê鐝伴梺闈涱樈閻撳牓寮?x=0(濠电偞鍨堕幐鍝ョ矓闂堟党锝夊箹娴ｅ摜顦悗骞垮劚鐎氼噣顢旈柆宥嗗仩婵炴垶顭囬悘杈ㄧ箾閸喎鐏╅柟顔藉娴狅箓鎮剧仦鑺ユ)闂?*/
    for (size_t li = 0; li < L.lines.size(); ++li) {
        const TextLayoutLine& ln = L.lines[li];
        size_t ls_off = (ln.cstart < nc) ? L.map[ln.cstart] : off;
        size_t le_off = (ln.cend < nc) ? L.map[ln.cend] : text.size();
        if (off < ls_off) {
            /* 闂備浇袙閸嬫捇鏌﹀Ο渚Ч闂婎剦鍓欓埥澶愬箻缁涜顣肩紓浣规煥椤曨參骞冮幍顔绘勃闁绘劦鍓氶惈姗€鏌ｈ箛鎾剁鐟滄壆鍋熺划濠氭晲婢跺﹨袝闁圭厧鐡ㄧ粙鍫ュ磻閹惧瓨濯撮悷娆忓鐎氭娊鏌ｉ悙瀵糕槈闁活厺绶氶妴渚€骞嬮悜鍥╃＞闂佸搫绋勬俊鍥敇濞差亝鐓?闂備礁鎲￠悷顖涚濠婂喛鑰挎い蹇撴閻艾螖閿旂瓔鍎ラ柡鈧挊澶嗘闁哄倹顑欓崕鏃€淇婇銏″仴闁?
             * \n 濠电姰鍨煎▔娑氣偓姘煎墲閵囨劙寮婚妷锕€娈?闁荤喐绮庢晶妤呭箰妞嬪海绀婇柡鍐ㄧ墕鐎氬銇勯幒鎴濇灓闁衡偓娴犲鍋犳繛鎴烆焽閻掑憡銇勯埡鍐笡鐎垫澘瀚板畷鐔碱敇閻斿皝鍋?*/
            *cx = 0;
            *cy = static_cast<int>(li) * lh;
            *ch = lh;
            return;
        }
        if (off >= ls_off && off <= le_off) {
            int xacc = 0;
            for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
                if (L.map[ci] >= off) {
                    break;
                }
                xacc += gw(disp_cp_at(L, ci), st);
            }
            *cx = xacc;
            *cy = static_cast<int>(li) * lh;
            *ch = lh;
            return;
        }
    }
    /* 闂備胶顭堢换鎴犲垝瀹€鈧懞?闂備礁鎼崐绋棵洪敃鈧敃銏″閺夋垵鐝樺銈嗗姂閸ㄥ宕?*/
    const TextLayoutLine& last = L.lines.back();
    *cx = last.w;
    *cy = static_cast<int>(L.lines.size() - 1) * lh;
    *ch = lh;
}

/* defined below (editing helpers); needed by the paint path above */
void text_origin(whaleui_render_t* r, whaleui_layout_node_t* n,
                 const std::string& text, int fs, const std::string& family,
                 bool bold, int* tx, int* ty);
struct whaleui_layout_node;
whaleui_layout_node_t* editable_geo(whaleui_layout_node_t* n);

size_t utf8_char_len(unsigned char c)
{
    if (c < 0x80) {
        return 1;
    }
    if ((c & 0xE0) == 0xC0) {
        return 2;
    }
    if ((c & 0xF0) == 0xE0) {
        return 3;
    }
    if ((c & 0xF8) == 0xF0) {
        return 4;
    }
    return 1;
}

void apply_text_transform(std::string& s, const std::string& t)
{
    if (t == "uppercase") {
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c < 0x80 && c >= 'a' && c <= 'z') {
                s[i] = static_cast<char>(c - 32);
            }
        }
    } else if (t == "lowercase") {
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c < 0x80 && c >= 'A' && c <= 'Z') {
                s[i] = static_cast<char>(c + 32);
            }
        }
    } else if (t == "capitalize") {
        bool word_start = true;
        for (size_t i = 0; i < s.size(); ++i) {
            unsigned char c = static_cast<unsigned char>(s[i]);
            if (c >= 0x80) {
                i += utf8_char_len(c) - 1;
                word_start = false;
                continue;
            }
            if (c == ' ' || c == '\t' || c == '-') {
                word_start = true;
            } else if (word_start) {
                if (c >= 'a' && c <= 'z') {
                    s[i] = static_cast<char>(c - 32);
                }
                word_start = false;
            }
        }
    }
}

void draw_text_at(whaleui_render_t* r, const std::string& text,
                  int bx, int by, int bw, int bh,
                  int fs, const std::string& family, unsigned int color,
                  int style, int align, lxb_dom_element* ckey,
                  const Clip* clip, int lsp, bool wrap, float opacity,
                  bool outline)
{
    /* 缂傚倸鍊搁崐褰掑箰閹间焦鍋ら柕濞炬櫅閽冪喖鏌曟径妯煎帥闁搞倕瀚伴弻娑滅疀閹捐泛鈪插?text+闂備礁鎼粔鎾床閼碱剚顫曢柍鈺佸暟閳绘梻鈧箍鍎遍幊搴ｇ礊娓氣偓閺?闂備礁婀遍崕銈囨暜閻愬瓨娅?layout_text)濠电偞鍨堕幐鍛婎殽閹间焦鍋ょ憸鎴﹀Φ閹版澘顫呴柣妯诲絻鏉堝懘姊洪崫鍕㈤柟鍐叉捣閳ь剙鐏氶悡鈥愁嚕?
     * 婵犳鍣徊鐣屾崲閹版澘绠慨妯垮煐閻撳倻鈧箍鍎遍幏瀣ｆ繝姘仯濞撴艾锕︾壕鍧楁煟?闂備胶鍋ㄩ崕鏌ュ蓟閿熺姴鐒?闂備礁鎲￠弻锝夊礉鎼淬劌鏋侀柛鎾楀嫭娈伴悷婊冪Ч椤㈡岸顢欐径瑙勫笩缁犳稒鎯旈妸銉︾杺 run 闂傚倷鐒﹁ぐ鍐矓閻㈢钃熷┑鐘叉搐缁犳娊鏌熼悜妯荤叆妞わ絽銈搁弻锟犲炊閳轰椒澹曞┑?42ms 闂備焦鐪归崝宀€鈧凹鍓熸俊鐢稿炊閵娿儳绐炲┑鐑囩秵閸忔﹢宕?
     * 闂備礁鎲＄粙鎺楀垂濠靛鍤堥柟杈鹃檮閸庡酣鎮楀☉娅亝寰勫澶嬬厽妞ゎ偒鍓欐俊璺ㄧ磼閹插顩柍褜鍓氱粙鎺椻€﹂崶褉鏋旈柟瀵稿仦婵鈧箍鍎遍幊蹇曠矉閸績妲堥柟鐐▕椤庢鏌￠崟顐⑩偓濠氬焵?闂佸搫顦弲婵嬪磻濞戙垺鍋ょ憸搴ㄥ箯閸涙潙绠婚柡澶嬪灍閸欐椽鎮楀▓鍨灀闁?闂佽崵鍋炵粙鎴︽儗閸岀偞鍋熸い鏃€绁归崷顓涘亾閿濆骸鏋涙繛鍛€濆娲敊鐏忔牕浜鹃柣鏂挎惈閸旀粓鏌℃径鍡樻珔婵炲眰鍨介崺鈧?*/
    std::vector<unsigned int>* src = nullptr;
    int tw = 0, th = 0;
    int tx = bx, ty = by; /* paint origin (align/center applied below) */
    std::string ckey_str; /* cache key to write on miss ("" = no caching) */
#ifdef WHALEUI_BUILD_FULL
    if (ckey && !text.empty()) {
        uint64_t h = 1469598103934665603ull;
        for (size_t i = 0; i < text.size(); ++i) {
            h ^= static_cast<unsigned char>(text[i]);
            h *= 1099511628211ull;
        }
        char key[160];
        std::snprintf(key, sizeof(key), "%p|%d|%d|%s|%d|%u|%d|%llu",
                      static_cast<void*>(ckey), fs, style, family.c_str(),
                      wrap ? bw : -1, color, lsp,
                      static_cast<unsigned long long>(h));
        auto it = r->text_cache.find(key);
        if (it != r->text_cache.end() && !it->second.px.empty()) {
            whaleui_render_t::TextCacheEntry& e = it->second;
            src = &e.px;
            tw = e.w;
            th = e.h;
            e.last_use = ++r->tc_tick;
        } else {
            ckey_str = key;
        }
    }
#endif
    if (!src) {
        /* cache miss: layout + rasterize this run */
        if (fs <= 0) {
            fs = 16;
        }
        const bool bold = (style & kFontBold) != 0;
        int lh = text_line_h(r, fs, family, bold);
        if (lh <= 0) {
            lh = fs;
        }
        /* 缂傚倸鍊烽懗鍫曞窗瀹ュ洨鍗氶悗鐢电《閸嬫挸鈽夊▎妯荤暥闂佸ジ鏅查崡鎶界嵁閹烘唯闁靛鍎崇粙?闂備礁婀遍崕銈囨暜閻愬瓨娅?婵犵數鍋炲娆擃敄閸涙惌鏁?濠电偞鍨堕幐绋棵规搴″灊妞ゆ牜鍋涚粈鍡涙偣閸濆嫭鎯堢憸鐗堢懇閺岋綁锝為鈧俊濂告煙椤旇姤灏扮紒瀣樀閸┾偓妞ゆ帒瀚憴锕傚箹鏉堝墽绉靛ù鐓庡€块幃妤€鈽夊▎妯荤暥闂佸ジ鏅查崡鍐差嚕閸洖唯闁挎柨澧介崺?advance/闂備胶顭堥鍛崲閹哄秶鏄?
         * 濠电偞鍨堕幐鍫曞磿閺屻儲鍋嬮柛娑橈功閳绘棃鏌嶈閸撶喖骞?full 濠?stb 闂備礁鎲￠悷顖涚濠靛棴鑰垮ù锝堫潐娴溿倖绻涢崱妯诲碍婵炲應鈧枼妲堥柟鎯х－瀛濋梺?婵犵數鍋為幐绋款嚕閸洘鍋傞悗锝庝憾閸ゆ銇勮箛鎾搭棞缂佺姵宀搁弻娑樷枎濡湱鍑瑰┑鐘亾濞达絽婀遍埢鏃堟煃瑜滈崜姘辩矉?*/
        int baseline_off;
        TextLayout L;
#ifdef WHALEUI_BUILD_FULL
        TTF_Font* font = render_get_font(r, family, fs, style);
        if (!font) {
            return;
        }
        baseline_off = TTF_GetFontAscent(font);
        TextMeasureCtx mc = { r, fs, family, bold };
        L = layout_text(text, (wrap && bw > 0) ? bw : 0, lh, glyph_ttf, &mc);
#else
        StbFonts stb(family, fs);
        if (stb.pref == static_cast<size_t>(-1)) {
            return;
        }
        baseline_off = static_cast<int>(stb.fonts[stb.pref].asc *
                                        stb.fonts[stb.pref].scale + 0.5f);
        L = layout_text(text, (wrap && bw > 0) ? bw : 0, lh, glyph_stb, &stb);
#endif
        if (L.lines.empty()) {
            return;
        }
        tw = L.tw;
        th = L.th;
        /* letter-spacing is added to the pen per glyph (px += advance +
         * lsp) but L.tw is the plain advance sum: a spaced line's last
         * glyph lands lsp*(chars-1) past tw and the raster clip (tx2 >=
         * tw) sliced its right side off - small fonts with letter-spacing
         * visibly lost their tail. Grow the buffer by the widest line's
         * spacing so every glyph fits. */
        if (lsp > 0) {
            size_t max_ch = 0;
            for (size_t li = 0; li < L.lines.size(); ++li) {
                size_t ch = L.lines[li].cend - L.lines[li].cstart;
                if (ch > max_ch) {
                    max_ch = ch;
                }
            }
            if (max_ch > 1) {
                tw += lsp * static_cast<int>(max_ch - 1);
            }
        }
        /* some glyphs are wider than their advance (msyh's f/t/v/w/y/
         * A/V/W/Y/Z/&/_// have maxx 1px past advance; italic/kerning add
         * more): L.tw is the advance sum, so a line's LAST glyph's ink
         * falls past tw and the raster clip (tx2 >= tw) sliced it off -
         * small mixed CJK/latin text lost its tail. The 2px slack covers
         * the typical 1px overflow plus a hair of anti-aliasing. */
        tw += 2;
        if (tw <= 0 || th <= 0) {
            return;
        }
        auto glyph_img = [&](unsigned int cp, GlyphImg& g) {
#ifdef WHALEUI_BUILD_FULL
            return glyph_img_ttf(r, family, fs, style, cp, color, g);
#else
            return glyph_img_stb(stb, cp, color, g);
#endif
        };
        /* 闂傚倷绶￠崑鍛村礉閺囥垺鍋ょ憸鎴﹀Φ閹版澘顫呴梽鍥€呴锔界厸?闂備礁鎽滈崕鎰板垂椤栨粎鍗氶柡澶嬪焾閸ゆ銇勮箛鎾搭棞缂?:闂佽瀛╃粙鎺椼€冮崨瀛樺殝闁绘鐗婃刊瀵糕偓骞垮劚閹冲繒绮?RGBA,闁诲海鎳撻幉陇銇愰崘顔肩畾闁割偁鍎辩粈鍫⑩偓骞垮劚濡瑩鎮甸鐐寸厾闁荤喐婢樼痪褔鏌涢妸锝呭闁靛洦鍔欓崺锟犲礋椤愵偅顥?emoji
         * 闂備胶鍘ч〃搴㈢閿濆顥婇柍鍝勫亰缁憋絾绻濇繝鍌涱棞妞?src-over 闂備礁鎲＄敮鐐存櫠濡ゅ懎鍑犻柛鎰靛枛鐎氬銇勯幒鎴濃偓缁樺緞閸曨垱鐓曢柟閭﹀墰濠€鎾煃瑜滈崗娑㈡閻栨亣 闂備礁鎼崯鐗堟叏閹绢喖绠栭幖娣妼缁狅綁鏌熼柇锕€鏋ら柣鎾村姇闇?闂備礁鎼幏瀣闯閿濆鐒垫い鎺嶆祰婢规﹢鏌ｉ埊娆忔娴滃綊鏌曡箛鏇炐㈢紒鈧担铏圭＜?
         * 1px 闂備礁鎲￠崝鏇犵矓閸洖鏋侀柣鎰靛墰閳绘棃鏌嶈閸撴瑩鍩?fake bold);full 闂備焦鐪归崝宀€鈧凹鍣ｉ幆宀勫冀閵婏箑顎撻梺瑙勫礃閸╂牠寮?FreeType 闂備線娼荤拹鐔煎礉瀹€鍕仱鐟滄垿濡甸幇鏉款潊闁绘ê寮堕弳銉╂煟鎼达絾鍤€闁哄牜鍓熷畷鐟邦潩鐠轰綍?*/
        std::vector<unsigned int> buf(static_cast<size_t>(tw) * th, 0);
        for (size_t li = 0; li < L.lines.size(); ++li) {
            const TextLayoutLine& ln = L.lines[li];
            const int baseline = static_cast<int>(li * lh) + baseline_off;
            int px = 0;
            for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
                GlyphImg g = {};
                if (glyph_img(disp_cp_at(L, ci), g)) {
                    const int passes =
#ifndef WHALEUI_BUILD_FULL
                        (bold && !g.colored) ? 2 :
#endif
                        1;
                for (int pass = 0; pass < passes; ++pass) {
                    const int dx0 = px + g.xoff + pass;
                    const int dy0 = baseline + g.yoff;
                    for (int yy = 0; yy < g.h; ++yy) {
                        const int ty2 = dy0 + yy;
                        if (ty2 < 0 || ty2 >= th) {
                            continue;
                        }
                        for (int xx = 0; xx < g.w; ++xx) {
                            const int tx2 = dx0 + xx;
                            if (tx2 < 0 || tx2 >= tw) {
                                continue;
                            }
                            const unsigned int sp =
                                g.px[static_cast<size_t>(yy) * g.w + xx];
                            const unsigned int sa = (sp >> 24) & 0xFF;
                            if (sa == 0) {
                                continue;
                            }
                            if (outline) {
                                /* text-stroke paints the glyph OUTLINE
                                 * only. The 8-direction whole-glyph copies
                                 * (dx/dy = +-sw) filled wide strokes solid
                                 * - a 200px glyph with 1px stroke came out
                                 * as a solid silhouette ("glyph 闂佽楠稿﹢閬嶅磻濞戞氨绱?).
                                 * Keep only pixels with a transparent
                                 * neighbour; solid interiors stay empty. */
                                bool edge = false;
                                for (int oy2 = -1; oy2 <= 1 && !edge; ++oy2) {
                                    for (int ox2 = -1; ox2 <= 1 && !edge;
                                         ++ox2) {
                                        if (!ox2 && !oy2) {
                                            continue;
                                        }
                                        int ny2 = yy + oy2, nx2 = xx + ox2;
                                        unsigned int na = 0;
                                        if (ny2 >= 0 && ny2 < g.h &&
                                            nx2 >= 0 && nx2 < g.w) {
                                            na = (g.px[static_cast<size_t>(ny2) * g.w +
                                                         nx2] >>
                                                  24) & 0xFF;
                                        }
                                        if (na == 0) {
                                            edge = true;
                                        }
                                    }
                                }
                                if (!edge) {
                                    continue;
                                }
                            }
                            unsigned int& d =
                                buf[static_cast<size_t>(ty2) * tw + tx2];
                            const unsigned int da = (d >> 24) & 0xFF;
                            const unsigned int oa =
                                sa + da * (255 - sa) / 255;
                            if (oa == 0) {
                                continue;
                            }
                            const unsigned int sr = (sp >> 16) & 0xFF;
                            const unsigned int sg = (sp >> 8) & 0xFF;
                            const unsigned int sb = sp & 0xFF;
                            const unsigned int dr = (d >> 16) & 0xFF;
                            const unsigned int dg = (d >> 8) & 0xFF;
                            const unsigned int db = d & 0xFF;
                            d = (oa << 24) |
                                (((sr * sa + dr * da * (255 - sa) / 255) /
                                  oa) << 16) |
                                (((sg * sa + dg * da * (255 - sa) / 255) /
                                  oa) << 8) |
                                ((sb * sa + db * da * (255 - sa) / 255) / oa);
                        }
                    }
                }
            }
            px += g.advance + lsp;
        }
    }
    /* 闂佽閰ｅ褏绱炴繝鍕?line-box 闂佽绻掗崑娑㈠箠瀹ュ鍤?闂佺儵鍓濈敮鎺楀箠鎼淬劌鍚规い鎾卞灪閸庡酣鏌熼悜妯虹仼闁硅棄绉磋彁闁搞儯鍔庣粻鏍倵閸偅鈷愰柕鍥у瀹曞ジ寮撮悙鎻捫撻梺璇查叄濞佳呯礊婵犲嫮绀?select 闂備胶顭堥敃銊︾珶閸儱鍚规繝濠傛噺閸嬫﹢鎮橀悙鏉戠亰缂併劍濞婇幃? */
    tx = bx;
    if (align == 1) {
        tx = bx + (bw - tw) / 2;
    } else if (align == 2) {
        tx = bx + bw - tw;
    }
    /* 闂備礁鎲￠崝鏍偡瑜忓Σ鎰版晜闁款垰浜?full):miss 闂備礁鎼崯鎶藉春閺嶃劋绻嗛柟闂寸缁€鍡樻叏濮楀棗骞橀柛銊︽そ閺屸€愁吋閸パ冧粯闁诲骸鐏氶悡锟犲箚閸愵喖绀嬫い蹇撴瀛濋梻浣规偠閸庢煡宕曢幎鑺ュ仱闁靛ň鏅涚粈鍌炴煏婢诡垰鎳庨ˇ鈺呮煟鎼淬垻鈯曢惇澶岀磼閸撲焦鏆€规洏鍎查幆鏃堟晲閸ャ劍姣庨梺姹囧焺閸ㄥ酣宕橀悙顑晠姊?*/
    if (!ckey_str.empty()) {
        whaleui_render_t::TextCacheEntry& e = r->text_cache[ckey_str];
        if (e.px.empty() || e.w != tw || e.h != th) {
            /* account the old raster bytes before replacing */
            r->tc_bytes -= e.px.size() * sizeof(unsigned int);
            e.px = std::move(buf);
            e.w = tw;
            e.h = th;
            r->tc_bytes += e.px.size() * sizeof(unsigned int);
        }
        e.last_use = ++r->tc_tick;
        /* bounded cache: a large page (qwen 21k) has hundreds of runs; cap
         * the total raster bytes and evict the least-recently-used entries
         * so it cannot grow unbounded. */
        const size_t kMaxBytes = 16 * 1024 * 1024; /* 16MB */
        while (r->tc_bytes > kMaxBytes) {
            auto victim = r->text_cache.begin();
            for (auto it = r->text_cache.begin(); it != r->text_cache.end();
                 ++it) {
                if (it->second.last_use < victim->second.last_use) {
                    victim = it;
                }
            }
            if (victim == r->text_cache.end()) {
                break;
            }
            r->tc_bytes -= victim->second.px.size() * sizeof(unsigned int);
            r->text_cache.erase(victim);
        }
        src = &e.px;
    } else {
        src = &buf;
    }
    } /* end cache miss: layout + rasterize */
    /* 闂備焦鎮堕崝宀勫磹鐠囪铏规崉閵娿倖鍕冮梺鍛婁緱閸撴繈宕㈤鍕厵?闂佽瀛╃粙鎺椼€冮崨瀛樺殝濞寸厧鐡ㄩ崕?(ascent+descent)闂備礁鍚嬪姗€鎯岄崒姘肩劷妞ゅ繐妫欓崑妯尖偓鍏夊亾闁告洦鍘奸拏?th:th 闂備礁鎲￠崙褰掑磻婢舵劑鈧線骞嬮悩鍐茬／濠电娀娼уú锕偹囪閺屻倕效閸パ冨闁?
     * th 闂佽绻掗崑娑㈠箠瀹ュ鍤?闂佽瀛╃粙鎺椼€冮崨瀛樺殝?闂備焦鐪归崹濂割敋瑜嶉敃銏ゎ敂閸℃瑧锛濋梺瑙勫劤閸熷潡寮抽崡鐑嗘富闁靛牆鎳愰崺锝夋煕?濠电偞鍨堕幐鎼侇敄閸℃稑钃熼柣鏂垮悑閸嬧晜绻涢崱妤冪婵絽顦辩槐鎺戠暆閸愨晩浠╁┑?闂備礁鎼崐绋棵洪妶澶嬪仱鐟滃繘骞夐幘顔煎耿婵ê鍚嬬紞宥夋⒑缁嬫鍎忕紒璇差儑缁?闂備胶鍋ㄩ崕鏌ュ蓟閿熺姴鐒?input
     * 闂?闂備胶鎳撻崲鏌ュΧ閹间焦鍋傞柤鍝ユ暩閳绘柨鈹戦悩鍙夌ォ婵☆偆鍠栭弻锝夊Ω閵夈儺浠鹃梺缁橆殕閹稿啿鐣烽崼鏇熷亹妞ゆ梻鎳撴禍楣冩煕鐏炵偓鐨戠紒鐘冲灥椤啴濡堕崼顐㈡濠电姭鍋?cache miss 濠电偞鍨堕弻銊╊敄閸涙鍥ㄧ節濮橆剛顓奸悷婊勫灴閵?闂備礁鎲＄粙鎺楀垂濠靛鍤堥柟瀵稿Х绾句粙鏌熼幆褏锛嶉柟鐣屽█閺屻倕效閸パ冨Г闂佺粯鍩婇梽鍕焽?
     * ty 濠电儑绲藉ú锔炬崲閸愵亖鍋撻崹顐ｎ棃鐎规洘鑹鹃埞鎴﹀幢韫囨挷澹?by(濠碉紕鍋戦崐鏇㈡偉婵傜纾块悗鐢电《閸嬫捇妫冨☉姘毙ㄧ紓?,闂備礁鎲￠懝鐐附閺冨倻鍗氶柟缁㈠枛濡﹢鏌涢妷锝呭闁瑰嘲宕灋闁挎繂妫涙晶顏堟煙閼稿灚鐨戝ù鐙呯畵瀹曘劑顢楅崘銊ョ畱闂備線娼уΛ鏃傜矆娓氣偓楠炲啫螖閸愵亞锛滃銈嗘尵閸嬬偞鎱ㄦ惔銊﹀仯闁归偊鍘界亸锕傛煏閸℃韬€规洘鍨肩粻娑欐償閿濆洦鍟伴梻?*/
    {
        int gh = text_glyph_h(r, fs, family, (style & kFontBold) != 0);
        if (gh < 1) {
            gh = th;
        }
        ty = gh <= bh ? by + (bh - gh) / 2 : by;
    }
    /* blend:闂備胶鍎甸弲婊堝箰閹惰棄鐒?RGBA(濠电偞鍨堕幐鍝ョ矓閹绢喖鐤柍褜鍓熼弻锝夛綖椤掆偓婵＄厧顭胯婵炩偓鐎殿喗鐓￠、娑樷攽閸♀晜顥戦梻浣告惈閺堫剟骞戞担鍦彾?闁荤喐绮嶆竟瀣疾閻愬鐝?emoji 濠电儑绲藉ú锔炬崲閸曨垰姹查柍褜鍓熼弻銈嗙附婢跺鎹ｉ梻鍌毰堥弲婊堟晬閹邦剦鐓ラ柛鈩冾殢濡?闂?
     * opacity 闂備礁鎼€氱兘宕归悧鍫熷弿闁冲搫鎳庣粻鎴澝归敐鍥у妺闁?闂備礁鎲￠弻锝夊礉鎼淬劌鏋?濠电偞鍨堕幐濠氬蓟瑜忕划顓熷緞鐎ｎ偂姘﹀┑鐐村灦濮樸劍寰勯崟顖涘€?key,闂備礁婀遍。浠嬪磻閹捐秮褰掓偐椤旂厧濮庡┑鐘亾妞ゅ繐鎳忔禍銈嗙箾閸℃ɑ灏繛鍜冪節閺岀喓绮欏▎鐐﹂梺绋垮濮樸劌危閹扮増鍋愰柣銏㈡暩缁€鍡涙⒑鐞涒€充壕?
     * alpha 闂備胶鍋ㄩ崕鏌ュ蓟閿熺姴鐒?缂傚倸鍊搁崐褰掑箰閹间焦鍋ら柕濞炬櫅缁犳澘顭块懜闈涘濡ゆ鍨堕弻鐔碱敄鐠恒劎鐛㈠銈冨€撶欢姘跺箠濠靛绠甸柟鐑樼箖浜涢梻?opacity 闂備礁鎲￠弻锝夊礉鎼淬劌鏋侀柣鎰靛墰閳绘梻鈧箍鍎遍幊搴ㄥ疾濞嗗緷褰掓晲閸喓銆婄紓浣瑰敾婵″洭鍩€椤掍胶鈯曢柨鏇樺灲閸┾偓妞ゆ帊绀佹慨鍥煙閼哥數顣茬€垫澘瀚蹇涘Ω閿旂晫褰欓梻?
     * GPU 闂佽崵濮崇拃锕傚垂閹殿喗顐介柣鎰惈缁€?text_layer,CPU 闂佽崵濮崇拃锕傚垂閹殿喗顐介柣鎰惈缁€?framebuffer闂?*/
    std::vector<unsigned int>& fb = g_gpu ? r->text_layer : r->pixels;
    const int fw = g_gpu ? r->fb_w : r->width;
    const int fh = g_gpu ? r->fb_h : r->height;
    const bool fade = opacity < 1.0f;
    for (int yy = 0; yy < th; ++yy) {
        const int fy = ty + yy;
        if (fy < 0 || fy >= fh) {
            continue;
        }
        if (clip && (fy < clip->y || fy >= clip->y + clip->h)) {
            continue;
        }
        for (int xx = 0; xx < tw; ++xx) {
            unsigned int sp = (*src)[static_cast<size_t>(yy) * tw + xx];
            unsigned int sa = (sp >> 24) & 0xFF;
            if (sa == 0) {
                continue;
            }
            if (fade) {
                sa = static_cast<unsigned int>(sa * opacity);
                if (sa == 0) {
                    continue;
                }
                sp = (sa << 24) | (sp & 0x00FFFFFF);
            }
            const int fx = tx + xx;
            if (fx < 0 || fx >= fw) {
                continue;
            }
            if (clip && (fx < clip->x || fx >= clip->x + clip->w)) {
                continue;
            }
            unsigned int& d = fb[static_cast<size_t>(fy) * fw + fx];
            if (sa == 255) {
                /* opaque: direct copy, no src-over math (the common case
                 * for CJK/body glyph centers) */
                d = sp;
                continue;
            }
            const unsigned int da = (d >> 24) & 0xFF;
            if (da == 0) {
                /* destination transparent (the text layer was just cleared):
                 * write through without src-over math */
                d = sp;
                continue;
            }
            const unsigned int oa = sa + da * (255 - sa) / 255;
            if (oa == 0) {
                continue;
            }
            const unsigned int sr = (sp >> 16) & 0xFF;
            const unsigned int sg = (sp >> 8) & 0xFF;
            const unsigned int sb = sp & 0xFF;
            const unsigned int dr = (d >> 16) & 0xFF;
            const unsigned int dg = (d >> 8) & 0xFF;
            const unsigned int db = d & 0xFF;
            d = (oa << 24) |
                (((sr * sa + dr * da * (255 - sa) / 255) / oa) << 16) |
                (((sg * sa + dg * da * (255 - sa) / 255) / oa) << 8) |
                ((sb * sa + db * da * (255 - sa) / 255) / oa);
        }
    }
}

bool sel_range_for(whaleui_render_t* r, lxb_dom_element* el, size_t len,
                   size_t* a, size_t* b, int seq, int sel_lo, int sel_hi)
{    lxb_dom_element* sa = r->sel_anchor_el;
    lxb_dom_element* sf = r->sel_focus_el;
    if (!sa || !sf || !el) {
        return false;
    }
    if (sa == sf) {
        /* collapsed (caret / plain click): nothing is highlighted anywhere */
        if (r->sel_anchor == r->sel_focus) {
            return false;
        }
        if (el == sa) {
            size_t lo = static_cast<size_t>(r->sel_anchor);
            size_t hi = static_cast<size_t>(r->sel_focus);
            if (lo > hi) {
                std::swap(lo, hi);
            }
            *a = lo;
            *b = hi;
            return *a < *b && *a < len;
        }
        return false; /* same-element selection touches only that element */
    }
    /* cross-element: endpoint elements partially, everything between fully */
    if (el == sa) {
        *a = static_cast<size_t>(r->sel_anchor);
        *b = len;
        return *a < len;
    }
    if (el == sf) {
        *a = 0;
        *b = static_cast<size_t>(r->sel_focus);
        return *b > 0;
    }
    if (sel_lo >= 0 && sel_hi >= 0 && seq > sel_lo && seq < sel_hi) {
        *a = 0;
        *b = len;
        return len > 0;
    }
    return false;
}

void sel_seq(whaleui_render_t* r, int* lo, int* hi, const Clip* clip)
{
    *lo = *hi = -1;
    lxb_dom_element* sa = r->sel_anchor_el;
    lxb_dom_element* sf = r->sel_focus_el;
    if (!sa || !sf || sa == sf || !r->tree) {
        return;
    }
    int idx = 0;
    std::function<void(whaleui_layout_node_t*, int, int, bool)> walk =
        [&](whaleui_layout_node_t* n, int off_x, int off_y, bool tc) {
            if (!n->visible) {
                return;
            }
            const int my = idx++;
            if (n->el == sa && *lo < 0) {
                *lo = my;
            }
            if (n->el == sf && *hi < 0) {
                *hi = my;
            }
            /* same transform/fixed rule as paint_node, so the sequence
             * numbers stay aligned with what actually gets painted */
            if (!tc && n->el && !n->is_text) {
                std::string tv = sget(n->style, "transform");
                if (!tv.empty() && tv != "none") {
                    tc = true;
                } else if (sget(n->style, "position") == "fixed") {
                    tc = true;
                }
            }
            /* a selection endpoint outside the repaint region must still
             * receive its sequence number (paint_node does the same), so
             * the in-viewport middle of the selection keeps highlighting.
             * Text runs skip the cull exactly like paint_node. */
            if (!tc && !n->is_text &&
                !(n->el && (n->el == sa || n->el == sf)) &&
                paint_cull(r, n, off_x, off_y, clip)) {
                return;
            }
            if (n->is_text) {
                return;
            }
            /* clipped containers fully off-screen are skipped by paint too */
            std::string ov = sget(n->style, "overflow");
            if (ov == "hidden" || ov == "auto" || ov == "scroll") {
                int y0 = n->border.y + off_y;
                if (y0 + n->border.h <= 0 || y0 >= r->fb_h) {
                    return;
                }
            }
            int child_off = off_y + scroll_delta(r, n);
            for (whaleui_layout_node_t* c = n->first_child; c; c = c->next) {
                walk(c, off_x, child_off, tc);
            }
        };
    walk(r->tree->root, 0, 0, false);
    if (*lo > *hi) {
        std::swap(*lo, *hi);
    }
}

unsigned int accent_hl(whaleui_render_t* r, unsigned int alpha)
{
    unsigned int hl = (alpha << 24);
    auto it = r->theme_vars.find("--accent");
    if (it != r->theme_vars.end()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(it->second.c_str(), &c) == 0) {
            hl = (alpha << 24) | (c & 0x00FFFFFF);
        }
    }
    return hl;
}

void expand_hl_rects(std::vector<TRect>& rects, int lh)
{
    for (size_t i = 0; i < rects.size(); ++i) {
        TRect& rc = rects[i];
        if (rc.h < lh) {
            int d = lh - rc.h;
            rc.y -= d / 2 + 2;
            rc.h = lh;
        } else {
            rc.y -= 2;
            rc.h += 4;
        }
    }
}

void paint_text_selection(whaleui_render_t* r, whaleui_layout_node_t* n,
                          int fs, const std::string& family, bool bold,
                          int off_x, int off_y, int seq, int sel_lo,
                          int sel_hi, const Clip* clip)
{
        size_t a = 0, b = 0;
    int tw = 0, th = 0;
    int ww = run_wrap_w(n);
    text_size(r, n->text, fs, family, bold, &tw, &th, ww);
    if (th <= 0) {
        return;
    }
    int tx = 0, ty = 0;
    text_origin(r, n, n->text, fs, family, bold, &tx, &ty, ww);
    tx += off_x;
    ty += off_y;
    std::vector<TRect> rects = sel_rects(r, n->text, fs, family, bold, a, b,
                                         ww);
    expand_hl_rects(rects, text_line_h(r, fs, family, bold));
    unsigned int hl = sel_hl_color(r, n, 0x3C);
    for (size_t i = 0; i < rects.size(); ++i) {
        fill_rect(r->pixels, r->fb_w, r->fb_h,
                  tx + rects[i].x, ty + rects[i].y,
                  rects[i].w, rects[i].h, hl, clip);
    }
}

unsigned int sel_hl_color(whaleui_render_t* r, whaleui_layout_node_t* n,
                          unsigned int alpha)
{
    std::string v = sget(n->style, "selection-bg");
    if (!v.empty()) {
        unsigned int c = 0;
        if (whaleui_render_parse_color(v.c_str(), &c) == 0) {
            return (alpha << 24) | (c & 0x00FFFFFF);
        }
    }
    return accent_hl(r, alpha);
}

void paint_caret(whaleui_render_t* r, int tx, int ty, const std::string& text,
                 int fs, const std::string& family, bool bold,
                 size_t off, const Clip* clip, int wrap_w)
{
    if ((SDL_GetTicks() / 500) & 1) {
        return; /* blink: off half the time */
    }
    int cx = 0, cy = 0, ch = 16;
    caret_pos(r, text, fs, family, bold, off, &cx, &cy, &ch, wrap_w);
    fill_rect(r->pixels, r->fb_w, r->fb_h, tx + cx, ty + cy, 1, ch,
              accent_hl(r, 0xFF), clip);
}

void update_ime_area(whaleui_render_t* r, const std::string& val, int fs,
                     const std::string& family, bool bold, size_t caret,
                     int tx, int ty, int wrap_w)
{
    if (!r->edit_el || !r->window) {
        return;
    }
    int cxx = 0, cyy = 0, chh = 16;
    caret_pos(r, val, fs, family, bold, caret, &cxx, &cyy, &chh, wrap_w);
    int wx = tx + cxx;
    int wy = ty + cyy;
    if (r->fb_w != r->width && r->width > 0) {
        wx = wx * r->width / r->fb_w;
    }
    if (r->fb_h != r->height && r->height > 0) {
        wy = wy * r->height / r->fb_h;
    }
    SDL_Rect rect = {wx, wy, 2, chh};
    if (r->window) {
        struct ImeAreaTask {
            SDL_Window* w;
            SDL_Rect r;
        };
        SDL_Window* ww = r->window;
        ImeAreaTask* t = new ImeAreaTask{ww, rect};
        whaleui_sdl_on_main(
            [](void* p) {
                ImeAreaTask* a = static_cast<ImeAreaTask*>(p);
                SDL_SetTextInputArea(a->w, &a->r, 0);
                delete a;
            },
            t);
    }
}

void paint_text(whaleui_render_t* r, whaleui_layout_node_t* n, int off_x,
                int off_y, int seq, int sel_lo, int sel_hi, const Clip* clip)
{
    /* cull runs fully outside the framebuffer: creating a TTF_Text per run
     * per frame is the dominant paint cost on scroll-heavy pages */
    int ty = n->border.y + off_y;
    if (ty + n->border.h <= 0 || ty >= r->fb_h) {
        return;
    }
    unsigned int color = color_of(n->style, "color", 0xFF000000);
    /* opacity is applied at blend time (draw_text_at's opacity param), NOT
     * baked into the color: baking it made the text_cache key change every
     * animation frame, forcing full text re-rasterization per frame. */
    (void)0;

    int fs = 16;
    std::string fsv = sget(n->style, "font-size");
    if (!fsv.empty()) {
        /* clamp()/vw font-sizes (q21k h3/glyph) resolve like the layout
         * pass - atoi treated "clamp(30px,...)" as 0 and drew 16px */
        int f = font_size_px(r, fsv);
        if (f > 0) {
            fs = f;
        }
    }
    std::string family = sget(n->style, "font-family");
    /* font-weight: bold/bolder/600-900 render bold; font-style italic/
     * oblique render italic (TTF style bits, per-tag UA defaults make
     * <strong>/<em> work without any page CSS) */
    std::string fw = sget(n->style, "font-weight");
    bool bold = fw == "bold" || fw == "bolder" ||
                (!fw.empty() && std::atoi(fw.c_str()) >= 600);
    std::string fst = sget(n->style, "font-style");
    int style = (bold ? kFontBold : 0) |
                ((fst == "italic" || fst == "oblique") ? kFontItalic : 0);
    /* text-align aligns within the parent element's content box; inline
     * line members (mixed with siblings) stay left-aligned at their laid
     * out x so the line flows as one run sequence */
    std::string ta = sget(n->style, "text-align");
    int align = 0;
    if (ta == "center") {
        align = 1;
    } else if (ta == "right") {
        align = 2;
    }
    if (n->in_inline) {
        align = 0;
    }
    /* text-transform + letter-spacing apply to the painted text (ASCII
     * transforms keep the byte length, so selection offsets stay valid) */
    std::string shown = n->text;
    std::string tt = sget(n->style, "text-transform");
    if (!tt.empty() && tt != "none") {
        apply_text_transform(shown, tt);
    }
    int lsp = 0;
    std::string lsv = sget(n->style, "letter-spacing");
    if (!lsv.empty() && lsv != "normal") {
        float v = static_cast<float>(std::atof(lsv.c_str()));
        lsp = static_cast<int>(lsv.find("em") != std::string::npos
                                   ? v * fs
                                   : v);
    }
    whaleui_layout_node_t* box = n;
    if (n->parent && !n->parent->is_text) {
        box = n->parent;
    }
    paint_text_selection(r, n, fs, family, bold, off_x, off_y, seq, sel_lo,
                         sel_hi, clip);
    bool wrap = sget(n->style, "white-space") != "nowrap";
    /* paint at the run's laid-out position: block runs sit at the parent
     * content origin, inline-line runs at their accumulated x. The wrap
     * width is run_wrap_w: the block line-box remainder (inline ancestors
     * skipped, mirroring the layout pass) - the parent-box estimate here
     * wrapped an inline <code> run at its own content width (~= the text
     * width) and painted the second line over the text below. */
    int tx0 = n->border.x + off_x;
    int ty0 = n->border.y + off_y;
    int avail_w = run_wrap_w(n);
    if (avail_w < 1) {
        avail_w = 1;
    }

    /* text-shadow: offset copy (plus 2 spread layers approximating the
     * blur) painted under the glyphs. The glyph raster is cached per
     * element, so the copies only re-tint at blend time. */
    std::string tsh = sget(n->style, "text-shadow");
    if (!tsh.empty() && tsh != "none") {
        int sox = 0, soy = 0, sblur = 0;
        unsigned int scol = 0;
        if (parse_shadow_any(tsh, sox, soy, sblur, scol) == 0) {
            unsigned int sa = (scol >> 24) & 0xFF;
            if (sblur > 0) {
                for (int k = 1; k <= 2 && k <= sblur; ++k) {
                    unsigned int ka =
                        static_cast<unsigned>(sa * (sblur - k + 1) /
                                              (sblur + 1));
                    unsigned int sc = (ka << 24) | (scol & 0x00FFFFFF);
                    draw_text_at(r, shown, tx0 + sox - k, ty0 + soy - k,
                                 avail_w, n->border.h, fs, family, sc,
                                 style, align, n->el, clip, lsp, wrap,
                                 n->opacity);
                }
            }
            draw_text_at(r, shown, tx0 + sox, ty0 + soy, avail_w,
                         n->border.h, fs, family, scol, style, align, n->el,
                         clip, lsp, wrap, n->opacity);
        }
    }
    /* -webkit-text-stroke: 8-direction outline copies (stroke width is
     * usually 1px; outline color replaces the transparent fill) */
    std::string tsk = sget(n->style, "-webkit-text-stroke");
    if (tsk.empty()) {
        tsk = sget(n->style, "text-stroke");
    }
    if (!tsk.empty() && tsk != "none") {
        std::vector<std::string> toks = split_space2(tsk);
        int sw = 1;
        unsigned int scc = 0xFF000000;
        if (!toks.empty()) {
            char* end = nullptr;
            float w = std::strtof(toks[0].c_str(), &end);
            if (end != toks[0].c_str()) {
                sw = w > 0 ? static_cast<int>(w) : 1;
            }
            std::string cstr;
            for (size_t i = 1; i < toks.size(); ++i) {
                if (!cstr.empty()) {
                    cstr += ' ';
                }
                cstr += toks[i];
            }
            if (!cstr.empty()) {
                whaleui_render_parse_color(cstr.c_str(), &scc);
            }
        }
        for (int dy = -1; dy <= 1; ++dy) {
            for (int dx = -1; dx <= 1; ++dx) {
                if (!dx && !dy) {
                    continue;
                }
                draw_text_at(r, shown, tx0 + dx * sw, ty0 + dy * sw,
                             avail_w, n->border.h, fs, family, scc,
                             style, align, n->el, clip, lsp, wrap,
                             n->opacity, true);
            }
        }
    }

    /* the run's own box carries the scroll shift; draw_text_at centers the
     * glyphs in it, matching text_origin's hit/highlight geometry */
    draw_text_at(r, shown, tx0, ty0, avail_w, n->border.h,
                 fs, family, color, style, align, n->el, clip, lsp, wrap,
                 n->opacity);

    /* text-decoration: underline / line-through lines over the box (width
     * = the run's own text extent, clamped to the line remainder) */
    std::string td = sget(n->style, "text-decoration");
    if (!td.empty() && td != "none") {
        int lw = 0;
        for (size_t i = 0; i < shown.size();) {
            unsigned char c2 = static_cast<unsigned char>(shown[i]);
            if (c2 < 0x80) {
                lw += fs / 2;
                ++i;
            } else {
                size_t n2 = (c2 & 0xE0) == 0xC0 ? 2 : (c2 & 0xF0) == 0xE0 ? 3 : 4;
                lw += fs;
                i += n2;
            }
        }
        if (lw > avail_w) {
            lw = avail_w;
        }
        if (lw < 1) {
            lw = 1;
        }
        if (td.find("underline") != std::string::npos) {
            fill_rect(r->pixels, r->fb_w, r->fb_h, tx0,
                      ty0 + n->border.h - 2, lw, 1, color, clip);
        }
        if (td.find("line-through") != std::string::npos) {
            fill_rect(r->pixels, r->fb_w, r->fb_h, tx0,
                      ty0 + n->border.h / 2, lw, 1, color, clip);
        }
    }
}

void text_origin(whaleui_render_t* r, whaleui_layout_node_t* n,
                 const std::string& text, int fs, const std::string& family,
                 bool bold, int* tx, int* ty, int wrap_w)
{
    int tw = 0, th = 0;
    text_size(r, text, fs, family, bold, &tw, &th, wrap_w);
    /* vertical centering, clamped to non-negative: the layout box height
     * (estimated wrap lines) can come out shorter than the painted text
     * (per-glyph wrap), and a negative (border.h - th)/2 pushes the first
     * line above the box - invisible text, caret drifting below it */
    if (n->is_text) {
        *tx = n->border.x;
        int dy = (n->border.h - th) / 2;
        *ty = n->border.y + (dy > 0 ? dy : 0);
    } else {
        *tx = n->content.x;
        /* empty value (th == 0): top-aligned, not centered - centering
         * put the caret of an empty textarea at the bottom of the box */
        int dy = th > 0 ? (n->content.h - th) / 2 : 0;
        *ty = n->content.y + (dy > 0 ? dy : 0);
    }
}

/* wrap width a text run paints at (draw_text_at's avail_w): the parent
 * content right edge minus the run's laid-out x; 0 when the run never
 * wraps (white-space: nowrap) */
int run_wrap_w(whaleui_layout_node_t* n)
{
    if (!n) {
        return 0;
    }
    if (sget(n->style, "white-space") == "nowrap") {
        return 0;
    }
    whaleui_layout_node_t* box =
        (n->parent && !n->parent->is_text) ? n->parent : n;
    /* an inline element's text follows the OUTER line box: its wrap width
     * is the block ancestor's remaining line space, not the inline box's
     * own content width (~= the text width - wrapping exactly at it split
     * a single <code> line into two, the second drawing over the line
     * below). Only plain inline boxes are skipped; inline-block (button/
     * input/textarea) wraps at its own content width. Must mirror the
     * layout pass (layout.cpp, text-run avail walk). */
    while (box && !box->is_text &&
           sget(box->style, "display") == "inline" && box->parent &&
           !box->parent->is_text) {
        box = box->parent;
    }
    std::string disp = sget(box->style, "display");
    if (disp == "flex" || disp == "inline-flex") {
        /* a flex item's text does not soft-wrap (browser behavior): it
         * paints at its laid-out width. Wrapping against the container's
         * content edge split a 2-char checkbox label into 3 lines (the
         * parent box is narrower than the checkbox+label pair). */
        return n->border.w > 0 ? n->border.w : 0;
    }
    int w = box->content.x + box->content.w - n->border.x;
    return w > 0 ? w : 0;
}

/* byte offset of the text under (px,py), relative to the text top-left.
 * Uses the shared program-side layout, so wrapped lines, control
 * characters and both renderers (full/stb) behave identically. */
size_t byte_at_text(whaleui_render_t* r, const std::string& text, int fs,
                    const std::string& family, bool bold, int px, int py,
                    int wrap_w)
{
    if (text.empty()) {
        return 0;
    }
    int lh = text_line_h(r, fs, family, bold);
    if (lh <= 0) {
        lh = fs > 0 ? fs : 16;
    }
#ifdef WHALEUI_BUILD_FULL
    TextMeasureCtx mc = { r, fs, family, bold };
    TextGlyphFn gw = glyph_ttf;
    void* st = &mc;
#else
    StbFonts stb(family, fs);
    TextGlyphFn gw = glyph_stb;
    void* st = &stb;
#endif
    TextLayout L = layout_text(text, wrap_w, lh, gw, st);
    if (L.lines.empty()) {
        return 0;
    }
    if (px < 0) {
        px = 0;
    }
    if (py < 0) {
        py = 0;
    }
    size_t li = static_cast<size_t>(py / lh);
    if (li >= L.lines.size()) {
        li = L.lines.size() - 1;
    }
    const TextLayoutLine& ln = L.lines[li];
    const size_t nc = L.map.size();
    int xacc = 0;
    for (size_t ci = ln.cstart; ci < ln.cend; ++ci) {
        int w = gw(disp_cp_at(L, ci), st);
        if (px < xacc + w / 2) {
            return L.map[ci];
        }
        xacc += w;
    }
    /* past the line's right edge: the LINE end (not the whole text end) */
    return (ln.cend < nc) ? L.map[ln.cend] : text.size();
}
