#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the compact CJK dictionaries for word navigation.

Reads jieba's dict.txt (installed via `pip install jieba`; the file lists
words in descending frequency) and emits two C headers grouped by the first
character, so each head char is stored once and only the word tails repeat:

    full: ~20k most frequent 2-4 char words  (src/render/cjk_dict_full.h)
    lite: ~1k  most frequent 2-4 char words  (src/render/cjk_dict_lite.h)

Minimal builds skip segmentation entirely (per-char stepping), so they get
no dictionary. Run from the repo root:
    python tools/gen_cjk_dict.py
"""
import os
import sys


def load_words(limit):
    import jieba
    dict_path = os.path.join(os.path.dirname(jieba.__file__), "dict.txt")
    scored = []
    with open(dict_path, encoding="utf-8") as f:
        for line in f:
            parts = line.split()
            if len(parts) < 2:
                continue
            w = parts[0]
            if not (2 <= len(w) <= 4):
                continue
            if not all("\u4e00" <= c <= "\u9fff" for c in w):
                continue  # pure hanzi only
            try:
                freq = int(parts[1])
            except ValueError:
                freq = 0
            scored.append((freq, w))
    scored.sort(key=lambda kv: -kv[0])  # descending frequency
    return [w for _, w in scored[:limit]]


def esc(s):
    b = s.encode("utf-8")
    return "".join("\\x%02X" % x for x in b)


def gen(path, words, guard):
    groups = {}
    for w in words:
        groups.setdefault(w[0], []).append(w[1:])
    items = sorted(groups.items(), key=lambda kv: ord(kv[0][0]))
    with open(path, "w", encoding="utf-8", newline="\n") as out:
        out.write("/* generated by tools/gen_cjk_dict.py from jieba dict.txt */\n")
        out.write("/* do not edit by hand */\n")
        out.write("#ifndef %s\n#define %s\n\n" % (guard, guard))
        out.write("struct CjkWordGroup { const char* head;\n"
                  "                     const char* const* tails; int count; };\n\n")
        for i, (head, tails) in enumerate(items):
            out.write("static const char* const t%d[] = {\n" % i)
            for t in tails:
                out.write("    \"%s\",\n" % esc(t))
            out.write("};\n\n")
        out.write("static const struct CjkWordGroup kCjkDict[] = {\n")
        for i, (head, tails) in enumerate(items):
            out.write("    {\"%s\", t%d, %d},\n" % (esc(head), i, len(tails)))
        out.write("};\n")
        out.write("static const int kCjkGroupCount = %d;\n" % len(items))
        out.write("\n#endif /* %s */\n" % guard)
    print("wrote %s (%d words, %d groups)" % (path, len(words), len(items)))


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    full = load_words(20000)
    lite = load_words(1000)
    gen(os.path.join(root, "src", "render", "cjk_dict_full.h"), full,
        "WHALEUI_CJK_DICT_FULL_H")
    gen(os.path.join(root, "src", "render", "cjk_dict_lite.h"), lite,
        "WHALEUI_CJK_DICT_LITE_H")
    return 0


if __name__ == "__main__":
    sys.exit(main())
